import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import vm from 'node:vm';
import {start} from '../server/server.mjs';
import {createSalon,snapshot,passwordHash,id,backupTo,openStore} from '../server/store.mjs';
const temporary=mkdtempSync(join(tmpdir(),'salon-cloud-'));
const instance=await start({file:join(temporary,'test.sqlite'),port:0,origin:'http://localhost:8080'}),url='http://127.0.0.1:'+instance.server.address().port;
const a=await createSalon(instance.db,{name:'Lavender',slug:'lavender',owner:'Owner A',email:'owner@a.test',password:'A-test-password-123'});
const b=await createSalon(instance.db,{name:'Rose',slug:'rose-salon',owner:'Owner B',email:'owner@b.test',password:'B-test-password-123'});
const cashier=id();instance.db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(cashier,a.salonId,'cashier@a.test','Cashier',await passwordHash('Cashier-password-123'),'cashier');
async function req(path,method='GET',data,session={},extra={}){const response=await fetch(url+'/api/'+path,{method,headers:{'Content-Type':'application/json',...(session.cookie?{Cookie:session.cookie}:{}),...(session.csrf?{'X-CSRF-Token':session.csrf}:{}),...extra},...(data===undefined?{}:{body:JSON.stringify(data)})});return{status:response.status,data:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0]}}
async function login(salon,email,password){const r=await req('login','POST',{salon,email,password});assert.equal(r.status,200);return{cookie:r.cookie,csrf:r.data.csrf,user:r.data.user}}
const sa=await login('lavender','owner@a.test','A-test-password-123'),sb=await login('rose-salon','owner@b.test','B-test-password-123'),sc=await login('lavender','cashier@a.test','Cashier-password-123');
const op=(kind,key,data,base=0)=>({id:randomUUID(),kind,key,action:'put',base,data});
function sale(state,key){const service=state.services[0],total=service.price;return{id:key,date:new Date().toISOString(),items:[{...service,qty:1}],sub:total,off:0,tax:0,total,received:total,change:0,customerId:'',customer:'Walk-in customer',staff:'Stylist 1',method:'Cash',shop:state.settings,status:'Paid'}}
let successfulSale;
await test('unauthenticated requests and missing CSRF are rejected',async()=>{assert.equal((await req('state')).status,401);assert.equal((await req('sync','POST',op('customers','x',{id:'x',name:'Test',phone:''}),{cookie:sa.cookie})).status,403);assert.equal((await req('login','POST',{salon:'lavender',email:'owner@a.test',password:'wrong'})).status,401)});
await test('tenant isolation: same record id has separate values',async()=>{assert.equal((await req('sync','POST',op('customers','same',{id:'same',name:'A only',phone:'1'}),sa)).status,200);assert.equal((await req('sync','POST',op('customers','same',{id:'same',name:'B only',phone:'2'}),sb)).status,200);assert.equal((await req('state','GET',undefined,sa)).data.state.customers[0].name,'A only');assert.equal((await req('state','GET',undefined,sb)).data.state.customers[0].name,'B only')});
await test('cashier cannot change catalogue or manage accounts',async()=>{assert.equal((await req('sync','POST',op('services','s1',{id:'s1',name:'Bad price',category:'Hair',price:1},1),sc)).status,403);assert.equal((await req('users','GET',undefined,sc)).status,403);assert.equal((await req('audit','GET',undefined,sc)).status,403)});
await test('replaying an operation does not create duplicate sales',async()=>{const state=(await req('state','GET',undefined,sa)).data.state;successfulSale=op('sales','sale-one',sale(state,'sale-one'));const first=await req('sync','POST',successfulSale,sc),again=await req('sync','POST',successfulSale,sc);assert.equal(first.status,200);assert.deepEqual(first.data,again.data);assert.equal((await req('state','GET',undefined,sa)).data.state.sales.length,1);const altered=structuredClone(successfulSale);altered.data.received+=100;assert.equal((await req('sync','POST',altered,sc)).status,409)});
await test('totals are recomputed and tampered prices rejected',async()=>{let data=sale((await req('state','GET',undefined,sa)).data.state,'tampered');data.total=1;assert.equal((await req('sync','POST',op('sales','tampered',data),sa)).status,409);data=sale((await req('state','GET',undefined,sa)).data.state,'badprice');data.items[0].price=1;assert.equal((await req('sync','POST',op('sales','badprice',data),sa)).status,409)});
await test('optimistic version conflicts preserve first edit',async()=>{const first=op('customers','same',{id:'same',name:'A updated',phone:'1'},1),second=op('customers','same',{id:'same',name:'Stale edit',phone:'1'},1);assert.equal((await req('sync','POST',first,sa)).status,200);assert.equal((await req('sync','POST',second,sa)).status,409);assert.equal((await req('state','GET',undefined,sa)).data.state.customers[0].name,'A updated')});
await test('appointment overlaps are blocked across devices',async()=>{const when=new Date(Date.now()+86400000).toISOString(),data={id:'appt1',when,duration:30,customer:'A updated',service:'Haircut',staffId:'t1',staff:'Stylist 1',status:'Booked'};assert.equal((await req('sync','POST',op('appointments','appt1',data),sa)).status,200);assert.equal((await req('sync','POST',op('appointments','appt2',{...data,id:'appt2'}),sc)).status,409)});
await test('refund requires owner and preserves original money fields',async()=>{const old=(await req('state','GET',undefined,sa)).data.state.sales[0],refund=op('sales',old.id,{...old,status:'Refunded',refundReason:'Customer request',total:1},1);assert.equal((await req('sync','POST',refund,sc)).status,403);const r=await req('sync','POST',{...refund,id:randomUUID()},sa);assert.equal(r.status,200);assert.equal(r.data.data.total,old.total);assert.equal(r.data.data.status,'Refunded')});
await test('cashiers see only their own sale history',async()=>{const state=(await req('state','GET',undefined,sa)).data.state;assert.equal((await req('sync','POST',op('sales','owner-sale',sale(state,'owner-sale')),sa)).status,200);const cashierState=(await req('state','GET',undefined,sc)).data;assert.equal(cashierState.state.sales.length,1);assert.equal(cashierState.revisions['sales:owner-sale'],undefined)});
await test('cross-tenant user changes and cross-origin writes are rejected',async()=>{assert.equal((await req('users/'+b.userId,'PATCH',{active:false},sa)).status,404);assert.equal((await req('logout','POST',{},sa,{Origin:'https://evil.test'})).status,403)});
await test('cashier discard requires a same-salon owner and is audited',async()=>{const operations=[{id:'pending-recovery-test'}];assert.equal((await req('approve-discard','POST',{operations,email:'cashier@a.test',password:'Cashier-password-123'},sc)).status,403);assert.equal((await req('approve-discard','POST',{operations,email:'owner@b.test',password:'B-test-password-123'},sc)).status,403);assert.equal((await req('approve-discard','POST',{operations,email:'owner@a.test',password:'A-test-password-123'},sc)).status,200);assert((await req('audit','GET',undefined,sa)).data.some(x=>x.action.startsWith('approve-discard-for:')))});
await test('disable revokes active sessions',async()=>{assert.equal((await req('users/'+cashier,'PATCH',{active:false},sa)).status,200);assert.equal((await req('state','GET',undefined,sc)).status,401)});
await test('password hashes and backup restore retain correct salon records',async()=>{const raw=instance.db.prepare('SELECT password FROM users WHERE id=?').get(a.userId).password;assert(!raw.includes('A-test-password'));await backupTo(instance.db,join(temporary,'backup.sqlite'));const copy=openStore(join(temporary,'backup.sqlite'));assert.equal(snapshot(copy,a.salonId).state.customers[0].name,'A updated');assert.equal(snapshot(copy,b.salonId).state.customers[0].name,'B only');copy.close()});
await test('outbox survives disconnect, rebase and acknowledgement',()=>{const context={};vm.createContext(context);vm.runInContext(readFileSync(new URL('../web/sync-core.js',import.meta.url),'utf8'),context);const c=context.SyncCore,base=snapshot(instance.db,a.salonId),cache={base:base.state,revisions:base.revisions,pending:[]},before=c.project(cache),after=structuredClone(before);after.customers.push({id:'offline',name:'Offline customer',phone:''});cache.pending.push(...c.diff(before,after,cache,randomUUID));const reboot=JSON.parse(JSON.stringify(cache));assert.equal(c.project(reboot).customers.at(-1).name,'Offline customer');const op=reboot.pending[0];c.ack(reboot,{id:op.id,kind:op.kind,key:op.key,data:op.data,version:1});assert.equal(reboot.pending.length,0);assert.equal(c.project(reboot).customers.at(-1).name,'Offline customer')});
await test('sign out invalidates the session',async()=>{assert.equal((await req('logout','POST',{},sb)).status,200);assert.equal((await req('state','GET',undefined,sb)).status,401)});
await instance.close();rmSync(temporary,{recursive:true,force:true});
