import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {start} from '../server/server.mjs';
import {createSalon,passwordHash,snapshot} from '../server/store.mjs';
import {businessDay} from '../server/finance.mjs';
const dir=mkdtempSync(join(tmpdir(),'salon-finance-')),app=await start({file:join(dir,'db.sqlite'),port:0}),base='http://127.0.0.1:'+app.server.address().port;
const a=await createSalon(app.db,{name:'A',slug:'salon-a',owner:'A',email:'a@test.test',password:'test-password-123'});
await createSalon(app.db,{name:'B',slug:'salon-b',owner:'B',email:'b@test.test',password:'test-password-123'});
app.db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run('cashier',a.salonId,'c@test.test','Cashier',await passwordHash('test-password-123'),'cashier');
async function req(path,method='GET',data,session={},headers={}){const r=await fetch(base+'/api/'+path,{method,headers:{'Content-Type':'application/json',Cookie:session.cookie||'','X-CSRF-Token':session.csrf||'',...headers},...(data?{body:JSON.stringify(data)}:{})});return{status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]}}
async function login(salon,email){const r=await req('login','POST',{salon,email,password:'test-password-123'});assert.equal(r.status,200);return{cookie:r.cookie,csrf:r.data.csrf}}
const sa=await login('salon-a','a@test.test'),sb=await login('salon-b','b@test.test'),sc=await login('salon-a','c@test.test');
const op=(kind,key,data,base=0)=>({id:randomUUID(),kind,key,data,base,action:'put'});
const today=businessDay(),yesterday=businessDay(new Date(Date.now()-86400000));
const expense={id:'expense-one',date:today,amount:1000,method:'Cash',category:'Supplies',note:'Towels'};
const report=async()=>{const r=await req('finance/report?date='+today,'GET',null,sa);assert.equal(r.status,200);return r.data};
const sale=(id,date=new Date().toISOString())=>({id,date,items:[{id:'s1',price:5000,qty:1}],sub:5000,off:1000,tax:0,total:4000,received:5000,customerId:'',staffId:'t1',staff:'Stylist 1',commissionBps:2500,method:'Cash',status:'Paid'});
try{
await test('finance access requires owner, valid session and CSRF; businesses remain isolated',async()=>{assert.equal((await req('finance/report')).status,401);assert.equal((await req('finance/report','GET',null,sc)).status,403);assert.equal((await req('finance/expenses','POST',expense,sc)).status,403);assert.equal((await req('finance/expenses','POST',expense,{cookie:sa.cookie})).status,403);assert.equal((await req('finance/expenses','POST',expense,sa,{Origin:'https://evil.test'})).status,403);assert.equal((await req('finance/report?date=2026-02-30','GET',null,sa)).status,400)});
await test('commission snapshots ignore supplied totals and survive later rate changes',async()=>{assert.equal((await req('sync','POST',op('staff','t1',{name:'Stylist 1',commissionBps:2500},1),sa)).status,200);assert.equal((await req('sync','POST',op('staff','t1',{name:'Bad',commissionBps:10001},2),sa)).status,400);const r=await req('sync','POST',op('sales','sale-today',{...sale('sale-today'),commissionAmount:999999}),sc);assert.equal(r.status,200);assert.equal(r.data.data.commissionAmount,1000);assert.equal(r.data.data.change,1000);assert.equal((await report()).totals.cashSales,4000);assert.equal((await report()).totals.commission,1000);const prior=sale('sale-yesterday',new Date(Date.now()-86400000).toISOString());assert.equal((await req('sync','POST',op('sales','sale-yesterday',prior),sa)).status,200);assert.equal((await req('sync','POST',op('staff','t1',{name:'Renamed',commissionBps:5000},2),sa)).status,200);assert.equal((await report()).totals.commission,1000);assert.equal((await req('sync','POST',op('sales','stale-rate',sale('stale-rate')),sa)).status,409)});
await test('refund reverses saved commission on refund date rather than original date',async()=>{const old=snapshot(app.db,a.salonId).state.sales.find(s=>s.id==='sale-yesterday');assert.equal((await req('sync','POST',op('sales',old.id,{...old,status:'Refunded',refundReason:'Requested',commissionAmount:999},1),sa)).status,200);const r=await report();assert.equal(r.totals.commission,0);assert.equal(r.totals.cashRefunds,4000);assert.equal((await req('finance/report?date='+yesterday,'GET',null,sa)).data.totals.commission,1000)});
await test('expenses are validated, replay-safe, private, and cash/card are distinguished',async()=>{assert.equal((await req('finance/expenses','POST',{...expense,amount:-1},sa)).status,400);assert.equal((await req('finance/expenses','POST',expense,sa)).status,201);assert.equal((await req('finance/expenses','POST',expense,sa)).status,200);assert.equal((await req('finance/expenses','POST',{...expense,amount:2},sa)).status,409);assert.equal((await req('finance/expenses','POST',{...expense,id:'card-expense',method:'Bank / card',amount:2000},sa)).status,201);const r=await report();assert.equal(r.expenses.length,2);assert.equal(r.totals.expenses,3000);assert.equal(r.totals.cashExpenses,1000);assert.equal((await req('finance/report?date='+today,'GET',null,sb)).data.expenses.length,0);assert.equal((await req('finance/void-expense','POST',{id:expense.id,reason:'Wrong'},sb)).status,404)});
let closing;
await test('cash closing detects concurrent changes, computes expected cash and prevents duplicate closes',async()=>{const r=await report();const b={id:'close-one',date:today,fingerprint:r.fingerprint,opening:2000,cashIn:500,cashOut:100,counted:1400,note:'All devices synced'};assert.equal((await req('finance/close','POST',{...b,fingerprint:'stale'},sa)).status,409);const result=await req('finance/close','POST',b,sa);assert.equal(result.status,201);closing=result.data;assert.equal(closing.expected,1400);assert.equal(closing.variance,0);assert.equal((await req('finance/close','POST',b,sa)).status,200);assert.equal((await req('finance/close','POST',{...b,id:'second'},sa)).status,409);assert.equal((await report()).changedSinceClose,false)});
await test('late synced sales and voided expenses flag adjustments without rewriting closing',async()=>{const late={...sale('late-sale'),commissionBps:5000};const operation=op('sales','late-sale',late);assert.equal((await req('sync','POST',operation,sc)).status,200);assert.equal((await req('sync','POST',operation,sc)).status,200);let r=await report();assert.equal(r.changedSinceClose,true);assert.deepEqual(r.closing,closing);assert.equal(r.totals.cashSales,8000);assert.equal((await req('finance/void-expense','POST',{id:expense.id,reason:'Duplicate paperwork'},sa)).status,200);r=await report();assert.equal(r.totals.cashExpenses,0);assert.equal(r.totals.expenses,2000);assert(r.expenses.find(e=>e.id===expense.id).voided_at);assert.deepEqual(r.closing,closing)});
await test('UAE business day handles UTC midnight boundary',()=>{assert.equal(businessDay('2026-09-22T20:00:00Z'),'2026-09-23');assert.equal(businessDay('2026-09-22T19:59:59Z'),'2026-09-22')});
}finally{await app.close();rmSync(dir,{recursive:true,force:true})}
