import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {start} from '../server/server.mjs';import {bootstrapProvider} from '../server/provider.mjs';import {recoveryMailer} from '../server/recovery.mjs';
const password='old-password-123!',email='owner@example.com';
async function fixture(t,mail){const dir=await mkdtemp(join(tmpdir(),'recovery-')),messages=[];const app=await start({file:join(dir,'db'),port:0,recoveryMail:mail===undefined?async m=>messages.push(m):mail});t.after(async()=>{await app.close();await rm(dir,{recursive:true,force:true})});const base='http://127.0.0.1:'+app.server.address().port;
 const call=async(path,data,cookie='',csrf='',method=data===undefined?'GET':'POST',extra={})=>{const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json',Cookie:cookie,'X-CSRF-Token':csrf,...extra},body:data===undefined?undefined:JSON.stringify(data)});return{status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]||''}};
 await bootstrapProvider(app.db,{name:'Admin',email:'admin@example.com',password});const admin=await call('/api/provider/login',{email:'admin@example.com',password});
 const created=await call('/api/provider/salons',{name:'One',slug:'salon-one',owner:'Owner',email,plan:'Professional',status:'active',expires:'2099-12-31'},admin.cookie,admin.data.csrf);
 await call('/api/activate',{token:created.data.activationUrl.split('#')[1],password});const login=await call('/api/login',{salon:'salon-one',email,password});return{...app,base,call,messages,admin,login,sid:created.data.id};}
const token=m=>m.text.match(/\/recover#([a-f0-9]{64})/)[1];
test('reset is private, single use, revokes sessions and leaves tenant data intact',async t=>{const f=await fixture(t);const request={salon:'salon-one',email};const known=await f.call('/api/recovery/password',request),unknown=await f.call('/api/recovery/password',{...request,email:'unknown@example.com'});assert.deepEqual(known.data,unknown.data);assert.equal(known.status,202);assert.equal(f.messages.length,1);const raw=token(f.messages[0]);assert.equal(f.db.prepare('SELECT * FROM password_resets WHERE token=?').get(raw),undefined);const before=f.db.prepare('SELECT * FROM records').all();const r=await f.call('/api/recovery/reset',{token:raw,password:'new-password-123!'});assert.equal(r.status,200);assert.equal(r.data.salonCode,'salon-one');assert.equal((await f.call('/api/me',undefined,f.login.cookie)).status,401);assert.equal((await f.call('/api/login',{...request,password})).status,401);assert.equal((await f.call('/api/login',{...request,password:'new-password-123!'})).status,200);assert.equal((await f.call('/api/recovery/reset',{token:raw,password})).status,400);assert.deepEqual(f.db.prepare('SELECT * FROM records').all(),before);});
test('expired, concurrent and superseded resets cannot override a new password',async t=>{const f=await fixture(t);await f.call('/api/recovery/password',{email,salon:'salon-one'});let raw=token(f.messages[0]);assert.equal((await f.call('/api/recovery/reset',{token:raw,password:'short'})).status,400);f.db.prepare('UPDATE password_resets SET expires=0').run();assert.equal((await f.call('/api/recovery/reset',{token:raw,password})).status,400);await f.call('/api/recovery/password',{email,salon:'salon-one'});raw=token(f.messages[1]);await f.call('/api/password',{current:password,password:'changed-password-123!'},f.login.cookie,f.login.data.csrf);assert.equal((await f.call('/api/recovery/reset',{token:raw,password})).status,400);await f.call('/api/recovery/password',{email,salon:'salon-one'});raw=token(f.messages[2]);const results=await Promise.all([f.call('/api/recovery/reset',{token:raw,password}),f.call('/api/recovery/reset',{token:raw,password})]);assert.deepEqual(results.map(r=>r.status).sort(),[200,400]);});
test('code recovery mails only matching accounts; limits and mail failures are safe',async t=>{const f=await fixture(t);const known=await f.call('/api/recovery/codes',{email}),unknown=await f.call('/api/recovery/codes',{email:'nobody@example.com'});assert.deepEqual(known.data,unknown.data);assert.equal(f.messages.length,1);assert.match(f.messages[0].text,/salon-one/);assert.match(f.messages[0].subject,/Palace POS/);assert.ok(!JSON.stringify(known.data).includes('salon-one'));await f.call('/api/recovery/codes',{email});await f.call('/api/recovery/codes',{email});assert.equal((await f.call('/api/recovery/codes',{email})).status,429);const disabled=await fixture(t,null);assert.equal((await disabled.call('/api/recovery/codes',{email})).status,503);const failed=await fixture(t,async()=>{throw Error('private')});assert.equal((await failed.call('/api/recovery/password',{email,salon:'salon-one'})).status,202);assert.equal(failed.db.prepare('SELECT count(*) n FROM password_resets').get().n,0);assert.equal((await failed.call('/api/recovery/password',{email,salon:'salon-one'},'','','POST',{Origin:'https://evil.example'})).status,403);});
test('provider code change requires admin and CSRF, preserves data and rejects duplicates',async t=>{const f=await fixture(t),path='/api/provider/salons/'+f.sid+'/code';assert.equal((await f.call(path,{slug:'new-code'},f.login.cookie,f.login.data.csrf)).status,401);assert.equal((await f.call(path,{slug:'new-code'},f.admin.cookie)).status,403);assert.equal((await f.call(path,{slug:'!'},f.admin.cookie,f.admin.data.csrf)).status,400);f.db.prepare('INSERT INTO businesses(id,name,slug,active,created,type) VALUES (?,?,?,?,?,?)').run('other','Other','taken-code',1,new Date().toISOString(),'salon');assert.equal((await f.call(path,{slug:'taken-code'},f.admin.cookie,f.admin.data.csrf)).status,409);const records=f.db.prepare('SELECT * FROM records').all();assert.equal((await f.call(path,{slug:'new-code'},f.admin.cookie,f.admin.data.csrf)).status,200);assert.deepEqual(f.db.prepare('SELECT * FROM records').all(),records);assert.equal((await f.call('/api/me',undefined,f.login.cookie)).status,401);assert.equal((await f.call('/api/login',{email,password,salon:'salon-one'})).status,401);assert.equal((await f.call('/api/login',{email,password,salon:'new-code'})).status,200);await f.call('/api/recovery/codes',{email});assert.match(f.messages[0].text,/new-code/);});
test('password reset accepts the business field and returns the business code',async t=>{const f=await fixture(t);await f.call('/api/recovery/password',{email,business:'salon-one'});assert.equal(f.messages.length,1);const r=await f.call('/api/recovery/reset',{token:token(f.messages[0]),password:'new-password-123!'});assert.equal(r.data.businessCode,'salon-one');});
test('recovery email does not require signup flag; recovery pages are not cached',async t=>{let captured;const mail=recoveryMailer({RESEND_API_KEY:'test',MAIL_FROM:'test@example.com'},async(url,opts)=>{captured={url,opts};return{ok:true}});await mail({email,subject:'Reset',text:'Link'});assert.equal(captured.url,'https://api.resend.com/emails');assert.equal(JSON.parse(captured.opts.body).subject,'Reset');const f=await fixture(t);for(const path of ['/recover','/recovery.js']){const r=await fetch(f.base+path);assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store')}});
