import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {start} from '../server/server.mjs';import {signupMailer} from '../server/signup.mjs';import {hash} from '../server/store.mjs';
const registration={name:'New Salon',owner:'Owner',email:'owner@example.com',phone:'+971 50 1234567'},password='Long-password-123!';
async function fixture(t,mailer){const dir=await mkdtemp(join(tmpdir(),'signup-'));const messages=[];const app=await start({file:join(dir,'db.sqlite'),port:0,host:'127.0.0.1',origin:'http://localhost:8080',mailer:mailer===undefined?async m=>messages.push(m):mailer});const base='http://127.0.0.1:'+app.server.address().port;t.after(async()=>{await app.close();await rm(dir,{recursive:true,force:true})});const call=async(path,b,headers={})=>{const r=await fetch(base+path,{method:b===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...headers},body:b===undefined?undefined:JSON.stringify(b)});return{status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')}};return{...app,base,messages,call}}
test('verified signup creates owner and 14-day tenant, consumes all links, allows login and enforces expiry',async t=>{const f=await fixture(t);for(let i=0;i<2;i++)assert.equal((await f.call('/api/signup/request',registration)).status,202);assert.equal(f.db.prepare('SELECT count(*) n FROM businesses').get().n,0);const token=f.messages[0].url.split('#')[1];assert.equal(f.db.prepare('SELECT token FROM signup_requests WHERE token=?').get(token),undefined);const before=Date.now();const r=await f.call('/api/signup/verify',{token,password});assert.equal(r.status,201);assert.match(r.body.salonCode,/^new-salon-/);assert.ok(Date.parse(r.body.expires)>=before+14*86400000);assert.ok(Date.parse(r.body.expires)<Date.now()+14*86400000+1000);assert.equal(f.db.prepare('SELECT count(*) n FROM signup_requests').get().n,0);assert.equal(f.db.prepare('SELECT count(*) n FROM provider_admins').get().n,0);assert.equal(f.db.prepare('SELECT status FROM subscriptions').get().status,'trial');assert.equal(f.db.prepare('SELECT role FROM users').get().role,'owner');assert.equal((await f.call('/api/signup/verify',{token:f.messages[1].url.split('#')[1],password})).status,400);const login=await f.call('/api/login',{salon:r.body.salonCode,email:registration.email,password});assert.equal(login.status,200);const state=await f.call('/api/state',undefined,{Cookie:login.cookie.split(';')[0]});assert.equal(state.body.state.settings.phone,registration.phone);assert.equal(state.body.state.sales.length,0);f.db.prepare('UPDATE subscriptions SET expires=?').run(new Date(Date.now()-1000).toISOString());assert.equal((await f.call('/api/state',undefined,{Cookie:login.cookie.split(';')[0]})).status,403);assert.equal((await f.call('/api/signup/request',registration)).status,202);assert.equal(f.messages.length,2);});
test('expired tokens, invalid inputs, weak passwords and cross-origin requests create no accounts',async t=>{const f=await fixture(t);assert.equal((await f.call('/api/signup/request',{...registration,email:'bad'})).status,400);assert.equal((await f.call('/api/signup/request',registration,{Origin:'https://evil.example'})).status,403);await f.call('/api/signup/request',registration);const token=f.messages[0].url.split('#')[1];assert.equal((await f.call('/api/signup/verify',{token,password:'short'})).status,400);f.db.prepare('UPDATE signup_requests SET expires=0').run();assert.equal((await f.call('/api/signup/verify',{token,password})).status,400);assert.equal((await f.call('/api/signup/verify',{token:'x',password})).status,400);assert.equal(f.db.prepare('SELECT count(*) n FROM businesses').get().n,0);});
test('simultaneous activation creates exactly one tenant',async t=>{const f=await fixture(t);await f.call('/api/signup/request',registration);const token=f.messages[0].url.split('#')[1];const results=await Promise.all([f.call('/api/signup/verify',{token,password}),f.call('/api/signup/verify',{token,password})]);assert.deepEqual(results.map(x=>x.status).sort(),[201,400]);assert.equal(f.db.prepare('SELECT count(*) n FROM businesses').get().n,1);});
test('disabled and failing mail fail closed; email rate limit bounds resends',async t=>{const disabled=await fixture(t,null);assert.equal((await disabled.call('/api/signup/status')).body.enabled,false);assert.equal((await disabled.call('/api/signup/request',registration)).status,503);const failed=await fixture(t,async()=>{throw Error('secret transport detail')});const r=await failed.call('/api/signup/request',registration);assert.equal(r.status,503);assert.ok(!JSON.stringify(r.body).includes('secret'));assert.equal(failed.db.prepare('SELECT count(*) n FROM signup_requests').get().n,0);const f=await fixture(t);for(let i=0;i<3;i++)assert.equal((await f.call('/api/signup/request',registration)).status,202);assert.equal((await f.call('/api/signup/request',registration)).status,429);});
test('mail adapter uses server credentials and fixed endpoint; signup assets served without caching',async t=>{assert.equal(signupMailer({}),null);let captured;const mailer=signupMailer({SIGNUP_ENABLED:'true',RESEND_API_KEY:'private-test',MAIL_FROM:'WiFi Palace <sender@example.com>'},async(url,options)=>{captured={url,options};return{ok:true}});await mailer({email:'owner@example.com',url:'https://example.com/signup#abc'});assert.equal(captured.url,'https://api.resend.com/emails');assert.equal(captured.options.headers.Authorization,'Bearer private-test');assert.deepEqual(JSON.parse(captured.options.body).to,['owner@example.com']);const f=await fixture(t);for(const path of ['/signup','/signup.js']){const r=await fetch(f.base+path);assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store')}});
test('signup records the business type, defaults to salon and refuses unsupported types',async t=>{const f=await fixture(t);
 const bad=await f.call('/api/signup/request',{...registration,email:'bad@example.com',type:'spaceship'});assert.equal(bad.status,400);assert.equal(f.messages.length,0);
 assert.equal((await f.call('/api/signup/request',{...registration,email:'proto@example.com',type:'constructor'})).status,400);
 assert.deepEqual((await f.call('/api/signup/status')).body.businessTypes,['salon','laundry','gym','grocery','restaurant','petshop']);
 assert.equal((await f.call('/api/signup/request',{...registration,type:'salon'})).status,202);
 const token=f.messages[0].url.split('#')[1];const r=await f.call('/api/signup/verify',{token,password});assert.equal(r.status,201);assert.equal(r.body.businessType,'salon');assert.equal(r.body.businessCode,r.body.salonCode);
 assert.equal(f.db.prepare('SELECT type FROM businesses WHERE slug=?').get(r.body.businessCode).type,'salon');
 const login=await f.call('/api/login',{salon:r.body.businessCode,email:registration.email,password});assert.equal(login.status,200);assert.equal(login.body.user.businessType,'salon');});
