import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {start} from '../server/server.mjs';import {createSalon,passwordHash} from '../server/store.mjs';import {staffReport,financeReport} from '../server/finance.mjs';
test('staff totals reconcile with finance, use UAE boundaries and preserve legacy and tenant isolation',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'stylist-')),app=await start({file:join(dir,'db'),port:0});t.after(async()=>{await app.close();await rm(dir,{recursive:true,force:true})});
 const a=await createSalon(app.db,{name:'A',slug:'salon-a',owner:'Owner',email:'a@example.com',password:'long-password-123'}),b=await createSalon(app.db,{name:'B',slug:'salon-b',owner:'Owner',email:'b@example.com',password:'long-password-123'});
 const put=(salon,id,s)=>app.db.prepare("INSERT INTO records(business_id,kind,id,data,version) VALUES (?,'sales',?,?,1)").run(salon,id,JSON.stringify({id,number:id,customer:'Customer',staff:'Same name',staffId:'stylist-one',items:[{name:'Haircut',qty:2}],sub:10000,off:1000,total:9450,method:'Cash',status:'Paid',date:'2026-09-25T20:00:00Z',...s}));
 put(a.salonId,'one',{});put(a.salonId,'two',{staffId:'stylist-two',status:'Refunded',refundDate:'2026-09-26T20:00:00Z'});put(a.salonId,'legacy',{staffId:null,date:'2026-09-25T19:59:59Z',status:'Refunded',refundDate:'2026-09-26T12:00:00Z'});put(b.salonId,'secret',{});
 const r=staffReport(app.db,a.salonId,'2026-09-26','2026-09-26');assert.equal(r.staff.length,3);assert.deepEqual(r.totals,{bills:2,services:4,gross:20000,discounts:2000,refunds:9000,net:9000,sessions:0});assert.equal(r.totals.net,financeReport(app.db,a.salonId,'2026-09-26').totals.netSalesBeforeTax);assert.equal(r.staff.filter(x=>!x.legacy).length,2);assert.equal(r.staff.find(x=>x.legacy).bills,0);assert.equal(r.staff.find(x=>x.legacy).details[0].total,-9450);assert.equal(staffReport(app.db,a.salonId,'2026-09-27','2026-09-27').totals.net,-9000);assert.equal(staffReport(app.db,a.salonId,'2020-01-01','2020-01-02').stylists.length,0);assert.throws(()=>staffReport(app.db,a.salonId,'2026-02-30','2026-03-01'));assert.throws(()=>staffReport(app.db,a.salonId,'2026-09-27','2026-09-26'));
 app.db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run('cashier',a.salonId,'c@example.com','Cashier',await passwordHash('long-password-123'),'cashier');
 const base='http://127.0.0.1:'+app.server.address().port;const login=async(email,salon)=>{const res=await fetch(base+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,salon,password:'long-password-123'})});return res.headers.get('set-cookie').split(';')[0]};
 const url=base+'/api/finance/staff?from=2026-09-26&to=2026-09-26';assert.equal((await fetch(url)).status,401);assert.equal((await fetch(url,{headers:{Cookie:await login('c@example.com','salon-a')}})).status,403);const report=await fetch(url,{headers:{Cookie:await login('b@example.com','salon-b')}});assert.equal(report.status,200);assert.equal((await report.json()).totals.bills,1);
});
test('laundry counter sales are credited to the team member who took them',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'staff-')),app=await start({file:join(dir,'db'),port:0});t.after(async()=>{await app.close();await rm(dir,{recursive:true,force:true})});
 const l=await createSalon(app.db,{name:'L',slug:'laundry-l',owner:'Owner Name',email:'l@example.com',password:'long-password-123',type:'laundry'});
 app.db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run('cashier-l',l.businessId,'cl@example.com','Counter Staff',await passwordHash('long-password-123'),'cashier');
 const put=(id,by,s={})=>app.db.prepare("INSERT INTO records(business_id,kind,id,data,version) VALUES (?,'sales',?,?,1)").run(l.businessId,id,JSON.stringify({id,number:id,customer:'C',staff:'Typed name',staffId:'',createdBy:by,items:[{name:'Shirt',qty:3},{name:'Wash & fold',unit:'kg',qty:2.5}],sub:5000,off:0,total:5250,method:'Cash',status:'Paid',date:'2026-09-26T08:00:00Z',...s}));
 put('a',l.userId);put('b','cashier-l');put('c','cashier-l');put('d','deleted-user');
 const r=staffReport(app.db,l.businessId,'2026-09-26','2026-09-26');
 assert.deepEqual(r.staff.map(x=>[x.name,x.bills,x.legacy]),[['Counter Staff',2,false],['Owner Name',1,false],['Typed name',1,true]]);
 assert.equal(r.staff[0].services,8);assert.equal(r.totals.net,20000);
});
