plugins { id 'com.android.application' }
android {
    namespace 'com.wifipalace.salonpos'
    compileSdk 35
    defaultConfig {
        applicationId 'com.wifipalace.saloncloud'
        minSdk 26
        targetSdk 34
        versionCode 3
        versionName '2.0'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
