'use strict';
// Accounts inside Finance (owner, online): purchases & suppliers, VAT return, profit & loss, cash & bank.
// The daily report and closing stay as they were under "Daily closing".
const ACC_VIEWS=[['Daily','Daily closing'],['Purchases','Purchases & suppliers'],['VAT','VAT report'],['PL','Profit & loss'],['Book','Cash & bank']];
let financeView='Daily',accData=null,accRequest=0,accFrom=(d=>{d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()-2);return d.toISOString().slice(0,10)})(new Date(financeDay()+'T00:00:00Z')),accTo=financeDay(),billFilter='open';
const dailyFinanceScreen=financeScreen;
financeScreen=async function(){if(financeView==='Daily'){await dailyFinanceScreen();if(tab==='Finance'&&financeView==='Daily')financeBar();return}accountsScreen()};
function financeBar(){if($('financeBar'))$('financeBar').remove();$('app').insertAdjacentHTML('afterbegin',`<div class="actions finance-bar" id="financeBar" role="tablist">${ACC_VIEWS.map(([k,l])=>`<button role="tab" class="${financeView===k?'primary':''}" aria-selected="${financeView===k}" data-fin-view="${k}">${esc(l)}</button>`).join('')}</div>`);document.querySelectorAll('[data-fin-view]').forEach(b=>b.onclick=()=>{financeView=b.dataset.finView;financeScreen()})}
const accAed=v=>(v/100).toFixed(2),amt=v=>money(v).replace('AED -','-AED ');
const accCell=v=>'"'+String(v??'').replace(/^[\s]*[=+@-]/,"'$&").replace(/"/g,'""')+'"';
const saveCsv=(name,rows)=>download(name,'﻿'+rows.map(r=>r.map(accCell).join(',')).join('\r\n'),'text/csv');
function monthStart(d,back=0){const x=new Date(d+'T00:00:00Z');x.setUTCDate(1);x.setUTCMonth(x.getUTCMonth()-back);return x.toISOString().slice(0,10)}
function monthEnd(d){const x=new Date(d+'T00:00:00Z');x.setUTCMonth(x.getUTCMonth()+1,0);return x.toISOString().slice(0,10)}
function quarterStart(d,back=0){const x=new Date(d+'T00:00:00Z');x.setUTCDate(1);x.setUTCMonth(Math.floor(x.getUTCMonth()/3)*3-back*3);return x.toISOString().slice(0,10)}
function periodPicker(){const t=financeDay(),min=(a,b)=>a<b?a:b,qs=quarterStart(t),lq=quarterStart(t,1),presets=[['Last 3 months',monthStart(t,2),t],['This month',monthStart(t),t],['Last month',monthStart(t,1),monthEnd(monthStart(t,1))],['This quarter',qs,t],['Last quarter',lq,monthEnd(monthStart(qs,1))],['This year',t.slice(0,4)+'-01-01',t]];
 return `<form id="accPeriod" class="panel"><div class="row" style="flex-wrap:wrap;align-items:flex-end;gap:10px"><label style="flex:1 1 140px;min-width:0">From<input type="date" id="accFrom" value="${esc(accFrom)}" max="${t}" required></label><label style="flex:1 1 140px;min-width:0">To<input type="date" id="accTo" value="${esc(accTo)}" max="${t}" required></label><button class="primary">Show</button></div><div class="actions">${presets.map(([l,f,to])=>`<button type="button" data-acc-preset="${f}|${min(to,t)}">${esc(l)}</button>`).join('')}</div><p class="helper">UAE dates. Your VAT periods are set by the FTA (usually quarterly); pick the same dates as your return.</p></form>`}
function wirePeriod(){$('accPeriod').onsubmit=e=>{e.preventDefault();accFrom=$('accFrom').value;accTo=$('accTo').value;accountsScreen()};document.querySelectorAll('[data-acc-preset]').forEach(b=>b.onclick=()=>{[accFrom,accTo]=b.dataset.accPreset.split('|');accountsScreen()})}
async function accountsScreen(){const request=++accRequest,view=financeView;accData=null;$('app').innerHTML='<div class="panel"><p>Loading…</p></div>';financeBar();
 const path={Purchases:'finance/payables',VAT:'finance/vat',PL:'finance/pnl',Book:'finance/book'}[view]+(view==='Purchases'?'':'?from='+encodeURIComponent(accFrom)+'&to='+encodeURIComponent(accTo));
 try{const r=await api(path);if(tab!=='Finance'||request!==accRequest||financeView!==view)return;accData=r;$('app').innerHTML=({Purchases:purchasesHtml,VAT:vatHtml,PL:plHtml,Book:bookHtml})[view](r);financeBar();if(view!=='Purchases')wirePeriod();else wirePurchases()}
 catch(e){if(tab==='Finance'&&request===accRequest){$('app').innerHTML=`<div class="panel"><h2>${esc(ACC_VIEWS.find(v=>v[0]===view)[1])}</h2><p>${esc(e.message)}</p><p>Accounts need the internet.</p><button onclick="accountsScreen()">Retry</button></div>`;financeBar()}}}
// Print on A4 (not the receipt printer). Android falls back to a CSV download.
function printReport(title,html){if(window.Android){alert('Use Export CSV on this device, or print from a computer.');return}const f=document.createElement('iframe');f.style.cssText='position:fixed;right:0;bottom:0;width:0;height:0;border:0';document.body.appendChild(f);const d=f.contentDocument;d.open();d.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>body{font:12px/1.4 system-ui,Arial,sans-serif;margin:18mm;color:#111}h1{font-size:18px;margin:0}h2{font-size:14px;margin:18px 0 6px}table{width:100%;border-collapse:collapse;margin:6px 0}th,td{border-bottom:1px solid #ccc;padding:4px 6px;text-align:left}td.n,th.n{text-align:right}tr.total td{font-weight:700;border-top:2px solid #111}.muted{color:#555;font-size:11px}</style></head><body><h1>${esc(db.settings.name||'')}</h1>${db.settings.trn?`<div class="muted">TRN ${esc(db.settings.trn)}</div>`:''}${html}<p class="muted">Printed ${esc(new Date().toLocaleString('en-GB',{timeZone:'Asia/Dubai'}))} (UAE) from Palace POS.</p></body></html>`);d.close();setTimeout(()=>{f.contentWindow.focus();f.contentWindow.print();setTimeout(()=>f.remove(),60000)},200)}

// ---------- Purchases & suppliers ----------
function purchasesHtml(r){const t=r.totals,sup=new Map(r.suppliers.map(s=>[s.id,s])),bills=r.bills.filter(b=>billFilter==='all'||b.status==='Unpaid'||b.status==='Part paid').slice().reverse(),today=financeDay();
 return `<div class="row"><div><div class="eyebrow">OWNER ACCOUNTS</div><h2>Purchases & suppliers</h2><p>Supplier bills, VAT paid on them, and what you still owe.</p></div><div class="actions">${typeof groceryReceive==='function'&&['grocery','petshop','perfume','meat','mobile','tailor','electronics','optical'].includes(cloudUser?.businessType)?'<button onclick="groceryReceive()">+ Invoice with stock items</button>':''}<button onclick="supplierForm()">+ Supplier</button><button class="primary" onclick="billForm()"${r.suppliers.length?'':' disabled title="Add a supplier first"'}>+ Purchase bill</button><button onclick="supplierPayForm()"${r.suppliers.length?'':' disabled'}>Pay supplier</button></div></div>
 <div class="grid">${[['You owe suppliers',t.owed],['Overdue',t.overdue],['Open bills',r.bills.filter(b=>b.outstanding>0).length,1]].map(([l,v,n])=>`<div class="panel">${l}<div class="metric">${n?v:money(v)}</div></div>`).join('')}</div>
 <div class="panel"><h3>Suppliers</h3>${r.suppliers.length?`<div class="scroll"><table><tr><th>Supplier</th><th>TRN</th><th>Phone</th><th>Open bills</th><th>Balance owed</th><th>Overdue</th><th></th></tr>${r.suppliers.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.trn||'—')}</td><td>${esc(s.phone||'')}</td><td>${s.openBills}</td><td>${amt(s.balance)}</td><td>${s.overdue?`<b>${money(s.overdue)}</b>`:'—'}</td><td class="actions"><button data-sup-edit="${esc(s.id)}">Edit</button>${s.balance>0?`<button data-sup-pay="${esc(s.id)}">Pay</button>`:''}<button data-sup-statement="${esc(s.id)}">Statement</button></td></tr>`).join('')}</table></div>`:'<p>No suppliers yet. Add the companies you buy from, then record their bills.</p>'}</div>
 <div class="panel"><div class="row"><h3>Purchase bills</h3><div class="actions"><button data-bill-filter="open" class="${billFilter==='open'?'primary':''}">Open</button><button data-bill-filter="all" class="${billFilter==='all'?'primary':''}">All</button></div></div>${bills.length?`<div class="scroll"><table><tr><th>Date</th><th>Supplier</th><th>Invoice no.</th><th>Category</th><th>Before VAT</th><th>VAT</th><th>Total</th><th>Status</th><th>Still owed</th><th></th></tr>${bills.slice(0,300).map(b=>`<tr${b.status==='Voided'?' style="opacity:.55"':''}><td>${esc(b.date)}${b.due&&b.outstanding&&b.due<today?`<br><small><b>Due ${esc(b.due)}</b></small>`:b.due&&b.outstanding?`<br><small>Due ${esc(b.due)}</small>`:''}</td><td>${esc(sup.get(b.supplier_id)?.name||'')}</td><td>${esc(b.number)}</td><td>${esc(b.category)}</td><td>${money(b.net)}</td><td>${money(b.vat)}</td><td>${money(b.total)}</td><td>${esc(b.status)}${b.void_reason?`<br><small>${esc(b.void_reason)}</small>`:''}</td><td>${b.outstanding?money(b.outstanding):'—'}</td><td class="actions">${b.outstanding?`<button data-bill-pay="${esc(b.id)}">Pay</button>`:''}${b.status!=='Voided'?`<button data-bill-void="${esc(b.id)}">Void</button>`:''}</td></tr>`).join('')}</table></div>`:`<p>${billFilter==='open'?'No unpaid bills.':'No bills yet.'}</p>`}<p class="helper">Enter the amount before VAT and the VAT exactly as printed on the supplier's tax invoice. Only claim VAT when the invoice shows the supplier's TRN. Receive the goods into stock separately from the Stock screen.</p></div>
 <div class="panel"><h3>Recent supplier payments</h3>${r.payments.length?`<div class="scroll"><table><tr><th>Date</th><th>Supplier</th><th>Paid from</th><th>Amount</th><th>Note</th><th></th></tr>${r.payments.slice().reverse().slice(0,50).map(p=>`<tr${p.voided_at?' style="opacity:.55"':''}><td>${esc(p.date)}</td><td>${esc(sup.get(p.supplier_id)?.name||'')}</td><td>${esc(p.method)}</td><td>${money(p.amount)}</td><td>${esc(p.note)}${p.voided_at?`<br><small>Voided: ${esc(p.void_reason)}</small>`:''}</td><td>${p.voided_at?'':`<button data-pay-void="${esc(p.id)}">Void</button>`}</td></tr>`).join('')}</table></div>`:'<p>No payments yet.</p>'}</div>
 <div class="actions"><button onclick="exportPurchases()">Export bills CSV</button></div>`}
function wirePurchases(){const on=(sel,fn)=>document.querySelectorAll(sel).forEach(b=>b.onclick=()=>fn(b));
 on('[data-sup-edit]',b=>supplierForm(b.dataset.supEdit));on('[data-sup-pay]',b=>supplierPayForm(b.dataset.supPay));on('[data-sup-statement]',b=>supplierStatement(b.dataset.supStatement));
 on('[data-bill-filter]',b=>{billFilter=b.dataset.billFilter;accountsScreen()});on('[data-bill-pay]',b=>{const x=accData.bills.find(y=>y.id===b.dataset.billPay);supplierPayForm(x.supplier_id,x.id)});
 on('[data-bill-void]',b=>voidAccount('finance/void-bill',b.dataset.billVoid,'Reason for voiding this bill (it stays on record):'));on('[data-pay-void]',b=>voidAccount('finance/void-supplier-payment',b.dataset.payVoid,'Reason for voiding this payment (it stays on record):'))}
async function voidAccount(path,id,question){const reason=prompt(question);if(!reason?.trim())return;try{await api(path,'POST',{id,reason:reason.trim()});accountsScreen()}catch(e){alert(e.message)}}
async function submitAcc(form,path,data){$('accError').textContent='';$('accSubmit').disabled=true;try{await api(path,'POST',data);closeModal();accountsScreen()}catch(e){$('accError').textContent=e.message;$('accSubmit').disabled=false}}
function supplierForm(id){const s=accData?.suppliers.find(x=>x.id===id),key=s?.id||crypto.randomUUID();modal(`<h2>${s?'Edit':'Add'} supplier</h2><form id="supForm"><label>Supplier name</label><input id="supName" maxlength="100" required value="${esc(s?.name||'')}"><label>TRN (15 digits, if VAT registered)</label><input id="supTrn" inputmode="numeric" maxlength="20" value="${esc(s?.trn||'')}"><label>Phone</label><input id="supPhone" maxlength="40" value="${esc(s?.phone||'')}"><label>Note</label><input id="supNote" maxlength="200" value="${esc(s?.note||'')}"><p id="accError" role="alert"></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary" id="accSubmit">Save supplier</button></div></form>`);$('supForm').onsubmit=e=>{e.preventDefault();submitAcc(e.target,'finance/suppliers',{id:key,name:$('supName').value,trn:$('supTrn').value,phone:$('supPhone').value,note:$('supNote').value})}}
function billForm(){if(!accData)return;const id=crypto.randomUUID(),pay=crypto.randomUUID(),rate=Number(db.settings.tax)||5;modal(`<h2>Record purchase bill</h2><form id="billForm"><label>Supplier</label><select id="billSup" required>${accData.suppliers.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}${s.trn?'':' (no TRN)'}</option>`).join('')}</select><label>Supplier invoice number</label><input id="billNo" maxlength="60" required><div class="row"><label>Bill date<input id="billDate" type="date" value="${financeDay()}" max="${financeDay()}" required></label><label>Due date (optional)<input id="billDue" type="date"></label></div><label>Category</label><select id="billCat">${accData.categories.map(c=>`<option>${esc(c)}</option>`).join('')}</select><div class="row"><label>Total on invoice (AED)<input id="billTotal" type="number" min="0.01" max="1000000" step="0.01" required></label><label>VAT (AED)<input id="billVat" type="number" min="0" max="50000" step="0.01" value="0" required></label></div><div class="actions"><button type="button" id="billCalc">VAT ${rate}% included</button><button type="button" id="billNoVat">No VAT</button></div><p class="helper" id="billNet">Before VAT: —</p><label>Paid?</label><select id="billPaid"><option value="">Not yet (on credit)</option><option>Cash</option><option>Bank / card</option></select><label>Note</label><input id="billNote" maxlength="300"><p id="accError" role="alert"></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary" id="accSubmit">Save bill</button></div></form>`);
 const net=()=>cents($('billTotal').value||0)-cents($('billVat').value||0),show=()=>{$('billNet').textContent='Before VAT: '+money(net())};$('billTotal').oninput=show;$('billVat').oninput=show;
 $('billCalc').onclick=()=>{const t=cents($('billTotal').value||0);$('billVat').value=accAed(Math.round(t*rate/(100+rate)));show()};$('billNoVat').onclick=()=>{$('billVat').value='0';show()};
 $('billForm').onsubmit=e=>{e.preventDefault();if(net()<=0){$('accError').textContent='The total must be more than the VAT.';return}const m=$('billPaid').value;submitAcc(e.target,'finance/bills',{id,supplierId:$('billSup').value,number:$('billNo').value.trim(),date:$('billDate').value,due:$('billDue').value,category:$('billCat').value,net:net(),vat:cents($('billVat').value||0),note:$('billNote').value,...(m?{paid:{id:pay,method:m}}:{})})}}
function supplierPayForm(supplierId,billId){if(!accData)return;const id=crypto.randomUUID(),owing=accData.suppliers.filter(s=>s.balance>0);if(!owing.length){alert('You do not owe any supplier right now.');return}const first=supplierId||owing[0].id;
 modal(`<h2>Pay supplier</h2><form id="payForm"><label>Supplier</label><select id="paySup">${owing.map(s=>`<option value="${esc(s.id)}"${s.id===first?' selected':''}>${esc(s.name)} · owed ${esc(money(s.balance))}</option>`).join('')}</select><label>Against bill</label><select id="payBill"></select><label>Amount (AED)</label><input id="payAmount" type="number" min="0.01" step="0.01" required><div class="row"><label>Date<input id="payDate" type="date" value="${financeDay()}" max="${financeDay()}" required></label><label>Paid from<select id="payMethod"><option>Cash</option><option>Bank / card</option></select></label></div><label>Note (cheque / transfer ref.)</label><input id="payNote" maxlength="200"><p class="helper">Choose Cash only when paid from the shop drawer: it lowers the expected cash at closing.</p><p id="accError" role="alert"></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary" id="accSubmit">Save payment</button></div></form>`);
 const fill=()=>{const s=accData.suppliers.find(x=>x.id===$('paySup').value),open=accData.bills.filter(b=>b.supplier_id===s.id&&b.outstanding>0);$('payBill').innerHTML=`<option value="">Oldest bills first</option>`+open.map(b=>`<option value="${esc(b.id)}"${b.id===billId?' selected':''}>${esc(b.number)} · ${esc(b.date)} · owed ${esc(money(b.outstanding))}</option>`).join('');setAmt()},setAmt=()=>{const s=accData.suppliers.find(x=>x.id===$('paySup').value),b=accData.bills.find(x=>x.id===$('payBill').value);$('payAmount').value=accAed(b?b.outstanding:s.balance);$('payAmount').max=accAed(b?b.outstanding:s.balance)};
 $('paySup').onchange=()=>{billId='';fill()};$('payBill').onchange=setAmt;fill();
 $('payForm').onsubmit=e=>{e.preventDefault();submitAcc(e.target,'finance/supplier-payments',{id,supplierId:$('paySup').value,billId:$('payBill').value,amount:cents($('payAmount').value),date:$('payDate').value,method:$('payMethod').value,note:$('payNote').value})}}
function statementRows(id){const rows=[...accData.bills.filter(b=>b.supplier_id===id&&b.status!=='Voided').map(b=>({date:b.date,what:'Bill '+b.number+' · '+b.category,debit:b.total,credit:0})),...accData.payments.filter(p=>p.supplier_id===id&&!p.voided_at).map(p=>({date:p.date,what:'Payment · '+p.method+(p.note?' · '+p.note:''),debit:0,credit:p.amount}))].sort((a,b)=>a.date.localeCompare(b.date)||b.debit-a.debit);let bal=0;for(const r of rows){bal+=r.debit-r.credit;r.balance=bal}return rows}
function supplierStatement(id){const s=accData.suppliers.find(x=>x.id===id),rows=statementRows(id),table=`<table><tr><th>Date</th><th>Details</th><th class="n">Billed</th><th class="n">Paid</th><th class="n">Balance</th></tr>${rows.map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.what)}</td><td class="n">${r.debit?accAed(r.debit):''}</td><td class="n">${r.credit?accAed(r.credit):''}</td><td class="n">${accAed(r.balance)}</td></tr>`).join('')}<tr class="total"><td colspan="4">Balance owed (AED)</td><td class="n">${accAed(s.balance)}</td></tr></table>`;
 modal(`<h2>${esc(s.name)} · statement</h2>${s.trn?`<p>TRN ${esc(s.trn)}</p>`:''}<div class="scroll">${table}</div><div class="actions"><button onclick="closeModal()">Close</button><button id="stmtCsv">Export CSV</button><button class="primary" id="stmtPrint">Print / Save PDF</button></div>`);
 $('stmtPrint').onclick=()=>printReport(s.name+' statement',`<h2>Supplier statement · ${esc(s.name)}</h2>${s.trn?`<div class="muted">Supplier TRN ${esc(s.trn)}</div>`:''}${table}`);
 $('stmtCsv').onclick=()=>saveCsv('supplier-'+s.name.replace(/\W+/g,'-').toLowerCase()+'.csv',[['Supplier statement',s.name,s.trn],['Date','Details','Billed AED','Paid AED','Balance AED'],...rows.map(r=>[r.date,r.what,r.debit?accAed(r.debit):'',r.credit?accAed(r.credit):'',accAed(r.balance)])])}
function exportPurchases(){const r=accData;if(!r)return;const sup=new Map(r.suppliers.map(s=>[s.id,s]));saveCsv('purchase-bills.csv',[['Date','Supplier','Supplier TRN','Invoice no.','Category','Before VAT AED','VAT AED','Total AED','Status','Still owed AED','Due','Note'],...r.bills.map(b=>[b.date,sup.get(b.supplier_id)?.name,sup.get(b.supplier_id)?.trn,b.number,b.category,accAed(b.net),accAed(b.vat),accAed(b.total),b.status,accAed(b.outstanding),b.due,b.note])])}

// ---------- VAT return ----------
function vatTable(r){return `<table><tr><th>Box</th><th>Description</th><th class="n">Amount (AED)</th><th class="n">VAT (AED)</th></tr>${r.boxes.map(b=>`<tr${['8','11'].includes(b.box)?' class="total"':''}><td>${b.box}</td><td>${esc(b.label)}</td><td class="n">${accAed(b.amount)}</td><td class="n">${b.vat===null?'—':accAed(b.vat)}</td></tr>`).join('')}<tr><td>12</td><td>Total value of due tax for the period</td><td></td><td class="n">${accAed(r.output.standardVat)}</td></tr><tr><td>13</td><td>Total value of recoverable tax for the period</td><td></td><td class="n">${accAed(r.input.vat)}</td></tr><tr class="total"><td>14</td><td>${r.netVat>=0?'Payable tax for the period':'Refundable tax for the period'}</td><td></td><td class="n">${accAed(Math.abs(r.netVat))}</td></tr></table>`}
function vatLines(rows,input){const sum=k=>rows.reduce((n,x)=>n+x[k],0);return `<table><tr><th>Date</th><th>Document</th><th>No.</th><th>${input?'Supplier / details':'Customer'}</th>${input?'<th>Supplier TRN</th>':''}<th class="n">Before VAT</th><th class="n">VAT</th><th class="n">Total</th></tr>${rows.map(x=>`<tr${x.vat<0?' style="color:#b42318"':''}><td>${esc(x.date)}</td><td>${esc(x.type)}</td><td>${esc(x.number)}</td><td>${esc(x.party)}</td>${input?`<td>${esc(x.trn||'—')}</td>`:''}<td class="n">${accAed(x.net)}</td><td class="n">${accAed(x.vat)}</td><td class="n">${accAed(x.total)}</td></tr>`).join('')}<tr class="total"><td colspan="${input?5:4}">Total</td><td class="n">${accAed(sum('net'))}</td><td class="n">${accAed(sum('vat'))}</td><td class="n">${accAed(sum('total'))}</td></tr></table>`}
function vatHtml(r){const due=r.netVat>=0;return `<div class="row"><div><div class="eyebrow">OWNER ACCOUNTS</div><h2>VAT report</h2><p>${esc(r.from)} to ${esc(r.to)}${r.trn?' · TRN '+esc(r.trn):''}</p></div></div>${periodPicker()}
 ${r.trn?'':'<p class="pending-note">No TRN is saved in Settings. If you are VAT registered, add it so your bills print as tax invoices.</p>'}
 <div class="grid"><div class="panel">Output VAT<br><small>collected from customers on sales</small><div class="metric">${money(r.output.standardVat)}</div></div><div class="panel">Input VAT<br><small>paid to suppliers on purchases & expenses</small><div class="metric">${money(r.input.vat)}</div></div><div class="panel">${due?'Net VAT payable to FTA':'Net VAT refundable from FTA'}<br><small>output VAT − input VAT</small><div class="metric">${money(Math.abs(r.netVat))}</div></div></div>
 <div class="panel"><h3>Output VAT · sales</h3><p class="helper">Every tax invoice issued in the period. Refunds (credit notes) are shown in red and reduce the VAT collected.</p>${r.outputLines.length?`<details${r.outputLines.length<=15?' open':''}><summary><b>${r.outputLines.length} documents</b> · VAT ${money(r.output.standardVat)} · show / hide list</summary><div class="scroll">${vatLines(r.outputLines,false)}</div></details>`:'<p>No sales in this period.</p>'}</div>
 <div class="panel"><div class="row"><h3>Input VAT · purchases & expenses</h3><button class="primary" onclick="financeView='Purchases';financeScreen()">+ Record purchase bill</button></div><p class="helper">VAT you paid on supplier tax invoices (Finance → Purchases & suppliers) and on expenses with VAT (Finance → Daily closing → Record expense). Only claim VAT when the invoice shows the supplier's TRN.</p><div class="scroll">${r.inputLines.length?`<p><b>${r.inputLines.length} documents</b> · VAT ${money(r.input.vat)}</p>`+vatLines(r.inputLines,true):'<p class="pending-note">No purchases recorded in this period, so input VAT is 0. Record your supplier bills to claim the VAT you paid.</p>'}</div></div>
 <div class="panel"><h3>VAT return · FTA VAT 201 boxes</h3><p class="helper">Copy these figures into EmaraTax.</p><div class="scroll">${vatTable(r)}</div>${r.notes.map(n=>`<p class="pending-note">${esc(n)}</p>`).join('')}</div>
 <div class="actions"><button onclick="exportVat()">Export CSV (with every invoice)</button><button class="primary" onclick="printVat()">Print / Save PDF</button></div>`}
function exportVat(){const r=accData;if(!r)return;const row=x=>[x.date,x.type,x.number,x.party,x.trn??'',accAed(x.net),accAed(x.vat),accAed(x.total)];saveCsv('vat-report-'+r.from+'-'+r.to+'.csv',[['VAT report',r.business,'TRN',r.trn],['Period',r.from,r.to],[],['Output VAT (sales)',accAed(r.output.standardVat)],['Input VAT (purchases & expenses)',accAed(r.input.vat)],[r.netVat>=0?'Net VAT payable':'Net VAT refundable',accAed(Math.abs(r.netVat))],[],['OUTPUT VAT · SALES'],['Date','Document','No.','Customer','','Before VAT','VAT','Total'],...r.outputLines.map(row),[],['INPUT VAT · PURCHASES & EXPENSES'],['Date','Document','No.','Supplier / details','Supplier TRN','Before VAT','VAT','Total'],...r.inputLines.map(row),[],['FTA VAT 201'],['Box','Description','Amount AED','VAT AED'],...r.boxes.map(b=>[b.box,b.label,accAed(b.amount),b.vat===null?'':accAed(b.vat)]),['14',r.netVat>=0?'Payable tax':'Refundable tax','',accAed(Math.abs(r.netVat))],[],...r.notes.map(n=>['Note',n])])}
function printVat(){const r=accData;if(r)printReport('VAT report '+r.from,`<h2>VAT report · ${esc(r.from)} to ${esc(r.to)}</h2><table><tr><td>Output VAT (sales)</td><td class="n">${accAed(r.output.standardVat)}</td></tr><tr><td>Input VAT (purchases & expenses)</td><td class="n">${accAed(r.input.vat)}</td></tr><tr class="total"><td>${r.netVat>=0?'Net VAT payable':'Net VAT refundable'}</td><td class="n">${accAed(Math.abs(r.netVat))}</td></tr></table><h2>Output VAT · sales</h2>${vatLines(r.outputLines,false)}<h2>Input VAT · purchases & expenses</h2>${vatLines(r.inputLines,true)}<h2>FTA VAT 201 boxes</h2>${vatTable(r)}${r.notes.map(n=>`<p class="muted">${esc(n)}</p>`).join('')}`)}

// ---------- Profit & loss ----------
function plTable(r){const line=(l,v,cls='')=>`<tr${cls?` class="${cls}"`:''}><td>${esc(l)}</td><td class="n">${accAed(v)}</td></tr>`;return `<table><tr><th>Income</th><th class="n">AED</th></tr>${line('Sales before discounts',r.sales.gross)}${line('Less discounts',-r.sales.discounts)}${line('Less refunds',-r.sales.refunds)}${line('Net sales',r.sales.net,'total')}<tr><th>Cost of sales</th><th></th></tr>${line('Stock purchases',-r.costOfSales)}${line('Gross profit',r.grossProfit,'total')}<tr><th>Expenses</th><th></th></tr>${r.expenses.map(e=>line(e.label,-e.amount)).join('')||'<tr><td>No expenses recorded</td><td></td></tr>'}${line('Total expenses',-r.totalExpenses,'total')}${line(r.netProfit>=0?'Net profit':'Net loss',r.netProfit,'total')}</table>`}
function plHtml(r){return `<div class="row"><div><div class="eyebrow">OWNER ACCOUNTS</div><h2>Profit & loss</h2><p>${esc(r.from)} to ${esc(r.to)} · before VAT</p></div></div>${periodPicker()}
 <div class="grid">${[['Net sales',r.sales.net],['Gross profit',r.grossProfit],[r.netProfit>=0?'Net profit':'Net loss',r.netProfit]].map(([l,v])=>`<div class="panel">${l}<div class="metric">${amt(v)}</div></div>`).join('')}<div class="panel">Net margin<div class="metric">${r.margin}%</div></div></div>
 <div class="panel"><div class="scroll">${plTable(r)}</div>${r.notes.map(n=>`<p class="helper">${esc(n)}</p>`).join('')}</div>
 <div class="actions"><button onclick="exportPl()">Export CSV</button><button class="primary" onclick="printPl()">Print / Save PDF</button></div>`}
function exportPl(){const r=accData;if(!r)return;saveCsv('profit-loss-'+r.from+'-'+r.to+'.csv',[['Profit & loss',r.from,r.to,'AED before VAT'],['Sales before discounts',accAed(r.sales.gross)],['Discounts',accAed(-r.sales.discounts)],['Refunds',accAed(-r.sales.refunds)],['Net sales',accAed(r.sales.net)],['Stock purchases',accAed(-r.costOfSales)],['Gross profit',accAed(r.grossProfit)],...r.expenses.map(e=>[e.label,accAed(-e.amount)]),['Total expenses',accAed(-r.totalExpenses)],['Net profit',accAed(r.netProfit)],[],...r.notes.map(n=>['Note',n])])}
function printPl(){const r=accData;if(r)printReport('Profit and loss '+r.from,`<h2>Profit & loss · ${esc(r.from)} to ${esc(r.to)}</h2>${plTable(r)}${r.notes.map(n=>`<p class="muted">${esc(n)}</p>`).join('')}`)}

// ---------- Cash & bank ----------
const BOOK_LABEL={Cash:'Cash book',Bank:'Bank / card book'};
function bookTable(name,b){return `<table><tr><th>Date</th><th>Type</th><th>Details</th><th class="n">In</th><th class="n">Out</th><th class="n">Balance</th></tr><tr><td></td><td colspan="4">Opening balance</td><td class="n">${accAed(b.opening)}</td></tr>${b.entries.map(e=>`<tr><td>${esc(e.date)}</td><td>${esc(e.type)}</td><td>${esc(e.detail)}</td><td class="n">${e.amount>0?accAed(e.amount):''}</td><td class="n">${e.amount<0?accAed(-e.amount):''}</td><td class="n">${accAed(e.balance)}</td></tr>`).join('')}<tr class="total"><td colspan="3">Closing balance</td><td class="n">${accAed(b.inflow)}</td><td class="n">${accAed(b.outflow)}</td><td class="n">${accAed(b.closing)}</td></tr></table>`}
function bookHtml(r){return `<div class="row"><div><div class="eyebrow">OWNER ACCOUNTS</div><h2>Cash & bank book</h2><p>${esc(r.from)} to ${esc(r.to)} · every money movement recorded in the POS</p></div></div>${periodPicker()}
 <div class="grid">${['Cash','Bank'].map(k=>`<div class="panel">${BOOK_LABEL[k]} · in ${money(r.books[k].inflow)} · out ${money(r.books[k].outflow)}<div class="metric">${amt(r.books[k].closing-r.books[k].opening)}</div><small>movement in period</small></div>`).join('')}</div>
 ${['Cash','Bank'].map(k=>`<div class="panel"><h3>${BOOK_LABEL[k]}</h3><div class="scroll">${bookTable(k,r.books[k])}</div></div>`).join('')}${r.notes.map(n=>`<p class="helper">${esc(n)}</p>`).join('')}
 <div class="actions"><button onclick="exportBook()">Export CSV</button><button class="primary" onclick="printBook()">Print / Save PDF</button></div>`}
function exportBook(){const r=accData;if(!r)return;saveCsv('cash-bank-'+r.from+'-'+r.to+'.csv',[['Cash & bank book',r.from,r.to,'AED'],...['Cash','Bank'].flatMap(k=>{const b=r.books[k];return[[],[BOOK_LABEL[k]],['Date','Type','Details','In','Out','Balance'],['','Opening balance','','','',accAed(b.opening)],...b.entries.map(e=>[e.date,e.type,e.detail,e.amount>0?accAed(e.amount):'',e.amount<0?accAed(-e.amount):'',accAed(e.balance)]),['','Closing balance','',accAed(b.inflow),accAed(b.outflow),accAed(b.closing)]]})])}
function printBook(){const r=accData;if(r)printReport('Cash and bank '+r.from,`<h2>Cash & bank book · ${esc(r.from)} to ${esc(r.to)}</h2>${['Cash','Bank'].map(k=>`<h2>${BOOK_LABEL[k]}</h2>${bookTable(k,r.books[k])}`).join('')}${r.notes.map(n=>`<p class="muted">${esc(n)}</p>`).join('')}`)}

function openFinanceView(v){financeView=v;navigate('Finance')}
