'use strict';
// Subscription & payment (Stripe). Trial / renewal reminders, plan chooser, Stripe Checkout and Stripe's billing page,
// and the lock screen shown to an owner whose trial or subscription has ended (data is kept; paying unlocks it).
let billingInfo=null,billingFetched=0,billingYearly=false;
const BILLING_PLANS=[['Starter','For a small shop with one counter',['1 branch · 1 device','1 owner + 1 staff login','VAT invoices & receipts','Works offline up to 12 hours']],['Pro','For busy shops with a team',['1 branch · up to 3 devices','Unlimited staff logins','Staff & sales reports, cash closing','Works offline up to 7 days']],['Business','For several branches or kiosks',['Up to 3 branches · 10 devices','Stock per branch & transfers','Works offline up to 30 days','On-site setup in Dubai']]];
const billDate=v=>v?new Date(v).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Dubai'}):'';
async function loadBilling(force){if(!force&&billingInfo&&Date.now()-billingFetched<3600000)return billingInfo;try{billingInfo=await api('billing/status');billingFetched=Date.now()}catch{}return billingInfo}
// Locked shops: skip the normal workspace and show the payment screen.
const enterBeforeBilling=enterSalon;
enterSalon=async function(session){if(session.user?.billingLocked){csrf=session.csrf;cloudUser=session.user;await loadBilling(true);showBillingLock();return}await enterBeforeBilling(session);loadBilling(true).then(()=>{if(cloudReady)billingBar()})};
function showBillingLock(){$('boot').classList.add('hidden');$('boot').setAttribute('inert','');$('nav').innerHTML='';$('cloudStatus')?.remove();$('billingBar')?.remove();const b=billingInfo||{},owner=cloudUser?.role==='owner';
 $('app').innerHTML=`<div class="panel" style="max-width:760px;margin:30px auto"><div class="eyebrow">SUBSCRIPTION</div><h2>${b.status==='trial'?'Your free trial has ended':'Your subscription has ended'}</h2><p>Your shop, products, customers and sales are <b>safe and kept</b>. Choose a plan to continue right where you left off.</p>${b.enabled?'':`<p class="pending-note">Online payment is not switched on yet. Contact WiFi Palace on WhatsApp to renew.</p>`}<div id="billingPlans">${plansHtml(b)}</div><div class="actions">${b.subscription?'<button onclick="billingPortal()">Update card / invoices</button>':''}<button onclick="billingSignOut()">Sign out</button></div><p class="helper">Payments are handled by Stripe. Prices exclude 5% VAT. Tills that were offline keep their unsent sales and upload them after renewal.</p></div>`;
 wirePlans()}
async function billingSignOut(){try{await api('logout','POST',{})}catch{}location.reload()}
function plansHtml(b){const p=b.prices||{Starter:{month:4900,year:49000},Pro:{month:12900,year:129000},Business:{month:24900,year:249000}},cur=b.subscription;
 return `<div class="actions" role="group" aria-label="Billing period" style="margin-bottom:12px"><button data-bill-period="month" class="${billingYearly?'':'primary'}">Monthly</button><button data-bill-period="year" class="${billingYearly?'primary':''}">Yearly · 2 months free</button></div><div class="grid">${BILLING_PLANS.map(([name,note,items])=>{const amount=p[name][billingYearly?'year':'month'],same=cur&&cur.plan===name&&cur.interval===(billingYearly?'year':'month');return `<div class="panel"><h3>${name}</h3><div class="metric" style="font-size:28px;white-space:nowrap">AED ${(amount/100).toFixed(0)}<small style="font-size:13px">/${billingYearly?'year':'month'}</small></div><p class="helper">${note}</p><ul style="padding-left:18px;margin:8px 0 14px">${items.map(i=>`<li>${esc(i)}</li>`).join('')}</ul><button class="${name==='Pro'?'primary':''}" data-bill-plan="${name}" ${same?'disabled':''}>${same?'Current plan':cur&&['active','trialing','past_due'].includes(cur.status)?'Switch to '+name:'Choose '+name}</button></div>`}).join('')}</div>`}
function wirePlans(){document.querySelectorAll('[data-bill-period]').forEach(x=>x.onclick=()=>{billingYearly=x.dataset.billPeriod==='year';$('billingPlans').innerHTML=plansHtml(billingInfo||{});wirePlans()});document.querySelectorAll('[data-bill-plan]').forEach(x=>x.onclick=()=>choosePlan(x.dataset.billPlan,x))}
async function choosePlan(plan,button){if(cloudUser?.role!=='owner'){alert('Ask the shop owner to choose a plan.');return}const interval=billingYearly?'year':'month',live=billingInfo?.subscription&&['active','trialing','past_due'].includes(billingInfo.subscription.status);
 if(live&&!confirm(`Switch to ${plan} (${interval==='year'?'yearly':'monthly'})? The difference is charged or credited now on your card.`))return;
 button.disabled=true;const old=button.textContent;button.textContent='Opening secure payment…';
 try{if(live){billingInfo=await api('billing/change','POST',{plan,interval});toast('Plan changed to '+plan);closeModal?.();if(cloudUser?.billingLocked)location.reload();else render();return}const r=await api('billing/checkout','POST',{plan,interval});location.href=r.url}
 catch(e){alert(e.message);button.disabled=false;button.textContent=old}}
async function billingPortal(){try{const r=await api('billing/portal','POST',{});location.href=r.url}catch(e){alert(e.message)}}
function planModal(){loadBilling(true).then(b=>{modal(`<h2>Choose your plan</h2><div id="billingPlans">${plansHtml(b||{})}</div><p class="helper">Payments by card through Stripe · prices exclude 5% VAT · cancel any time from Manage billing.${b?.status==='trial'&&b.daysLeft>0?' Your remaining free days are kept: the first charge is on '+esc(billDate(b.expires))+'.':''}</p><div class="actions"><button onclick="closeModal()">Close</button></div>`);wirePlans()})}
// Reminder bar: trial ending, payment problem, or cancellation scheduled.
function billingBar(){$('billingBar')?.remove();const b=billingInfo;if(!b||!cloudReady||cloudUser?.demo)return;const owner=cloudUser?.role==='owner',sub=b.subscription;let text='',action='';
 if(sub?.status==='past_due'){text=`Card payment failed. Update your card before ${billDate(b.expires)} to keep using the POS.`;action=owner?'<button class="primary" onclick="billingPortal()">Update card</button>':''}
 else if(b.status==='trial'&&!sub&&b.daysLeft!==null&&b.daysLeft<=7){text=`Free trial: ${b.daysLeft} day${b.daysLeft===1?'':'s'} left.`;action=owner?'<button class="primary" onclick="planModal()">Choose a plan</button>':''}
 else if(sub?.cancelAtPeriodEnd){text=`Subscription ends on ${billDate(sub.periodEnd)}.`;action=owner?'<button onclick="billingPortal()">Keep subscription</button>':''}
 if(!text||(!owner&&sub?.status!=='past_due'&&b.daysLeft>3))return;
 const bar=document.createElement('div');bar.id='billingBar';bar.className='pending-note';bar.style.cssText='display:flex;gap:12px;align-items:center;justify-content:space-between;flex-wrap:wrap;margin:10px 16px';bar.innerHTML=`<span>${esc(text)}${owner?'':' Tell the shop owner.'}</span>${action}`;($('cloudStatus')||$('nav')).after(bar)}
const renderBeforeBilling=render;
render=function(){renderBeforeBilling.apply(this,arguments);if(cloudReady){if(!$('billingBar'))billingBar();if(Date.now()-billingFetched>6*3600000)loadBilling(true).then(billingBar)}};
// Account screen: subscription panel for the owner.
const accountBeforeBilling=accountScreen;
accountScreen=function(){accountBeforeBilling();if(cloudUser?.role!=='owner'||cloudUser?.demo)return;const host=document.querySelector('#app .layout')||$('app');const panel=document.createElement('section');panel.className='panel';panel.id='billingPanel';panel.innerHTML='<h2>Subscription</h2><p>Loading…</p>';host.appendChild(panel);
 loadBilling(true).then(b=>{if(!$('billingPanel')||!b)return;const sub=b.subscription,state=sub?({active:'Active',trialing:'Free trial (card saved)',past_due:'Payment failed',canceled:'Cancelled',unpaid:'Unpaid'}[sub.status]||sub.status):b.status==='trial'?'Free trial':'Active';
  $('billingPanel').innerHTML=`<h2>Subscription</h2><p><b>${esc(b.plan||'—')}</b>${sub?' · '+(sub.interval==='year'?'yearly':'monthly'):''} · ${esc(state)}</p><p>${sub&&sub.periodEnd?(sub.cancelAtPeriodEnd?'Ends on ':'Next payment on ')+esc(billDate(sub.periodEnd)):b.expires?(b.status==='trial'?'Free trial until ':'Paid until ')+esc(billDate(b.expires)):''}</p>${b.enabled?`<div class="actions"><button class="primary" onclick="planModal()">${sub&&['active','trialing','past_due'].includes(sub.status)?'Change plan':'Choose a plan'}</button>${sub?'<button onclick="billingPortal()">Manage card, invoices & cancel</button>':''}</div>`:'<p class="helper">Online payment is being set up. To renew, contact WiFi Palace on WhatsApp.</p>'}<p class="helper">Prices exclude 5% VAT. Tax invoices are emailed after each payment.</p>`})};
// Back from Stripe Checkout.
(function(){const q=new URLSearchParams(location.search),r=q.get('billing');if(!r)return;history.replaceState(null,'',location.pathname+(location.hash||''));
 if(r==='cancelled'){setTimeout(()=>toast('Payment cancelled. Nothing was charged.'),1500);return}
 let tries=0;const check=async()=>{tries++;try{const me=await api('me');if(me.user.billingLocked&&tries<10){setTimeout(check,3000);return}await loadBilling(true);toast('Payment received. Thank you!');if(cloudUser?.billingLocked&&!me.user.billingLocked)location.reload();else billingBar()}catch{if(tries<10)setTimeout(check,3000)}};setTimeout(check,2000)})();
