'use strict';
const CLOUD_KEY='wifi-palace-cloud-v2';
let cloudUser=null,csrf='',cache=null,cloudOnline=false,syncing=false,reconciling=false,syncProblem='',cloudReady=false;
const localRender=render,localSettings=settings,localReceipt=receipt,localDownload=download;
const clone=SyncCore.clone;
// Device storage: IndexedDB (hundreds of MB) instead of localStorage (about 5 MB). put() copies the value
// synchronously, so saveCache keeps its simple call-and-continue behaviour; write failures raise a banner.
const IDB_NAME='wifi-palace-pos',IDB_STORE='kv',HISTORY_DAYS=35,FULL_REFRESH_MS=6*3600000;
let idb=null,storageError='';
function idbOpen(){return new Promise((resolve,reject)=>{if(!window.indexedDB){reject(Error('IndexedDB unavailable'));return}const r=indexedDB.open(IDB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(IDB_STORE);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function idbGet(key){return new Promise((resolve,reject)=>{const q=idb.transaction(IDB_STORE).objectStore(IDB_STORE).get(key);q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}
function idbWrite(key,value){const tx=idb.transaction(IDB_STORE,'readwrite'),store=tx.objectStore(IDB_STORE);value===undefined?store.delete(key):store.put(value,key);return new Promise((resolve,reject)=>{tx.oncomplete=()=>{if(storageError){storageError='';paintStatus()}resolve()};tx.onerror=tx.onabort=()=>{storageError='This device could not save data ('+(tx.error?.message||'storage error')+'). Free up space and sync now.';paintStatus();reject(tx.error)}})}
function saveCache(){if(!cache)throw Error('No signed-in business');if(idb){idbWrite(CLOUD_KEY,cache).catch(()=>{});return}localStorage.setItem(CLOUD_KEY,JSON.stringify(cache))}
function dropCache(){if(idb)idbWrite(CLOUD_KEY,undefined).catch(()=>{});try{localStorage.removeItem(CLOUD_KEY)}catch{}}
async function loadCache(){try{idb=await idbOpen();navigator.storage?.persist?.().catch(()=>{})}catch{idb=null}
 if(idb){const stored=await idbGet(CLOUD_KEY);if(stored)return stored;const raw=localStorage.getItem(CLOUD_KEY);if(!raw)return null;const old=JSON.parse(raw);await idbWrite(CLOUD_KEY,old);localStorage.removeItem(CLOUD_KEY);return old}
 const raw=localStorage.getItem(CLOUD_KEY);return raw?JSON.parse(raw):null}
function offlineMs(){return (cache?.offlineHours||cloudUser?.offlineHours||12)*3600000}
// Light sync: recent history only, then just the records that changed since the last cursor.
function applyMeta(r){if('summary' in r)cache.summary=r.summary||null;cache.lastSynced=r.serverTime;cache.offlineHours=r.offlineHours||cache.offlineHours||12;cache.offlineUntil=Date.now()+offlineMs()}
async function refreshState(forceFull=false){
 if(!forceFull&&Number.isSafeInteger(cache.seq)&&cache.fullAt&&Date.now()-cache.fullAt<FULL_REFRESH_MS){const c=await api('changes?after='+cache.seq+'&days='+HISTORY_DAYS);if(!c.reload){for(const r of c.records){SyncCore.apply(cache.base,{kind:r.kind,key:r.key,data:r.data});cache.revisions[r.kind+':'+r.key]=r.version}cache.seq=c.seq;applyMeta(c);return}}
 const st=await api('state?days='+HISTORY_DAYS);cache.base=st.state;cache.revisions=st.revisions;cache.seq=st.seq;cache.historyDays=st.historyDays;cache.fullAt=Date.now();applyMeta(st)}
// Each device is a till with its own invoice series, so receipts printed offline are final tax invoices.
async function ensureTill(){try{let dev=await (idb?idbGet('device'):null);if(!dev?.id){dev={id:crypto.randomUUID()};if(idb)await idbWrite('device',dev)}const t=await api('till','POST',{device:dev.id,name:''});const same=cache.till&&cache.till.business===cache.user.salonId&&cache.till.code===t.code;cache.till={business:cache.user.salonId,code:t.code,name:t.name,next:Math.max(same?cache.till.next:1,(t.last||0)+1)};saveCache()}catch{}}
function numberNewSales(before){if(!cache?.till||cache.till.business!==cache.user.salonId)return;const known=new Set(before.sales.map(s=>s.id));for(const s of db.sales)if(!known.has(s.id)&&!/^INV-/.test(s.number||'')){s.number='INV-T'+cache.till.code+'-'+String(cache.till.next++).padStart(6,'0')}}
function cloudDownload(name,text,type='application/json'){let a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
// Android delegates exports to the original native bridge. Web browsers download directly.
download=function(name,text,type){if(window.Android)Android.exportFile(name,text,type);else cloudDownload(name,text,type)};
async function api(path,method='GET',data,{timeout}={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout||(path.startsWith('state')?45000:15000));try{const response=await fetch('/api/'+path,{method,credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},...(data===undefined?{}:{body:JSON.stringify(data)}),signal:controller.signal});let result=await response.json();if(!response.ok){const error=Error(result.error||'Request failed');error.status=response.status;throw error}return result}finally{clearTimeout(timer)}}
function trustedCache(c){return c&&c.schema===2&&c.user?.id&&c.user?.salonId&&['owner','cashier'].includes(c.user.role)&&valid(c.base)&&Array.isArray(c.pending)&&c.revisions&&c.pending.every(o=>o.id&&o.kind&&o.key&&Number.isInteger(o.base))}
function paintStatus(){const node=$('cloudStatus');if(!node)return;const n=cache?.pending.length||0,left=cache?.offlineUntil?cache.offlineUntil-Date.now():0,soon=!cloudOnline&&left<24*3600000;
 const note=storageError?`<span class="danger">${esc(storageError)}</span>`:!cloudOnline&&cache?`<span class="${soon?'danger':'helper'}">Offline since ${esc(cache.lastSynced?new Date(cache.lastSynced).toLocaleString([], {day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'—')} · works offline until ${esc(new Date(cache.offlineUntil).toLocaleString([], {day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}))}${soon?' · connect soon':''}</span>`:'';
 node.innerHTML=`<span class="badge">${syncing?'Syncing…':syncProblem?'Needs attention':cloudOnline?'Cloud connected':'Offline'}</span> <span>${n} pending</span> ${note} <button onclick="syncNow(true)">Sync now</button> ${!cloudOnline&&n?'<button onclick="exportPending()">Back up pending</button>':''} <button onclick="navigate('Account')">${esc(cloudUser?.name||'Account')}</button>`}
render=function(){if(!cloudReady)return;localRender();let strip=$('cloudStatus');if(!strip){strip=document.createElement('div');strip.id='cloudStatus';strip.className='cloud-status';$('nav').after(strip)}paintStatus();const tabs=cloudUser?.role==='owner'?['Dashboard','Checkout','Appointments','Customers','Sales','Services & staff','Settings','Finance','Reports','Team','Sync centre','Account']:['Checkout','Appointments','Customers','My sales','Sync centre','Account'];$('nav').innerHTML=tabs.map(t=>`<button class="${tab===t?'active':''}" data-cloud-tab="${esc(t)}">${esc(t)}</button>`).join('');document.querySelectorAll('[data-cloud-tab]').forEach(b=>b.onclick=()=>navigate(b.dataset.cloudTab));$('footerVersion').textContent='Cloud edition 2.0';};
const basicNavigate=navigate;
navigate=function(next){if(!cloudReady)return;if(cloudUser.role!=='owner'&&['Dashboard','Sales','Services & staff','Settings','Finance','Reports','Team'].includes(next)){alert('Owner access required');return}tab=next;if(['Account','Team','Sync centre','My sales'].includes(tab)){renderCloudOnly();return}basicNavigate(next)};
const renderOriginal=render;
render=function(){if(!cloudReady)return;if(['Account','Team','Sync centre','My sales'].includes(tab)){renderCloudOnly();return}renderOriginal()};
function renderCloudOnly(){const next=tab;tab=cloudUser.role==='owner'?'Dashboard':'Checkout';renderOriginal();tab=next;document.querySelectorAll('[data-cloud-tab]').forEach(b=>b.classList.toggle('active',b.dataset.cloudTab===tab));if(tab==='Account')accountScreen();if(tab==='Team')teamScreen();if(tab==='Sync centre')syncScreen();if(tab==='My sales'){sales();document.querySelectorAll('[data-refund]').forEach(b=>b.remove());$('app').insertAdjacentHTML('afterbegin','<p class="helper">Showing sales created by your account.</p>')}}
change=function(fn){if(reconciling){alert('Wait for pending-change review to finish');return false}if(!cloudReady||!cache){alert('Sign in first');return false}if(!cloudOnline&&Date.now()>cache.offlineUntil){alert('Offline access expired. Connect and sign in before continuing.');return false}const before=clone(db),oldCache=clone(cache);try{fn();numberNewSales(before);if(!valid(db))throw Error('Invalid record');const ops=SyncCore.diff(before,db,cache,()=>crypto.randomUUID());if(cloudUser.role!=='owner'&&ops.some(o=>['settings','vendor','services','staff'].includes(o.kind)||(o.kind==='sales'&&o.base>0)))throw Error('Owner permission required');cache.pending.push(...ops);saveCache();render();setTimeout(()=>syncNow(),150);return true}catch(e){db=before;cache=oldCache;alert('Not saved: '+e.message);return false}};
persist=function(){saveCache()};
restoreData=function(){alert('Replacing cloud records with an offline backup is disabled. Existing offline backups need a reviewed migration, so they cannot overwrite cloud sales.')};
backup=function(){if(cloudUser?.role!=='owner'){alert('Only an owner can export a business backup');return}download('salon-cloud-backup-'+day()+'.json',JSON.stringify({schema:2,exportedAt:new Date().toISOString(),user:cloudUser,state:db,pending:cache.pending},null,2),'application/json')};
const originalRefund=refund;refund=function(id){if(cloudUser?.role!=='owner'){alert('Only an owner can refund a sale');return}originalRefund(id)};
receipt=function(id){localReceipt(id);const pending=cache.pending.some(o=>o.kind==='sales'&&o.key===id);$('modal').insertAdjacentHTML('afterbegin',`<p class="${pending?'pending-note':'helper'}">${pending?'Saved on this device · Awaiting cloud confirmation':'Cloud-confirmed receipt'}</p>`)};
function forceSignIn(message){cloudOnline=false;cloudReady=false;showLogin(message);}
async function syncNow(manual=false){if(syncing||!cloudReady)return;syncing=true;paintStatus();try{const session=await api('me');if(session.user.id!==cache.user.id||session.user.salonId!==cache.user.salonId){forceSignIn('This browser signed into another account. Sign back into the original account to sync.');return}csrf=session.csrf;cloudUser=session.user;cache.user=cloudUser;cloudOnline=true;
 while(cache.pending.length){const op=clone(cache.pending[0]);let result;try{result=await api('sync','POST',op)}catch(e){if([400,403,409,413].includes(e.status)){syncProblem=e.message;cache.problem={id:op.id,message:e.message};saveCache();if(manual)alert('Sync paused: '+e.message);break}throw e}
  const previous=clone(cache);try{SyncCore.ack(cache,result);delete cache.problem;saveCache();db=SyncCore.project(cache)}catch(e){cache=previous;throw e}
 }
 await refreshState(manual);saveCache();db=SyncCore.project(cache);if(!cache.pending.length){syncProblem='';delete cache.problem;saveCache()}if(manual&&!cache.pending.length)toast('All changes synced');
 // Avoid rebuilding a live form or unpaid bill while a background response arrives.
 if(!$('modal').open&&!['Checkout','Settings','Customers','Appointments','Services & staff','Account','Finance','Reports','Marketing','HR','Ingredients','Team'].includes(tab))render();
 }catch(e){cloudOnline=false;if(e.status===401){forceSignIn(e.message)}else{syncProblem=e.status?e.message:'';if(manual)alert(e.status?e.message:'Cannot reach the server. Your saved changes remain on this device.')}}finally{syncing=false;paintStatus()}}
function showLogin(message=''){$('boot').classList.add('hidden');$('boot').setAttribute('inert','');$('nav').innerHTML='';$('cloudStatus')?.remove();$('app').innerHTML=`<div class="login-shell"><div class="login-story"><div class="eyebrow">PALACE POS · BY WIFI PALACE</div><h2>Your business.<br>Connected.</h2><p>One workspace for your team, your customers and every sale.</p><div class="login-points"><div>01 &nbsp; A private workspace for each business</div><div>02 &nbsp; Offline billing with cloud sync</div><div>03 &nbsp; Owner access from anywhere</div></div></div><div class="panel login-form"><span class="badge">Cloud edition</span><h2 style="margin-top:20px">Welcome back</h2><p>Sign in to your business workspace.</p>${message?`<p class="pending-note" role="alert">${esc(message)}</p>`:''}<form id="loginForm"><label>Business code</label><input id="salonCode" autocomplete="organization" required placeholder="e.g. al-noor-laundry"><label>Email</label><input id="loginEmail" type="email" autocomplete="username" required><label>Password</label><input id="loginPassword" type="password" autocomplete="current-password" required><button class="primary" id="loginButton" style="width:100%">Sign in →</button></form><p class="helper">New business owner? <a href="/signup">Start your free month</a>. Team accounts are created by your business owner. <a href="/recover">Forgot password?</a> · <a href="/recover?codes=1">Forgot business code?</a></p>${cache?.pending.length?`<p class="pending-note">${cache.pending.length} changes are waiting for ${esc(cache.user.email)}. Sign into that account to sync them.</p>`:''}${cache&&Date.now()<cache.offlineUntil?'<button onclick="resumeOffline()">Continue on this device offline</button>':''}<p style="margin-top:18px;text-align:center"><a href="/demo">Try a demo shop →</a></p></div></div>`;$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginButton').disabled=true;try{const result=await api('login','POST',{salon:$('salonCode').value,email:$('loginEmail').value,password:$('loginPassword').value});if(cache?.pending.length&&cache.user.id!==result.user.id){csrf=result.csrf;await api('logout','POST',{});throw Error('Sync the pending changes in the original account before switching accounts.')}await enterSalon(result)}catch(e){showLogin(e.message)}}}
const BUSINESS_LABELS={salon:'Salon & spa',laundry:'Laundry',grocery:'Grocery & baqala',restaurant:'Restaurant & café',petshop:'Pet shop',perfume:'Perfume & oud',meat:'Meat shop',mobile:'Mobile shop',tailor:'Tailoring & abaya',electronics:'Electronics & computers',gym:'Gym & fitness'};
function showBusinessType(user){if($('brandTag'))$('brandTag').textContent=(BUSINESS_LABELS[user?.businessType]||'Point of sale').toUpperCase()}
async function enterSalon(session){csrf=session.csrf;showBusinessType(session.user);const previous=cache;if(!(cache&&cache.user.id===session.user.id))cache={schema:2,user:session.user,base:null,revisions:{},pending:[]};cache.user=session.user;cache.offlineHours=session.user.offlineHours||12;try{await refreshState(true)}catch(e){cache=previous;throw e}await ensureTill();saveCache();cloudUser=session.user;cloudOnline=true;cloudReady=true;db=SyncCore.project(cache);storageFault=false;demoBar();cart=[];customer='';discount=0;stylist=db.staff[0]?.id||'';tab=cloudUser.role==='owner'?'Dashboard':'Checkout';render();showBoot();await syncNow()}
function resumeOffline(){if(!cache||Date.now()>cache.offlineUntil){alert('Connect and sign in to renew offline access');return}cloudUser=cache.user;cloudOnline=false;cloudReady=true;db=SyncCore.project(cache);tab=cloudUser.role==='owner'?'Dashboard':'Checkout';render();toast('Offline access · New changes stay on this device')}
async function logoutCloud(){if(cache.pending.length){alert('Sync your pending changes before signing out. They must stay with this account.');return}try{await api('logout','POST',{})}catch(e){alert('Connect to the server before signing out securely.');return}dropCache();cache=null;cloudUser=null;cloudReady=false;csrf='';cart=[];db=initial();$('headerLogo').innerHTML='P';$('brand').textContent='Palace POS';if($('brandTag'))$('brandTag').textContent='POINT OF SALE';showLogin()}
function syncScreen(){$('app').innerHTML=`<div class="row"><div><div class="eyebrow">EVERY CHANGE ACCOUNTED FOR</div><h2>Sync centre</h2></div><button class="primary" onclick="syncNow(true)">Sync now</button></div><div class="panel"><p>Last successful refresh: ${esc(cache.lastSynced?new Date(cache.lastSynced).toLocaleString():'Not yet')}</p><p class="helper">Requests are replay-safe: reconnecting does not create a second copy of a sale. Conflicts pause the queue for review.</p>${cache.problem?`<p class="pending-note">${esc(cache.problem.message)}</p>`:''}${cache.pending.length?cache.pending.map((o,i)=>`<div class="row"><div><b>${esc(o.kind)} · ${esc(o.action)}</b><div class="helper">${esc(o.key)}</div></div><span class="badge">${i===0&&cache.problem?'Needs review':'Waiting'}</span></div>`).join(''):'<div class="empty">All saved changes are in the cloud.</div>'}<div class="actions"><button onclick="exportPending()">Back up pending changes</button><label class="button" style="display:inline-block;cursor:pointer">Restore from backup<input type="file" accept=".json,application/json" hidden onchange="if(this.files[0])restorePending(this.files[0])"></label>${cache.pending.length?'<button class="danger" onclick="discardPending()">Review & discard pending changes</button>':''}</div><p class="helper">A backup holds only this device's unsynced changes. If a till breaks while offline, restore its backup on another device signed into the same business; nothing is duplicated.</p>${cache.till?`<p class="helper">This device is <b>Till ${cache.till.code}</b>. Next invoice number: INV-T${cache.till.code}-${String(cache.till.next).padStart(6,'0')}.</p>`:''}</div>`}
function exportPending(){if(!cache)return;download('pos-pending-backup-'+(cache.till?'T'+cache.till.code+'-':'')+new Date().toISOString().replace(/\D/g,'').slice(0,12)+'.json',JSON.stringify({format:'wifi-palace-pending',version:1,businessId:cache.user.salonId,user:{id:cache.user.id,email:cache.user.email},till:cache.till||null,exportedAt:new Date().toISOString(),pending:cache.pending},null,1),'application/json')}
function restorePending(file){const reader=new FileReader();reader.onload=()=>{try{const b=JSON.parse(reader.result);if(b.format!=='wifi-palace-pending'||!Array.isArray(b.pending))throw Error('This is not a pending-sales backup');if(b.businessId!==cache.user.salonId)throw Error('This backup belongs to a different business');const have=new Set(cache.pending.map(o=>o.id)),add=b.pending.filter(o=>o&&o.id&&o.kind&&o.key&&Number.isInteger(o.base)&&!have.has(o.id));if(!add.length){alert('Nothing new in this backup. Its changes are already on this device or already synced.');return}if(!confirm('Add '+add.length+' changes from this backup and sync them? Changes already in the cloud are recognised and not duplicated.'))return;cache.pending.push(...add);saveCache();db=SyncCore.project(cache);render();syncNow(true)}catch(e){alert('Not restored: '+e.message)}};reader.readAsText(file)}
async function discardPending(){
 if(syncing){alert('Wait for the current sync to finish');return}
 if(cloudUser.role!=='owner'){modal(`<h2>Owner review required</h2><p>Export the recovery copy and reconcile any money collected before discarding these pending changes.</p><form id="discardForm"><label>Owner email</label><input id="approvalEmail" type="email" required autocomplete="off"><label>Owner password</label><input id="approvalPassword" type="password" required autocomplete="off"><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="danger">Approve discard</button></div></form>`);$('discardForm').onsubmit=async e=>{e.preventDefault();const credentials={email:$('approvalEmail').value,password:$('approvalPassword').value};await executeDiscard(credentials)};return}
 await executeDiscard({});
}
async function executeDiscard(credentials){
 if(!confirm('Discard ALL unsynced changes from this device? Export a recovery copy first. Money already collected must be reconciled separately.'))return;
 syncing=true;reconciling=true;paintStatus();
 try{await api('approve-discard','POST',{...credentials,operations:cache.pending.map(x=>({id:x.id}))});const previous=clone(cache);await refreshState(true);cache.pending=[];delete cache.problem;try{saveCache()}catch(e){cache=previous;throw e}db=SyncCore.project(cache);syncProblem='';closeModal();render()}catch(e){alert('Not discarded: '+e.message)}finally{syncing=false;reconciling=false;paintStatus()}
}

settings=function(){localSettings();$('restore').disabled=true;for(const b of document.querySelectorAll('button'))if((b.getAttribute('onclick')||'').includes('restoreBackup'))b.disabled=true;$('app').insertAdjacentHTML('afterbegin','<p class="pending-note">Cloud settings sync across your business. Offline backup replacement is disabled to protect shared records.</p>')};
function accountScreen(){$('app').innerHTML=`<div class="layout"><section class="panel"><h2>Your account</h2><p>${esc(cloudUser.name)} · ${esc(cloudUser.email)}</p><span class="badge">${esc(cloudUser.role)}</span><form id="passwordForm" style="margin-top:24px"><h3>Change password</h3><label>Current password</label><input id="currentPassword" type="password" autocomplete="current-password" required><label>New password · at least 12 characters</label><input id="newPassword" type="password" autocomplete="new-password" minlength="12" maxlength="128" required><button class="primary">Change password</button></form><div class="support"><button onclick="logoutCloud()">Sign out of this device</button></div></section><aside class="panel"><h3>Device & cloud</h3><p>Business: ${esc(db.settings.name)}<br>Currency: AED</p><p class="helper">Online sessions last up to 12 hours. Offline access continues for up to ${(cache?.offlineHours||12)>=24?((cache?.offlineHours||12)/24)+' days':(cache?.offlineHours||12)+' hours'} after the last successful online connection on this trusted device. Keep your device locked when unattended.</p><p class="helper">Software by WiFi Palace<br>sales@wifipalace.com</p></aside></div>`;$('passwordForm').onsubmit=async e=>{e.preventDefault();if(cache.pending.length){alert('Sync pending changes before changing your password');return}try{await api('password','POST',{current:$('currentPassword').value,password:$('newPassword').value});forceSignIn('Password updated. All sessions were signed out. Sign in with your new password.')}catch(e){alert(e.message)}}}
async function teamScreen(){$('app').innerHTML='<div class="panel"><h2>Team access</h2><p>Loading accounts…</p></div>';try{const users=await api('users');if(tab!=='Team')return;$('app').innerHTML=`<div class="panel"><div class="row"><div><div class="eyebrow">THE RIGHT ACCESS FOR EVERY ROLE</div><h2>Team accounts</h2></div><button class="primary" onclick="addUserForm()">+ Add login</button></div><p>Staff names and sign-in accounts are separate. Owners manage the business; cashiers handle bookings and their own sales.${cloudUser.businessType==='restaurant'?' Waiters only take orders and send them to the kitchen.':''}</p><p class="helper">A PIN (4–6 digits) lets staff switch user quickly on a device that is already signed in. Owners always use their password.</p>${users.map(u=>`<div class="row"><div><b>${esc(u.name)}</b><div class="helper">${u.email.endsWith('@pin.invalid')?'PIN only':esc(u.email)} · ${esc(u.role)} · ${u.active?'Active':'Disabled'}${u.role==='owner'?'':u.hasPin?' · PIN set':' · no PIN'}</div></div>${u.id===cloudUser.id?'<span class="badge">You</span>':`<span class="actions" style="margin:0">${u.role==='owner'?'':`<button data-pin-user="${esc(u.id)}" data-pin-name="${esc(u.name)}">${u.hasPin?'Change PIN':'Set PIN'}</button>`}<button data-user="${esc(u.id)}" data-enable="${u.active?'false':'true'}">${u.active?'Disable':'Enable'}</button></span>`}</div>`).join('')}</div><div class="panel"><h3>Audit history</h3><button onclick="showAudit()">Load recent account & record changes</button><div id="auditLog"></div></div>`;document.querySelectorAll('[data-user]').forEach(b=>b.onclick=async()=>{if(!confirm('Change this account’s access?'))return;try{await api('users/'+b.dataset.user,'PATCH',{active:b.dataset.enable==='true'});teamScreen()}catch(e){alert(e.message)}});document.querySelectorAll('[data-pin-user]').forEach(b=>b.onclick=async()=>{const pin=prompt('New PIN for '+b.dataset.pinName+' (4 to 6 digits). Leave empty to remove the PIN.');if(pin===null)return;try{await api('users/'+b.dataset.pinUser,'PATCH',{pin:pin.trim()});toast(pin.trim()?'PIN saved':'PIN removed');teamScreen()}catch(e){alert(e.message)}})}catch(e){if(tab==='Team')$('app').innerHTML=`<div class="panel"><h2>Team access</h2><p>${esc(e.message)}</p><p>Team accounts require an online connection.</p></div>`}}
function addUserForm(){modal(`<h2>Create team login</h2><form id="userForm"><label>Name</label><input id="userName" required maxlength="100"><label>Role</label><select id="userRole"><option value="cashier">Cashier</option>${cloudUser.businessType==='restaurant'?'<option value="waiter">Waiter (orders only, no payments)</option>':''}<option value="owner">Owner</option></select><label id="userPinLabel">PIN for quick switching (4–6 digits, optional)</label><input id="userPin" inputmode="numeric" pattern="\\d{4,6}" maxlength="6" autocomplete="off"><label id="userEmailLabel">Email</label><input id="userEmail" type="email" required><label id="userPasswordLabel">Initial password</label><input id="userPassword" type="password" minlength="12" maxlength="128" required autocomplete="new-password"><p class="helper" id="userWaiterHelp" hidden>A waiter with a PIN needs no email or password: they tap <b>Switch user</b> on a phone or tablet that is already signed in. Add an email and password only if they sign in on their own phone.</p><p class="helper">Share credentials securely with your employee. They can change the password in Account. No email is sent automatically.</p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Create login</button></div></form>`);const roleChanged=()=>{const r=$('userRole').value,w=r==='waiter',o=r==='owner';$('userEmail').required=!w;$('userPassword').required=!w;$('userWaiterHelp').hidden=!w;$('userPin').disabled=o;$('userPinLabel').textContent=o?'PIN (owners use their password)':w?'PIN (4–6 digits)':'PIN for quick switching (4–6 digits, optional)';$('userEmailLabel').textContent=w?'Email (optional)':'Email';$('userPasswordLabel').textContent=w?'Password (optional, 12+ characters)':'Initial password'};$('userRole').onchange=roleChanged;roleChanged();$('userForm').onsubmit=async e=>{e.preventDefault();try{const pin=$('userRole').value==='owner'?'':$('userPin').value.trim();await api('users','POST',{name:$('userName').value,role:$('userRole').value,...($('userEmail').value?{email:$('userEmail').value}:{}),...($('userPassword').value?{password:$('userPassword').value}:{}),...(pin?{pin}:{})});closeModal();teamScreen()}catch(e){alert(e.message)}}}
async function showAudit(){try{const records=await api('audit');$('auditLog').innerHTML=records.map(r=>`<div class="row"><div>${esc(r.action)}<div class="helper">${esc(r.actor||'Account')} · ${esc(r.entity)}</div></div><span class="helper">${new Date(r.at).toLocaleString()}</span></div>`).join('')}catch(e){alert(e.message)}}
async function initCloud(){try{cache=await loadCache();if(cache&&!trustedCache(cache))throw Error('Invalid local cache')}catch{showLogin('Saved cloud data could not be read. Do not clear browser data; contact support for recovery.');return}try{const session=await api('me');await enterSalon(session)}catch(e){const why=e?.name==='AbortError'?'the server took too long to answer':(e?.message||'unknown error');showLogin(e.status===401?'':(cache?'The server is unreachable. You can continue offline on this previously signed-in device.':'Could not open your workspace.')+' (Details: '+why+')')}setInterval(()=>syncNow(),30000);window.addEventListener('online',()=>syncNow());if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').then(watchUpdates).catch(()=>{})}
// One tab at a time (protects this device's unsynced changes). "Use it here" asks the other tab to step aside:
// it reloads, and this tab waits for the lock the moment it is released.
const TAB_LOCK='salon-cloud-exclusive-tab',tabChannel=typeof BroadcastChannel==='function'?new BroadcastChannel('wifipos-tab'):null;
function holdTab(){if(tabChannel)tabChannel.onmessage=e=>{if(e.data==='takeover'){try{sessionStorage.setItem('wifipos-aside','1')}catch{}location.reload()}}}
const steppedAside=(()=>{try{const v=sessionStorage.getItem('wifipos-aside');sessionStorage.removeItem('wifipos-aside');return !!v}catch{return false}})();
function tabBusy(){showLogin('Palace POS is already open in another tab or window.');$('loginForm').innerHTML=tabChannel?'<button class="primary" id="takeoverTab" type="button" style="width:100%">Use it in this tab</button><p class="helper" style="margin-top:10px">The other tab will close the POS. Nothing is lost: unsynced changes stay on this device.</p>':'<p>Close the other tab, then reload this one.</p>';if($('takeoverTab'))$('takeoverTab').onclick=()=>{$('takeoverTab').disabled=true;$('takeoverTab').textContent='Opening…';tabChannel.postMessage('takeover');navigator.locks.request(TAB_LOCK,async()=>{holdTab();await initCloud();await new Promise(()=>{})})}}
if(navigator.locks&&steppedAside){tabBusy()}else if(navigator.locks){navigator.locks.request(TAB_LOCK,{ifAvailable:true},async lock=>{if(!lock){tabBusy();return}holdTab();await initCloud();await new Promise(()=>{})})}else{showLogin('Update your browser or Android System WebView to use this cloud edition safely.');$('loginForm').innerHTML=''}

// Demo shops: a thin bar so nobody mistakes the shared demo for a real shop.
function demoBar(){let bar=document.getElementById('demoBar');if(!cloudUser?.demo){bar?.remove();return}if(bar)return;bar=document.createElement('div');bar.id='demoBar';bar.setAttribute('role','note');bar.style.cssText='position:sticky;top:0;z-index:50;background:#fff4d9;color:#674d19;padding:8px 16px;text-align:center;font-size:14px';bar.innerHTML='<b>Demo shop</b> · sample data, shared with other visitors, reset every night · <a href="/demo" style="color:#5744ac">Other demos</a>';document.body.prepend(bar)}

// App updates: a new version installs in the background. On the sign-in screen it is applied at once; while working,
// a bar offers "Update" so a bill in progress is never interrupted (unsynced changes are kept on the device either way).
let appReloading=false,updateRequested=false;const hadController=!!navigator.serviceWorker?.controller;
// Reload only when it cannot interrupt work: on the sign-in screen, or when this tab's user pressed Update.
// (First install on a new device, or an update started from another tab, never reloads a working screen.)
if('serviceWorker'in navigator)navigator.serviceWorker.addEventListener('controllerchange',()=>{if(appReloading||!hadController)return;if(updateRequested||!cloudReady){appReloading=true;location.reload()}});
function watchUpdates(reg){if(!reg)return;const offer=w=>{if(!w)return;if(!cloudReady){w.postMessage('skipWaiting');return}updateBar(w)};
 if(reg.waiting&&navigator.serviceWorker.controller)offer(reg.waiting);
 reg.addEventListener('updatefound',()=>{const w=reg.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)offer(w)})});
 setInterval(()=>reg.update().catch(()=>{}),30*60000)}
function updateBar(w){if(document.getElementById('updateBar'))return;const bar=document.createElement('div');bar.id='updateBar';bar.setAttribute('role','status');bar.style.cssText='position:fixed;left:50%;bottom:18px;transform:translateX(-50%);z-index:60;background:#19172d;color:#fff;padding:10px 14px;border-radius:14px;display:flex;gap:12px;align-items:center;box-shadow:0 10px 30px #0005;font-size:15px;max-width:calc(100% - 24px)';bar.innerHTML='<span>A new version of Palace POS is ready.</span><button class="primary" type="button" style="white-space:nowrap">Update now</button>';bar.querySelector('button').onclick=()=>{bar.querySelector('button').disabled=true;updateRequested=true;const go=()=>{if(!appReloading){appReloading=true;location.reload()}};if(w.state==='activated'){go();return}w.addEventListener('statechange',()=>{if(w.state==='activated')go()});w.postMessage('skipWaiting');setTimeout(go,6000)};document.body.append(bar)}
