'use strict';
const CLOUD_KEY='wifi-palace-cloud-v2';
let cloudUser=null,csrf='',cache=null,cloudOnline=false,syncing=false,reconciling=false,syncProblem='',cloudReady=false;
const localRender=render,localSettings=settings,localReceipt=receipt,localDownload=download;
const clone=SyncCore.clone;
function saveCache(){if(!cache)throw Error('No signed-in business');localStorage.setItem(CLOUD_KEY,JSON.stringify(cache))}
function cloudDownload(name,text,type='application/json'){let a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
// Android delegates exports to the original native bridge. Web browsers download directly.
download=function(name,text,type){if(window.Android)Android.exportFile(name,text,type);else cloudDownload(name,text,type)};
async function api(path,method='GET',data){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const response=await fetch('/api/'+path,{method,credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},...(data===undefined?{}:{body:JSON.stringify(data)}),signal:controller.signal});let result=await response.json();if(!response.ok){const error=Error(result.error||'Request failed');error.status=response.status;throw error}return result}finally{clearTimeout(timer)}}
function trustedCache(c){return c&&c.schema===2&&c.user?.id&&c.user?.salonId&&['owner','cashier'].includes(c.user.role)&&valid(c.base)&&Array.isArray(c.pending)&&c.revisions&&c.pending.every(o=>o.id&&o.kind&&o.key&&Number.isInteger(o.base))}
function paintStatus(){const node=$('cloudStatus');if(node)node.innerHTML=`<span class="badge">${syncing?'Syncing…':syncProblem?'Needs attention':cloudOnline?'Cloud connected':'Offline'}</span> <span>${cache?.pending.length||0} pending</span> <button onclick="syncNow(true)">Sync now</button> <button onclick="navigate('Account')">${esc(cloudUser?.name||'Account')}</button>`}
render=function(){if(!cloudReady)return;localRender();let strip=$('cloudStatus');if(!strip){strip=document.createElement('div');strip.id='cloudStatus';strip.className='cloud-status';$('nav').after(strip)}paintStatus();const tabs=cloudUser?.role==='owner'?['Dashboard','Checkout','Appointments','Customers','Sales','Services & staff','Settings','Finance','Reports','Team','Sync centre','Account']:['Checkout','Appointments','Customers','My sales','Sync centre','Account'];$('nav').innerHTML=tabs.map(t=>`<button class="${tab===t?'active':''}" data-cloud-tab="${esc(t)}">${esc(t)}</button>`).join('');document.querySelectorAll('[data-cloud-tab]').forEach(b=>b.onclick=()=>navigate(b.dataset.cloudTab));$('footerVersion').textContent='Cloud edition 2.0';};
const basicNavigate=navigate;
navigate=function(next){if(!cloudReady)return;if(cloudUser.role!=='owner'&&['Dashboard','Sales','Services & staff','Settings','Finance','Reports','Team'].includes(next)){alert('Owner access required');return}tab=next;if(['Account','Team','Sync centre','My sales'].includes(tab)){renderCloudOnly();return}basicNavigate(next)};
const renderOriginal=render;
render=function(){if(!cloudReady)return;if(['Account','Team','Sync centre','My sales'].includes(tab)){renderCloudOnly();return}renderOriginal()};
function renderCloudOnly(){const next=tab;tab=cloudUser.role==='owner'?'Dashboard':'Checkout';renderOriginal();tab=next;document.querySelectorAll('[data-cloud-tab]').forEach(b=>b.classList.toggle('active',b.dataset.cloudTab===tab));if(tab==='Account')accountScreen();if(tab==='Team')teamScreen();if(tab==='Sync centre')syncScreen();if(tab==='My sales'){sales();document.querySelectorAll('[data-refund]').forEach(b=>b.remove());$('app').insertAdjacentHTML('afterbegin','<p class="helper">Showing sales created by your account.</p>')}}
change=function(fn){if(reconciling){alert('Wait for pending-change review to finish');return false}if(!cloudReady||!cache){alert('Sign in first');return false}if(!cloudOnline&&Date.now()>cache.offlineUntil){alert('Offline access expired. Connect and sign in before continuing.');return false}const before=clone(db),oldCache=clone(cache);try{fn();if(!valid(db))throw Error('Invalid record');const ops=SyncCore.diff(before,db,cache,()=>crypto.randomUUID());if(cloudUser.role!=='owner'&&ops.some(o=>['settings','vendor','services','staff'].includes(o.kind)||(o.kind==='sales'&&o.base>0)))throw Error('Owner permission required');cache.pending.push(...ops);saveCache();render();setTimeout(()=>syncNow(),150);return true}catch(e){db=before;cache=oldCache;alert('Not saved: '+e.message);return false}};
persist=function(){saveCache()};
restoreData=function(){alert('Replacing cloud records with an offline backup is disabled. Existing offline backups need a reviewed migration, so they cannot overwrite cloud sales.')};
backup=function(){if(cloudUser?.role!=='owner'){alert('Only an owner can export a business backup');return}download('salon-cloud-backup-'+day()+'.json',JSON.stringify({schema:2,exportedAt:new Date().toISOString(),user:cloudUser,state:db,pending:cache.pending},null,2),'application/json')};
const originalRefund=refund;refund=function(id){if(cloudUser?.role!=='owner'){alert('Only an owner can refund a sale');return}originalRefund(id)};
receipt=function(id){localReceipt(id);const pending=cache.pending.some(o=>o.kind==='sales'&&o.key===id);$('modal').insertAdjacentHTML('afterbegin',`<p class="${pending?'pending-note':'helper'}">${pending?'Saved on this device · Awaiting cloud confirmation':'Cloud-confirmed receipt'}</p>`)};
function forceSignIn(message){cloudOnline=false;cloudReady=false;showLogin(message);}
async function syncNow(manual=false){if(syncing||!cloudReady)return;syncing=true;paintStatus();try{const session=await api('me');if(session.user.id!==cache.user.id||session.user.salonId!==cache.user.salonId){forceSignIn('This browser signed into another account. Sign back into the original account to sync.');return}csrf=session.csrf;cloudUser=session.user;cache.user=cloudUser;cloudOnline=true;
 while(cache.pending.length){const op=clone(cache.pending[0]);let result;try{result=await api('sync','POST',op)}catch(e){if([400,403,409,413].includes(e.status)){syncProblem=e.message;cache.problem={id:op.id,message:e.message};saveCache();if(manual)alert('Sync paused: '+e.message);break}throw e}
  const previous=clone(cache);try{SyncCore.ack(cache,result);delete cache.problem;saveCache();db=SyncCore.project(cache)}catch(e){cache=previous;throw e}
 }
 const state=await api('state');cache.base=state.state;cache.revisions=state.revisions;cache.lastSynced=state.serverTime;cache.offlineUntil=Date.now()+12*3600000;saveCache();db=SyncCore.project(cache);if(!cache.pending.length){syncProblem='';delete cache.problem;saveCache()}if(manual&&!cache.pending.length)toast('All changes synced');
 // Avoid rebuilding a live form or unpaid bill while a background response arrives.
 if(!$('modal').open&&!['Checkout','Settings','Customers','Appointments','Services & staff','Account'].includes(tab))render();
 }catch(e){cloudOnline=false;if(e.status===401){forceSignIn(e.message)}else{syncProblem=e.status?e.message:'';if(manual)alert(e.status?e.message:'Cannot reach the server. Your saved changes remain on this device.')}}finally{syncing=false;paintStatus()}}
function showLogin(message=''){$('boot').classList.add('hidden');$('boot').setAttribute('inert','');$('nav').innerHTML='';$('cloudStatus')?.remove();$('app').innerHTML=`<div class="login-shell"><div class="login-story"><div class="eyebrow">WIFI PALACE POS</div><h2>Your business.<br>Connected.</h2><p>One workspace for your team, your customers and every sale.</p><div class="login-points"><div>01 &nbsp; A private workspace for each business</div><div>02 &nbsp; Offline billing with cloud sync</div><div>03 &nbsp; Owner access from anywhere</div></div></div><div class="panel login-form"><span class="badge">Cloud edition</span><h2 style="margin-top:20px">Welcome back</h2><p>Sign in to your business workspace.</p>${message?`<p class="pending-note" role="alert">${esc(message)}</p>`:''}<form id="loginForm"><label>Business code</label><input id="salonCode" autocomplete="organization" required placeholder="e.g. al-noor-laundry"><label>Email</label><input id="loginEmail" type="email" autocomplete="username" required><label>Password</label><input id="loginPassword" type="password" autocomplete="current-password" required><button class="primary" id="loginButton" style="width:100%">Sign in →</button></form><p class="helper">New business owner? <a href="/signup">Start your 14-day free trial</a>. Team accounts are created by your business owner. <a href="/recover">Forgot password?</a> · <a href="/recover?codes=1">Forgot business code?</a></p>${cache?.pending.length?`<p class="pending-note">${cache.pending.length} changes are waiting for ${esc(cache.user.email)}. Sign into that account to sync them.</p>`:''}${cache&&Date.now()<cache.offlineUntil?'<button onclick="resumeOffline()">Continue on this device offline</button>':''}</div></div>`;$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginButton').disabled=true;try{const result=await api('login','POST',{salon:$('salonCode').value,email:$('loginEmail').value,password:$('loginPassword').value});if(cache?.pending.length&&cache.user.id!==result.user.id){csrf=result.csrf;await api('logout','POST',{});throw Error('Sync the pending changes in the original account before switching accounts.')}await enterSalon(result)}catch(e){showLogin(e.message)}}}
const BUSINESS_LABELS={salon:'Salon & spa',laundry:'Laundry',grocery:'Grocery & baqala',restaurant:'Restaurant & café',gym:'Gym & fitness'};
function showBusinessType(user){if($('brandTag'))$('brandTag').textContent=(BUSINESS_LABELS[user?.businessType]||'Point of sale').toUpperCase()}
async function enterSalon(session){csrf=session.csrf;showBusinessType(session.user);const state=await api('state');if(cache&&cache.user.id===session.user.id){cache.base=state.state;cache.revisions=state.revisions;cache.user=session.user}else cache={schema:2,user:session.user,base:state.state,revisions:state.revisions,pending:[]};cache.lastSynced=state.serverTime;cache.offlineUntil=Date.now()+12*3600000;saveCache();cloudUser=session.user;cloudOnline=true;cloudReady=true;db=SyncCore.project(cache);storageFault=false;cart=[];customer='';discount=0;stylist=db.staff[0]?.id||'';tab=cloudUser.role==='owner'?'Dashboard':'Checkout';render();showBoot();await syncNow()}
function resumeOffline(){if(!cache||Date.now()>cache.offlineUntil){alert('Connect and sign in to renew offline access');return}cloudUser=cache.user;cloudOnline=false;cloudReady=true;db=SyncCore.project(cache);tab=cloudUser.role==='owner'?'Dashboard':'Checkout';render();toast('Offline access · New changes stay on this device')}
async function logoutCloud(){if(cache.pending.length){alert('Sync your pending changes before signing out. They must stay with this account.');return}try{await api('logout','POST',{})}catch(e){alert('Connect to the server before signing out securely.');return}localStorage.removeItem(CLOUD_KEY);cache=null;cloudUser=null;cloudReady=false;csrf='';cart=[];db=initial();$('headerLogo').innerHTML='W';$('brand').textContent='WiFi Palace POS';if($('brandTag'))$('brandTag').textContent='POINT OF SALE';showLogin()}
function syncScreen(){$('app').innerHTML=`<div class="row"><div><div class="eyebrow">EVERY CHANGE ACCOUNTED FOR</div><h2>Sync centre</h2></div><button class="primary" onclick="syncNow(true)">Sync now</button></div><div class="panel"><p>Last successful refresh: ${esc(cache.lastSynced?new Date(cache.lastSynced).toLocaleString():'Not yet')}</p><p class="helper">Requests are replay-safe: reconnecting does not create a second copy of a sale. Conflicts pause the queue for review.</p>${cache.problem?`<p class="pending-note">${esc(cache.problem.message)}</p>`:''}${cache.pending.length?cache.pending.map((o,i)=>`<div class="row"><div><b>${esc(o.kind)} · ${esc(o.action)}</b><div class="helper">${esc(o.key)}</div></div><span class="badge">${i===0&&cache.problem?'Needs review':'Waiting'}</span></div>`).join(''):'<div class="empty">All saved changes are in the cloud.</div>'}<div class="actions"><button onclick="exportPending()">Export recovery copy</button>${cache.pending.length?'<button class="danger" onclick="discardPending()">Review & discard pending changes</button>':''}</div><p class="helper">A recovery copy includes unsynced transactions. Keep it until an owner has reconciled every payment.</p></div>`}
function exportPending(){download('salon-pending-recovery-'+day()+'.json',JSON.stringify(cache,null,2),'application/json')}
async function discardPending(){
 if(syncing){alert('Wait for the current sync to finish');return}
 if(cloudUser.role!=='owner'){modal(`<h2>Owner review required</h2><p>Export the recovery copy and reconcile any money collected before discarding these pending changes.</p><form id="discardForm"><label>Owner email</label><input id="approvalEmail" type="email" required autocomplete="off"><label>Owner password</label><input id="approvalPassword" type="password" required autocomplete="off"><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="danger">Approve discard</button></div></form>`);$('discardForm').onsubmit=async e=>{e.preventDefault();const credentials={email:$('approvalEmail').value,password:$('approvalPassword').value};await executeDiscard(credentials)};return}
 await executeDiscard({});
}
async function executeDiscard(credentials){
 if(!confirm('Discard ALL unsynced changes from this device? Export a recovery copy first. Money already collected must be reconciled separately.'))return;
 syncing=true;reconciling=true;paintStatus();
 try{await api('approve-discard','POST',{...credentials,operations:cache.pending.map(x=>({id:x.id}))});const state=await api('state'),previous=clone(cache);cache.base=state.state;cache.revisions=state.revisions;cache.pending=[];delete cache.problem;try{saveCache()}catch(e){cache=previous;throw e}db=SyncCore.project(cache);syncProblem='';closeModal();render()}catch(e){alert('Not discarded: '+e.message)}finally{syncing=false;reconciling=false;paintStatus()}
}

settings=function(){localSettings();$('restore').disabled=true;for(const b of document.querySelectorAll('button'))if((b.getAttribute('onclick')||'').includes('restoreBackup'))b.disabled=true;$('app').insertAdjacentHTML('afterbegin','<p class="pending-note">Cloud settings sync across your business. Offline backup replacement is disabled to protect shared records.</p>')};
function accountScreen(){$('app').innerHTML=`<div class="layout"><section class="panel"><h2>Your account</h2><p>${esc(cloudUser.name)} · ${esc(cloudUser.email)}</p><span class="badge">${esc(cloudUser.role)}</span><form id="passwordForm" style="margin-top:24px"><h3>Change password</h3><label>Current password</label><input id="currentPassword" type="password" autocomplete="current-password" required><label>New password · at least 12 characters</label><input id="newPassword" type="password" autocomplete="new-password" minlength="12" maxlength="128" required><button class="primary">Change password</button></form><div class="support"><button onclick="logoutCloud()">Sign out of this device</button></div></section><aside class="panel"><h3>Device & cloud</h3><p>Business: ${esc(db.settings.name)}<br>Currency: AED</p><p class="helper">Online sessions last up to 12 hours. Offline access continues for up to 12 hours after the last successful online verification on this trusted device. Keep your device locked when unattended.</p><p class="helper">Software by WiFi Palace<br>sales@wifipalace.com</p></aside></div>`;$('passwordForm').onsubmit=async e=>{e.preventDefault();if(cache.pending.length){alert('Sync pending changes before changing your password');return}try{await api('password','POST',{current:$('currentPassword').value,password:$('newPassword').value});forceSignIn('Password updated. All sessions were signed out. Sign in with your new password.')}catch(e){alert(e.message)}}}
async function teamScreen(){$('app').innerHTML='<div class="panel"><h2>Team access</h2><p>Loading accounts…</p></div>';try{const users=await api('users');if(tab!=='Team')return;$('app').innerHTML=`<div class="panel"><div class="row"><div><div class="eyebrow">THE RIGHT ACCESS FOR EVERY ROLE</div><h2>Team accounts</h2></div><button class="primary" onclick="addUserForm()">+ Add login</button></div><p>Staff names and sign-in accounts are separate. Owners manage the business; cashiers handle bookings and their own sales.</p>${users.map(u=>`<div class="row"><div><b>${esc(u.name)}</b><div class="helper">${esc(u.email)} · ${esc(u.role)} · ${u.active?'Active':'Disabled'}</div></div>${u.id===cloudUser.id?'<span class="badge">You</span>':`<button data-user="${esc(u.id)}" data-enable="${u.active?'false':'true'}">${u.active?'Disable':'Enable'}</button>`}</div>`).join('')}</div><div class="panel"><h3>Audit history</h3><button onclick="showAudit()">Load recent account & record changes</button><div id="auditLog"></div></div>`;document.querySelectorAll('[data-user]').forEach(b=>b.onclick=async()=>{if(!confirm('Change this account’s access?'))return;try{await api('users/'+b.dataset.user,'PATCH',{active:b.dataset.enable==='true'});teamScreen()}catch(e){alert(e.message)}})}catch(e){if(tab==='Team')$('app').innerHTML=`<div class="panel"><h2>Team access</h2><p>${esc(e.message)}</p><p>Team accounts require an online connection.</p></div>`}}
function addUserForm(){modal(`<h2>Create team login</h2><form id="userForm"><label>Name</label><input id="userName" required maxlength="100"><label>Email</label><input id="userEmail" type="email" required><label>Role</label><select id="userRole"><option value="cashier">Cashier</option><option value="owner">Owner</option></select><label>Initial password</label><input id="userPassword" type="password" minlength="12" maxlength="128" required autocomplete="new-password"><p class="helper">Share credentials securely with your employee. They can change the password in Account. No email is sent automatically.</p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Create login</button></div></form>`);$('userForm').onsubmit=async e=>{e.preventDefault();try{await api('users','POST',{name:$('userName').value,email:$('userEmail').value,role:$('userRole').value,password:$('userPassword').value});closeModal();teamScreen()}catch(e){alert(e.message)}}}
async function showAudit(){try{const records=await api('audit');$('auditLog').innerHTML=records.map(r=>`<div class="row"><div>${esc(r.action)}<div class="helper">${esc(r.actor||'Account')} · ${esc(r.entity)}</div></div><span class="helper">${new Date(r.at).toLocaleString()}</span></div>`).join('')}catch(e){alert(e.message)}}
async function initCloud(){try{const raw=localStorage.getItem(CLOUD_KEY);cache=raw?JSON.parse(raw):null;if(cache&&!trustedCache(cache))throw Error('Invalid local cache')}catch{showLogin('Saved cloud data could not be read. Do not clear browser data; contact support for recovery.');return}try{const session=await api('me');await enterSalon(session)}catch(e){showLogin(e.status===401?'':cache?'The server is unreachable. You can continue offline on this previously signed-in device.':'Connect to the internet to sign in for the first time.')}setInterval(()=>syncNow(),30000);window.addEventListener('online',()=>syncNow());if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})}
if(navigator.locks){navigator.locks.request('salon-cloud-exclusive-tab',{ifAvailable:true},async lock=>{if(!lock){showLogin('WiFi Palace POS is already open in another tab. Close that tab before using this one.');$('loginForm').innerHTML='';return}await initCloud();await new Promise(()=>{})})}else{showLogin('Update your browser or Android System WebView to use this cloud edition safely.');$('loginForm').innerHTML=''}
