// Electronics & computer shop screens for Palace POS (business type "electronics"). Serial numbers, warranty,
// repairs and used devices come from mobile.js (same engine as the phone shop, worded for devices); this file adds
// Quotes (custom PC builds and company quotations, turned into a bill), Jobs (delivery and installation) and
// RMA (warranty claims sent to the supplier), plus the LPO number on company bills.
(function(){
 'use strict';
 const R=window.RetailUI,M=R?.ext?.mobile;if(!R||!M)return;
 const EXT=R.ext.electronics={...M};
 const RMA_NEXT={Open:'Sent',Sent:'Back',Back:'Closed'},OUTCOMES=['Repaired','Replaced','Credit note','Rejected'],JOB_TYPES=['Delivery','Installation','Delivery & installation'];
 let quoteView='Open',jobView='Upcoming',rmaView='Open',draft=null;
 const today=()=>R.localDay(),plus=n=>{const d=new Date();d.setDate(d.getDate()+n);return R.localDay(d)};
 const item=id=>db.grocery_items.find(i=>i.id===id);
 const cust=id=>db.customers.find(c=>c.id===id);
 const custOptions=(sel='',none='Choose customer…')=>`<option value="">${none}</option>`+db.customers.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(c=>`<option value="${esc(c.id)}" ${c.id===sel?'selected':''}>${esc(c.name)}${c.phone?' · '+esc(c.phone):''}</option>`).join('');
 const newCust=(p)=>`<div id="${p}New" class="business-grid" style="display:none"><div><label for="${p}Name">Name / company</label><input id="${p}Name" maxlength="100"></div><div><label for="${p}Phone">Phone</label><input id="${p}Phone" maxlength="40"></div></div>`;
 const badge=s=>`<span class="badge" style="${['Accepted','Done','Closed','Back'].includes(s)?'background:#dff3e9;color:#155e48':['Lost','Cancelled'].includes(s)?'background:#fde8e6;color:#8a1c14':['Sent','On the way'].includes(s)?'background:#fdf0d8;color:#7a5200':''}">${esc(s)}</span>`;
 const totals=q=>{const sub=q.lines.reduce((n,l)=>n+l.price*l.qty,0),off=Math.min(q.discount||0,sub),tax=Math.round((sub-off)*(db.settings.tax||0)/100);return{sub,off,tax,total:sub-off+tax}};
 const wa=(phone,msg)=>{try{window.open(SalonWhatsApp.link(phone,msg),'_blank','noopener')}catch(e){alert(e.message)}};
 const tabs=(views,cur,fn)=>views.map(([v,c])=>`<button class="${cur===v?'primary':''}" onclick="${fn}('${v}')">${v}${c!==''?' ('+c+')':''}</button>`).join('');
 const line='--------------------------------';
 const head=()=>`${db.settings.name}\n${db.settings.address||''}\n${db.settings.phone||''}${db.settings.trn?'\nTRN: '+db.settings.trn:''}\n${line}\n`;
 const slip=(title,text)=>modal(`<h2>${title}</h2><pre class="receipt" id="receiptText">${esc(text)}</pre><div class="actions"><button onclick="closeModal()">Close</button><button class="primary" onclick="printReceipt()">Print / Save PDF</button></div>`);

 // --- product form, checkout, dashboard ---------------------------------------------------------------
 EXT.services={types:[['repair','Repair labour'],['installation','Installation'],['delivery','Delivery'],['other','Other service']],category:()=>'Services',blank:{name:'',category:'Services',serviceType:'repair',price:0,duration:60,openPrice:true}};
 EXT.checkoutExtra=(c,t)=>`${M.checkoutExtra(c,t)}${c?`${c.trn?`<p class="helper">Company TRN ${esc(c.trn)} prints on the invoice.</p>`:''}<label for="gLpo">LPO / PO number (optional)</label><input id="gLpo" maxlength="40" value="${esc(R.cartState().extra.lpo||'')}" oninput="RetailUI.setExtra('lpo',this.value.trim())">`:''}`;
 EXT.onPaid=(sale,links,extra)=>{let msg=M.onPaid(sale,links,extra)||'';
  for(const l of links){if(l.kind==='elec_quotes'){const q=db.elec_quotes.find(x=>x.id===l.id);if(q&&q.status==='Open'){q.status='Accepted';q.saleId=sale.id;msg='Quotation #'+q.number+' accepted and billed'}}
   if(l.kind==='elec_jobs'){const j=db.elec_jobs.find(x=>x.id===l.id);if(j&&!j.saleId){j.saleId=sale.id;msg='Job #'+j.number+' billed'}}}
  return msg};
 EXT.dashboard=()=>{const q=db.elec_quotes.filter(x=>x.status==='Open'),jobs=db.elec_jobs.filter(j=>!['Done','Cancelled'].includes(j.status)),rma=db.elec_rma.filter(r=>!['Closed','Cancelled'].includes(r.status));
  return `${M.dashboard()}<section class="panel"><div class="grid">${[['Open quotations',q.length,money(q.reduce((n,x)=>n+totals(x).total,0)),'Quotes'],['Jobs today',jobs.filter(j=>j.date===today()).length,jobs.filter(j=>j.date<today()).length+' overdue · '+jobs.filter(j=>j.date>today()).length+' upcoming','Jobs'],['Warranty claims open',rma.length,rma.filter(r=>r.status==='Sent').length+' with the supplier','RMA']].map(([l,v,h,t])=>`<div class="panel" style="margin:0;cursor:pointer" onclick="navigate('${t}')">${l}<div class="metric">${v}</div><p class="helper">${h}</p></div>`).join('')}</div></section>`};

 // --- quotations ---------------------------------------------------------------
 function quotes(){const list=db.elec_quotes.filter(q=>q.status===quoteView).sort((a,b)=>b.created.localeCompare(a.created)).slice(0,200),n=s=>db.elec_quotes.filter(q=>q.status===s).length;
  $('app').innerHTML=`<div class="panel"><div class="row" style="flex-wrap:wrap;gap:8px"><h2>Quotations</h2><div class="actions" style="margin:0;flex-wrap:wrap">${tabs([['Open',n('Open')],['Accepted',''],['Lost','']],quoteView,'elecQuotes')}<button class="primary" onclick="elecQuoteNew()">+ New quotation</button></div></div>
  ${list.map(q=>{const t=totals(q);return `<div class="row" style="padding:10px 0;border-bottom:1px solid #eee;flex-wrap:wrap;gap:10px"><div style="min-width:240px;flex:1"><b>#${q.number||'…'} · ${esc(q.customer)}</b> ${badge(q.status)}<div class="helper">${esc(q.title||q.lines.map(l=>l.qty+' × '+l.name).join(', ').slice(0,90))}</div><div class="helper">${q.lines.length} line${q.lines.length===1?'':'s'} · <b>${money(t.total)}</b> incl. VAT · <span${q.status==='Open'&&q.validUntil<today()?' style="color:#b42318;font-weight:700"':''}>valid until ${esc(q.validUntil)}</span></div></div><button onclick="elecQuoteOpen('${esc(q.id)}')">Open</button></div>`}).join('')||`<div class="empty">${quoteView==='Open'?'No open quotations. Price a PC build or a company order with “+ New quotation”.':'Nothing here.'}</div>`}</div>`}
 function readQuote(){const d=draft;if(!d||!$('eQuote'))return;d.customerId=$('eqCust').value;d.newName=$('eqName').value;d.newPhone=$('eqPhone').value;d.title=$('eqTitle').value;d.discount=$('eqOff').value;d.validUntil=$('eqValid').value;d.note=$('eqNote').value;
  d.lines.forEach((l,n)=>{l.qty=Math.max(1,Math.min(1000,Math.round(Number(document.querySelector(`[data-ql-qty="${n}"]`).value)||1)));const p=document.querySelector(`[data-ql-price="${n}"]`);if(p)l.price=cents(p.value||0)})}
 function quoteForm(){const d=draft,t=totals({lines:d.lines,discount:cents(d.discount||0)}),items=db.grocery_items.slice().sort((a,b)=>a.category.localeCompare(b.category)||a.name.localeCompare(b.name));
  modal(`<h2>${d.id?'Edit quotation':'New quotation'}</h2><form id="eQuote">${d.id?`<p><b>${esc(d.customer)}</b></p><input type="hidden" id="eqCust" value="${esc(d.customerId)}"><input type="hidden" id="eqName"><input type="hidden" id="eqPhone">`:`<label for="eqCust">Customer</label><select id="eqCust">${custOptions(d.customerId)}<option value="+" ${d.customerId==='+'?'selected':''}>+ New customer…</option></select>${newCust('eq')}`}
  <label for="eqTitle">Title (optional)</label><input id="eqTitle" maxlength="100" value="${esc(d.title||'')}" placeholder="e.g. Gaming PC build, office laptops">
  <label for="eqAdd">Add a product or service</label><select id="eqAdd"><option value="">Choose…</option>${items.map(i=>`<option value="${esc(i.id)}">${esc(i.category)} · ${esc(i.name)} · ${money(i.price)}</option>`).join('')}</select>
  ${d.lines.map((l,n)=>`<div class="row" style="padding:8px 0;border-bottom:1px solid #eee;gap:8px"><div style="flex:1"><b>${esc(l.name)}</b><div class="helper">${item(l.itemId)?.openPrice?`AED <input data-ql-price="${n}" type="number" min="0" step="0.01" value="${(l.price/100).toFixed(2)}" style="width:100px;display:inline-block;margin:0">`:money(l.price)} each</div></div><input data-ql-qty="${n}" aria-label="Quantity" type="number" min="1" max="1000" step="1" value="${l.qty}" style="width:76px"><b style="min-width:90px;text-align:right">${money(l.price*l.qty)}</b><button type="button" data-ql-del="${n}" aria-label="Remove">×</button></div>`).join('')||'<div class="empty">No lines yet.</div>'}
  <div class="business-grid"><div><label for="eqOff">Discount (AED)</label><input id="eqOff" type="number" min="0" step="0.01" value="${esc(d.discount||'')}" placeholder="0.00"></div><div><label for="eqValid">Valid until</label><input id="eqValid" type="date" min="${today()}" value="${esc(d.validUntil)}" required></div></div>
  <label for="eqNote">Note on the quotation</label><input id="eqNote" maxlength="300" value="${esc(d.note||'')}" placeholder="e.g. Delivery in 3 days · 50% advance">
  <p>Subtotal ${money(t.sub)}${t.off?' · discount −'+money(t.off):''} · VAT ${money(t.tax)} · <b>Total ${money(t.total)}</b> <button type="button" id="eqCalc">Recalculate</button></p>
  <p id="eqErr" class="pending-note" role="alert" hidden></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save quotation</button></div></form>`);
  if($('eqCust').tagName==='SELECT'){const show=()=>{$('eqNew').style.display=$('eqCust').value==='+'?'grid':'none'};show();$('eqCust').onchange=show;$('eqName').value=d.newName||'';$('eqPhone').value=d.newPhone||''}
  const redo=()=>{readQuote();quoteForm()};$('eqCalc').onclick=redo;
  $('eqAdd').onchange=()=>{const i=item($('eqAdd').value);if(!i)return;readQuote();if(draft.lines.length>=40){alert('A quotation has up to 40 lines.');return}const same=draft.lines.find(l=>l.itemId===i.id&&!i.openPrice);if(same)same.qty++;else draft.lines.push({key:uid(),itemId:i.id,name:i.name,qty:1,price:i.price,note:''});quoteForm()};
  document.querySelectorAll('[data-ql-del]').forEach(b=>b.onclick=()=>{readQuote();draft.lines.splice(Number(b.dataset.qlDel),1);quoteForm()});
  $('eQuote').onsubmit=e=>{e.preventDefault();readQuote();const x=draft,err=m=>{$('eqErr').textContent=m;$('eqErr').hidden=!m};let cid=x.customerId;
   if(!cid){err('Choose the customer, or add a new one.');return}if(cid==='+'&&!x.newName?.trim()){err('Enter the customer name.');return}if(!x.lines.length){err('Add at least one line.');return}
   const discount=x.discount?cents(x.discount):0,sub=x.lines.reduce((n,l)=>n+l.price*l.qty,0);if(!(discount>=0)||discount>sub){err('The discount is more than the quotation.');return}if(!x.validUntil){err('Choose the validity date.');return}
   const id=x.id||uid(),lines=x.lines.map(l=>({key:l.key,itemId:l.itemId,name:l.name,qty:l.qty,price:l.price,note:l.note||''}));
   if(change(()=>{let c=cust(cid);if(cid==='+'){c={id:uid(),name:x.newName.trim(),phone:(x.newPhone||'').trim(),dob:''};db.customers.push(c);cid=c.id}
    const old=db.elec_quotes.find(q=>q.id===id);if(old)Object.assign(old,{title:x.title.trim(),lines,sub,discount,validUntil:x.validUntil,note:x.note.trim()});
    else db.elec_quotes.push({id,number:0,customerId:cid,customer:c.name,phone:c.phone||'',title:x.title.trim(),lines,sub,discount,validUntil:x.validUntil,note:x.note.trim(),status:'Open',saleId:'',created:new Date().toISOString()})})){draft=null;quoteView='Open';render();quoteOpen(id)}}}
 const quoteText=q=>{const t=totals(q),c=cust(q.customerId);return `${head()}QUOTATION${q.number?' No. '+q.number:''}\nDate: ${new Date(q.created).toLocaleDateString()}\nValid until: ${q.validUntil}\n${line}\nTo: ${q.customer}${c?.address?'\n'+c.address:''}${c?.trn?'\nTRN: '+c.trn:''}${q.phone?'\nPhone: '+q.phone:''}${q.title?'\nFor: '+q.title:''}\n${line}\n${q.lines.map(l=>`${l.name}\n  ${l.qty} x ${money(l.price)}  = ${money(l.price*l.qty)}`).join('\n')}\n${line}\nSubtotal (excl. VAT): ${money(t.sub)}\n${t.off?'Discount: -'+money(t.off)+'\n':''}VAT ${db.settings.tax||0}%: ${money(t.tax)}\nTOTAL (incl. VAT): ${money(t.total)}\n${line}\n${q.note?q.note+'\n':''}Prices are valid until the date above and\nsubject to stock. Warranty as per the\nmanufacturer, shown on the tax invoice.\n\nAll amounts in AED`};
 // Put the quotation on the bill. Fixed-price lines go straight on; each serial-numbered device asks for its serial.
 function quoteBill(q){const link={kind:'elec_quotes',id:q.id};if(R.billed(link)){navigate('Checkout');return}
  const queue=[];for(const l of q.lines){const i=item(l.itemId);if(!i){alert(l.name+' is no longer in your products; add it by hand.');continue}if(i.serial)for(let k=0;k<l.qty;k++)queue.push({i,l});else queue.push({i,l,plain:true})}
  R.bill({lines:[],customerId:q.customerId});
  const next=()=>{const x=queue.shift();if(!x){if(q.discount)R.setDiscount(q.discount,{...R.cartState().extra,offLabel:'Quotation discount'});else R.refresh();toast('Quotation #'+q.number+' is on the bill · take payment');return}
   const o={link,...(x.i.openPrice?{price:x.l.price}:{})};
   if(x.plain){R.add(x.i.id,x.l.qty,o);next()}else EXT.chooseUnit(x.i,u=>{R.add(x.i.id,1,{...o,price:x.i.openPrice?(x.l.price||u.price):undefined,cut:u});next()})};
  next()}
 function quoteOpen(id){const q=db.elec_quotes.find(x=>x.id===id);if(!q)return;const t=totals(q),sale=q.saleId?db.sales.find(s=>s.id===q.saleId):null,open=q.status==='Open';
  modal(`<h2>Quotation #${q.number||'…'} · ${esc(q.customer)}</h2><p>${badge(q.status)} ${q.title?esc(q.title)+' · ':''}valid until ${esc(q.validUntil)}${q.lostReason?' · '+esc(q.lostReason):''}</p>${q.number?'':'<p class="pending-note">The quotation number is issued when this device syncs.</p>'}
  ${q.lines.map(l=>`<div class="row" style="padding:6px 0;border-bottom:1px solid #eee"><span>${l.qty} × ${esc(l.name)}</span><b>${money(l.price*l.qty)}</b></div>`).join('')}
  <p>Subtotal ${money(t.sub)}${t.off?' · discount −'+money(t.off):''} · VAT ${money(t.tax)} · <b>Total ${money(t.total)}</b></p>${q.note?`<p class="helper">${esc(q.note)}</p>`:''}
  <div class="actions">${open?'<button class="primary" id="eqBill">Accepted → bill it</button><button id="eqEdit">Edit</button>':''}<button id="eqPrint">Print / PDF</button>${q.phone?'<button id="eqWa">WhatsApp</button>':''}${sale?`<button onclick="receipt('${esc(sale.id)}')">Invoice ${esc(sale.number||'')}</button>`:''}</div>
  <div class="actions"><button onclick="closeModal()">Close</button>${open?'<button class="danger" id="eqLost">Mark as lost</button>':''}</div>`);
  $('eqPrint').onclick=()=>slip('Quotation',quoteText(q));
  if($('eqWa'))$('eqWa').onclick=()=>wa(q.phone,`Hello ${q.customer.split(' ')[0]}, your quotation no. ${q.number} from ${db.settings.name}${q.title?' ('+q.title+')':''}:\n${q.lines.map(l=>l.qty+' x '+l.name+' — '+money(l.price*l.qty)).join('\n')}\n${t.off?'Discount: -'+money(t.off)+'\n':''}Total incl. VAT: ${money(t.total)}\nValid until ${q.validUntil}.${q.note?'\n'+q.note:''}`);
  if(!open)return;
  $('eqBill').onclick=()=>{closeModal();quoteBill(q)};
  $('eqEdit').onclick=()=>{draft={id:q.id,customerId:q.customerId,customer:q.customer,title:q.title,lines:q.lines.map(l=>({...l})),discount:q.discount?(q.discount/100).toFixed(2):'',validUntil:q.validUntil,note:q.note};quoteForm()};
  $('eqLost').onclick=()=>{const why=prompt('Why was it lost? (price, bought elsewhere, no reply…)');if(why===null)return;if(change(()=>{q.status='Lost';q.lostReason=why.trim().slice(0,200)})){closeModal();toast('Marked as lost');if(tab==='Quotes')quotes()}}}

 // --- delivery & installation jobs ---------------------------------------------------------------
 const jobOpenState=j=>!['Done','Cancelled'].includes(j.status);
 function jobs(){const list=db.elec_jobs.filter(j=>jobView==='Upcoming'?jobOpenState(j):!jobOpenState(j)).sort((a,b)=>jobView==='Upcoming'?(a.date+a.slot).localeCompare(b.date+b.slot):b.date.localeCompare(a.date)).slice(0,200);
  $('app').innerHTML=`<div class="panel"><div class="row" style="flex-wrap:wrap;gap:8px"><h2>Delivery &amp; installation</h2><div class="actions" style="margin:0">${tabs([['Upcoming',db.elec_jobs.filter(jobOpenState).length],['Closed','']],jobView,'elecJobs')}<button class="primary" onclick="elecJobNew()">+ New job</button></div></div>
  ${list.map(j=>`<div class="row" style="padding:10px 0;border-bottom:1px solid #eee;flex-wrap:wrap;gap:10px"><div style="min-width:240px;flex:1"><b>#${j.number||'…'} · ${esc(j.type)} · ${esc(j.customer)}</b> ${badge(j.status)}<div class="helper">${esc(j.what)}</div><div class="helper"><span${jobOpenState(j)&&j.date<today()?' style="color:#b42318;font-weight:700"':j.date===today()&&jobOpenState(j)?' style="font-weight:700"':''}>${j.date===today()?'Today':esc(j.date)}${j.slot?' · '+esc(j.slot):''}</span> · ${esc(j.address)}${j.staff?' · '+esc(j.staff):''}${j.charge?' · '+money(j.charge)+(j.saleId?' billed':''):''}</div></div><button onclick="elecJobOpen('${esc(j.id)}')">Open</button></div>`).join('')||'<div class="empty">No jobs here. Book a delivery or a TV / CCTV / PC installation with “+ New job”.</div>'}</div>`}
 const jobFields=j=>`<div class="business-grid"><div><label for="ejDate">Date</label><input id="ejDate" type="date" value="${esc(j.date)}" required></div><div><label for="ejSlot">Time</label><input id="ejSlot" maxlength="40" value="${esc(j.slot||'')}" placeholder="e.g. 4–6 pm"></div></div><label for="ejAddr">Address</label><input id="ejAddr" maxlength="200" value="${esc(j.address||'')}" required placeholder="Building, flat, area"><label for="ejWhat">What to deliver / install</label><input id="ejWhat" maxlength="200" value="${esc(j.what||'')}" required placeholder="e.g. Wall-mount 55&quot; TV, set up printer"><div class="business-grid"><div><label for="ejStaff">Technician / driver</label><input id="ejStaff" maxlength="100" list="ejStaffs" value="${esc(j.staff||'')}"><datalist id="ejStaffs">${db.staff.map(s=>`<option value="${esc(s.name)}">`).join('')}</datalist></div><div><label for="ejCharge">Charge (AED, 0 = free)</label><input id="ejCharge" type="number" min="0" step="0.01" value="${((j.charge||0)/100).toFixed(2)}"></div></div><label for="ejNote">Note</label><input id="ejNote" maxlength="200" value="${esc(j.note||'')}">`;
 const jobRead=()=>({date:$('ejDate').value,slot:$('ejSlot').value.trim(),address:$('ejAddr').value.trim(),what:$('ejWhat').value.trim(),staff:$('ejStaff').value.trim(),charge:cents($('ejCharge').value||0),note:$('ejNote').value.trim()});
 function jobNew(pre={}){modal(`<h2>New delivery / installation</h2><form id="eJob"><label for="ejCust">Customer</label><select id="ejCust">${custOptions(pre.customerId||'')}<option value="+">+ New customer…</option></select>${newCust('ej')}<label for="ejType">Job</label><select id="ejType">${JOB_TYPES.map(t=>`<option>${t}</option>`).join('')}</select>${jobFields({date:today(),address:cust(pre.customerId)?.address||'',what:pre.what||''})}<p id="ejErr" class="pending-note" role="alert" hidden></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save job</button></div></form>`);
  $('ejCust').onchange=()=>{const v=$('ejCust').value;$('ejNew').style.display=v==='+'?'grid':'none';const a=cust(v)?.address;if(a&&!$('ejAddr').value)$('ejAddr').value=a};
  $('eJob').onsubmit=e=>{e.preventDefault();let cid=$('ejCust').value;const err=m=>{$('ejErr').textContent=m;$('ejErr').hidden=!m};if(!cid){err('Choose the customer, or add a new one.');return}if(cid==='+'&&!$('ejName').value.trim()){err('Enter the customer name.');return}
   const id=uid(),f=jobRead(),type=$('ejType').value,now=new Date().toISOString();
   if(change(()=>{let c=cust(cid);if(cid==='+'){c={id:uid(),name:$('ejName').value.trim(),phone:$('ejPhone').value.trim(),dob:''};db.customers.push(c);cid=c.id}
    db.elec_jobs.push({id,number:0,type,customerId:cid,customer:c.name,phone:c.phone||'',...f,status:'Booked',saleId:'',created:now,history:[{status:'Booked',at:now}]})})){jobView='Upcoming';closeModal();toast('Job booked');if(tab==='Jobs')jobs()}}}
 function jobOpen(id){const j=db.elec_jobs.find(x=>x.id===id);if(!j)return;const open=jobOpenState(j),sale=j.saleId?db.sales.find(s=>s.id===j.saleId):null;
  modal(`<h2>#${j.number||'…'} · ${esc(j.type)}</h2><p>${badge(j.status)} <b>${esc(j.customer)}</b>${j.phone?' · '+esc(j.phone):''}</p>
  ${open?`<form id="eJobE">${jobFields(j)}<button>Save details</button></form><h3 style="margin-top:14px">Status</h3><div class="actions">${j.status==='Booked'?'<button data-ej="On the way">On the way</button>':'<button data-ej="Booked">Back to booked</button>'}<button class="primary" data-ej="Done">Done</button>${j.saleId?`<span class="badge">Billed${sale?' · '+esc(sale.number||''):''}</span>`:'<button id="ejBill">Bill the charge</button>'}${j.phone?'<button id="ejWa">WhatsApp the customer</button>':''}</div>`
   :`<p>${esc(j.date)}${j.slot?' · '+esc(j.slot):''} · ${esc(j.address)}</p><p>${esc(j.what)}${j.staff?' · '+esc(j.staff):''}${j.cancelReason?'<br>Cancelled: '+esc(j.cancelReason):''}${sale?'<br>Bill '+esc(sale.number||'')+' · '+money(sale.total):''}</p>`}
  <div class="actions"><button onclick="closeModal()">Close</button><button id="ejSheet">Job sheet</button>${open?'<button class="danger" id="ejCancel">Cancel job</button>':''}</div>`);
  $('ejSheet').onclick=()=>slip('Job sheet',`${head()}${j.type.toUpperCase()}${j.number?' No. '+j.number:''}\n${j.date}${j.slot?' · '+j.slot:''}\n${line}\nCustomer: ${j.customer}\nPhone: ${j.phone||'-'}\nAddress: ${j.address}\n${line}\n${j.what}\n${j.staff?'Technician: '+j.staff+'\n':''}${j.charge?'Charge: '+money(j.charge)+' + VAT'+(j.saleId?' (billed)':' (to collect)')+'\n':''}${j.note?'Note: '+j.note+'\n':''}${line}\nWork completed and checked with the\ncustomer.\n\nCustomer signature: ______________`);
  if(!open)return;
  const upd=(fn,msg)=>{if(change(()=>fn(db.elec_jobs.find(x=>x.id===id)))){closeModal();toast(msg);if(tab==='Jobs')jobs()}};
  $('eJobE').onsubmit=e=>{e.preventDefault();upd(x=>Object.assign(x,jobRead()),'Saved')};
  document.querySelectorAll('[data-ej]').forEach(b=>b.onclick=()=>upd(x=>{Object.assign(x,jobRead());x.status=b.dataset.ej},'#'+j.number+' → '+b.dataset.ej));
  $('ejCancel').onclick=()=>{const why=prompt('Reason for cancelling this job:');if(why?.trim())upd(x=>{x.status='Cancelled';x.cancelReason=why.trim()},'Job cancelled')};
  if($('ejBill'))$('ejBill').onclick=()=>{const want=j.type==='Delivery'?'delivery':'installation',svc=db.grocery_items.find(i=>R.isSvc(i)&&i.serviceType===want&&i.openPrice)||db.grocery_items.find(i=>R.isSvc(i)&&i.openPrice);if(!svc){alert('Add a service (e.g. Installation) with “price can change” on Products first.');return}const f=jobRead();if(!f.charge){alert('Enter the charge first (0 means free: no bill needed).');return}
   const link={kind:'elec_jobs',id};if(change(()=>Object.assign(db.elec_jobs.find(x=>x.id===id),f))){closeModal();if(!R.billed(link))R.bill({lines:[{id:svc.id,qty:1,price:f.charge,link,note:('Job #'+j.number+' '+j.what).slice(0,100)}],customerId:j.customerId});else navigate('Checkout')}};
  if($('ejWa'))$('ejWa').onclick=()=>wa(j.phone,`Hello ${j.customer.split(' ')[0]}, this is ${db.settings.name}. Your ${j.type.toLowerCase()} (${j.what}) is booked for ${j.date}${j.slot?', '+j.slot:''} at ${j.address}.${j.staff?' Our technician: '+j.staff+'.':''} Please reply if the time does not suit you.`)}

 // --- warranty claims to the supplier (RMA) ---------------------------------------------------------------
 const rmaOpenState=r=>!['Closed','Cancelled'].includes(r.status);
 function rma(){const list=db.elec_rma.filter(r=>rmaView==='Open'?rmaOpenState(r):!rmaOpenState(r)).sort((a,b)=>rmaView==='Open'?a.created.localeCompare(b.created):b.created.localeCompare(a.created)).slice(0,200),days=r=>Math.floor((Date.now()-Date.parse(r.created))/86400000);
  $('app').innerHTML=`<div class="panel"><div class="row" style="flex-wrap:wrap;gap:8px"><div><h2>Warranty claims (RMA)</h2><p class="helper">Faulty items sent back to the supplier, until they come back repaired, replaced or credited.</p></div><div class="actions" style="margin:0">${tabs([['Open',db.elec_rma.filter(rmaOpenState).length],['Closed','']],rmaView,'elecRma')}<button class="primary" onclick="elecRmaNew()">+ New claim</button></div></div>
  ${list.map(r=>`<div class="row" style="padding:10px 0;border-bottom:1px solid #eee;flex-wrap:wrap;gap:10px"><div style="min-width:240px;flex:1"><b>#${r.number||'…'} · ${esc(r.item)}</b> ${badge(r.status==='Open'?'With us':r.status==='Sent'?'With supplier':r.status==='Back'?'Back · '+r.outcome:r.status)}<div class="helper">${r.serial?'S/N '+esc(r.serial)+' · ':''}${esc(r.fault)}</div><div class="helper">${esc(r.supplier)}${r.ref?' · ref '+esc(r.ref):''} · ${r.customer?esc(r.customer):'Shop stock'}${rmaOpenState(r)?` · <span${days(r)>14?' style="color:#b42318;font-weight:700"':''}>${days(r)} day${days(r)===1?'':'s'}</span>`:''}</div></div><button onclick="elecRmaOpen('${esc(r.id)}')">Open</button></div>`).join('')||'<div class="empty">No warranty claims here.</div>'}</div>`}
 function rmaNew(){const sups=[...new Set(db.grocery_stock.map(s=>s.supplier).filter(Boolean))].slice(0,50);
  modal(`<h2>New warranty claim</h2><form id="eRma"><label for="erSerial">Serial number (scan it: a device sold here fills in the rest)</label><input id="erSerial" maxlength="40" autocomplete="off"><label for="erItem">Item</label><input id="erItem" maxlength="100" required list="erItems"><datalist id="erItems">${db.grocery_items.filter(i=>!R.isSvc(i)).map(i=>`<option value="${esc(i.name)}">`).join('')}</datalist><label for="erFault">Fault</label><input id="erFault" maxlength="300" required placeholder="e.g. No display, dead pixels"><label for="erSup">Supplier / service centre</label><input id="erSup" maxlength="100" required list="erSups"><datalist id="erSups">${sups.map(s=>`<option value="${esc(s)}">`).join('')}</datalist><label for="erCust">Customer</label><select id="erCust">${custOptions('','Shop stock (not a customer’s item)')}</select><label for="erNote">Note</label><input id="erNote" maxlength="300" placeholder="e.g. with box and charger"><p id="erHint" class="helper"></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save &amp; print slip</button></div></form>`);
  $('erSerial').onchange=()=>{const code=$('erSerial').value.trim().toUpperCase().replace(/[\s-]/g,''),u=code.length>=4?db.mobile_units.find(x=>x.imei===code):null;if(!u){$('erHint').textContent='';return}$('erItem').value=u.item;const sale=u.saleId?db.sales.find(s=>s.id===u.saleId):null;const who=sale?.customerId||db.customers.find(c=>c.name===u.customer)?.id;if(who)$('erCust').value=who;$('erHint').textContent=u.status==='sold'?'Sold '+(u.soldAt||'').slice(0,10)+(u.warrantyUntil?' · warranty until '+u.warrantyUntil+(u.warrantyUntil<today()?' (ended)':''):' · no warranty'):'In stock'};
  $('eRma').onsubmit=e=>{e.preventDefault();const id=uid(),c=cust($('erCust').value),now=new Date().toISOString();
   if(change(()=>db.elec_rma.push({id,number:0,supplier:$('erSup').value.trim(),item:$('erItem').value.trim(),serial:$('erSerial').value.trim().toUpperCase(),fault:$('erFault').value.trim(),customerId:c?.id||'',customer:c?.name||'',phone:c?.phone||'',ref:'',note:$('erNote').value.trim(),outcome:'',newSerial:'',status:'Open',created:now,history:[{status:'Open',at:now}]}))){rmaView='Open';render();rmaSlip(id)}}}
 function rmaSlip(id){const r=db.elec_rma.find(x=>x.id===id);if(!r)return;slip('Warranty claim slip',`${head()}WARRANTY CLAIM${r.number?' No. '+r.number:''}\n${new Date(r.created).toLocaleString()}\n${line}\nItem: ${r.item}${r.serial?'\nS/N: '+r.serial:''}\nFault: ${r.fault}\n${r.note?'With: '+r.note+'\n':''}${line}\n${r.customer?'Customer: '+r.customer+'\nPhone: '+(r.phone||'-')+'\n':'Shop stock\n'}Sent to: ${r.supplier}${r.ref?'\nSupplier ref: '+r.ref:''}\n${line}\nThe item is sent to the supplier / service\ncentre for inspection. Repair, replacement\nor rejection is decided by the\nmanufacturer's warranty terms. Back up\nyour data: it may be erased.\n\nCustomer signature: ______________`)}
 function rmaOpen(id){const r=db.elec_rma.find(x=>x.id===id);if(!r)return;const open=rmaOpenState(r),next=RMA_NEXT[r.status];
  modal(`<h2>Claim #${r.number||'…'} · ${esc(r.item)}</h2><p>${badge(r.status)} ${r.serial?'S/N '+esc(r.serial)+' · ':''}${esc(r.fault)}</p><p class="helper">${esc(r.supplier)}${r.ref?' · supplier ref '+esc(r.ref):''} · ${r.customer?esc(r.customer)+(r.phone?' · '+esc(r.phone):''):'Shop stock'}${r.note?' · '+esc(r.note):''}${r.outcome?'<br><b>'+esc(r.outcome)+'</b>'+(r.newSerial?' · new S/N '+esc(r.newSerial):''):''}${r.cancelReason?'<br>Cancelled: '+esc(r.cancelReason):''}</p>
  ${next==='Sent'?`<form id="erStep"><label for="esRef">Supplier’s claim / RMA number (optional)</label><input id="esRef" maxlength="60" value="${esc(r.ref||'')}"><button class="primary">Sent to supplier</button></form>`:next==='Back'?`<form id="erStep"><label for="esOut">Back from the supplier: what did they do?</label><select id="esOut">${OUTCOMES.map(o=>`<option>${o}</option>`).join('')}</select><label for="esNew">New serial number (if replaced)</label><input id="esNew" maxlength="40"><button class="primary">Back from supplier</button></form>`:next==='Closed'?`<form id="erStep"><p class="helper">${r.customer?'Hand the item back to the customer':'Put the item back on the shelf (or record the credit note in Finance → Purchases)'}, then close the claim.</p><button class="primary">Close claim</button></form>${r.phone?'<div class="actions"><button id="esWa">WhatsApp “ready”</button></div>':''}`:''}
  <div class="actions"><button onclick="closeModal()">Close</button><button id="esSlip">Claim slip</button>${r.status==='Open'?'<button class="danger" id="esCancel">Cancel claim</button>':''}</div>`);
  $('esSlip').onclick=()=>rmaSlip(id);if(!open)return;
  const upd=(fn,msg)=>{if(change(()=>fn(db.elec_rma.find(x=>x.id===id)))){closeModal();toast(msg);if(tab==='RMA')rma()}};
  $('erStep').onsubmit=e=>{e.preventDefault();upd(x=>{if(next==='Sent')x.ref=$('esRef').value.trim();if(next==='Back'){x.outcome=$('esOut').value;x.newSerial=$('esNew').value.trim().toUpperCase()}x.status=next},'Claim #'+r.number+' → '+next)};
  if($('esCancel'))$('esCancel').onclick=()=>{const why=prompt('Reason for cancelling this claim:');if(why?.trim())upd(x=>{x.status='Cancelled';x.cancelReason=why.trim()},'Claim cancelled')};
  if($('esWa'))$('esWa').onclick=()=>wa(r.phone,`Hello ${r.customer.split(' ')[0]}, your ${r.item} is back from the service centre (${r.outcome.toLowerCase()}) and ready for collection at ${db.settings.name}. Claim no. ${r.number}.`)}

 Object.assign(R.screens,{Quotes:quotes,Jobs:jobs,RMA:rma});
 Object.assign(window,{elecQuotes:v=>{quoteView=v;quotes()},elecQuoteNew:()=>{draft={customerId:'',title:'',lines:[],discount:'',validUntil:plus(14),note:''};quoteForm()},elecQuoteOpen:quoteOpen,elecJobs:v=>{jobView=v;jobs()},elecJobNew:()=>jobNew(),elecJobOpen:jobOpen,elecRma:v=>{rmaView=v;rma()},elecRmaNew:rmaNew,elecRmaOpen:rmaOpen});
})();
