'use strict';
// Owner screens that work for every business type: Marketing (loyalty, coupons, customer groups, WhatsApp
// campaigns) and HR (staff files, attendance, leave, salaries). Restaurants also get Ingredients (recipes and
// food cost). All need the internet. Tills get two small buttons: Rewards (redeem points / coupon) and Clock in/out.
const EX_TABS=['Marketing','HR','Ingredients'];
let exData={},exReq=0,hrView='Staff',hrMonth=financeDay().slice(0,7),exTill={rewards:null,clock:[],forBusiness:''};
const exOwner=()=>cloudUser?.role==='owner'&&!cloudUser?.waiter,exTabs=()=>exOwner()?['Marketing','HR',...(cloudUser.businessType==='restaurant'?['Ingredients']:[])]:[];
const exAed=v=>(v/100).toFixed(2),exNum=v=>Number(v)||0,exId=()=>crypto.randomUUID();
const exErr=m=>{const n=$('exError');if(n){n.textContent=m||'';n.hidden=!m}else if(m)alert(m)};
async function exPost(path,data,after){try{const r=await api(path,'POST',data);if(after)await after(r);return r}catch(e){exErr(e.status?e.message:'This needs the internet. Nothing was saved.');return null}}
// ---- navigation: extra tabs are added after whatever tabs the business type shows ----
function exNav(){const nav=$('nav');if(!nav||!cloudReady)return;nav.querySelectorAll('[data-extra-tab]').forEach(b=>b.remove());const before=[...nav.querySelectorAll('[data-cloud-tab]')].find(b=>['Team','Sync centre','Account'].includes(b.dataset.cloudTab));
 for(const t of exTabs()){const b=document.createElement('button');b.dataset.extraTab=t;b.textContent=t;if(tab===t)b.className='active';b.onclick=()=>navigate(t);before?nav.insertBefore(b,before):nav.appendChild(b)}
 if(EX_TABS.includes(tab))nav.querySelectorAll('[data-cloud-tab]').forEach(b=>b.classList.remove('active'))}
const navigateBeforeExtras=navigate,renderBeforeExtras=render;
navigate=function(next){if(!EX_TABS.includes(next)){navigateBeforeExtras(next);return}if(!cloudReady||!exTabs().includes(next)){alert('Owner access required');return}tab=next;exData[next]=null;render()};
render=function(){if(!EX_TABS.includes(tab)||!cloudReady){renderBeforeExtras();exNav();return}if(!exTabs().includes(tab)){tab='Dashboard';renderBeforeExtras();exNav();return}
 const t=tab;tab='Dashboard';renderBeforeExtras();tab=t;exNav();exScreen()};
const EX_LOAD={Marketing:()=>api('marketing/overview'),HR:async()=>({o:await api('hr/overview'),att:await api('hr/attendance?month='+hrMonth),pay:await api('hr/payroll?month='+hrMonth)}),Ingredients:async()=>({k:await api('recipes/overview'),pay:await api('finance/payables')})};
const EX_DRAW={Marketing:mkScreen,HR:hrScreen,Ingredients:ingScreen};
async function exScreen(reload){const t=tab;if(exData[t]&&!reload){EX_DRAW[t](exData[t]);return}const request=++exReq;if(!exData[t])$('app').innerHTML=`<div class="panel"><h2>${esc(t)}</h2><p>Loading…</p></div>`;
 try{const d=await EX_LOAD[t]();if(tab!==t||request!==exReq)return;exData[t]=d;EX_DRAW[t](d)}catch(e){if(tab===t&&request===exReq)$('app').innerHTML=`<div class="panel"><h2>${esc(t)}</h2><p>${esc(e.status?e.message:'This screen needs the internet.')}</p><button onclick="exScreen(true)">Retry</button></div>`}}
const exReload=()=>{closeModal();return exScreen(true)};

// =============================== MARKETING ===============================
function mkScreen(d){const L=d.loyalty,gcount=k=>d.groups[k].length;
 $('app').innerHTML=`<div class="row"><div><div class="eyebrow">BRING CUSTOMERS BACK</div><h2>Marketing</h2><p>Loyalty points, coupons and WhatsApp campaigns for your saved customers.</p></div></div>
 <div class="layout"><section>
 <div class="panel"><div class="row"><h3>Customer groups</h3></div><p class="helper">Worked out from your sales. Only customers saved on the bill are counted.</p>${d.groupNames.map(([k,l])=>`<div class="row" style="padding:8px 0;border-bottom:1px solid #eee"><div><b>${esc(l)}</b><div class="helper">${gcount(k)} customer${gcount(k)===1?'':'s'}</div></div><span class="actions" style="margin:0"><button data-mk-view="${k}" ${gcount(k)?'':'disabled'}>View</button><button class="primary" data-mk-camp="${k}" ${d.groups[k].some(c=>c.phone)?'':'disabled'}>Message them</button></span></div>`).join('')}</div>
 <div class="panel"><h3>Campaigns</h3>${d.campaigns.length?`<div class="scroll"><table><tr><th>Campaign</th><th>Group</th><th>Sent</th><th>Came back (30 days)</th><th>Sales after</th><th></th></tr>${d.campaigns.map(c=>`<tr><td>${esc(c.name)}<div class="helper">${esc(c.createdAt.slice(0,10))}</div></td><td>${esc((d.groupNames.find(g=>g[0]===c.group)||[])[1]||c.group)}</td><td>${c.sent} / ${c.recipients.length}</td><td>${c.returned}</td><td>${money(c.revenue)}</td><td><button data-mk-send="${esc(c.id)}">${c.sent<c.recipients.length?'Continue sending':'View'}</button></td></tr>`).join('')}</table></div>`:'<p>No campaigns yet. Choose a group above and press “Message them”.</p>'}<p class="helper">The POS opens WhatsApp with the message ready for each customer; you press Send. Nothing is sent automatically.</p></div>
 </section><aside>
 <div class="panel"><h3>Loyalty points</h3>${d.builtInLoyalty?'<p class="helper">Perfume shops use the built-in loyalty points (Settings → Loyalty), which work on the bill even offline.</p>':`<form id="mkLoyalty"><label style="display:flex;gap:8px;align-items:center"><input type="checkbox" id="mkOn" ${L.enabled?'checked':''} style="width:auto"> Give points on sales to saved customers</label><label>Points per AED spent</label><input id="mkEarn" type="number" min="1" max="100" value="${L.earnPerAed}" required><label>Value of 1 point (fils)</label><input id="mkFils" type="number" min="1" max="1000" value="${L.redeemFils}" required><label>Minimum points to redeem</label><input id="mkMin" type="number" min="1" value="${L.minRedeem}" required><p class="helper" id="mkExample"></p><p id="exError" class="pending-note" role="alert" hidden></p><button class="primary">Save loyalty settings</button></form>`}
 ${d.balances.length?`<h3 style="margin-top:18px">Top point balances</h3>${d.balances.slice(0,8).map(c=>`<div class="row" style="padding:4px 0"><span>${esc(c.name)}</span><b>${c.balance} pts · ${money(c.value)}</b></div>`).join('')}`:''}</div>
 <div class="panel"><div class="row"><h3>Coupons</h3><button class="primary" onclick="mkCoupon()">+ Coupon</button></div>${d.coupons.length?d.coupons.map(c=>`<div class="row" style="padding:8px 0;border-bottom:1px solid #eee"><div><b>${esc(c.code)}</b> · ${c.kind==='percent'?c.value/100+'% off':money(c.value)+' off'}<div class="helper">${c.minSpend?'Min spend '+money(c.minSpend)+' · ':''}${c.expires?'Until '+esc(c.expires)+' · ':''}Used ${c.uses}${c.maxUses?' / '+c.maxUses:''}${c.active?'':' · Off'}</div></div><button data-mk-coupon="${esc(c.id)}">Edit</button></div>`).join(''):'<p class="helper">No coupons yet.</p>'}<p class="helper">At the till, press <b>Rewards</b> in the status bar to redeem points or a coupon. It needs the internet.</p></div>
 </aside></div>`;
 if($('mkLoyalty')){const ex=()=>{$('mkExample').textContent='Example: a customer who spends AED 100 earns '+100*exNum($('mkEarn').value)+' points, worth AED '+exAed(100*exNum($('mkEarn').value)*exNum($('mkFils').value))+'.'};$('mkEarn').oninput=ex;$('mkFils').oninput=ex;ex();
  $('mkLoyalty').onsubmit=e=>{e.preventDefault();exPost('marketing/loyalty',{enabled:$('mkOn').checked,earnPerAed:exNum($('mkEarn').value),redeemFils:exNum($('mkFils').value),minRedeem:exNum($('mkMin').value)},async()=>{toast('Loyalty settings saved');await exScreen(true);exLoadTill()})}}
 document.querySelectorAll('[data-mk-view]').forEach(b=>b.onclick=()=>{const k=b.dataset.mkView,rows=d.groups[k];modal(`<h2>${esc(d.groupNames.find(g=>g[0]===k)[1])}</h2><div class="scroll" style="max-height:55vh"><table><tr><th>Customer</th><th>Phone</th><th>Visits</th><th>Spent</th><th>Last visit</th></tr>${rows.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.phone||'—')}</td><td>${c.visits}</td><td>${money(c.spend)}</td><td>${esc(c.last?c.last.slice(0,10):'—')}</td></tr>`).join('')}</table></div><div class="actions"><button onclick="closeModal()">Close</button><button class="primary" id="mkCsv">Export CSV</button></div>`);$('mkCsv').onclick=()=>saveCsv('customers-'+k+'.csv',[['Customer','Phone','Visits','Spent AED','First visit','Last visit'],...rows.map(c=>[c.name,c.phone,c.visits,exAed(c.spend),c.first.slice(0,10),c.last.slice(0,10)])])});
 document.querySelectorAll('[data-mk-camp]').forEach(b=>b.onclick=()=>mkCampaign(b.dataset.mkCamp,d));
 document.querySelectorAll('[data-mk-send]').forEach(b=>b.onclick=()=>mkSend(d.campaigns.find(c=>c.id===b.dataset.mkSend)));
 document.querySelectorAll('[data-mk-coupon]').forEach(b=>b.onclick=()=>mkCoupon(d.coupons.find(c=>c.id===b.dataset.mkCoupon)))}
function mkCoupon(c){const id=c?.id||exId();modal(`<h2>${c?'Edit':'New'} coupon</h2><form id="mkC"><label>Code (customers say or show this)</label><input id="mcCode" maxlength="40" required value="${esc(c?.code||'')}" placeholder="e.g. EID10" style="text-transform:uppercase"><div class="business-grid"><div><label>Type</label><select id="mcKind"><option value="percent" ${c?.kind==='amount'?'':'selected'}>Percent off</option><option value="amount" ${c?.kind==='amount'?'selected':''}>Amount off (AED)</option></select></div><div><label>Value</label><input id="mcValue" type="number" min="0.01" step="0.01" required value="${c?c.value/100:''}"></div></div><div class="business-grid"><div><label>Minimum spend (AED, optional)</label><input id="mcMin" type="number" min="0" step="0.01" value="${c?.minSpend?exAed(c.minSpend):''}"></div><div><label>Valid until (optional)</label><input id="mcExp" type="date" value="${esc(c?.expires||'')}"></div></div><label>Usage limit (0 = unlimited)</label><input id="mcMax" type="number" min="0" step="1" value="${c?.maxUses||0}"><label style="display:flex;gap:8px;align-items:center"><input type="checkbox" id="mcOn" ${c&&!c.active?'':'checked'} style="width:auto"> Active</label><p id="exError" class="pending-note" role="alert" hidden></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save coupon</button></div></form>`);
 $('mkC').onsubmit=e=>{e.preventDefault();exPost('marketing/coupons',{id,code:$('mcCode').value.trim(),kind:$('mcKind').value,value:cents($('mcValue').value),minSpend:cents($('mcMin').value||0),expires:$('mcExp').value,maxUses:exNum($('mcMax').value),active:$('mcOn').checked},async()=>{await exReload();exLoadTill()})}}
function mkCampaign(k,d){const label=d.groupNames.find(g=>g[0]===k)[1],n=d.groups[k].filter(c=>c.phone).length,shop=db.settings.name||'us',id=exId();
 const preset={top:`Hi {name}, thank you for being one of our best customers at ${shop}! Show this message for a special offer on your next visit.`,birthday:`Happy birthday {name}! Enjoy a birthday treat from ${shop} this month.`,new:`Hi {name}, thank you for visiting ${shop}. We hope to see you again soon!`,all:`Hi {name}, news from ${shop}: `}[k]||`Hi {name}, we miss you at ${shop}! Come back this week for a special offer.`;
 modal(`<h2>Message: ${esc(label)}</h2><p class="helper">${n} customer${n===1?'':'s'} with a phone number. The list is fixed when you create the campaign.</p><form id="mkCp"><label>Campaign name</label><input id="cpName" maxlength="80" required value="${esc(label.split(' (')[0])} · ${financeDay()}"><label>Message ({name} becomes the customer's name)</label><textarea id="cpMsg" rows="5" maxlength="1000" required>${esc(preset)}</textarea><p id="exError" class="pending-note" role="alert" hidden></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Create &amp; start sending</button></div></form>`);
 $('mkCp').onsubmit=e=>{e.preventDefault();exPost('marketing/campaigns',{id,name:$('cpName').value,group:k,message:$('cpMsg').value},async()=>{await exScreen(true);mkSend(exData.Marketing.campaigns.find(c=>c.id===id))})}}
function mkSend(c){if(!c)return;const draw=()=>{modal(`<h2>${esc(c.name)}</h2><p class="helper">Tap a customer to open WhatsApp with the message ready, then press Send there. ${c.recipients.filter(r=>r.sentAt).length} of ${c.recipients.length} done.</p><div class="scroll" style="max-height:55vh">${c.recipients.map((r,i)=>`<div class="row" style="padding:8px 0;border-bottom:1px solid #eee"><div><b>${esc(r.name)}</b><div class="helper">${esc(r.phone)}</div></div>${r.sentAt?'<span class="badge" style="background:#dff3e9;color:#155e48">Opened ✓</span>':`<button class="primary" data-cp-send="${i}">Open WhatsApp</button>`}</div>`).join('')}</div><div class="actions"><button onclick="exReload()">Done</button></div>`);
  document.querySelectorAll('[data-cp-send]').forEach(b=>b.onclick=async()=>{const r=c.recipients[Number(b.dataset.cpSend)];let url;try{url=SalonWhatsApp.link(r.phone,c.message.replaceAll('{name}',r.name.split(' ')[0]))}catch(e){alert(r.name+': '+e.message);return}window.open(url,'_blank','noopener');r.sentAt=new Date().toISOString();draw();try{await api('marketing/campaigns/sent','POST',{id:c.id,customerId:r.id})}catch{}})};draw()}

// =============================== HR ===============================
function hrScreen(d){const o=d.o,emp=new Map(o.employees.map(e=>[e.id,e])),views=['Staff','Attendance','Leave','Salaries'];
 const head=`<div class="row"><div><div class="eyebrow">YOUR TEAM</div><h2>HR</h2><p>Staff files, attendance, leave and monthly salaries.</p></div></div><div class="actions" role="tablist">${views.map(v=>`<button role="tab" class="${hrView===v?'primary':''}" data-hr-view="${v}">${v}</button>`).join('')}</div>${o.expiring.length?`<div class="pending-note"><b>Documents to renew:</b> ${o.expiring.map(x=>`${esc(x.employee)} · ${esc(x.type)} ${x.expired?'<b>expired</b>':'expires'} ${esc(x.expiry)}`).join(' &nbsp;|&nbsp; ')}</div>`:''}`;
 const monthPick=`<label style="max-width:220px">Month<input type="month" id="hrMonth" value="${esc(hrMonth)}" max="${financeDay().slice(0,7)}"></label>`;
 let body='';
 if(hrView==='Staff')body=`<div class="panel"><div class="row"><h3>Staff files</h3><button class="primary" onclick="hrEmployee()">+ Employee</button></div>${o.employees.length?`<div class="scroll"><table><tr><th>Name</th><th>Job</th><th>Joined</th><th>Basic</th><th>Allowances</th><th>Today</th><th>Gratuity estimate</th><th></th></tr>${o.employees.map(e=>{const t=o.todayAttendance.filter(a=>a.employee_id===e.id);return `<tr${e.active?'':' style="opacity:.55"'}><td><b>${esc(e.name)}</b>${e.active?'':' (left)'}<div class="helper">${esc(e.phone)}${e.hasPin?' · PIN set':''}</div></td><td>${esc(e.job)}</td><td>${esc(e.joined)}</td><td>${money(e.basic)}</td><td>${money(e.allowances)}</td><td>${t.length?esc(t.map(a=>a.time_in+'–'+(a.time_out||'…')).join(', ')):'—'}</td><td>${money(e.gratuity.amount)}<div class="helper">${e.gratuity.years} yr</div></td><td><button data-hr-edit="${esc(e.id)}">Edit</button></td></tr>`}).join('')}</table></div>`:'<p>No employees yet. Add your staff to track documents, attendance and salaries.</p>'}<p class="helper">Gratuity is an estimate on basic salary (21 days per year for the first 5 years, 30 days after, nothing before 1 year, capped at 2 years’ pay). Confirm the final amount with MOHRE rules or your PRO.</p></div>`;
 if(hrView==='Attendance')body=`<div class="panel"><div class="row"><h3>Attendance</h3>${monthPick}</div>${d.att.rows.length?`<div class="scroll"><table><tr><th>Employee</th><th>Days present</th><th>Hours</th><th>Late</th><th>Not clocked out</th><th></th></tr>${d.att.rows.map((r,i)=>`<tr><td>${esc(r.name)}</td><td>${r.days}</td><td>${r.hours}</td><td>${r.startTime?r.late:'—'}</td><td>${r.open||'—'}</td><td><button data-hr-days="${i}">Days</button></td></tr>`).join('')}</table></div>`:'<p>No attendance in this month.</p>'}<p class="helper">Staff press <b>Clock in / out</b> in the status bar of any signed-in device and enter their PIN (set it in the staff file). “Late” counts arrivals more than 10 minutes after the start time in the staff file.</p></div>`;
 if(hrView==='Leave')body=`<div class="panel"><div class="row"><h3>Leave</h3><button class="primary" onclick="hrLeave()" ${o.employees.length?'':'disabled'}>+ Record leave</button></div>${o.leaves.length?`<div class="scroll"><table><tr><th>Employee</th><th>Type</th><th>From</th><th>To</th><th>Days</th><th>Note</th><th></th></tr>${o.leaves.map(l=>`<tr><td>${esc(emp.get(l.employeeId)?.name||'')}</td><td>${esc(l.type)}</td><td>${esc(l.from)}</td><td>${esc(l.to)}</td><td>${l.days}</td><td>${esc(l.note)}</td><td><button data-hr-del="${esc(l.id)}">Delete</button></td></tr>`).join('')}</table></div>`:'<p>No leave recorded.</p>'}<p class="helper">Unpaid leave days are deducted on the salary sheet automatically (basic ÷ 30 per day).</p></div>`;
 if(hrView==='Salaries'){const p=d.pay,t=p.totals;body=`<div class="panel"><div class="row"><h3>Salaries · ${esc(p.month)}</h3>${monthPick}</div>${p.lines.length?`${p.paid?`<p><span class="badge" style="background:#dff3e9;color:#155e48">Paid ${esc(p.paidAt.slice(0,10))}</span></p>`:''}<div class="scroll"><table><tr><th>Employee</th><th>Basic</th><th>Allowances</th><th>Commission</th><th>Additions</th><th>Deductions</th><th>Note</th><th>Net pay</th><th></th></tr>${p.lines.map((l,i)=>`<tr><td>${esc(l.name)}</td><td>${money(l.basic)}</td><td>${money(l.allowances)}</td><td>${money(l.commission)}</td><td>${p.paid?money(l.additions):`<input data-pay-add="${i}" type="number" min="0" step="0.01" value="${exAed(l.additions)}" style="width:100px;margin:0">`}</td><td>${p.paid?money(l.deductions):`<input data-pay-ded="${i}" type="number" min="0" step="0.01" value="${exAed(l.deductions)}" style="width:100px;margin:0">`}</td><td>${p.paid?esc(l.note):`<input data-pay-note="${i}" maxlength="200" value="${esc(l.note)}" style="width:150px;margin:0">`}</td><td><b>${money(l.net)}</b></td><td><button data-pay-slip="${i}">Payslip</button></td></tr>`).join('')}<tr><th>Total</th><th>${money(t.basic)}</th><th>${money(t.allowances)}</th><th>${money(t.commission)}</th><th>${money(t.additions)}</th><th>${money(t.deductions)}</th><th></th><th>${money(t.net)}</th><th></th></tr></table></div><p id="exError" class="pending-note" role="alert" hidden></p><div class="actions">${p.paid?'':`<button id="paySave">Save sheet</button><select id="payMethod" style="max-width:180px"><option>Bank / card</option><option>Cash</option></select><button class="primary" id="payPay">Mark salaries paid</button>`}<button id="payCsv">Export CSV</button></div>`:'<p>No employees for this month.</p>'}<p class="helper">Marking paid locks the month and records one expense (“Salary”) in Finance for the total, without the commission part: profit &amp; loss already counts earned commissions. Commission shows for employees linked to a POS staff member.</p></div>`}
 $('app').innerHTML=head+body;
 document.querySelectorAll('[data-hr-view]').forEach(b=>b.onclick=()=>{hrView=b.dataset.hrView;hrScreen(d)});
 if($('hrMonth'))$('hrMonth').onchange=e=>{if(e.target.value){hrMonth=e.target.value;exScreen(true)}};
 document.querySelectorAll('[data-hr-edit]').forEach(b=>b.onclick=()=>hrEmployee(emp.get(b.dataset.hrEdit)));
 document.querySelectorAll('[data-hr-del]').forEach(b=>b.onclick=()=>{if(confirm('Delete this leave record?'))exPost('hr/leaves/delete',{id:b.dataset.hrDel},()=>exScreen(true))});
 document.querySelectorAll('[data-hr-days]').forEach(b=>b.onclick=()=>{const r=d.att.rows[Number(b.dataset.hrDays)];modal(`<h2>${esc(r.name)} · ${esc(d.att.month)}</h2><div class="scroll" style="max-height:55vh"><table><tr><th>Date</th><th>In</th><th>Out</th></tr>${r.entries.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.in)}</td><td>${esc(x.out||'not clocked out')}</td></tr>`).join('')}</table></div><div class="actions"><button onclick="closeModal()">Close</button></div>`)});
 if(hrView==='Salaries'&&d.pay.lines.length){const p=d.pay,lines=()=>p.lines.map((l,i)=>({employeeId:l.employeeId,additions:cents(document.querySelector(`[data-pay-add="${i}"]`)?.value||0),deductions:cents(document.querySelector(`[data-pay-ded="${i}"]`)?.value||0),note:document.querySelector(`[data-pay-note="${i}"]`)?.value||''}));
  if($('paySave'))$('paySave').onclick=()=>exPost('hr/payroll/save',{month:p.month,lines:lines()},async()=>{toast('Salary sheet saved');await exScreen(true)});
  if($('payPay'))$('payPay').onclick=()=>{if(confirm('Mark salaries for '+p.month+' as paid by '+$('payMethod').value+'? This locks the month and records the expense.'))exPost('hr/payroll/pay',{month:p.month,method:$('payMethod').value,lines:lines()},async()=>{toast('Salaries marked paid');await exScreen(true)})};
  $('payCsv').onclick=()=>saveCsv('salaries-'+p.month+'.csv',[['Salaries',p.month,p.paid?'Paid '+p.paidAt.slice(0,10):'Not paid'],['Employee','Job','Basic','Allowances','Commission','Additions','Deductions','Net pay','Note'],...p.lines.map(l=>[l.name,l.job,exAed(l.basic),exAed(l.allowances),exAed(l.commission),exAed(l.additions),exAed(l.deductions),exAed(l.net),l.note]),['TOTAL','',exAed(p.totals.basic),exAed(p.totals.allowances),exAed(p.totals.commission),exAed(p.totals.additions),exAed(p.totals.deductions),exAed(p.totals.net)]]);
  document.querySelectorAll('[data-pay-slip]').forEach(b=>b.onclick=()=>{const l=p.lines[Number(b.dataset.paySlip)],row=(a,v)=>`<tr><td>${a}</td><td class="n">${exAed(v)}</td></tr>`;printReport('Payslip '+l.name+' '+p.month,`<h2>Payslip · ${esc(p.month)}</h2><p><b>${esc(l.name)}</b>${l.job?' · '+esc(l.job):''}</p><table><tr><th>Earnings</th><th class="n">AED</th></tr>${row('Basic salary',l.basic)}${row('Allowances',l.allowances)}${l.commission?row('Commission',l.commission):''}${l.additions?row('Additions',l.additions):''}<tr><th>Deductions</th><th></th></tr>${row('Deductions'+(l.note?' ('+esc(l.note)+')':''),-l.deductions)}<tr class="total"><td>Net pay</td><td class="n">${exAed(l.net)}</td></tr></table><p class="muted">${p.paid?'Paid on '+esc(p.paidAt.slice(0,10))+' by '+esc(l.method||''):'Not yet paid'}</p><p style="margin-top:40px">Employee signature: ____________________</p>`)})}}
function hrEmployee(e){const o=exData.HR.o,id=e?.id||exId(),docs=e?.docs?.length?e.docs.map(x=>({...x})):[];
 const docRows=()=>docs.map((x,i)=>`<div class="business-grid" style="grid-template-columns:1fr 1fr 1fr auto;align-items:end"><div><label>Document</label><select data-doc-type="${i}">${o.docTypes.map(t=>`<option ${x.type===t?'selected':''}>${t}</option>`).join('')}</select></div><div><label>Number</label><input data-doc-no="${i}" maxlength="60" value="${esc(x.number||'')}"></div><div><label>Expiry</label><input data-doc-exp="${i}" type="date" value="${esc(x.expiry||'')}"></div><button type="button" data-doc-del="${i}" aria-label="Remove document">×</button></div>`).join('');
 const read=()=>docs.forEach((x,i)=>{x.type=document.querySelector(`[data-doc-type="${i}"]`).value;x.number=document.querySelector(`[data-doc-no="${i}"]`).value;x.expiry=document.querySelector(`[data-doc-exp="${i}"]`).value});
 const wire=()=>{$('heDocs').innerHTML=docRows();document.querySelectorAll('[data-doc-del]').forEach(b=>b.onclick=()=>{read();docs.splice(Number(b.dataset.docDel),1);wire()})};
 modal(`<h2>${e?'Edit':'Add'} employee</h2><form id="hrE"><div class="business-grid"><div><label>Full name</label><input id="heName" maxlength="100" required value="${esc(e?.name||'')}"></div><div><label>Job title</label><input id="heJob" maxlength="80" value="${esc(e?.job||'')}"></div></div><div class="business-grid"><div><label>Joining date</label><input id="heJoined" type="date" required max="${financeDay()}" value="${esc(e?.joined||financeDay())}"></div><div><label>Phone</label><input id="hePhone" maxlength="40" value="${esc(e?.phone||'')}"></div></div><div class="business-grid"><div><label>Basic salary (AED / month)</label><input id="heBasic" type="number" min="0" step="0.01" required value="${e?exAed(e.basic):''}"></div><div><label>Allowances (AED / month)</label><input id="heAllow" type="number" min="0" step="0.01" value="${e?exAed(e.allowances):'0'}"></div></div><div class="business-grid"><div><label>Work starts at (for “late”, optional)</label><input id="heStart" type="time" value="${esc(e?.startTime||'')}"></div><div><label>Clock-in PIN (4–6 digits${e?.hasPin?', leave empty to keep':''})</label><input id="hePin" inputmode="numeric" maxlength="6" autocomplete="off"></div></div>${o.posStaff.length?`<label>Linked POS staff member (for commission on the payslip)</label><select id="heStaff"><option value="">Not linked</option>${o.posStaff.map(s=>`<option value="${esc(s.id)}" ${e?.staffId===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select>`:''}<h3 style="margin-top:14px">Documents</h3><div id="heDocs"></div><button type="button" id="heAddDoc">+ Document</button>${e?`<label style="display:flex;gap:8px;align-items:center;margin-top:12px"><input type="checkbox" id="heActive" ${e.active?'checked':''} style="width:auto"> Currently employed</label>`:''}<p id="exError" class="pending-note" role="alert" hidden></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save employee</button></div></form>`);
 wire();$('heAddDoc').onclick=()=>{read();if(docs.length<12){docs.push({type:'Visa',number:'',expiry:''});wire()}};
 $('hrE').onsubmit=ev=>{ev.preventDefault();read();const pin=$('hePin').value.trim();exPost('hr/employees',{id,name:$('heName').value,job:$('heJob').value,joined:$('heJoined').value,phone:$('hePhone').value,basic:cents($('heBasic').value),allowances:cents($('heAllow').value||0),startTime:$('heStart').value,staffId:$('heStaff')?.value||'',docs,active:$('heActive')?$('heActive').checked:true,...(pin?{pin}:{})},async()=>{await exReload();exLoadTill()})}}
function hrLeave(){const o=exData.HR.o;modal(`<h2>Record leave</h2><form id="hrL"><label>Employee</label><select id="hlEmp">${o.employees.filter(e=>e.active).map(e=>`<option value="${esc(e.id)}">${esc(e.name)}</option>`).join('')}</select><label>Type</label><select id="hlType">${o.leaveTypes.map(t=>`<option>${t}</option>`).join('')}</select><div class="business-grid"><div><label>From</label><input id="hlFrom" type="date" required value="${financeDay()}"></div><div><label>To</label><input id="hlTo" type="date" required value="${financeDay()}"></div></div><label>Note</label><input id="hlNote" maxlength="200"><p id="exError" class="pending-note" role="alert" hidden></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save leave</button></div></form>`);
 $('hrL').onsubmit=e=>{e.preventDefault();exPost('hr/leaves',{id:exId(),employeeId:$('hlEmp').value,type:$('hlType').value,from:$('hlFrom').value,to:$('hlTo').value,note:$('hlNote').value},exReload)}}

// =============================== INGREDIENTS (restaurants) ===============================
const ingQty=(n,u)=>(Math.round(n*1000)/1000)+' '+u;
function ingScreen(d){const k=d.k,low=k.ingredients.filter(i=>i.low),withRecipe=k.menu.filter(m=>m.lines.length).length;
 $('app').innerHTML=`<div class="row"><div><div class="eyebrow">KNOW YOUR FOOD COST</div><h2>Ingredients &amp; recipes</h2><p>${esc(k.from)} to ${esc(k.to)}</p></div><div class="actions" style="margin:0"><button onclick="ingForm()">+ Ingredient</button><button class="primary" onclick="ingReceive()" ${k.ingredients.length?'':'disabled'}>+ Supplier invoice</button></div></div>
 <div class="grid">${[['Food cost · dishes with a recipe',k.foodCostPct===null?'—':k.foodCostPct+'%'],['Ingredients used (at cost)',money(k.usageCost)],['Stock value',money(k.stockValue)],['Low stock',low.length]].map(([l,v])=>`<div class="panel">${l}<div class="metric">${v}</div></div>`).join('')}</div>
 ${low.length?`<p class="pending-note"><b>Low stock:</b> ${low.map(i=>esc(i.name)+' ('+esc(ingQty(i.stock,i.unit))+')').join(', ')}</p>`:''}
 <div class="panel"><h3>Ingredients</h3>${k.ingredients.length?`<div class="scroll"><table><tr><th>Ingredient</th><th>In stock</th><th>Cost / unit</th><th>Value</th><th>Used this month</th><th></th></tr>${k.ingredients.map(i=>`<tr${i.active?'':' style="opacity:.55"'}><td><b>${esc(i.name)}</b>${i.minStock?`<div class="helper">Minimum ${esc(ingQty(i.minStock,i.unit))}</div>`:''}</td><td${i.stock<0?' style="color:#b42318"':''}>${esc(ingQty(i.stock,i.unit))}</td><td>${money(i.cost)}/${esc(i.unit)}</td><td>${money(i.value)}</td><td>${esc(ingQty(i.periodUsed,i.unit))}</td><td class="actions" style="margin:0"><button data-ing-count="${esc(i.id)}">Count</button><button data-ing-waste="${esc(i.id)}">Waste</button><button data-ing-edit="${esc(i.id)}">Edit</button></td></tr>`).join('')}</table></div>`:'<p>Start by adding the ingredients you buy (rice, chicken, oil…), then give each dish its recipe below.</p>'}<p class="helper">Stock = last count + deliveries − waste − what paid bills used according to the recipes. Refunded bills give ingredients back. Negative stock means a delivery was not recorded or a recipe uses too much.</p></div>
 <div class="panel"><h3>Recipes &amp; dish cost</h3><p class="helper">${withRecipe} of ${k.menu.length} dishes have a recipe. Aim for a food cost of roughly 25–35% of the price for most dishes.</p><div class="scroll"><table><tr><th>Dish</th><th>Price</th><th>Cost</th><th>Margin</th><th>Food cost</th><th></th></tr>${k.menu.map(m=>`<tr><td><b>${esc(m.name)}</b><div class="helper">${esc(m.category||'')}${m.lines.length?' · '+esc(m.lines.map(l=>ingQty(l.qty,l.unit)+' '+l.name).join(', ')):''}</div></td><td>${money(m.price)}</td><td>${m.lines.length?money(m.cost):'—'}</td><td>${m.lines.length?money(m.margin):'—'}</td><td${m.foodCostPct>40?' style="color:#b42318;font-weight:700"':''}>${m.foodCostPct===null?'—':m.foodCostPct+'%'}</td><td><button data-ing-recipe="${esc(m.id)}" ${k.ingredients.length?'':'disabled'}>${m.lines.length?'Edit recipe':'Add recipe'}</button></td></tr>`).join('')}</table></div></div>
 ${k.moves.length?`<div class="panel"><h3>Recent stock movements</h3><div class="scroll"><table><tr><th>When</th><th>Ingredient</th><th>Type</th><th>Qty</th><th>Note</th></tr>${k.moves.map(m=>`<tr><td>${esc(new Date(m.at).toLocaleString([], {day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}))}</td><td>${esc(m.name)}</td><td>${m.type==='in'?'Delivery':m.type==='count'?'Stock count':'Waste'}</td><td>${esc(ingQty(m.qty,m.unit))}</td><td class="helper">${esc(m.note)}${m.cost?' · '+money(m.cost)+'/'+esc(m.unit):''}</td></tr>`).join('')}</table></div></div>`:''}`;
 const ing=id=>k.ingredients.find(i=>i.id===id);
 document.querySelectorAll('[data-ing-edit]').forEach(b=>b.onclick=()=>ingForm(ing(b.dataset.ingEdit)));
 document.querySelectorAll('[data-ing-count]').forEach(b=>b.onclick=()=>ingMove(ing(b.dataset.ingCount),'count'));
 document.querySelectorAll('[data-ing-waste]').forEach(b=>b.onclick=()=>ingMove(ing(b.dataset.ingWaste),'waste'));
 document.querySelectorAll('[data-ing-recipe]').forEach(b=>b.onclick=()=>ingRecipe(k.menu.find(m=>m.id===b.dataset.ingRecipe)))}
function ingForm(i){const k=exData.Ingredients.k,id=i?.id||exId();modal(`<h2>${i?'Edit':'Add'} ingredient</h2><form id="ingF"><label>Name</label><input id="igName" maxlength="80" required value="${esc(i?.name||'')}"><div class="business-grid"><div><label>Unit you buy and measure in</label><select id="igUnit">${k.units.map(u=>`<option ${i?.unit===u?'selected':''}>${u}</option>`).join('')}</select></div><div><label>Cost per unit before VAT (AED)</label><input id="igCost" type="number" min="0" step="0.01" value="${i?exAed(i.cost):''}"></div></div><label>Minimum level (for the low-stock warning, optional)</label><input id="igMin" type="number" min="0" step="0.001" value="${i?.minStock||''}">${i?`<label style="display:flex;gap:8px;align-items:center"><input type="checkbox" id="igOn" ${i.active?'checked':''} style="width:auto"> In use</label>`:''}<p id="exError" class="pending-note" role="alert" hidden></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save ingredient</button></div></form>`);
 $('ingF').onsubmit=e=>{e.preventDefault();exPost('recipes/ingredients',{id,name:$('igName').value,unit:$('igUnit').value,cost:cents($('igCost').value||0),minStock:exNum($('igMin').value),active:$('igOn')?$('igOn').checked:true},exReload)}}
function ingMove(i,type){modal(`<h2>${type==='count'?'Stock count':'Record waste'} · ${esc(i.name)}</h2><p class="helper">The system shows ${esc(ingQty(i.stock,i.unit))}.</p><form id="ingM"><label>${type==='count'?'Counted quantity now':'Quantity wasted'} (${esc(i.unit)})</label><input id="imQty" type="number" min="0" step="0.001" required><label>Reason</label><input id="imNote" maxlength="200" required placeholder="${type==='count'?'e.g. Weekly count':'e.g. Expired, spilled, burnt'}"><p id="exError" class="pending-note" role="alert" hidden></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save</button></div></form>`);
 $('ingM').onsubmit=e=>{e.preventDefault();exPost('recipes/moves',{id:exId(),ingredientId:i.id,type,qty:exNum($('imQty').value),note:$('imNote').value},exReload)}}
function ingRecipe(m){const k=exData.Ingredients.k,lines=m.lines.map(l=>({ingredientId:l.ingredientId,qty:l.qty})),active=k.ingredients.filter(i=>i.active),ing=id=>k.ingredients.find(i=>i.id===id);
 const draw=()=>{const cost=lines.reduce((n,l)=>n+Math.round(l.qty*(ing(l.ingredientId)?.cost||0)),0);$('rcLines').innerHTML=(lines.length?`<table><tr><th>Ingredient</th><th>Per portion</th><th>Cost</th><th></th></tr>${lines.map((l,i)=>`<tr><td>${esc(ing(l.ingredientId).name)}</td><td>${esc(ingQty(l.qty,ing(l.ingredientId).unit))}</td><td>${money(Math.round(l.qty*ing(l.ingredientId).cost))}</td><td><button type="button" data-rc-del="${i}" aria-label="Remove">×</button></td></tr>`).join('')}</table>`:'<p class="helper">No ingredients yet.</p>')+`<p>Cost per portion <b>${money(cost)}</b> · price ${money(m.price)} · food cost <b>${m.price?Math.round(cost/m.price*1000)/10:0}%</b></p>`;document.querySelectorAll('[data-rc-del]').forEach(b=>b.onclick=()=>{lines.splice(Number(b.dataset.rcDel),1);draw()})};
 modal(`<h2>Recipe · ${esc(m.name)}</h2><p class="helper">What one portion uses. Small amounts are fine: 0.150 kg, 0.02 l.</p><form id="rcF"><div class="business-grid"><div><label>Ingredient</label><select id="rcIng">${active.map(i=>`<option value="${esc(i.id)}">${esc(i.name)} (${esc(i.unit)})</option>`).join('')}</select></div><div><label>Quantity per portion</label><input id="rcQty" type="number" min="0.001" step="0.001"></div></div><button type="button" id="rcAdd">+ Add to recipe</button><div id="rcLines" class="scroll" style="margin-top:10px"></div><p id="exError" class="pending-note" role="alert" hidden></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save recipe</button></div></form>`);
 $('rcAdd').onclick=()=>{const id=$('rcIng').value,q=Math.round(exNum($('rcQty').value)*1000)/1000;if(!id||!(q>0)){exErr('Choose an ingredient and enter the quantity.');return}if(lines.some(l=>l.ingredientId===id)){exErr('This ingredient is already in the recipe. Remove it to change it.');return}exErr('');lines.push({ingredientId:id,qty:q});$('rcQty').value='';draw()};draw();
 $('rcF').onsubmit=e=>{e.preventDefault();exPost('recipes/recipe',{itemId:m.id,lines},exReload)}}
function ingReceive(){const d=exData.Ingredients,k=d.k,pay=d.pay,lines=[],rate=Number(db.settings.tax)||5,active=k.ingredients.filter(i=>i.active),billId=exId(),payId=exId();
 modal(`<h2>Supplier invoice · ingredients</h2><p class="helper">Adds the stock, updates each ingredient’s cost, and records the bill with VAT in Finance.</p><form id="irF"><div class="business-grid"><div><label>Supplier</label><select id="irSup">${pay.suppliers.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('')}<option value="">+ New supplier…</option></select></div><div><label>Supplier invoice no.</label><input id="irNo" maxlength="60" required></div></div><div id="irNew" class="business-grid" style="display:${pay.suppliers.length?'none':'grid'}"><div><label>New supplier name</label><input id="irName" maxlength="100"></div><div><label>Supplier TRN (if any)</label><input id="irTrn" inputmode="numeric" maxlength="20"></div></div><label>Invoice date</label><input id="irDate" type="date" value="${financeDay()}" max="${financeDay()}" required style="max-width:220px"><h3 style="margin-top:14px">Items</h3><div class="business-grid" style="grid-template-columns:2fr 1fr 1fr"><div><label>Ingredient</label><select id="irIng">${active.map(i=>`<option value="${esc(i.id)}">${esc(i.name)} (${esc(i.unit)})</option>`).join('')}</select></div><div><label>Quantity</label><input id="irQty" type="number" min="0" step="0.001"></div><div><label>Cost / unit (AED)</label><input id="irCost" type="number" min="0" step="0.01"></div></div><button type="button" id="irAdd">+ Add item</button><div id="irLines" class="scroll" style="margin-top:10px"></div><div class="business-grid"><div><label>VAT on the invoice (AED)</label><input id="irVat" type="number" min="0" step="0.01" value="0"><div class="actions" style="margin:6px 0 0"><button type="button" id="irVatAuto">Add ${rate}% VAT</button><button type="button" id="irVatNone">No VAT</button></div></div><div><label>Paid?</label><select id="irPaid"><option value="">Not yet (on credit)</option><option>Cash</option><option>Bank / card</option></select><p class="helper" id="irTotal"></p></div></div><p id="exError" class="pending-note" role="alert" hidden></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary" id="irSave">Save invoice &amp; add stock</button></div></form>`);
 const ing=id=>k.ingredients.find(i=>i.id===id),net=()=>lines.reduce((n,l)=>n+Math.round(l.qty*l.cost),0),vat=()=>cents($('irVat').value||0);
 const draw=()=>{$('irLines').innerHTML=lines.length?`<table><tr><th>Ingredient</th><th>Qty</th><th>Cost / unit</th><th>Amount</th><th></th></tr>${lines.map((l,i)=>`<tr><td>${esc(ing(l.ingredientId).name)}</td><td>${esc(ingQty(l.qty,ing(l.ingredientId).unit))}</td><td>${money(l.cost)}</td><td>${money(Math.round(l.qty*l.cost))}</td><td><button type="button" data-ir-del="${i}" aria-label="Remove">×</button></td></tr>`).join('')}</table>`:'<p class="helper">No items yet.</p>';document.querySelectorAll('[data-ir-del]').forEach(b=>b.onclick=()=>{lines.splice(Number(b.dataset.irDel),1);draw()});$('irTotal').innerHTML=`Before VAT <b>${money(net())}</b> · VAT <b>${money(vat())}</b> · Total <b>${money(net()+vat())}</b>`};
 $('irSup').onchange=()=>{$('irNew').style.display=$('irSup').value===''?'grid':'none'};$('irVat').oninput=draw;$('irVatAuto').onclick=()=>{$('irVat').value=exAed(Math.round(net()*rate/100));draw()};$('irVatNone').onclick=()=>{$('irVat').value='0';draw()};
 const fillCost=()=>{const i=ing($('irIng').value);$('irCost').value=i?.cost?exAed(i.cost):''};$('irIng').onchange=fillCost;fillCost();
 $('irAdd').onclick=()=>{const id=$('irIng').value,q=Math.round(exNum($('irQty').value)*1000)/1000,cost=cents($('irCost').value||0);if(!id||!(q>0)){exErr('Enter the quantity.');return}if(!(cost>0)){exErr('Enter the cost per unit before VAT.');return}if(lines.some(l=>l.ingredientId===id)){exErr('This ingredient is already on the invoice.');return}exErr('');lines.push({ingredientId:id,qty:q,cost});$('irQty').value='';draw()};draw();
 $('irF').onsubmit=async e=>{e.preventDefault();exErr('');if(!lines.length){exErr('Add at least one item.');return}let supplierId=$('irSup').value;$('irSave').disabled=true;
  if(!supplierId){const name=$('irName').value.trim();if(!name){exErr('Enter the supplier name.');$('irSave').disabled=false;return}supplierId=exId();if(!await exPost('finance/suppliers',{id:supplierId,name,trn:$('irTrn').value.trim()})){$('irSave').disabled=false;return}}
  const paid=$('irPaid').value;if(!await exPost('recipes/receive',{billId,supplierId,number:$('irNo').value.trim(),date:$('irDate').value,vat:vat(),lines,...(paid?{paid:{id:payId,method:paid}}:{})},async()=>{toast('Invoice saved · stock updated');await exReload()}))$('irSave').disabled=false}}

// =============================== TILL: REWARDS and CLOCK IN/OUT ===============================
async function exLoadTill(){if(!cloudReady)return;const b=cloudUser.businessId;try{const [rewards,clock]=await Promise.all([cloudUser.waiter?null:api('marketing/rewards'),api('hr/clock-list')]);exTill={rewards,clock,forBusiness:b}}catch{}paintStatus()}
const paintBeforeExtras=paintStatus;
paintStatus=function(){paintBeforeExtras();const node=$('cloudStatus');if(!node||!cloudReady||exTill.forBusiness!==cloudUser?.businessId)return;
 const add=(id,label,fn)=>{if($(id))return;const b=document.createElement('button');b.id=id;b.textContent=label;b.onclick=fn;node.appendChild(b)};
 if(exTill.rewards&&(exTill.rewards.loyalty.enabled||exTill.rewards.coupons>0))add('exRewards','Rewards',exRewards);
 if(exTill.clock.length)add('exClock','Clock in / out',exClock)};
const enterBeforeExtras=enterSalon;
enterSalon=async function(session){exData={};await enterBeforeExtras(session);if(cloudReady)exLoadTill()};
// Where the discount goes: salon checkout and the retail checkouts take it directly; others show the amount to type.
function exBill(){const t=cloudUser.businessType||'salon';
 if(['grocery','petshop','perfume','meat','mobile'].includes(t)&&window.RetailUI?.cartState){const s=RetailUI.cartState();return{customerId:s.customerId||'',sub:s.totals?.sub||0,apply:a=>{RetailUI.setDiscount((s.off||0)+a,s.extra);return true}}}
 if(t==='salon'&&typeof totals==='function'&&typeof cart!=='undefined')return{customerId:typeof customer==='string'?customer:'',sub:totals().sub,apply:a=>{discount=(discount||0)+a;if(tab==='Checkout')render();return true}};
 return{customerId:'',sub:0,apply:()=>false}}
function exRewards(){const bill=exBill(),L=exTill.rewards.loyalty,custs=(db.customers||[]).slice().sort((a,b)=>a.name.localeCompare(b.name));let pts=null;
 modal(`<h2>Rewards</h2>${L.enabled?`<h3>Loyalty points</h3><label>Customer</label><select id="rwCust"><option value="">Choose customer…</option>${custs.map(c=>`<option value="${esc(c.id)}" ${c.id===bill.customerId?'selected':''}>${esc(c.name)}${c.phone?' · '+esc(c.phone):''}</option>`).join('')}</select><p id="rwBal" class="helper"></p><div class="business-grid"><div><label>Points to redeem</label><input id="rwPts" type="number" min="${L.minRedeem}" step="1"></div><div><label>&nbsp;</label><button class="primary" id="rwRedeem" disabled>Redeem points</button></div></div>`:''}${exTill.rewards.coupons?`<h3 style="margin-top:16px">Coupon</h3><div class="business-grid"><div><label>Coupon code</label><input id="rwCode" maxlength="40" style="text-transform:uppercase" autocomplete="off"></div><div><label>Bill amount before VAT (AED)</label><input id="rwSub" type="number" min="0.01" step="0.01" value="${bill.sub?exAed(bill.sub):''}"></div></div><button class="primary" id="rwCoupon">Apply coupon</button>`:''}<p id="exError" class="pending-note" role="alert" hidden></p><div id="rwDone"></div><div class="actions"><button onclick="closeModal()">Close</button></div>`);
 const done=(amount,what)=>{const ok=bill.apply(amount);$('rwDone').innerHTML=`<p class="pending-note" style="background:#dff3e9;color:#155e48;border-color:#a8dcc4"><b>${esc(what)}: ${money(amount)} off.</b> ${ok?'The discount was added to the current bill.':'Enter AED '+exAed(amount)+' as the discount on this bill.'}</p>`;if(ok)toast(money(amount)+' discount added')};
 if(L.enabled){const load=async()=>{pts=null;$('rwRedeem').disabled=true;const id=$('rwCust').value;if(!id){$('rwBal').textContent='Points are earned on bills saved with the customer.';return}try{pts=(await api('marketing/rewards?customerId='+encodeURIComponent(id))).points;$('rwBal').innerHTML=`Balance <b>${pts.balance} points</b> · worth <b>${money(pts.value)}</b>${pts.balance<L.minRedeem?' · needs '+L.minRedeem+' to redeem':''}`;if(pts.balance>=L.minRedeem){const need=bill.sub?Math.ceil(bill.sub/L.redeemFils):pts.balance;$('rwPts').value=Math.min(pts.balance,Math.max(L.minRedeem,need));$('rwPts').max=pts.balance;$('rwRedeem').disabled=false}}catch(e){$('rwBal').textContent=e.status?e.message:'Rewards need the internet.'}};$('rwCust').onchange=load;load();
  $('rwRedeem').onclick=async()=>{exErr('');$('rwRedeem').disabled=true;const r=await exPost('marketing/redeem',{id:exId(),type:'points',customerId:$('rwCust').value,points:Math.round(exNum($('rwPts').value))});if(r){done(r.amount,r.points+' points redeemed');load()}else $('rwRedeem').disabled=false}}
 if($('rwCoupon'))$('rwCoupon').onclick=async()=>{exErr('');const sub=cents($('rwSub').value||0);if(!$('rwCode').value.trim()||!(sub>0)){exErr('Enter the coupon code and the bill amount.');return}$('rwCoupon').disabled=true;const r=await exPost('marketing/redeem',{id:exId(),type:'coupon',code:$('rwCode').value.trim(),subtotal:sub,customerId:$('rwCust')?.value||''});if(r)done(r.amount,'Coupon '+r.code);else $('rwCoupon').disabled=false}}
async function exClock(){let list;try{list=await api('hr/clock-list')}catch(e){alert(e.status?e.message:'Clocking in needs the internet.');return}exTill.clock=list;
 modal(`<h2>Clock in / out</h2><p class="helper">Tap your name, then enter your PIN.</p><div class="grid">${list.map(e=>`<button class="service" data-clock="${esc(e.id)}"><span>${e.in?'Clocked in · tap to clock out':'Not clocked in'}</span><strong>${esc(e.name)}</strong></button>`).join('')}</div><div class="actions"><button onclick="closeModal()">Cancel</button></div>`);
 document.querySelectorAll('[data-clock]').forEach(b=>b.onclick=()=>{const e=list.find(x=>x.id===b.dataset.clock);modal(`<h2>${esc(e.name)}</h2><form id="clkF"><label>PIN</label><input id="clkPin" type="password" inputmode="numeric" maxlength="6" autocomplete="off" required autofocus style="font-size:24px;letter-spacing:8px;text-align:center"><p id="exError" class="pending-note" role="alert" hidden></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">${e.in?'Clock out':'Clock in'}</button></div></form>`);$('clkPin').focus();
  $('clkF').onsubmit=async ev=>{ev.preventDefault();const r=await exPost('hr/clock',{employeeId:e.id,pin:$('clkPin').value});if(r){closeModal();toast(r.name+' clocked '+r.action+' at '+r.time)}else $('clkPin').value=''}})}
