// Grocery & baqala screens for WiFi Palace POS. Active only when the signed-in business type is "grocery".
// Checkout: scan a barcode (USB/Bluetooth scanners type like a keyboard + Enter) or search by name;
// weighed items ask for kilos. Pay by cash, card or customer credit (khata).
// Products: price list with live stock, low-stock filter, CSV import/export. Stock: goods in and counts.
// Credit: customer balances, payments received, statements and WhatsApp reminders.
(function(){
 'use strict';
 const RetailUI=window.RetailUI=window.RetailUI||{screens:{}};RetailUI.ext??={};
 const OWN=['Dashboard','Checkout','Products','Stock','Credit','Pets','Grooming','Boarding','Blends','Clients','Orders','Breakdown'];
 const OWNER_ONLY=['Dashboard','Sales','Settings','Finance','Reports','Team'];
 const GROCERY_CATEGORIES=['Fruits & vegetables','Dairy & eggs','Bakery','Meat & fish','Rice, flour & grains','Cooking & spices','Snacks & sweets','Drinks','Frozen','Household & cleaning','Personal care','Baby','Tobacco','Other'];
 const CREDIT='Credit (account)';
 const PET_CATEGORIES=['Dog food','Cat food','Bird & fish food','Treats','Accessories','Toys','Health & hygiene','Litter & cages','Aquarium','Live animals','Grooming','Boarding & daycare','Other'];
 // The pet shop uses these same screens (products, stock, checkout, credit) plus its own Pets, Grooming and Boarding (petshop.js).
 const isPet=()=>typeof cloudUser!=='undefined'&&cloudUser?.businessType==='petshop';
 const isGrocery=()=>typeof cloudUser!=='undefined'&&['grocery','petshop','perfume','meat'].includes(cloudUser?.businessType);
 const isMeat=()=>typeof cloudUser!=='undefined'&&cloudUser?.businessType==='meat';
 const MEAT_CATEGORIES=['Mutton & goat','Lamb','Beef','Veal','Camel','Chicken','Fish & seafood','Minced & marinated','Offal','Whole animals','Frozen','Bones & fat','Delivery & services','Other'];
 const isPerf=()=>typeof cloudUser!=='undefined'&&cloudUser?.businessType==='perfume';
 const PERFUME_CATEGORIES=['Perfumes (bottles)','Oils & attar','Oud & bakhoor','Bottles & packaging','Gift sets','Burners & accessories','Body & home','Gift wrapping','Other'];
 const X=()=>RetailUI.ext[cloudUser?.businessType]||{}; // per-type add-ons (petshop.js, perfume.js)
 const dec=u=>!!u&&u!=='piece'; // sold in decimals: kg, ml, g, tola
 const per=u=>dec(u)?' / '+u:'';
 const CATS=()=>isPet()?PET_CATEGORIES:isPerf()?PERFUME_CATEGORIES:isMeat()?MEAT_CATEGORIES:GROCERY_CATEGORIES;
 const isSvc=i=>i?.type==='service';
 const K=k=>{try{return localStorage.getItem(k)||''}catch{return ''}};
 const isOwner=()=>cloudUser?.role==='owner';
 const PET_TABS=['Grooming','Boarding','Pets'];
 const tabs=()=>{const pet=isPet()?PET_TABS:isPerf()?['Blends','Clients']:isMeat()?['Orders','Breakdown']:[];return isOwner()?['Dashboard','Checkout',...pet,'Products','Stock','Credit','Customers','Sales','Settings','Finance','Reports','Team','Sync centre','Account']:['Checkout',...pet,'Products','Stock','Credit','Customers','My sales','Sync centre','Account']};
 const localDay=(d=new Date())=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);
 const qtyText=(q,unit)=>unit&&unit!=='piece'?(+q.toFixed(3))+' '+unit:String(+q.toFixed(3));
 const line=i=>Math.round(i.price*i.qty);
 let cart=[],cartCustomer='',scanText='',productSearch='',productFilter='All',stockSearch='',creditSearch='';

 // --- derived data ---------------------------------------------------------------------------------
 function shim(){if(db){db.services??=[];db.appointments??=[];for(const k of ['grocery_items','grocery_stock','grocery_payments','grocery_config','pets','appointments','pet_stays','perfume_blends','perfume_profiles','perfume_points'])db[k]??=[]}}
 // Stock and credit come from the server's totals across every till (cache.summary), plus this device's
 // own changes that have not synced yet. Without a summary (older server) they are computed locally.
 const pendingOps=()=>(typeof cache!=='undefined'&&cache?.pending)||[];
 const summary=()=>(typeof cache!=='undefined'&&cache?.summary)||null;
 // Several branches (perfume): this device sells from one branch; stock shown is that branch's.
 const branches=()=>db.grocery_config.find(c=>c.id==='config')?.branches||[];
 const branch=()=>{const list=branches();if(!list.length)return '';const b=K('wifipos-branch');return list.some(x=>x.id===b)?b:list[0].id};
 const branchName=(id=branch())=>branches().find(b=>b.id===id)?.name||'';
 // Change in stock at branch b from one movement (b='' = all branches).
 const moved=(e,b)=>!b?(e.type==='transfer'?0:e.qty):e.type==='transfer'?(e.toBranch===b?e.qty:e.branch===b?-e.qty:0):(e.branch===b?e.qty:0);
 function stockLevels(b=branch()){const s0=summary(),sum=s0?.stock,byB=s0?.stockByBranch,m=new Map(db.grocery_items.map(i=>[i.id,sum?(b&&byB?(byB[i.id]?.[b]||0):(sum[i.id]||0)):0])),add=(k,v)=>{if(m.has(k))m.set(k,m.get(k)+v)};
  if(sum){for(const o of pendingOps()){if(o.action!=='put'||!o.data)continue;if(o.kind==='grocery_stock'&&o.base===0)add(o.data.itemId,moved(o.data,b&&byB?b:''));if(o.kind==='sales'&&(!b||!byB||o.data.branch===b)){const sign=o.base===0&&o.data.status==='Paid'?-1:o.base>0&&o.data.status==='Refunded'?1:0;if(sign)for(const i of o.data.items)add(i.id,sign*i.qty)}}}
  else{for(const e of db.grocery_stock)add(e.itemId,moved(e,b));for(const s of db.sales)if(s.status==='Paid'&&(!b||s.branch===b))for(const i of s.items)add(i.id,-i.qty)}
  for(const [k,v] of m)m.set(k,Math.round(v*1000)/1000);return m}
 const low=(i,levels)=>!isSvc(i)&&levels.get(i.id)<=(i.minStock||0);
 function balances(){const sum=summary()?.credit,m=new Map(sum?Object.entries(sum):[]),add=(k,v)=>m.set(k,(m.get(k)||0)+v);
  if(sum){for(const o of pendingOps()){if(o.action!=='put'||!o.data)continue;if(o.kind==='grocery_payments'&&o.base===0)add(o.data.customerId,-o.data.amount);if(o.kind==='sales'&&o.data.method===CREDIT){if(o.base===0&&o.data.status==='Paid')add(o.data.customerId,o.data.total);if(o.base>0&&o.data.status==='Refunded')add(o.data.customerId,-o.data.total)}}}
  else{for(const s of db.sales)if(s.method===CREDIT&&s.status==='Paid')add(s.customerId,s.total);for(const p of db.grocery_payments)add(p.customerId,-p.amount)}
  return m}
 const balanceOf=id=>balances().get(id)||0;

 // --- navigation ------------------------------------------------------------------------------------
 function paintNav(){$('nav').innerHTML=tabs().map(t=>`<button class="${tab===t?'active':''}" data-cloud-tab="${esc(t)}">${esc(t)}</button>`).join('');document.querySelectorAll('[data-cloud-tab]').forEach(b=>b.onclick=()=>navigate(b.dataset.cloudTab))}
 const prevRender=render,prevNavigate=navigate;
 render=function(){
  if(!isGrocery()){prevRender();return}
  if(!cloudReady)return;shim();
  if(!tabs().includes(tab))tab=tabs()[0];
  if(OWN.includes(tab)){const t=tab;tab='Customers';prevRender();tab=t;paintNav();document.title=db.settings.name+' | WiFi Palace POS';(SCREENS[t]||RetailUI.screens[t])();return}
  prevRender();paintNav();
 };
 navigate=function(next){
  if(!isGrocery()){prevNavigate(next);return}
  if(!isOwner()&&OWNER_ONLY.includes(next)){alert('Owner access required');return}
  if(OWN.includes(next)){tab=next;render();return}
  shim();prevNavigate(next);paintNav();
 };

 // --- dashboard ---------------------------------------------------------------------------------------
 function dashboard(){
  const today=localDay(),levels=stockLevels(),lows=db.grocery_items.filter(i=>low(i,levels)).sort((a,b)=>levels.get(a.id)-levels.get(b.id)),bal=balances(),owing=db.customers.filter(c=>(bal.get(c.id)||0)>0).sort((a,b)=>bal.get(b.id)-bal.get(a.id)),outstanding=owing.reduce((n,c)=>n+bal.get(c.id),0);
  const collected=TrendCharts.collections(db.sales,db.grocery_payments)(today),bills=db.sales.filter(s=>localDay(new Date(s.date))===today).length;
  $('app').innerHTML=`<div class="hero"><div><div class="eyebrow">${esc(new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase())}</div><h2 style="margin-top:14px">${isPet()?'Happy pets, happy owners.':isMeat()?'Fresh cuts, happy customers.':isPerf()?'Every scent, every client remembered.':'Shelves full, customers happy.'}</h2><p>${esc(db.settings.name)} · today at a glance.</p></div><button onclick="navigate('Checkout')">Open checkout →</button></div>
  <div class="kpis"><div class="kpi"><div class="dot"></div><small>Today’s net collections</small><div class="metric">${money(collected)}</div><span class="helper">Cash + card, incl. account payments</span></div><div class="kpi"><div class="dot" style="background:#e3ba98"></div><small>Bills today</small><div class="metric">${bills}</div><span class="helper">All payment types</span></div><div class="kpi"><div class="dot" style="background:#d98a8a"></div><small>Low stock</small><div class="metric">${lows.length}</div><span class="helper">At or below the alert level</span></div><div class="kpi"><div class="dot" style="background:#95bbb0"></div><small>Credit outstanding</small><div class="metric">${money(outstanding)}</div><span class="helper">${owing.length} customer${owing.length===1?'':'s'}</span></div></div>
  ${X().dashboard?X().dashboard():''}
  ${TrendCharts.section([{id:'grCash',title:'Net collections (AED)',value:TrendCharts.collections(db.sales,db.grocery_payments),money:true},{id:'grBills',title:'Bills',value:TrendCharts.countBy(db.sales,x=>x.date)}],'render')}
  <div class="layout"><section class="panel"><div class="row"><h3>Low stock</h3><button onclick="groceryProducts('Low stock')">View all →</button></div>${lows.length?lows.slice(0,10).map(i=>`<div class="row" style="padding:8px 0;border-bottom:1px solid #eee"><span>${esc(i.name)}</span><span class="${levels.get(i.id)<=0?'danger':'helper'}">${esc(qtyText(levels.get(i.id),i.unit))} left · alert at ${esc(qtyText(i.minStock||0,i.unit))}</span></div>`).join(''):'<div class="empty">Every product is above its alert level.</div>'}</section>
  <aside class="panel"><div class="row"><h3>Top balances</h3><button onclick="navigate('Credit')">Credit →</button></div>${owing.length?owing.slice(0,8).map(c=>`<div class="row" style="padding:8px 0;border-bottom:1px solid #eee"><span>${esc(c.name)}</span><b>${money(bal.get(c.id))}</b></div>`).join(''):'<div class="empty">No customer owes anything.</div>'}</aside></div>`;
  TrendCharts.wire();
 }

 // --- barcode label scale ---------------------------------------------------------------------------------
 // A label scale prints an EAN-13 sticker: prefix (2 or 20-29) + product scale code (PLU) + weight in grams
 // (or price in fils) + check digit. Scanning it adds that product with the weight from the label.
 const SCALE_DEFAULT={prefix:'21',codeDigits:5,value:'weight'};
 const scaleCfg=()=>({...SCALE_DEFAULT,...(db.grocery_config.find(c=>c.id==='config')?.scale||{})});
 const eanOk=c=>{let n=0;for(let i=0;i<12;i++)n+=Number(c[i])*(i%2?3:1);return (10-n%10)%10===Number(c[12])};
 function scaleFormat(c=scaleCfg()){const v=12-c.prefix.length-c.codeDigits;return c.prefix+' '+'C'.repeat(c.codeDigits)+' '+(c.value==='weight'?'W':'P').repeat(v)+' K'}
 // Returns null when the code is not a scale label, otherwise {item, qty} or {error}.
 function parseScale(code,c=scaleCfg()){
  if(!/^\d{13}$/.test(code)||!code.startsWith(c.prefix))return null;
  if(!eanOk(code))return{error:'Label barcode did not read correctly. Scan it again.'};
  const p=c.prefix.length,plu=String(Number(code.slice(p,p+c.codeDigits))),raw=Number(code.slice(p+c.codeDigits,12));
  const item=db.grocery_items.find(i=>i.unit==='kg'&&i.plu===plu);if(!item)return{error:'No product has scale code '+plu+(isOwner()?' · set it on Products → Edit':'')};
  let grams=c.value==='weight'?raw:(item.price>0?Math.round(raw/item.price*1000):0);
  if(!(grams>0&&grams<=1000000))return{error:'The label shows no weight.'};
  return{item,qty:grams/1000,labelPrice:c.value==='price'?raw:null};
 }
 function scaleForm(){const c=scaleCfg();
  modal(`<h2>Barcode label scale</h2><p class="helper">Weigh fruit, vegetables, meat or cheese on the label scale and stick the label on the bag. The cashier scans it and the product and weight are added. Set each weighed product's <b>scale code (PLU)</b> on Products → Edit, and load the same codes into the scale.</p><form id="gScale"><div class="business-grid"><div><label for="gsPrefix">Label prefix</label><input id="gsPrefix" inputmode="numeric" maxlength="2" value="${esc(c.prefix)}" list="gsPrefixes" placeholder="e.g. 21 or 99"><datalist id="gsPrefixes">${['2','20','21','22','23','24','25','26','27','28','29','99'].map(x=>`<option value="${x}">`).join('')}</datalist></div><div><label for="gsDigits">Scale code length</label><select id="gsDigits">${[4,5,6].map(x=>`<option value="${x}" ${c.codeDigits===x?'selected':''}>${x} digits</option>`).join('')}</select></div></div><label for="gsValue">The label carries</label><select id="gsValue"><option value="weight" ${c.value==='weight'?'selected':''}>Weight in grams (recommended)</option><option value="price" ${c.value==='price'?'selected':''}>Price in fils (weight is worked out from the price per kg)</option></select><p class="helper">Format: <b id="gsFmt">${esc(scaleFormat(c))}</b> · C = scale code, ${c.value==='weight'?'W = grams':'P = price in fils'}, K = check digit. Copy this from the scale's barcode setting.</p><label for="gsTest">Test: scan a label here</label><input id="gsTest" autocomplete="off" placeholder="e.g. 9900007001561"><p id="gsTestOut" class="helper"></p><div class="actions"><button type="button" onclick="groceryPluExport()">Download PLU list for the scale</button><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save</button></div></form>`);
  const read=()=>({prefix:$('gsPrefix').value,codeDigits:Number($('gsDigits').value),value:$('gsValue').value});
  const test=()=>{const r=read(),code=$('gsTest').value.replace(/\s+/g,'');$('gsFmt').textContent=scaleFormat(r);if(!code){$('gsTestOut').textContent='';return}const x=parseScale(code,r);$('gsTestOut').innerHTML=!x?'<span class="danger">Not a scale label for this format (13 digits starting with '+esc(r.prefix)+').</span>':x.error?'<span class="danger">'+esc(x.error)+'</span>':'✓ '+esc(x.item.name)+' · '+esc(qtyText(x.qty,'kg'))+' · '+money(Math.round(x.item.price*x.qty))+(x.labelPrice!==null?' (label '+money(x.labelPrice)+')':'')};
  for(const id of ['gsPrefix','gsDigits','gsValue'])$(id).onchange=test;$('gsPrefix').oninput=test;$('gsTest').oninput=test;$('gsTest').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();test()}};
  $('gScale').onsubmit=e=>{e.preventDefault();const v=read();if(!/^\d{1,2}$/.test(v.prefix)){alert('The prefix is the first 1 or 2 digits of every scale label, e.g. 21 or 99');return}if(12-v.prefix.length-v.codeDigits<4){alert('Choose a shorter scale code for this prefix');return}
   if(change(()=>{const k=db.grocery_config.findIndex(x=>x.id==='config'),rec={id:'config',scale:v};if(k>=0)db.grocery_config[k]=rec;else db.grocery_config.push(rec)})){closeModal();toast('Scale settings saved')}};
 }
 function pluExport(){const rows=[['plu','name','price per kg (AED)','category'],...db.grocery_items.filter(i=>i.unit==='kg'&&i.plu).sort((a,b)=>Number(a.plu)-Number(b.plu)).map(i=>[i.plu,i.name,(i.price/100).toFixed(2),i.category])];if(rows.length<2){alert('No weighed products have a scale code yet. Set them on Products → Edit.');return}download('scale-plu-'+localDay()+'.csv','\ufeff'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n'),'text/csv')}

 // --- checkout ------------------------------------------------------------------------------------------
 function find(q){q=q.trim().toLowerCase();if(!q)return [];return db.grocery_items.filter(i=>i.name.toLowerCase().includes(q)||(i.barcode&&i.barcode.toLowerCase().includes(q))||(i.plu&&i.plu===String(Number(q))&&/^\d{1,6}$/.test(q))).slice(0,20)}
 function add(id,q,{price,link,note,cut}={}){const i=db.grocery_items.find(x=>x.id===id);if(!i)return;
  // Meat: choose the cutting option (curry cut, boneless…) first; its charge per kg is added to the price.
  if(X().chooseCut&&i.cuts?.length&&cut===undefined){X().chooseCut(i,c=>add(id,q,{price,link,note,cut:c}));return}
  const cutObj=cut?(i.cuts||[]).find(c=>c.id===cut):null;
  if(dec(i.unit)&&q===undefined){const w=prompt(i.unit==='kg'?'Weight of '+i.name+' in kg (e.g. 1.25):':'Quantity of '+i.name+' in '+i.unit+' (e.g. '+(i.unit==='tola'?'0.5':'6')+'):');if(w===null)return;q=Math.round(Number(w)*1000)/1000;if(!(q>0&&q<=(i.unit==='kg'?1000:100000))){alert('Enter a quantity in '+i.unit);return}}
  q=q??1;const cur=cart.find(x=>x.id===id&&!x.link&&!x.note&&(x.cut||'')===(cut||''));if(cur&&!dec(i.unit)&&!link&&!note)cur.qty=Math.min(1000,cur.qty+q);else cart.push({id:i.id,name:i.name,unit:i.unit,category:i.category,price:price??(i.price+(cutObj?.charge||0)),openPrice:i.openPrice===true,qty:q,...(link?{link}:{}),...(note?{note}:{}),...(cutObj?{cut:cutObj.id,cutName:cutObj.name+(cutObj.charge?' +'+(cutObj.charge/100).toFixed(2)+'/kg':'')}:{})});
  scanText='';checkout(true);
 }
 function scan(){const q=scanText.trim();if(!q)return;const exact=db.grocery_items.filter(i=>i.barcode&&i.barcode===q.replace(/\s+/g,''));if(exact.length===1){add(exact[0].id);return}
  const label=parseScale(q.replace(/\s+/g,''));if(label){scanText='';if(label.error){checkout(true);toast(label.error);beepError();return}add(label.item.id,label.qty);return}
  const found=find(q);if(found.length===1){add(found[0].id);return}if(!found.length){scanText='';checkout(true);toast('Not found: '+q+(isOwner()?' · add it on Products':''));return}checkout(true)}
 function beepError(){try{const a=new (window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.frequency.value=220;o.connect(g);g.connect(a.destination);g.gain.value=0.2;o.start();o.stop(a.currentTime+0.35)}catch{}}
 let cartOff=0,cartExtra={}; // discount from loyalty points (perfume) and what the add-on needs after payment
 function totals(){const sub=cart.reduce((n,i)=>n+line(i),0),off=Math.min(cartOff,sub),tax=Math.round((sub-off)*db.settings.tax/100);return{sub,off,tax,total:sub-off+tax}}
 function checkout(focus=true){
  const t=totals(),results=scanText.trim()?find(scanText):[],quick=db.grocery_items.filter(i=>!i.barcode).sort((a,b)=>(isSvc(b)-isSvc(a))).slice(0,30),levels=stockLevels(),c=db.customers.find(x=>x.id===cartCustomer),bal=c?balanceOf(c.id):0;
  $('app').innerHTML=`<div class="layout"><section><div class="panel"><label for="gScan">Scan barcode or type product name, then Enter</label><input id="gScan" value="${esc(scanText)}" autocomplete="off" placeholder="Scan or search…" style="font-size:20px">
  ${results.length?`<div style="margin-top:10px">${results.map(i=>`<div class="row" style="padding:8px 0;border-bottom:1px solid #eee"><span><b>${esc(i.name)}</b> <span class="helper">${isSvc(i)?'Service':esc(i.barcode||'')+' · '+esc(qtyText(levels.get(i.id)||0,i.unit))+' in stock'}</span></span><span>${money(i.price)}${per(i.unit)} <button class="primary" onclick="groceryAdd('${esc(i.id)}')">Add</button></span></div>`).join('')}</div>`:''}</div>
  ${quick.length?`<div class="panel"><h3>${isPet()?'Services & quick items':'Quick items (no barcode)'}</h3><div class="grid">${quick.map(i=>`<button class="service" onclick="groceryAdd('${esc(i.id)}')"><b>${esc(i.name)}</b><span>${money(i.price)}${per(i.unit)}</span></button>`).join('')}</div></div>`:''}</section>
  <aside class="panel"><div class="row"><h3>Bill${branches().length>1?` <button class="helper" style="font-weight:400;padding:2px 8px" title="Change this device's branch" onclick="perfBranchPick()">${esc(branchName())}</button>`:''}</h3>${cart.length?'<button onclick="groceryClear()">Clear</button>':''}</div>
  ${cart.length?cart.map((i,k)=>`<div class="row" style="padding:8px 0;border-bottom:1px solid #eee;gap:8px"><div style="flex:1"><b>${esc(i.name)}</b>${i.cutName?`<div class="helper">✂ ${esc(i.cutName)}</div>`:''}${i.note?`<div class="helper">${esc(i.note)}</div>`:''}${i.openPrice?`<div class="helper">AED <input aria-label="Price of ${esc(i.name)}" type="number" min="0" step="0.01" value="${(i.price/100).toFixed(2)}" style="width:90px;display:inline-block;margin:0" onchange="groceryPrice(${k},this.value)"></div>`:`<div class="helper">${money(i.price)}${per(i.unit)}</div>`}</div><input aria-label="Quantity of ${esc(i.name)}" type="number" min="${dec(i.unit)?'0.001':'1'}" step="${dec(i.unit)?'0.001':'1'}" value="${i.qty}" style="width:84px" onchange="groceryQty(${k},this.value)"><b style="min-width:86px;text-align:right">${money(line(i))}</b><button aria-label="Remove ${esc(i.name)}" onclick="groceryRemove(${k})">×</button></div>`).join(''):'<div class="empty">Scan the first item.</div>'}
  <div class="row" style="margin-top:10px"><span>Subtotal</span><span>${money(t.sub)}</span></div>${t.off?`<div class="row"><span>${esc(cartExtra.offLabel||'Discount')}</span><span>−${money(t.off)}</span></div>`:''}${t.tax?`<div class="row"><span>VAT ${db.settings.tax}%</span><span>${money(t.tax)}</span></div>`:''}<div class="row total"><b>Total</b><b>${money(t.total)}</b></div>
  <label for="gCustomer">Customer (needed for credit)</label><select id="gCustomer" onchange="groceryCustomer(this.value)"><option value="">Walk-in customer</option>${db.customers.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(x=>`<option value="${esc(x.id)}" ${cartCustomer===x.id?'selected':''}>${esc(x.name)}${x.phone?' · '+esc(x.phone):''}</option>`).join('')}</select>${c?`<p class="helper">Account balance: <b>${money(bal)}</b></p>`:''}${X().checkoutExtra?X().checkoutExtra(c,t):''}
  <div class="actions"><button class="primary" onclick="groceryPay('Cash')" ${cart.length?'':'disabled'}>Cash</button><button onclick="groceryPay('Card (external terminal)')" ${cart.length?'':'disabled'}>Card</button><button onclick="groceryPay('${CREDIT}')" ${cart.length?'':'disabled'}>Credit</button></div></aside></div>`;
  const input=$('gScan');input.oninput=e=>{scanText=e.target.value;if(!scanText.trim())checkout(true)};input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();scanText=input.value;scan()}};
  if(focus){input.focus();input.setSelectionRange(input.value.length,input.value.length)}
 }
 function pay(method){
  if(!cart.length)return;const t=totals(),c=db.customers.find(x=>x.id===cartCustomer);
  if(method===CREDIT&&!c){alert('Choose the customer whose account this goes on.');return}
  const finish=received=>{const card=method==='Card (external terminal)',credit=method===CREDIT;
   const sale={id:uid(),number:'SD-'+new Date().toISOString().replace(/\D/g,'').slice(0,14)+'-'+uid().slice(-3).toUpperCase(),date:new Date().toISOString(),items:cart.map(i=>({id:i.id,name:i.name,category:i.category,unit:i.unit,price:i.price,qty:i.qty,...(i.cut?{options:[{id:i.cut,name:i.cutName}]}:{}),...(i.note?{note:i.note}:{})})),sub:t.sub,off:t.off,...(branch()?{branch:branch()}:{}),tax:t.tax,total:t.total,customer:c?.name||'Walk-in customer',customerId:c?.id||'',staff:cloudUser.name||'Staff',staffId:'',commissionBps:0,method,cashAmount:credit||card?0:t.total,cardAmount:card?t.total:0,cashReceived:credit||card?0:received,received:credit?0:received,change:credit?0:received-t.total,shop:{...db.settings},status:'Paid'};
   const links=cart.filter(i=>i.link).map(i=>i.link),extra=cartExtra;let note='';if(change(()=>{db.sales.push(sale);if(X().onPaid)note=X().onPaid(sale,links,extra)||''})){cart=[];cartOff=0;cartExtra={};cartCustomer='';scanText='';closeModal();render();receipt(sale.id);if(note)toast(note)}};
  if(method==='Cash'){modal(`<h2>Cash · ${money(t.total)}</h2><form id="gCash"><label for="gReceived">Cash received (AED)</label><input id="gReceived" type="number" min="0" step="0.01" value="${(t.total/100).toFixed(2)}"><p id="gChange" class="helper"></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Complete sale</button></div></form>`);
   const show=()=>{const r=cents($('gReceived').value);$('gChange').textContent=Number.isSafeInteger(r)&&r>=t.total?'Change: '+money(r-t.total):'Cash received must cover the total'};$('gReceived').oninput=show;show();$('gReceived').select();
   $('gCash').onsubmit=e=>{e.preventDefault();const r=cents($('gReceived').value);if(!Number.isSafeInteger(r)||r<t.total){alert('Cash received must cover the total.');return}finish(r)};return}
  if(method===CREDIT){const bal=balanceOf(c.id);if(confirm(`Put ${money(t.total)} on ${c.name}'s account?\nBalance now ${money(bal)} → after this sale ${money(bal+t.total)}.`))finish(0);return}
  if(confirm('Confirm '+money(t.total)+' was approved on your card terminal?'))finish(t.total);
 }

 // --- products ------------------------------------------------------------------------------------------
 function products(){
  const levels=stockLevels(),q=productSearch.trim().toLowerCase(),list=db.grocery_items.filter(i=>(productFilter==='All'||(productFilter==='Low stock'?low(i,levels):i.category===productFilter))&&(!q||(i.name+' '+(i.barcode||'')+' '+(i.plu?'plu'+i.plu:'')).toLowerCase().includes(q)||(i.plu&&i.plu===q))).sort((a,b)=>a.name.localeCompare(b.name));
  const cats=[...new Set(db.grocery_items.map(i=>i.category))];
  $('app').innerHTML=`<div class="panel"><div class="row"><h2>Products</h2><div class="actions" style="margin:0">${isOwner()?`<button class="primary" onclick="groceryItemForm()">+ Add product</button>${isPet()||isPerf()||isMeat()?'<button onclick="groceryServiceForm()">+ Add service</button>':''}<button onclick="groceryImport()">Import CSV</button><button onclick="groceryScale()">Label scale</button>`:''}${X().productButtons?X().productButtons():''}<button onclick="groceryExport()">Export CSV</button></div></div>
  <div class="actions" style="justify-content:flex-start">${['All','Low stock',...cats].map(f=>`<button class="${productFilter===f?'primary':''}" onclick="groceryProducts('${esc(f)}')">${esc(f)}${f==='Low stock'?' ('+db.grocery_items.filter(i=>low(i,levels)).length+')':''}</button>`).join('')}</div>
  <label for="gpSearch" style="display:block;margin-top:14px">Search name or barcode</label><input id="gpSearch" value="${esc(productSearch)}" oninput="groceryProductSearch(this.value)">
  <div class="scroll"><table><tr><th>Product</th><th>Barcode</th><th>Price</th>${isOwner()?'<th>Cost</th>':''}<th>${branches().length>1?'Stock · '+esc(branchName()):'In stock'}</th><th></th></tr>${list.map(i=>{const s=levels.get(i.id);return `<tr><td><b>${esc(i.name)}</b><div class="helper">${esc(i.category)}</div></td><td>${esc(i.barcode||(i.plu?'':'—'))}${i.plu?`<div class="helper">Scale ${esc(i.plu)}</div>`:''}</td><td>${money(i.price)}${per(i.unit)}</td>${isOwner()?`<td>${i.cost?money(i.cost):'—'}</td>`:''}<td class="${s<=0?'danger':low(i,levels)?'':''}">${isSvc(i)?'<span class="helper">Service</span>':esc(qtyText(s,i.unit))+(branches().length>1?`<div class="helper">${branches().filter(b=>b.id!==branch()).map(b=>esc(b.name)+': '+esc(qtyText(stockLevels(b.id).get(i.id)||0,i.unit))).join(' · ')}</div>`:'')}${low(i,levels)?' <span class="badge" style="background:#f6e1e1;color:#8a1f1f">Low</span>':''}</td><td>${isSvc(i)?'':`<button onclick="groceryStockIn('${esc(i.id)}')">Stock in</button>`}${isOwner()?` <button onclick="groceryItemForm('${esc(i.id)}')">Edit</button>`:''}</td></tr>`}).join('')}</table></div>${list.length?'':'<div class="empty">No products here.</div>'}</div>`;
 }
 function itemForm(id){
  if(isSvc(db.grocery_items.find(x=>x.id===id))){serviceForm(id);return}
  const i=db.grocery_items.find(x=>x.id===id)||{name:'',barcode:'',category:isPet()?'Accessories':'Other',unit:'piece',price:0,cost:0,minStock:0};
  modal(`<h2>${id?'Edit product':'Add product'}</h2><form id="gItem"><label for="giName">Name</label><input id="giName" value="${esc(i.name)}" maxlength="100" required><label for="giCode">Barcode (scan it into this box)</label><input id="giCode" value="${esc(i.barcode||'')}" maxlength="40" autocomplete="off"><div class="business-grid"><div><label for="giCat">Category</label><select id="giCat">${CATS().map(c=>`<option ${i.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select></div><div><label for="giUnit">Sold by</label><select id="giUnit" ${id?'disabled':''}>${(isPerf()?[['piece','Piece'],['ml','Millilitre (ml)'],['g','Gram (g)'],['tola','Tola (11.66 g)']]:[['piece','Piece'],['kg','Weight (kg)']]).map(([u,l])=>`<option value="${u}" ${i.unit===u?'selected':''}>${l}</option>`).join('')}</select></div></div><div class="business-grid"><div><label for="giPrice">Selling price before VAT (AED)</label><input id="giPrice" type="number" min="0" step="0.01" value="${(i.price/100).toFixed(2)}" required></div><div><label for="giCost">Cost price (AED, optional)</label><input id="giCost" type="number" min="0" step="0.01" value="${((i.cost||0)/100).toFixed(2)}"></div></div><div id="giPluBox" style="${i.unit==='kg'?'':'display:none'}"><label for="giPlu">Scale code (PLU) · for barcode label scales</label><input id="giPlu" inputmode="numeric" maxlength="6" value="${esc(i.plu||'')}" placeholder="e.g. 12"></div>${X().itemFields?X().itemFields(i):''}<label for="giMin">Low-stock alert at</label><input id="giMin" type="number" min="0" step="${dec(i.unit)?'0.1':'1'}" value="${i.minStock||0}"><div class="actions">${id?`<button type="button" class="danger" onclick="groceryItemDelete('${esc(id)}')">Delete</button>`:''}<button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save product</button></div></form>`);
  $('giCode').onkeydown=e=>{if(e.key==='Enter')e.preventDefault()};$('giUnit').onchange=e=>{$('giPluBox').style.display=e.target.value==='kg'?'':'none'};
  $('gItem').onsubmit=e=>{e.preventDefault();const v={id:id||uid(),name:$('giName').value.trim(),barcode:$('giCode').value.replace(/\s+/g,''),category:$('giCat').value,unit:$('giUnit').value,price:cents($('giPrice').value),cost:cents($('giCost').value||'0'),minStock:Number($('giMin').value||0)};const xi=X().readItem?X().readItem(i):{};if(xi===false)return;Object.assign(v,xi);const pluRaw=$('giPlu').value.trim();if(v.unit==='kg'&&pluRaw){if(!/^\d{1,6}$/.test(pluRaw)){alert('Scale code must be 1 to 6 digits');return}v.plu=String(Number(pluRaw));const same=db.grocery_items.find(x=>x.plu===v.plu&&x.id!==v.id);if(same){alert('Scale code '+v.plu+' is already used by '+same.name);return}}
   if(!v.name||!Number.isSafeInteger(v.price)||v.price<0||!Number.isSafeInteger(v.cost)||v.cost<0||!(v.minStock>=0)){alert('Check the name, prices and alert level');return}
   const dupe=v.barcode&&db.grocery_items.find(x=>x.barcode===v.barcode&&x.id!==v.id);if(dupe){alert('Barcode already used by '+dupe.name);return}
   if(change(()=>{const k=db.grocery_items.findIndex(x=>x.id===v.id);if(k>=0)db.grocery_items[k]=v;else db.grocery_items.push(v)})){closeModal();toast('Product saved')}};
 }
 function serviceForm(id){
  const i=db.grocery_items.find(x=>x.id===id)||(isMeat()?{name:'',category:'Delivery & services',serviceType:'delivery',price:0,duration:60,openPrice:true}:isPerf()?{name:'',category:'Gift wrapping',serviceType:'wrapping',price:0,duration:10,openPrice:true}:{name:'',category:'Grooming',serviceType:'grooming',price:0,duration:60,openPrice:false});
  modal(`<h2>${id?'Edit service':'Add service'}</h2><form id="gSvc"><label for="gvName">Name</label><input id="gvName" value="${esc(i.name)}" maxlength="100" required placeholder="e.g. Full grooming (large dog)"><div class="business-grid"><div><label for="gvType">Type</label><select id="gvType">${(isPerf()?[['wrapping','Gift wrapping'],['other','Other service']]:isMeat()?[['delivery','Delivery charge'],['other','Other service']]:[['grooming','Grooming'],['boarding','Boarding (price per night)'],['daycare','Daycare (price per day)'],['other','Other service']]).map(([v,l])=>`<option value="${v}" ${i.serviceType===v?'selected':''}>${l}</option>`).join('')}</select></div><div><label for="gvPrice">Price before VAT (AED)</label><input id="gvPrice" type="number" min="0" step="0.01" value="${(i.price/100).toFixed(2)}" required></div></div><label for="gvDur">Usual time (minutes, for grooming bookings)</label><input id="gvDur" type="number" min="5" max="1440" value="${i.duration||60}"><label style="display:flex;gap:10px;align-items:center"><input id="gvOpen" type="checkbox" style="width:auto;margin:0" ${i.openPrice?'checked':''}> Price can change at checkout (e.g. by size or coat)</label><div class="actions">${id?`<button type="button" class="danger" onclick="groceryItemDelete('${esc(id)}')">Delete</button>`:''}<button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save service</button></div></form>`);
  $('gSvc').onsubmit=e=>{e.preventDefault();const type=$('gvType').value,v={id:id||uid(),type:'service',serviceType:type,name:$('gvName').value.trim(),barcode:'',category:type==='grooming'?'Grooming':type==='wrapping'?'Gift wrapping':isMeat()?'Delivery & services':type==='other'?'Other':'Boarding & daycare',unit:'piece',price:cents($('gvPrice').value),cost:0,minStock:0,duration:Math.round(Number($('gvDur').value)||60),openPrice:$('gvOpen').checked};if(!v.name||!Number.isSafeInteger(v.price)||v.price<0||!(v.duration>=5&&v.duration<=1440)){alert('Check the name, price and minutes');return}
   if(change(()=>{const k=db.grocery_items.findIndex(x=>x.id===v.id);if(k>=0)db.grocery_items[k]=v;else db.grocery_items.push(v)})){closeModal();toast('Service saved')}};
 }
 // CSV import: columns name, barcode, category, unit (piece/kg), price, cost, stock, min stock. Existing barcodes are updated.
 function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const ch=text[i];if(q){if(ch==='"'&&text[i+1]==='"'){cell+='"';i++}else if(ch==='"')q=false;else cell+=ch}else if(ch==='"')q=true;else if(ch===','||ch===';'||ch==='\t'){row.push(cell);cell=''}else if(ch==='\n'||ch==='\r'){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=''}else cell+=ch}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows}
 function importCSV(){
  modal(`<h2>Import products</h2><p>Use a CSV file. In Excel: <b>File → Save As → CSV (UTF-8)</b>. First row must be headers:</p><pre class="receipt">name, barcode, category, unit, price, cost, stock, min stock, plu</pre><p class="helper">${isPerf()?'unit = piece, ml, g or tola':'unit = piece or kg'} · prices in AED before VAT · stock = opening quantity (optional) · plu = scale code for kg products (optional). Rows with a barcode already in your list update that product's name and prices. Unknown categories go to "Other".</p><button onclick="groceryTemplate()">Download template</button><label for="gFile">CSV file</label><input id="gFile" type="file" accept=".csv,text/csv,.txt"><p id="gImportInfo" class="helper"></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary" id="gImportGo" disabled>Import</button></div>`);
  let plan=null;
  $('gFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;const rows=parseCSV((await f.text()).replace(/^﻿/,''));if(rows.length<2){$('gImportInfo').textContent='No rows found.';return}
   const head=rows[0].map(h=>h.trim().toLowerCase().replace(/[^a-z]/g,'')),col=n=>head.indexOf(n),get=(r,n)=>(col(n)>=0?r[col(n)]:'').trim(),errors=[],items=[],stock=[],byCode=new Map(db.grocery_items.filter(i=>i.barcode).map(i=>[i.barcode,i])),seen=new Set();
   if(col('name')<0||col('price')<0){$('gImportInfo').textContent='The first row must include at least "name" and "price" columns.';return}
   rows.slice(1).forEach((r,k)=>{const n=k+2,name=get(r,'name'),code=get(r,'barcode').replace(/\s+/g,''),unit=isPerf()?({ml:'ml',g:'g',gram:'g',grams:'g',gm:'g',tola:'tola'}[get(r,'unit').toLowerCase()]||'piece'):/^kg|kilo|weight/i.test(get(r,'unit'))?'kg':'piece',price=cents(get(r,'price')),cost=get(r,'cost')?cents(get(r,'cost')):0,open=Number(get(r,'stock')||0),min=Number(get(r,'minstock')||get(r,'min')||0),catRaw=get(r,'category'),pluRaw=get(r,'plu')||get(r,'scalecode'),category=CATS().find(c=>c.toLowerCase()===catRaw.toLowerCase())||'Other';
    if(!name){errors.push('Row '+n+': no name');return}if(!Number.isSafeInteger(price)||price<0){errors.push('Row '+n+': bad price');return}if(!Number.isSafeInteger(cost)||cost<0){errors.push('Row '+n+': bad cost');return}if(code&&!/^[A-Za-z0-9-]{3,40}$/.test(code)){errors.push('Row '+n+': bad barcode');return}if(code&&seen.has(code)){errors.push('Row '+n+': barcode repeated in file');return}if(pluRaw&&(!/^\d{1,6}$/.test(pluRaw)||unit!=='kg')){errors.push('Row '+n+': scale code needs a kg product and 1-6 digits');return}if(pluRaw&&seen.has('plu'+Number(pluRaw))){errors.push('Row '+n+': scale code repeated in file');return}if(pluRaw)seen.add('plu'+Number(pluRaw));if(code)seen.add(code);
    const old=code&&byCode.get(code);if(old&&old.unit!==unit){errors.push('Row '+n+': '+old.name+' is sold by '+old.unit);return}
    const v={id:old?.id||uid(),name,barcode:code,category:old&&!catRaw?old.category:category,unit,price,cost,minStock:min>=0?min:0};if(pluRaw)v.plu=String(Number(pluRaw));else if(old?.plu&&col('plu')<0)v.plu=old.plu;const clash=v.plu&&db.grocery_items.find(x=>x.plu===v.plu&&x.id!==v.id&&!items.some(y=>y.id===x.id));if(clash){errors.push('Row '+n+': scale code '+v.plu+' is used by '+clash.name);return}items.push(v);
    const q=dec(unit)?Math.round(open*1000)/1000:Math.round(open);if(q>0&&!old)stock.push({id:uid(),type:'in',...(branch()?{branch:branch()}:{}),itemId:v.id,qty:q,cost,supplier:'',invoice:'',note:'Opening stock (import)',at:new Date().toISOString()})});
   plan={items,stock};$('gImportInfo').innerHTML=`${items.length} products ready (${items.filter(i=>db.grocery_items.some(x=>x.id===i.id)).length} updates), ${stock.length} opening stock entries.${errors.length?'<br><span class="danger">'+errors.length+' rows skipped: '+esc(errors.slice(0,5).join('; '))+(errors.length>5?'…':'')+'</span>':''}${items.length>200?'<br>Large lists upload in the background; keep this device online until “0 pending”.':''}`;$('gImportGo').disabled=!items.length};
  $('gImportGo').onclick=()=>{if(!plan)return;if(change(()=>{for(const v of plan.items){const k=db.grocery_items.findIndex(x=>x.id===v.id);if(k>=0)db.grocery_items[k]=v;else db.grocery_items.push(v)}db.grocery_stock.push(...plan.stock)})){closeModal();toast(plan.items.length+' products imported')}};
 }
 const csvCell=v=>'"'+String(v??'').replace(/^[\s]*[=+@-]/,"'$&").replace(/"/g,'""')+'"';
 function exportCSV(){const levels=stockLevels();const rows=[['name','barcode','category','unit','price','cost','stock','min stock','plu'],...db.grocery_items.filter(i=>!isSvc(i)).map(i=>[i.name,i.barcode||'',i.category,i.unit,(i.price/100).toFixed(2),((i.cost||0)/100).toFixed(2),levels.get(i.id),i.minStock||0,i.plu||''])];download('products-'+localDay()+'.csv','﻿'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n'),'text/csv')}
 function template(){if(isPerf()){download('products-template.csv','\ufeffname,barcode,category,unit,price,cost,stock,min stock,plu\r\nOud Royal 100ml,6291003000017,Perfumes (bottles),piece,350.00,200.00,12,3,\r\nTaifi Rose oil,,Oils & attar,ml,15.00,8.00,250,20,\r\nDehn al Oud,,Oils & attar,tola,250.00,150.00,10,2,\r\n','text/csv');return}download('products-template.csv','﻿name,barcode,category,unit,price,cost,stock,min stock,plu\r\nMilk 1L,6291003000017,Dairy & eggs,piece,6.50,5.00,48,10,\r\nTomatoes,,Fruits & vegetables,kg,4.50,3.00,20,5,12\r\n','text/csv')}

 // --- stock -------------------------------------------------------------------------------------------------
 function stock(){
  const levels=stockLevels(),q=stockSearch.trim().toLowerCase(),recent=db.grocery_stock.slice().sort((a,b)=>b.at.localeCompare(a.at)).filter(e=>!q||e.item.toLowerCase().includes(q)).slice(0,60);
  $('app').innerHTML=`<div class="layout"><section class="panel"><div class="row"><h2>Stock${branches().length>1?' · '+esc(branchName()):''}</h2><div class="actions" style="margin:0"><button class="primary" onclick="groceryStockIn()">+ Goods in</button>${isOwner()?'<button onclick="groceryCount()">Stock count</button>':''}${X().stockButtons?X().stockButtons():''}</div></div><label for="gsSearch">Filter by product</label><input id="gsSearch" value="${esc(stockSearch)}" oninput="groceryStockSearch(this.value)">
  <div class="scroll"><table><tr><th>When</th><th>Product</th><th>Type</th><th>Qty</th><th>Details</th></tr>${recent.map(e=>`<tr><td>${esc(new Date(e.at).toLocaleString([], {day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}))}</td><td>${esc(e.item)}</td><td>${e.type==='in'?'Goods in':e.type==='transfer'?'Transfer → '+esc(branchName(e.toBranch)):e.type==='assemble'?'Gift set assembly':'Count adjustment'}${branches().length>1&&e.branch?`<div class="helper">${esc(branchName(e.branch))}</div>`:''}</td><td>${e.qty>0?'+':''}${esc(qtyText(e.qty,e.unit))}</td><td class="helper">${esc([e.supplier,e.invoice&&'Inv '+e.invoice,e.cost?money(e.cost)+'/unit':'',e.reason,e.note].filter(Boolean).join(' · '))}</td></tr>`).join('')}</table></div>${recent.length?'':'<div class="empty">No stock movements yet. Record goods in when a delivery arrives.</div>'}</section>
  <aside class="panel"><h3>How stock works</h3><p class="helper">Stock = goods in + count adjustments − items sold. Sales never block on stock; negative stock means a delivery was not recorded or the count is off.</p><p class="helper">${db.grocery_items.filter(i=>!isSvc(i)&&levels.get(i.id)<0).length} products show negative stock.</p><button onclick="groceryProducts('Low stock')">Low-stock list →</button></aside></div>`;
 }
 function pick(selected=''){return `<label for="gsItem">Product</label><select id="gsItem">${db.grocery_items.filter(i=>!isSvc(i)).slice().sort((a,b)=>a.name.localeCompare(b.name)).map(i=>`<option value="${esc(i.id)}" ${i.id===selected?'selected':''}>${esc(i.name)}${i.barcode?' · '+esc(i.barcode):''}</option>`).join('')}</select>`}
 function stockIn(id=''){
  modal(`<h2>Goods in</h2><form id="gIn">${pick(id)}<div class="business-grid"><div><label for="gsQty">Quantity received</label><input id="gsQty" type="number" min="0" step="0.001" required></div><div><label for="gsCost">Cost per unit (AED, optional)</label><input id="gsCost" type="number" min="0" step="0.01"></div></div><div class="business-grid"><div><label for="gsSupplier">Supplier</label><input id="gsSupplier" maxlength="100"></div><div><label for="gsInv">Supplier invoice no.</label><input id="gsInv" maxlength="60"></div></div><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Add to stock</button></div></form>`);
  $('gIn').onsubmit=e=>{e.preventDefault();const item=db.grocery_items.find(x=>x.id===$('gsItem').value),q=Number($('gsQty').value),qty=dec(item?.unit)?Math.round(q*1000)/1000:Math.round(q);if(!item||!(qty>0)){alert('Enter the quantity received in '+(dec(item?.unit)?item.unit:'pieces'));return}
   const cost=$('gsCost').value?cents($('gsCost').value):0;if(!Number.isSafeInteger(cost)||cost<0){alert('Check the cost');return}
   if(change(()=>db.grocery_stock.push({id:uid(),type:'in',itemId:item.id,item:item.name,unit:item.unit,qty,cost,...(branch()?{branch:branch()}:{}),supplier:$('gsSupplier').value.trim(),invoice:$('gsInv').value.trim(),note:'',at:new Date().toISOString()}))){closeModal();toast('+'+qtyText(qty,item.unit)+' '+item.name)}};
 }
 function count(){
  const levels=stockLevels();
  modal(`<h2>Stock count</h2><p class="helper">Enter what is physically on the shelf. The difference is recorded as an adjustment with your reason.</p><form id="gCount">${pick()}<p id="gcNow" class="helper"></p><label for="gcQty">Counted quantity</label><input id="gcQty" type="number" min="0" step="0.001" required><label for="gcReason">Reason</label><input id="gcReason" maxlength="200" required placeholder="e.g. Monthly count, expired, damaged"><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save count</button></div></form>`);
  const show=()=>{const i=db.grocery_items.find(x=>x.id===$('gsItem').value);$('gcNow').textContent=i?'System shows '+qtyText(levels.get(i.id),i.unit):''};$('gsItem').onchange=show;show();
  $('gCount').onsubmit=e=>{e.preventDefault();const item=db.grocery_items.find(x=>x.id===$('gsItem').value),n=Number($('gcQty').value),reason=$('gcReason').value.trim();if(!item||!(n>=0)||!reason)return;const diff=Math.round((n-levels.get(item.id))*1000)/1000,qty=dec(item.unit)?diff:Math.round(diff);if(!qty){closeModal();toast('Count matches · no change');return}
   if(change(()=>db.grocery_stock.push({id:uid(),type:'adjust',itemId:item.id,item:item.name,unit:item.unit,qty,reason,...(branch()?{branch:branch()}:{}),note:'',at:new Date().toISOString()}))){closeModal();toast(item.name+': '+(qty>0?'+':'')+qtyText(qty,item.unit))}};
 }

 // --- credit (khata) ------------------------------------------------------------------------------------------------
 function credit(){
  const bal=balances(),q=creditSearch.trim().toLowerCase(),has=new Set([...db.sales.filter(s=>s.method===CREDIT).map(s=>s.customerId),...db.grocery_payments.map(p=>p.customerId),...bal.keys()]),list=db.customers.filter(c=>has.has(c.id)&&(!q||(c.name+' '+c.phone).toLowerCase().includes(q))).sort((a,b)=>(bal.get(b.id)||0)-(bal.get(a.id)||0)),total=[...bal.values()].filter(v=>v>0).reduce((n,v)=>n+v,0);
  $('app').innerHTML=`<div class="panel"><div class="row"><div><h2>Customer credit</h2><p class="helper">Total outstanding <b>${money(total)}</b>. Sell on credit from Checkout by choosing the customer and pressing Credit.</p></div><button onclick="groceryNewAccount()">+ New customer</button></div><label for="gcSearch">Search name or mobile</label><input id="gcSearch" value="${esc(creditSearch)}" oninput="groceryCreditSearch(this.value)">
  ${list.length?list.map(c=>{const b=bal.get(c.id)||0;return `<div class="row" style="padding:12px 0;border-bottom:1px solid #eee;flex-wrap:wrap;gap:10px"><div style="min-width:200px"><b>${esc(c.name)}</b><div class="helper">${esc(c.phone||'No mobile')}</div></div><b class="${b>0?'danger':''}">${b>0?money(b)+' due':b<0?money(-b)+' in credit':'Settled'}</b><div class="actions" style="margin:0">${b>0?`<button class="primary" onclick="groceryPayment('${esc(c.id)}')">Receive payment</button>`:''}<button onclick="groceryStatement('${esc(c.id)}')">Statement</button>${b>0&&c.phone?`<button onclick="groceryRemind('${esc(c.id)}')">WhatsApp</button>`:''}</div></div>`}).join(''):'<div class="empty">No customer accounts yet.</div>'}</div>`;
 }
 function payment(id){
  const c=db.customers.find(x=>x.id===id);if(!c)return;const b=balanceOf(id);
  modal(`<h2>Receive payment · ${esc(c.name)}</h2><p>Balance due <b>${money(b)}</b></p><form id="gPayIn"><label for="gpAmt">Amount received (AED)</label><input id="gpAmt" type="number" min="0.01" step="0.01" value="${(b/100).toFixed(2)}" required><label for="gpMethod">Paid by</label><select id="gpMethod"><option>Cash</option><option value="Card (external terminal)">Card</option></select><label for="gpNote">Note (optional)</label><input id="gpNote" maxlength="200"><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save payment</button></div></form>`);
  $('gpAmt').select();
  $('gPayIn').onsubmit=e=>{e.preventDefault();const amount=cents($('gpAmt').value),method=$('gpMethod').value;if(!Number.isSafeInteger(amount)||amount<=0){alert('Enter the amount received');return}if(amount>b&&!confirm('This is more than the balance due. Keep the extra as credit in the customer’s favour?'))return;if(method!=='Cash'&&!confirm('Confirm '+money(amount)+' was approved on your card terminal?'))return;
   const p={id:uid(),customerId:c.id,customer:c.name,amount,method,note:$('gpNote').value.trim(),at:new Date().toISOString()};
   if(change(()=>db.grocery_payments.push(p))){closeModal();paymentReceipt(p.id,b)}};
 }
 function paymentReceipt(id,before){const p=db.grocery_payments.find(x=>x.id===id);if(!p)return;const s=db.settings,l='--------------------------------';
  modal(`<h2>Payment received</h2><pre class="receipt" id="receiptText">${esc(`${s.name}\n${s.phone||''}${s.trn?'\nTRN: '+s.trn:''}\n${l}\nACCOUNT PAYMENT RECEIPT\n${new Date(p.at).toLocaleString()}\n${l}\nCustomer: ${p.customer}\nReceived: ${money(p.amount)} (${p.method==='Cash'?'Cash':'Card'})${p.note?'\nNote: '+p.note:''}\n${l}\nBalance before: ${money(before)}\nBalance now: ${money(before-p.amount)}\n\nThank you!`)}</pre><div class="actions"><button onclick="closeModal()">Close</button><button class="primary" onclick="printReceipt()">Print</button></div>`)}
 function statement(id){
  const c=db.customers.find(x=>x.id===id);if(!c)return;
  const rows=[...db.sales.filter(s=>s.customerId===id&&s.method===CREDIT).flatMap(s=>[{at:s.date,text:'Bill '+s.number,amount:s.total},...(s.status==='Refunded'?[{at:s.refundDate,text:'Refund '+(s.creditNote||s.number),amount:-s.total}]:[])]),...db.grocery_payments.filter(p=>p.customerId===id).map(p=>({at:p.at,text:'Payment · '+(p.method==='Cash'?'cash':'card'),amount:-p.amount}))].sort((a,b)=>a.at.localeCompare(b.at));
  const total=balanceOf(id),visible=rows.reduce((n,r)=>n+r.amount,0),forward=total-visible;let run=forward;const lines=[...(forward?[{at:rows[0]?.at||new Date().toISOString(),text:'Balance brought forward',amount:forward,run:forward}]:[]),...rows.map(r=>{run+=r.amount;return{...r,run}})];const s=db.settings,l='--------------------------------';
  const text=`${s.name}\n${s.phone||''}\n${l}\nACCOUNT STATEMENT\n${c.name}${c.phone?'\n'+c.phone:''}\n${new Date().toLocaleDateString()}\n${l}\n${lines.map(r=>`${new Date(r.at).toLocaleDateString()} ${r.text}\n  ${r.amount>0?'+':''}${money(r.amount)}   bal ${money(r.run)}`).join('\n')||'No activity'}\n${l}\nBALANCE DUE: ${money(run)}`;
  modal(`<h2>Statement · ${esc(c.name)}</h2><pre class="receipt" id="receiptText">${esc(text)}</pre><div class="actions"><button onclick="closeModal()">Close</button><button class="primary" onclick="printReceipt()">Print / Save PDF</button></div>`);
 }
 function remind(id){const c=db.customers.find(x=>x.id===id);if(!c)return;const b=balanceOf(id);try{window.open(SalonWhatsApp.link(SalonWhatsApp.phone(c.phone),`Hello ${c.name}, this is a friendly reminder from ${db.settings.name}. Your account balance is ${money(b)}. You can pay at the shop any time. Thank you!`),'_blank','noopener')}catch(e){alert(e.message)}}
 function newAccount(){modal(`<h2>New customer</h2><form id="gAcc"><label for="gaName">Name</label><input id="gaName" maxlength="100" required><label for="gaPhone">Mobile (for WhatsApp reminders)</label><input id="gaPhone" type="tel" maxlength="40" placeholder="050 123 4567"><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Add</button></div></form>`);
  $('gAcc').onsubmit=e=>{e.preventDefault();const v={id:uid(),name:$('gaName').value.trim(),phone:$('gaPhone').value.trim(),dob:''};if(!v.name)return;if(change(()=>db.customers.push(v))){closeModal();cartCustomer=v.id;toast('Customer added · selected at checkout')}}}

 const SCREENS={'Dashboard':dashboard,'Checkout':()=>checkout(true),'Products':products,'Stock':stock,'Credit':credit};
 Object.assign(window,{
  groceryAdd:id=>add(id),groceryRemove:k=>{cart.splice(k,1);checkout(true)},groceryClear:()=>{if(confirm('Clear this bill?')){cart=[];cartCustomer='';cartOff=0;cartExtra={};checkout(true)}},
  groceryQty:(k,v)=>{const i=cart[k];if(!i)return;const n=dec(i.unit)?Math.round(Number(v)*1000)/1000:Math.round(Number(v)),max=dec(i.unit)&&i.unit!=='kg'?100000:1000;if(n>0&&n<=max)i.qty=n;else alert('Enter a quantity from '+(dec(i.unit)?'0.001 '+i.unit:'1')+' to '+max);setTimeout(()=>checkout(true))},
  groceryCustomer:id=>{cartCustomer=id;cartOff=0;cartExtra={};checkout(true)},groceryPay:pay,groceryServiceForm:serviceForm,
  groceryPrice:(k,v)=>{const i=cart[k];if(!i)return;const c=cents(v);if(Number.isSafeInteger(c)&&c>=0&&c<=10000000)i.price=c;else alert('Enter a price in AED');setTimeout(()=>checkout(true))},
  groceryProducts:f=>{productFilter=f;tab='Products';render()},
  groceryProductSearch:v=>{productSearch=v;products();const el=$('gpSearch');el.focus();el.setSelectionRange(v.length,v.length)},
  groceryScale:scaleForm,groceryPluExport:pluExport,groceryItemForm:itemForm,groceryImport:importCSV,groceryExport:exportCSV,groceryTemplate:template,
  groceryItemDelete:id=>{if(!confirm('Delete this product? Past bills keep their lines.'))return;if(change(()=>{db.grocery_items=db.grocery_items.filter(x=>x.id!==id)})){closeModal();toast('Product deleted')}},
  groceryStockIn:stockIn,groceryCount:count,groceryStockSearch:v=>{stockSearch=v;stock();const el=$('gsSearch');el.focus();el.setSelectionRange(v.length,v.length)},
  groceryPayment:payment,groceryStatement:statement,groceryRemind:remind,groceryNewAccount:newAccount,
  groceryCreditSearch:v=>{creditSearch=v;credit();const el=$('gcSearch');el.focus();el.setSelectionRange(v.length,v.length)}
 });
 // Used by petshop.js: put a grooming or boarding charge on the bill for that pet's owner and open checkout.
 Object.assign(RetailUI,{isPet,isPerf,isMeat,add:(id,q,o)=>add(id,q,o),isSvc,dec,stockLevels,qtyText,localDay,branches,branch,branchName,balanceOf,
  cartState:()=>({customerId:cartCustomer,off:cartOff,extra:cartExtra,totals:totals(),lines:cart}),setDiscount:(off,extra)=>{cartOff=Math.max(0,Math.round(off||0));cartExtra=extra||{};checkout(true)},refresh:()=>checkout(true),
  bill:({lines,customerId})=>{for(const l of lines)add(l.id,l.qty,{price:l.price,link:l.link,note:l.note,cut:l.cut??(X().chooseCut?'':undefined)});if(customerId)cartCustomer=customerId;tab='Checkout';render()},
  billed:link=>cart.some(i=>i.link&&i.link.kind===link.kind&&i.link.id===link.id)});
})();
