// Mobile phone shop screens for Palace POS (business type "mobile"). Checkout, products, stock, credit and
// branches come from grocery.js / perfume.js; this file adds IMEI tracking (receive phones, choose the IMEI at
// checkout, look up a phone and its warranty), Repairs (job cards) and buying used phones / trade-in.
(function(){
 'use strict';
 const R=window.RetailUI;if(!R)return;
 R.ext??={};const EXT=R.ext.mobile={};
 const FLOW={Received:['Diagnosing','Waiting for parts','Repairing','Ready','Cancelled'],Diagnosing:['Waiting for parts','Repairing','Ready','Cancelled'],'Waiting for parts':['Repairing','Ready','Cancelled'],Repairing:['Waiting for parts','Ready','Cancelled'],Ready:['Delivered','Repairing','Cancelled'],Delivered:[],Cancelled:[]};
 const ID_TYPES=['Emirates ID','Passport','Driving licence'];
 let repairView='Open',imeiSearch='';
 const isOwner=()=>cloudUser?.role==='owner';
 const item=id=>db.grocery_items.find(i=>i.id===id);
 const serialItems=()=>db.grocery_items.filter(i=>i.serial&&!R.isSvc(i)).sort((a,b)=>a.name.localeCompare(b.name));
 const inStock=id=>db.mobile_units.filter(u=>u.status==='in'&&(!id||u.itemId===id));
 const clean=v=>String(v||'').trim().toUpperCase().replace(/[\s-]/g,'');
 const okImei=v=>/^[A-Z0-9]{8,20}$/.test(v);
 const custOptions=(sel='')=>`<option value="">Choose customer…</option>`+db.customers.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(c=>`<option value="${esc(c.id)}" ${c.id===sel?'selected':''}>${esc(c.name)}${c.phone?' · '+esc(c.phone):''}</option>`).join('');
 const when=d=>new Date(d).toLocaleString([], {day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
 const badge=(s)=>`<span class="badge" style="${s==='Ready'?'background:#dff3e9;color:#155e48':s==='Delivered'?'background:#eceaf3;color:#555':s==='Cancelled'?'background:#fde8e6;color:#8a1c14':s==='Waiting for parts'?'background:#fdf0d8;color:#7a5200':''}">${esc(s)}</span>`;
 const warrantyState=u=>!u.warrantyUntil?'No warranty':u.warrantyUntil>=R.localDay()?'In warranty until '+u.warrantyUntil:'Warranty ended '+u.warrantyUntil;

 // --- checkout: choose which phone (IMEI) is being sold ---------------------------------------------------------------
 EXT.chooseUnit=(i,done)=>{const onBill=new Set((R.cartState().lines||[]).map(l=>l.cut)),units=inStock(i.id).filter(u=>!onBill.has(u.id)).sort((a,b)=>a.at.localeCompare(b.at));
  if(!units.length){alert('No '+i.name+' in stock with an IMEI. Receive it first: Stock → Receive phones.');return}
  modal(`<h2>${esc(i.name)}</h2><label for="muScan">Scan or type the IMEI</label><input id="muScan" autocomplete="off" inputmode="numeric" placeholder="IMEI + Enter"><p class="helper">…or tap the phone below (${units.length} in stock).</p><div class="scroll" style="max-height:45vh">${units.map(u=>`<button class="service" style="width:100%;text-align:left;margin:4px 0" data-unit="${esc(u.id)}"><strong>${esc(u.imei)}</strong><span>${esc([u.condition,u.source==='used'?'Used':'',R.branches().length>1?R.branchName(u.branch):'',u.price?money(u.price):''].filter(Boolean).join(' · '))}</span></button>`).join('')}</div><div class="actions"><button onclick="closeModal()">Cancel</button></div>`);
  const pick=u=>{closeModal();done({id:u.id,name:'IMEI '+u.imei,...(i.openPrice&&u.price?{price:u.price}:{})})};
  document.querySelectorAll('[data-unit]').forEach(b=>b.onclick=()=>pick(units.find(u=>u.id===b.dataset.unit)));
  $('muScan').focus();$('muScan').onkeydown=e=>{if(e.key!=='Enter')return;e.preventDefault();const code=clean($('muScan').value),u=units.find(x=>x.imei===code)||units.filter(x=>x.imei.endsWith(code)&&code.length>=4)[0];if(u)pick(u);else alert('IMEI '+code+' is not in stock for '+i.name)}};
 // After payment: mark the phones sold and attach the bill to its repair.
 EXT.onPaid=(sale,links)=>{let msg='';
  for(const l of sale.items)for(const o of l.options||[]){const u=db.mobile_units.find(x=>x.id===(o.id||o));if(u&&u.status==='in'){u.status='sold';u.saleId=sale.id;u.soldAt=sale.date;u.customer=sale.customer||''}}
  for(const l of links)if(l.kind==='mobile_repairs'){const r=db.mobile_repairs.find(x=>x.id===l.id);if(r&&!r.saleId){r.saleId=sale.id;if(r.status==='Ready'){r.status='Delivered';msg='Repair #'+r.number+' billed and handed over'}else msg='Repair #'+r.number+' billed · mark it Ready, then Delivered'}}
  return msg};
 // The receipt printed before the bill syncs shows the warranty too (the server prints the same on the tax invoice).
 const until=m=>{if(!m)return '';const d=new Date(Date.now()+4*3600000);d.setUTCMonth(d.getUTCMonth()+m);return d.toISOString().slice(0,10)};
 EXT.saleLine=(l,i)=>{const w=until(item(i.id)?.warrantyMonths);if(!w)return;if(l.options?.length)l.options[0]={...l.options[0],name:l.options[0].name+' · Warranty until '+w};else l.options=[{id:'warranty',name:'Warranty until '+w}]};
 EXT.checkoutExtra=c=>{if(!c)return '';const bal=R.balanceOf(c.id);return bal<0?`<p class="helper" style="background:#dff3e9;color:#155e48;padding:8px 10px;border-radius:8px">Trade-in / advance on account: <b>${money(-bal)}</b>. Press <b>Credit</b> to use it; the rest shows as owed on the account.</p>`:''};

 // --- product form: IMEI tracking, warranty, negotiable price ---------------------------------------------------------------
 EXT.itemFields=i=>`<div class="business-grid"><div><label for="mbWar">Warranty (months, 0 = none)</label><input id="mbWar" type="number" min="0" max="60" step="1" value="${i.warrantyMonths||0}"></div><div><label style="display:flex;gap:8px;align-items:center;margin-top:26px"><input type="checkbox" id="mbSerial" ${i.serial?'checked':''} style="width:auto"> Track each one by IMEI / serial</label><label style="display:flex;gap:8px;align-items:center"><input type="checkbox" id="mbOpen" ${i.openPrice?'checked':''} style="width:auto"> Price can change at checkout</label></div></div>`;
 EXT.readItem=()=>({...($('mbSerial')?.checked&&$('giUnit').value==='piece'?{serial:true}:{}),...(Number($('mbWar')?.value)>0?{warrantyMonths:Math.min(60,Math.round(Number($('mbWar').value)))}:{}),...($('mbOpen')?.checked?{openPrice:true}:{})});
 EXT.services={types:[['repair','Repair labour'],['recharge','Recharge / top-up'],['sim','SIM & plans'],['other','Other service']],category:t=>t==='repair'?'Repair services':t==='other'?'Other':'SIM & recharge',blank:{name:'',category:'Repair services',serviceType:'repair',price:0,duration:60,openPrice:true}};
 EXT.productButtons=()=>`${R.branches().length>1?`<button onclick="perfBranchPick()">Branch: ${esc(R.branchName())}</button>`:''}${isOwner()?'<button onclick="perfBranches()">Branches</button>':''}`;
 EXT.stockButtons=()=>`<button class="primary" onclick="mobReceive()">Receive phones (IMEI)</button><button onclick="mobBuy()">Buy used phone</button>${R.branches().length>1?`<button onclick="perfTransfer()">Transfer</button><button onclick="perfBranchPick()">Branch: ${esc(R.branchName())}</button>`:''}`;
 EXT.dashboard=()=>{const open=db.mobile_repairs.filter(r=>!['Delivered','Cancelled'].includes(r.status)),ready=open.filter(r=>r.status==='Ready'),late=open.filter(r=>r.due&&r.due<R.localDay()&&r.status!=='Ready'),phones=inStock();
  return `<div class="layout"><section class="panel"><div class="row"><h3>Repairs</h3><button onclick="navigate('Repairs')">Repairs →</button></div><div class="grid">${[['Open',open.length],['Ready for collection',ready.length],['Past due date',late.length]].map(([l,v])=>`<div class="panel" style="margin:0">${l}<div class="metric">${v}</div></div>`).join('')}</div></section><aside class="panel"><div class="row"><h3>Phones in stock</h3><button onclick="navigate('IMEI')">IMEI →</button></div><div class="metric">${phones.length}</div><p class="helper">${phones.filter(u=>u.source==='used').length} used · cost ${money(phones.reduce((n,u)=>n+(u.cost||0),0))}</p></aside></div>`};

 // --- receive new phones with their IMEIs ---------------------------------------------------------------
 function receive(){const items=serialItems();if(!items.length){alert('Mark a product “Track each one by IMEI” first (Products → Edit).');return}
  modal(`<h2>Receive phones</h2><form id="mRec"><label for="mrItem">Product</label><select id="mrItem">${items.map(i=>`<option value="${esc(i.id)}">${esc(i.name)}</option>`).join('')}</select><label for="mrImei">IMEI / serial numbers (one per line: scan each box)</label><textarea id="mrImei" rows="6" autocomplete="off" required placeholder="356789012345671&#10;356789012345689"></textarea><p class="helper" id="mrCount">0 phones</p><div class="business-grid"><div><label for="mrCost">Cost per phone (AED, before VAT)</label><input id="mrCost" type="number" min="0" step="0.01"></div><div><label for="mrSup">Supplier</label><input id="mrSup" maxlength="100"></div></div><label for="mrInv">Supplier invoice no.</label><input id="mrInv" maxlength="60"><p class="helper">To claim the VAT, also record the supplier’s bill in Finance → Purchases &amp; suppliers.</p><p id="mrErr" class="pending-note" role="alert" hidden></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Add to stock</button></div></form>`);
  const list=()=>[...new Set($('mrImei').value.split(/[\n,;]+/).map(clean).filter(Boolean))];$('mrImei').oninput=()=>{$('mrCount').textContent=list().length+' phone'+(list().length===1?'':'s')};
  $('mRec').onsubmit=e=>{e.preventDefault();const it=item($('mrItem').value),codes=list(),err=m=>{$('mrErr').textContent=m;$('mrErr').hidden=!m},cost=$('mrCost').value?cents($('mrCost').value):0;
   const bad=codes.filter(c=>!okImei(c));if(!codes.length||bad.length){err(bad.length?'Not a valid IMEI / serial (8–20 letters or digits): '+bad.slice(0,3).join(', '):'Scan at least one IMEI.');return}
   const dup=codes.filter(c=>db.mobile_units.some(u=>u.imei===c&&u.status==='in'));if(dup.length){err('Already in stock: '+dup.slice(0,3).join(', '));return}if(codes.length>200){err('Up to 200 phones at a time.');return}
   const at=new Date().toISOString(),b=R.branch();
   if(change(()=>{db.grocery_stock.push({id:uid(),type:'in',itemId:it.id,item:it.name,unit:it.unit,qty:codes.length,cost,...(b?{branch:b}:{}),supplier:$('mrSup').value.trim(),invoice:$('mrInv').value.trim(),note:'',at});for(const c of codes)db.mobile_units.push({id:uid(),itemId:it.id,item:it.name,imei:c,status:'in',cost,source:'purchase',...(b?{branch:b}:{}),at});if(cost&&isOwner())it.cost=cost})){closeModal();toast('+'+codes.length+' '+it.name)}}}

 // --- buy a used phone from a customer (cash, bank or trade-in credit) ---------------------------------------------------------------
 function buy(){const items=serialItems(),used=items.find(i=>i.category==='Used phones')||items[0];if(!used){alert('Add a product tracked by IMEI first, e.g. “Used phone”.');return}
  modal(`<h2>Buy a used phone</h2><form id="mBuy"><div class="business-grid"><div><label for="mbItem">Sell it as</label><select id="mbItem">${items.map(i=>`<option value="${esc(i.id)}" ${i.id===used.id?'selected':''}>${esc(i.name)}</option>`).join('')}</select></div><div><label for="mbImei">IMEI / serial</label><input id="mbImei" required autocomplete="off"></div></div><label for="mbCond">Model &amp; condition</label><input id="mbCond" maxlength="100" required placeholder="e.g. iPhone 13 128GB blue · good · battery 86%"><div class="business-grid"><div><label for="mbPrice">Price paid to the seller (AED)</label><input id="mbPrice" type="number" min="0.01" step="0.01" required></div><div><label for="mbAsk">Your selling price (AED, optional)</label><input id="mbAsk" type="number" min="0" step="0.01"></div></div>
   <h3 style="margin-top:14px">Seller</h3><div class="business-grid"><div><label for="mbSeller">Full name</label><input id="mbSeller" maxlength="100" required></div><div><label for="mbPhone">Phone</label><input id="mbPhone" maxlength="40" required></div></div><div class="business-grid"><div><label for="mbIdType">ID type</label><select id="mbIdType">${ID_TYPES.map(t=>`<option>${t}</option>`).join('')}</select></div><div><label for="mbIdNo">ID number</label><input id="mbIdNo" maxlength="40" required></div></div>
   <label for="mbMethod">How is the seller paid?</label><select id="mbMethod"><option>Cash</option><option>Bank / card</option><option value="Trade-in">Trade-in: credit on their customer account</option></select><div id="mbCustBox" style="display:none"><label for="mbCust">Customer account to credit</label><select id="mbCust">${custOptions()}</select><p class="helper">Add the customer on Customers first. The credit is used when their bill is paid by <b>Credit</b>.</p></div>
   <p class="helper">Check the ID against the person and keep a copy as your trade licence requires. Check the IMEI is not blocked or reported stolen before paying.</p><p id="mbErr" class="pending-note" role="alert" hidden></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save purchase</button></div></form>`);
  $('mbMethod').onchange=()=>{$('mbCustBox').style.display=$('mbMethod').value==='Trade-in'?'':'none'};
  $('mBuy').onsubmit=e=>{e.preventDefault();const err=m=>{$('mbErr').textContent=m;$('mbErr').hidden=!m},it=item($('mbItem').value),code=clean($('mbImei').value),price=cents($('mbPrice').value),ask=$('mbAsk').value?cents($('mbAsk').value):0,method=$('mbMethod').value,cust=$('mbCust').value;
   if(!okImei(code)){err('Enter a valid IMEI / serial (8–20 letters or digits).');return}if(db.mobile_units.some(u=>u.imei===code&&u.status==='in')){err('This IMEI is already in stock.');return}if(!(price>0)){err('Enter the price paid.');return}if(method==='Trade-in'&&!cust){err('Choose the customer account for the trade-in.');return}
   const at=new Date().toISOString(),b=R.branch(),buyId=uid(),rec={id:buyId,seller:$('mbSeller').value.trim(),phone:$('mbPhone').value.trim(),idType:$('mbIdType').value,idNumber:$('mbIdNo').value.trim(),itemId:it.id,item:it.name,imei:code,condition:$('mbCond').value.trim(),price,method,...(method==='Trade-in'?{customerId:cust}:{}),at};
   if(change(()=>{db.mobile_buys.push(rec);db.mobile_units.push({id:uid(),itemId:it.id,item:it.name,imei:code,status:'in',cost:price,source:'used',buyId,condition:rec.condition,...(ask?{price:ask}:{}),...(b?{branch:b}:{}),at});db.grocery_stock.push({id:uid(),type:'in',itemId:it.id,item:it.name,unit:it.unit,qty:1,cost:price,...(b?{branch:b}:{}),supplier:rec.seller.slice(0,100),invoice:'',note:'',at});
    if(method==='Trade-in'){const c=db.customers.find(x=>x.id===cust);db.grocery_payments.push({id:uid(),customerId:cust,customer:c?.name||'',amount:price,method:'Trade-in',note:'Trade-in '+code,at})}})){buyReceipt(rec)}}}
 function buyReceipt(b){const l='--------------------------------';modal(`<h2>Purchase receipt</h2><pre class="receipt" id="receiptText">${esc(`${db.settings.name}\n${db.settings.address||''}\n${db.settings.phone||''}\n${l}\nUSED DEVICE PURCHASE${b.number?' No. '+b.number:''}\n${new Date(b.at).toLocaleString()}\n${l}\nDevice: ${b.condition||b.item}\nIMEI: ${b.imei}\n${l}\nSeller: ${b.seller}\nPhone: ${b.phone}\n${b.idType}: ${b.idNumber}\n${l}\nPaid: ${money(b.price)}\nBy: ${b.method==='Trade-in'?'Credit on customer account':b.method}\n${l}\nI confirm I own this device, it is not\nstolen, blocked or under finance, and I\nhave removed my accounts and data.\n\nSeller signature: ______________\n\nShop: ______________`)}</pre><div class="actions"><button onclick="closeModal()">Close</button><button class="primary" onclick="printReceipt()">Print / Save PDF</button></div>`)}

 // --- IMEI: look up a phone, its bill and warranty; phones in stock; used purchases ---------------------------------------------------------------
 function imeiScreen(){const q=clean(imeiSearch),hits=q.length>=4?db.mobile_units.filter(u=>u.imei.includes(q)).sort((a,b)=>b.at.localeCompare(a.at)).slice(0,30):[],stock=inStock(),byItem=new Map();for(const u of stock){const k=u.itemId;byItem.set(k,[...(byItem.get(k)||[]),u])}
  const row=u=>{const sale=u.saleId?db.sales.find(s=>s.id===u.saleId):null;return `<div class="row" style="padding:10px 0;border-bottom:1px solid #eee;flex-wrap:wrap;gap:8px"><div style="min-width:220px"><b>${esc(u.imei)}</b> · ${esc(u.item)}<div class="helper">${esc([u.condition,u.source==='used'?'Bought used':'',R.branches().length>1&&u.status==='in'?R.branchName(u.branch):'',isOwner()&&u.cost?'cost '+money(u.cost):''].filter(Boolean).join(' · '))}</div></div><div>${u.status==='in'?'<span class="badge" style="background:#dff3e9;color:#155e48">In stock</span>':u.status==='sold'?`<span class="badge">Sold</span> <span class="helper">${esc(u.soldAt?u.soldAt.slice(0,10):'')}${u.customer?' · '+esc(u.customer):''}</span><div class="helper"><b>${esc(warrantyState(u))}</b></div>`:`<span class="badge" style="background:#fde8e6;color:#8a1c14">Removed</span> <span class="helper">${esc(u.reason||'')}</span>`}</div><span class="actions" style="margin:0">${sale?`<button onclick="receipt('${esc(sale.id)}')">Bill ${esc(sale.number||'')}</button>`:''}${u.status==='in'&&R.branches().length>1?`<button data-mu-move="${esc(u.id)}">Move branch</button>`:''}${isOwner()&&u.status==='in'?`<button data-mu-remove="${esc(u.id)}">Remove</button>`:''}${isOwner()&&u.status==='sold'&&sale?.status==='Refunded'?`<button class="primary" data-mu-back="${esc(u.id)}">Back to stock</button>`:''}</span></div>`};
  $('app').innerHTML=`<div class="panel"><div class="row"><h2>IMEI lookup</h2><div class="actions" style="margin:0"><button class="primary" onclick="mobReceive()">Receive phones</button><button onclick="mobBuy()">Buy used phone</button></div></div><label for="miSearch">Scan or type an IMEI (or its last digits)</label><input id="miSearch" value="${esc(imeiSearch)}" autocomplete="off" placeholder="e.g. 356789012345671">${q.length>=4?(hits.length?hits.map(row).join(''):'<div class="empty">No phone with this IMEI was received or sold here.</div>'):'<p class="helper">Find a phone to see whether it is in stock, who bought it, its bill and whether it is still under warranty.</p>'}</div>
  <div class="panel"><h3>Phones in stock · ${stock.length}</h3>${stock.length?[...byItem].sort((a,b)=>(item(a[0])?.name||'').localeCompare(item(b[0])?.name||'')).map(([id,us])=>`<details><summary><b>${esc(item(id)?.name||us[0].item)}</b> · ${us.length}</summary>${us.sort((a,b)=>a.at.localeCompare(b.at)).map(row).join('')}</details>`).join(''):'<div class="empty">No phones with an IMEI in stock. Use “Receive phones”.</div>'}</div>
  ${db.mobile_buys.length?`<div class="panel"><h3>Used phones bought</h3><div class="scroll"><table><tr><th>When</th><th>Device</th><th>IMEI</th><th>Seller</th><th>Paid</th><th></th></tr>${db.mobile_buys.slice().sort((a,b)=>b.at.localeCompare(a.at)).slice(0,40).map(b=>`<tr><td>${esc(when(b.at))}</td><td>${esc(b.condition||b.item)}</td><td>${esc(b.imei)}</td><td>${esc(b.seller)}<div class="helper">${esc(b.phone)}${isOwner()?' · '+esc(b.idType)+' '+esc(b.idNumber):''}</div></td><td>${money(b.price)}<div class="helper">${esc(b.method)}</div></td><td><button data-mb-print="${esc(b.id)}">Receipt</button></td></tr>`).join('')}</table></div></div>`:''}`;
  const el=$('miSearch');el.oninput=()=>{imeiSearch=el.value;imeiScreen();const n=$('miSearch');n.focus();n.setSelectionRange(n.value.length,n.value.length)};
  document.querySelectorAll('[data-mb-print]').forEach(b=>b.onclick=()=>buyReceipt(db.mobile_buys.find(x=>x.id===b.dataset.mbPrint)));
  document.querySelectorAll('[data-mu-back]').forEach(b=>b.onclick=()=>{if(change(()=>{const u=db.mobile_units.find(x=>x.id===b.dataset.muBack);u.status='in';for(const k of ['saleId','soldAt','customer','warrantyUntil'])delete u[k]}))toast('Back in stock')});
  document.querySelectorAll('[data-mu-remove]').forEach(b=>b.onclick=()=>{const u=db.mobile_units.find(x=>x.id===b.dataset.muRemove),why=prompt('Why is '+u.imei+' leaving stock? (returned to supplier, lost, damaged…)');if(!why?.trim())return;const at=new Date().toISOString();
   if(change(()=>{u.status='removed';u.reason=why.trim();db.grocery_stock.push({id:uid(),type:'adjust',itemId:u.itemId,item:u.item,unit:'piece',qty:-1,reason:'IMEI '+u.imei+': '+why.trim(),...(u.branch?{branch:u.branch}:{}),note:'',at})}))toast('Removed from stock')});
  document.querySelectorAll('[data-mu-move]').forEach(b=>b.onclick=()=>{const u=db.mobile_units.find(x=>x.id===b.dataset.muMove),others=R.branches().filter(x=>x.id!==u.branch);modal(`<h2>Move ${esc(u.imei)}</h2><p class="helper">From ${esc(R.branchName(u.branch))} to:</p>${others.map(o=>`<button style="display:block;width:100%;margin:6px 0" data-to="${esc(o.id)}">${esc(o.name)}</button>`).join('')}<div class="actions"><button onclick="closeModal()">Cancel</button></div>`);
   document.querySelectorAll('[data-to]').forEach(t=>t.onclick=()=>{const to=t.dataset.to,from=u.branch,at=new Date().toISOString();if(change(()=>{db.grocery_stock.push({id:uid(),type:'transfer',itemId:u.itemId,item:u.item,unit:'piece',qty:1,branch:from,toBranch:to,reason:'IMEI '+u.imei,note:'',at});u.branch=to})){closeModal();toast('Moved to '+R.branchName(to))}})});
 }

 // --- repairs ---------------------------------------------------------------
 function repairs(){const today=R.localDay(),list=db.mobile_repairs.filter(r=>repairView==='Open'?!['Delivered','Cancelled','Ready'].includes(r.status):repairView==='Ready'?r.status==='Ready':['Delivered','Cancelled'].includes(r.status)).sort((a,b)=>repairView==='Closed'?b.created.localeCompare(a.created):(a.due||'9999').localeCompare(b.due||'9999')||a.created.localeCompare(b.created)),n=f=>db.mobile_repairs.filter(f).length;
  $('app').innerHTML=`<div class="panel"><div class="row"><h2>Repairs</h2><div class="actions" style="margin:0">${[['Open',n(r=>!['Delivered','Cancelled','Ready'].includes(r.status))],['Ready',n(r=>r.status==='Ready')],['Closed','']].map(([v,c])=>`<button class="${repairView===v?'primary':''}" onclick="mobRepairs('${v}')">${v}${c!==''?' ('+c+')':''}</button>`).join('')}<button class="primary" onclick="mobRepairNew()">+ New repair</button></div></div>
  ${list.map(r=>`<div class="row" style="padding:10px 0;border-bottom:1px solid #eee;flex-wrap:wrap;gap:10px"><div style="min-width:240px;flex:1"><b>#${r.number} · ${esc(r.device)}</b> ${badge(r.status)}<div class="helper">${esc(r.customer)}${r.phone?' · '+esc(r.phone):''} · ${esc(r.fault)}</div><div class="helper">${r.due?`<span${r.due<today&&!['Ready','Delivered','Cancelled'].includes(r.status)?' style="color:#b42318;font-weight:700"':''}>Due ${esc(r.due)}</span> · `:''}${r.technician?esc(r.technician)+' · ':''}Estimate ${money(r.estimate||0)}</div></div><button onclick="mobRepairOpen('${esc(r.id)}')">Open</button></div>`).join('')||'<div class="empty">No repairs here.</div>'}</div>`}
 function repairNew(){const techs=db.staff.map(s=>s.name);
  modal(`<h2>New repair</h2><form id="mRep"><label for="rpCust">Customer</label><select id="rpCust">${custOptions()}<option value="+">+ New customer…</option></select><div id="rpNew" class="business-grid" style="display:none"><div><label for="rpName">Name</label><input id="rpName" maxlength="100"></div><div><label for="rpPhone">Phone</label><input id="rpPhone" maxlength="40"></div></div><div class="business-grid"><div><label for="rpDevice">Device</label><input id="rpDevice" maxlength="100" required placeholder="e.g. iPhone 13 Pro, blue"></div><div><label for="rpImei">IMEI / serial (optional)</label><input id="rpImei" autocomplete="off"></div></div><label for="rpFault">Problem reported</label><input id="rpFault" maxlength="300" required placeholder="e.g. Broken screen, not charging"><label for="rpAcc">Left with the device</label><input id="rpAcc" maxlength="200" placeholder="e.g. Case, SIM tray (no SIM), charger"><div class="business-grid"><div><label for="rpEst">Estimate (AED)</label><input id="rpEst" type="number" min="0" step="0.01" value="0"></div><div><label for="rpDue">Ready by</label><input id="rpDue" type="date" min="${R.localDay()}" value="${R.localDay()}"></div></div><label for="rpTech">Technician</label><input id="rpTech" maxlength="100" list="rpTechs"><datalist id="rpTechs">${techs.map(t=>`<option value="${esc(t)}">`).join('')}</datalist><label for="rpNote">Note</label><input id="rpNote" maxlength="200"><p id="rpErr" class="pending-note" role="alert" hidden></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save &amp; print job card</button></div></form>`);
  $('rpCust').onchange=()=>{$('rpNew').style.display=$('rpCust').value==='+'?'grid':'none'};
  $('mRep').onsubmit=e=>{e.preventDefault();const err=m=>{$('rpErr').textContent=m;$('rpErr').hidden=!m};let cid=$('rpCust').value;const code=clean($('rpImei').value);
   if(!cid){err('Choose the customer, or add a new one.');return}if(cid==='+'&&!$('rpName').value.trim()){err('Enter the customer name.');return}if(code&&!okImei(code)){err('Check the IMEI / serial.');return}
   const id=uid(),now=new Date().toISOString();let c=db.customers.find(x=>x.id===cid);
   if(change(()=>{if(cid==='+'){c={id:uid(),name:$('rpName').value.trim(),phone:$('rpPhone').value.trim(),dob:''};db.customers.push(c);cid=c.id}
    db.mobile_repairs.push({id,number:0,customerId:cid,customer:c.name,phone:c.phone||'',device:$('rpDevice').value.trim(),imei:code,fault:$('rpFault').value.trim(),accessories:$('rpAcc').value.trim(),estimate:cents($('rpEst').value||0),due:$('rpDue').value,technician:$('rpTech').value.trim(),diagnosis:'',note:$('rpNote').value.trim(),status:'Received',saleId:'',noCharge:false,created:now,history:[{status:'Received',at:now}]})})){repairView='Open';render();jobCard(id)}}}
 function jobCard(id){const r=db.mobile_repairs.find(x=>x.id===id);if(!r)return;const l='--------------------------------';
  modal(`<h2>Job card</h2>${r.number?'':'<p class="pending-note">The job number is issued when this device syncs. Reprint the card after syncing to show it.</p>'}<pre class="receipt" id="receiptText">${esc(`${db.settings.name}\n${db.settings.address||''}\n${db.settings.phone||''}\n${l}\nREPAIR JOB CARD${r.number?' No. '+r.number:''}\n${new Date(r.created).toLocaleString()}\n${l}\nCustomer: ${r.customer}\nPhone: ${r.phone||'-'}\n${l}\nDevice: ${r.device}${r.imei?'\nIMEI: '+r.imei:''}\nProblem: ${r.fault}${r.accessories?'\nLeft with us: '+r.accessories:''}\n${l}\nEstimate: ${money(r.estimate||0)} + VAT\n${r.due?'Ready by: '+r.due+'\n':''}${r.technician?'Technician: '+r.technician+'\n':''}${l}\nBring this card to collect your device.\nBack up your data: we are not responsible\nfor data loss. The estimate may change\nafter diagnosis; we will call you first.\nDevices not collected within 30 days of\nbeing ready may incur storage charges.\n\nCustomer signature: ______________`)}</pre><div class="actions"><button onclick="closeModal()">Close</button><button class="primary" onclick="printReceipt()">Print / Save PDF</button></div>`)}
 function repairOpen(id){const r=db.mobile_repairs.find(x=>x.id===id);if(!r)return;const closed=['Delivered','Cancelled'].includes(r.status),sale=r.saleId?db.sales.find(s=>s.id===r.saleId):null,next=FLOW[r.status].filter(s=>s!=='Cancelled'&&s!=='Delivered');
  modal(`<h2>#${r.number||'…'} · ${esc(r.device)}</h2><p>${badge(r.status)} ${esc(r.customer)}${r.phone?' · '+esc(r.phone):''}</p><p class="helper">${esc(r.fault)}${r.imei?' · IMEI '+esc(r.imei):''}${r.accessories?' · left: '+esc(r.accessories):''}</p>
  ${closed?`<p>${r.diagnosis?'Work done: '+esc(r.diagnosis)+'<br>':''}${r.cancelReason?'Cancelled: '+esc(r.cancelReason)+'<br>':''}${sale?'Bill '+esc(sale.number||'')+' · '+money(sale.total):r.noCharge?'No charge':''}</p>`:`<form id="mRe"><label for="reDiag">Diagnosis / work done</label><input id="reDiag" maxlength="500" value="${esc(r.diagnosis||'')}"><div class="business-grid"><div><label for="reEst">Estimate (AED)</label><input id="reEst" type="number" min="0" step="0.01" value="${((r.estimate||0)/100).toFixed(2)}"></div><div><label for="reDue">Ready by</label><input id="reDue" type="date" value="${esc(r.due||'')}"></div></div><label for="reTech">Technician</label><input id="reTech" maxlength="100" value="${esc(r.technician||'')}"><button>Save details</button></form>
  <h3 style="margin-top:14px">Move to</h3><div class="actions">${next.map(s=>`<button class="${s==='Ready'?'primary':''}" data-re-status="${esc(s)}">${esc(s)}</button>`).join('')}</div>
  <h3 style="margin-top:14px">Bill &amp; hand over</h3><div class="actions">${r.saleId?`<span class="badge">Billed${sale?' · '+esc(sale.number||''):''}</span>`:`<button class="primary" id="reBill">Bill this repair</button>`}${r.status==='Ready'?`${r.saleId?'<button class="primary" id="reDeliver">Hand over (delivered)</button>':'<button id="reFree">Hand over · no charge</button>'}`:''}${r.status==='Ready'&&r.phone?'<button id="reWa">WhatsApp “ready”</button>':''}</div>`}
  <div class="actions"><button onclick="closeModal()">Close</button><button id="reCard">Job card</button>${sale?`<button onclick="receipt('${esc(sale.id)}')">Receipt</button>`:''}${closed?'':'<button class="danger" id="reCancel">Cancel repair</button>'}</div>`);
  const upd=(fn,msg)=>{if(change(()=>{const x=db.mobile_repairs.find(y=>y.id===id);fn(x)})){closeModal();toast(msg);if(tab==='Repairs')repairs()}};
  $('reCard').onclick=()=>jobCard(id);if(closed)return;
  $('mRe').onsubmit=e=>{e.preventDefault();upd(x=>{x.diagnosis=$('reDiag').value.trim();x.estimate=cents($('reEst').value||0);x.due=$('reDue').value;x.technician=$('reTech').value.trim()},'Saved')};
  document.querySelectorAll('[data-re-status]').forEach(b=>b.onclick=()=>upd(x=>{x.diagnosis=$('reDiag').value.trim();x.estimate=cents($('reEst').value||0);x.status=b.dataset.reStatus},'#'+r.number+' → '+b.dataset.reStatus));
  $('reCancel').onclick=()=>{const why=prompt('Reason for cancelling this repair (e.g. customer declined, cannot be repaired):');if(why?.trim())upd(x=>{x.status='Cancelled';x.cancelReason=why.trim()},'Repair cancelled')};
  if($('reBill'))$('reBill').onclick=()=>{const labour=db.grocery_items.find(i=>R.isSvc(i)&&i.serviceType==='repair');if(!labour){alert('Add a service item of type “repair” (e.g. Repair labour) on Products first.');return}const link={kind:'mobile_repairs',id};if(R.billed(link)){closeModal();navigate('Checkout');return}
   closeModal();R.bill({lines:[{id:labour.id,qty:1,price:cents($('reEst')?.value||0)||r.estimate||labour.price,link,note:'Repair #'+r.number+' · '+r.device}],customerId:r.customerId});toast('Add any parts used, then take payment')};
  if($('reDeliver'))$('reDeliver').onclick=()=>upd(x=>{x.status='Delivered'},'Handed over');
  if($('reFree'))$('reFree').onclick=()=>{if(confirm('Hand over without a bill (warranty or goodwill repair)?'))upd(x=>{x.noCharge=true;x.status='Delivered'},'Handed over · no charge')};
  if($('reWa'))$('reWa').onclick=()=>{try{window.open(SalonWhatsApp.link(r.phone,`Hello ${r.customer.split(' ')[0]}, your ${r.device} is ready for collection at ${db.settings.name}. Job no. ${r.number}. ${r.saleId?'':'Amount: '+money(r.estimate||0)+' + VAT. '}Please bring your job card. Thank you!`),'_blank','noopener')}catch(e){alert(e.message)}}}

 Object.assign(R.screens,{Repairs:repairs,IMEI:imeiScreen});
 Object.assign(window,{mobReceive:receive,mobBuy:buy,mobRepairs:v=>{repairView=v;repairs()},mobRepairNew:repairNew,mobRepairOpen:repairOpen});
})();
