// Optical shop screens for Palace POS (business type "optical"). Checkout, products, stock, credit and branches
// come from grocery.js / perfume.js; this file adds Spectacles (frame + lens orders made to a prescription, lab
// status, advance and balance), Prescriptions, Eye tests (bookings), Claims (insurance) and Recalls (contact-lens
// reorder and yearly eye-test reminders).
(function(){
 'use strict';
 const R=window.RetailUI;if(!R)return;
 R.ext??={};const EXT=R.ext.optical={};
 const RX_TYPES=['Distance','Reading','Progressive / bifocal','Contact lens'];
 const INSURERS=['Daman','Thiqa','Sukoon (Oman Insurance)','GIG Gulf (AXA)','NAS','Neuron','NextCare','MedNet','ADNIC','Almadallah','Orient','Saico'];
 let view='Open',rxSearch='',testView='Upcoming',claimView='Outstanding',draft=null;
 const isOwner=()=>cloudUser?.role==='owner';
 const today=()=>R.localDay(),plus=n=>{const d=new Date();d.setDate(d.getDate()+n);return R.localDay(d)};
 const item=id=>db.grocery_items.find(i=>i.id===id),cust=id=>db.customers.find(c=>c.id===id);
 const custOptions=(sel='')=>`<option value="">Choose customer…</option>`+db.customers.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(c=>`<option value="${esc(c.id)}" ${c.id===sel?'selected':''}>${esc(c.name)}${c.phone?' · '+esc(c.phone):''}</option>`).join('');
 const newCust=p=>`<div id="${p}New" class="business-grid" style="display:none"><div><label for="${p}Name">Name</label><input id="${p}Name" maxlength="100"></div><div><label for="${p}Phone">Phone</label><input id="${p}Phone" maxlength="40"></div></div>`;
 const pickCust=p=>{const s=$(p+'Cust');if(s.value==='+'&&!$(p+'Name').value.trim())return{err:'Enter the customer name.'};if(!s.value)return{err:'Choose the customer, or add a new one.'};return{id:s.value,make:()=>{if(s.value!=='+')return cust(s.value);const c={id:uid(),name:$(p+'Name').value.trim(),phone:$(p+'Phone').value.trim(),dob:''};db.customers.push(c);return c}}};
 const badge=s=>`<span class="badge" style="${['Ready','Paid','Done'].includes(s)?'background:#dff3e9;color:#155e48':['Cancelled','Rejected','No-show'].includes(s)?'background:#fde8e6;color:#8a1c14':['At lab','Submitted','To submit'].includes(s)?'background:#fdf0d8;color:#7a5200':s==='Delivered'?'background:#eceaf3;color:#555':''}">${esc(s)}</span>`;
 const tabs=(views,cur,fn)=>views.map(([v,c])=>`<button class="${cur===v?'primary':''}" onclick="${fn}('${v}')">${v}${c!==''?' ('+c+')':''}</button>`).join('');
 const wa=(phone,msg)=>{try{window.open(SalonWhatsApp.link(phone,msg),'_blank','noopener')}catch(e){alert(e.message)}};
 const line='--------------------------------';
 const head=()=>`${db.settings.name}\n${db.settings.address||''}\n${db.settings.phone||''}\n${line}\n`;
 const slip=(title,text)=>modal(`<h2>${title}</h2><pre class="receipt" id="receiptText">${esc(text)}</pre><div class="actions"><button onclick="closeModal()">Close</button><button class="primary" onclick="printReceipt()">Print / Save PDF</button></div>`);
 const closed=o=>['Delivered','Cancelled'].includes(o.status);
 const late=o=>!closed(o)&&o.status!=='Ready'&&o.due<today();
 const orderTotal=o=>(o.framePrice||0)+(o.lensPrice||0);

 // --- prescription helpers ---------------------------------------------------------------
 const eyeText=e=>!e||!(e.sph||e.cyl||e.add)?'—':`${e.sph||'Plano'}${e.cyl?' / '+e.cyl+(e.axis?' × '+e.axis:''):''}${e.add?' ADD '+e.add:''}`;
 const rxLine=x=>`R ${eyeText(x.right)} · L ${eyeText(x.left)}${x.pd?' · PD '+x.pd:''}`;
 const rxTable=x=>`        SPH     CYL    AXIS   ADD\nRight   ${[x.right.sph||'-',x.right.cyl||'-',x.right.axis||'-',x.right.add||'-'].map(v=>String(v).padEnd(7)).join('')}\nLeft    ${[x.left.sph||'-',x.left.cyl||'-',x.left.axis||'-',x.left.add||'-'].map(v=>String(v).padEnd(7)).join('')}${x.pd?'\nPD: '+x.pd+' mm':''}`;
 const rxInputs=(p,x={})=>`<div class="scroll"><table style="min-width:300px"><tr><th></th><th>SPH</th><th>CYL</th><th>AXIS</th><th>ADD</th></tr>${[['right','Right (OD)'],['left','Left (OS)']].map(([k,l])=>`<tr><td><b>${l}</b></td>${['sph','cyl','axis','add'].map(f=>`<td><input id="${p}${k}${f}" aria-label="${l} ${f}" maxlength="6" inputmode="${f==='axis'?'numeric':'text'}" value="${esc(x[k]?.[f]||'')}" placeholder="${f==='axis'?'0–180':f==='add'?'+0.00':'±0.00'}" style="min-width:52px;margin:0;padding-left:6px;padding-right:6px"></td>`).join('')}</tr>`).join('')}</table></div><label for="${p}pd">PD (mm)</label><input id="${p}pd" maxlength="9" value="${esc(x.pd||'')}" placeholder="62 or 31/31" style="max-width:160px">`;
 const okPower=(s,max)=>!s||/^(pl|plano)$/i.test(s)||(/^[+-]?\d{1,2}(\.\d{1,2})?$/.test(s)&&Math.abs(Number(s))<=max&&Math.abs(Number(s)*4-Math.round(Number(s)*4))<1e-9);
 // Reads the grid; returns {error} or the prescription as typed (the cloud tidies it to +0.00 form).
 function readRx(p){const x={right:{},left:{},pd:$(p+'pd').value.trim()};
  for(const k of ['right','left']){for(const f of ['sph','cyl','axis','add'])x[k][f]=$(p+k+f).value.trim().replace(',','.');const e=x[k],side=k==='right'?'Right':'Left';
   if(!okPower(e.sph,30)||!okPower(e.cyl,10)||!okPower(e.add,4))return{error:side+' eye: powers go in steps of 0.25 (e.g. -2.25, +1.50).'};
   if(e.axis&&(!/^\d{1,3}$/.test(e.axis)||Number(e.axis)>180))return{error:side+' eye: the axis is 0 to 180.'}}
  if(x.pd&&!/^\d{2}(\.\d)?(\s*\/\s*\d{2}(\.\d)?)?$/.test(x.pd))return{error:'PD looks like 62 or 31/31.'};
  if(![x.right,x.left].some(e=>e.sph||e.cyl||e.add))return{error:'Enter the power for at least one eye.'};
  const fmt=v=>!v?'':/^(pl|plano)$/i.test(v)?'Plano':(Number(v)>0?'+':Number(v)<0?'-':'')+Math.abs(Number(v)).toFixed(2);for(const k of ['right','left'])for(const f of ['sph','cyl','add'])x[k][f]=fmt(x[k][f]);
  return x}
 const rxOf=cid=>db.optical_rx.filter(r=>r.customerId===cid).sort((a,b)=>b.date.localeCompare(a.date)||(b.created||'').localeCompare(a.created||''));
 const sameRx=(a,b)=>!!a&&!!b&&['right','left'].every(k=>['sph','cyl','axis','add'].every(f=>String(a[k]?.[f]||'').replace(/^\+|\.?0+$/g,'')===String(b[k]?.[f]||'').replace(/^\+|\.?0+$/g,'')));
 const recall=(c,type,due,about)=>{for(const r of db.optical_recalls)if(r.status==='Open'&&r.customerId===c.id&&r.type===type)r.status='Done';db.optical_recalls.push({id:uid(),type,customerId:c.id,customer:c.name,phone:c.phone||'',due,about,status:'Open',created:new Date().toISOString()})};

 // --- product form, buttons, dashboard, checkout ---------------------------------------------------------------
 EXT.units=[['piece','Piece']];
 EXT.services={types:[['lens','Lenses (pair)'],['eyetest','Eye test'],['other','Other service']],category:t=>t==='lens'?'Lenses':'Services',blank:{name:'',category:'Lenses',serviceType:'lens',price:0,duration:30,openPrice:true}};
 EXT.itemFields=i=>`<div class="business-grid"><div><label for="opBrand">Brand (optional)</label><input id="opBrand" maxlength="40" value="${esc(i.brand||'')}"></div><div><label for="opColour">Colour (optional)</label><input id="opColour" maxlength="30" value="${esc(i.colour||'')}"></div></div><div class="business-grid"><div><label for="opSize">Frame size (optional)</label><input id="opSize" maxlength="20" value="${esc(i.size||'')}" placeholder="52-18-140"></div><div><label for="opDays">Contact lenses: days one box lasts</label><input id="opDays" type="number" min="0" max="400" step="1" value="${i.supplyDays||''}" placeholder="e.g. 90"></div></div><p class="helper">With “days one box lasts”, the customer gets a reorder reminder on Recalls a week before they run out.</p>`;
 EXT.readItem=()=>{const x={};for(const [id,k] of [['opBrand','brand'],['opColour','colour'],['opSize','size']])if($(id)?.value.trim())x[k]=$(id).value.trim();const d=Math.round(Number($('opDays')?.value||0));if(d>0)x.supplyDays=Math.min(400,d);return x};
 EXT.productButtons=()=>`${R.branches().length>1?`<button onclick="perfBranchPick()">Branch: ${esc(R.branchName())}</button>`:''}${isOwner()?'<button onclick="perfBranches()">Branches</button>':''}`;
 EXT.stockButtons=()=>R.branches().length>1?`<button onclick="perfTransfer()">Transfer</button><button onclick="perfBranchPick()">Branch: ${esc(R.branchName())}</button>`:'';
 EXT.dashboard=()=>{const open=db.optical_orders.filter(o=>!closed(o)),t=today(),claims=db.optical_claims.filter(c=>['To submit','Submitted'].includes(c.status)),due=db.optical_recalls.filter(r=>r.status==='Open'&&r.due<=plus(7));
  return `<section class="panel"><div class="grid">${[['Spectacles in progress',open.filter(o=>o.status!=='Ready').length,open.filter(late).length+' late · '+open.filter(o=>o.status==='Ready').length+' ready for collection','Spectacles'],['Eye tests today',db.optical_tests.filter(x=>x.status==='Booked'&&R.localDay(new Date(x.when))===t).length,db.optical_tests.filter(x=>x.status==='Booked'&&R.localDay(new Date(x.when))>t).length+' upcoming','Eye tests'],['Insurance to collect',money(claims.reduce((n,c)=>n+c.amount,0)),claims.length+' claim'+(claims.length===1?'':'s')+' open','Claims'],['Reminders due',due.length,'Contact lenses & eye tests','Recalls']].map(([l,v,h,tb])=>`<div class="panel" style="margin:0;cursor:pointer" onclick="navigate('${tb}')">${l}<div class="metric">${v}</div><p class="helper">${h}</p></div>`).join('')}</div></section>`};
 // Checkout: advance already paid, and the insurer's share of this bill.
 EXT.checkoutExtra=(c,t)=>{if(!c)return '<p class="helper">Choose the customer to use an advance or bill an insurer.</p>';const bal=R.balanceOf(c.id),ins=R.cartState().extra.ins||{},share=Math.min(ins.amount||0,t?.total||0);
  return `${bal<0?`<p class="helper" style="background:#dff3e9;color:#155e48;padding:8px 10px;border-radius:8px">Advance on account: <b>${money(-bal)}</b>. Press <b>Credit</b> to use it; then receive the balance.</p>`:''}<details ${ins.insurer?'open':''}><summary>Insurance pays part of this bill</summary><label for="oiIns">Insurer</label><input id="oiIns" list="oiList" maxlength="80" value="${esc(ins.insurer||'')}" oninput="optIns('insurer',this.value)"><datalist id="oiList">${INSURERS.map(i=>`<option value="${esc(i)}">`).join('')}</datalist><div class="business-grid"><div><label for="oiMem">Member / card no.</label><input id="oiMem" maxlength="60" value="${esc(ins.memberId||'')}" oninput="optIns('memberId',this.value)"></div><div><label for="oiApp">Approval no.</label><input id="oiApp" maxlength="60" value="${esc(ins.approval||'')}" oninput="optIns('approval',this.value)"></div></div><label for="oiAmt">Insurer pays (AED, incl. VAT)</label><input id="oiAmt" type="number" min="0" step="0.01" value="${ins.amount?(ins.amount/100).toFixed(2):''}" onchange="optIns('amount',this.value);setTimeout(RetailUI.refresh)">${ins.insurer&&share?`<p class="helper" style="background:#fdf0d8;color:#7a5200;padding:8px 10px;border-radius:8px">${esc(ins.insurer)} pays <b>${money(share)}</b> · customer pays <b>${money(Math.max(0,(t?.total||0)-share-Math.max(0,-bal)))}</b>${bal<0?' after the advance':''}. Press <b>Credit</b>: the bill goes on the account, the claim is saved, then take the customer’s share.</p>`:''}</details>`};
 EXT.onPaid=(sale,links,extra)=>{let msg='';const c=cust(sale.customerId);
  for(const l of links)if(l.kind==='optical_orders'){const o=db.optical_orders.find(x=>x.id===l.id);if(o&&!o.saleId){o.saleId=sale.id;if(o.status==='Ready'){o.status='Delivered';msg='Order #'+o.number+' billed and handed over'}else msg='Order #'+o.number+' billed · hand it over when it is ready'}}
  if(c)for(const l of sale.items){const i=item(l.id);if(i?.supplyDays)recall(c,'contact',plus(Math.max(1,Math.round(i.supplyDays*l.qty)-7)),i.name)}
  const ins=extra?.ins;if(ins?.insurer&&ins.amount>0){if(c&&sale.method==='Credit (account)'){const amount=Math.min(ins.amount,sale.total);db.optical_claims.push({id:uid(),number:0,saleId:sale.id,invoice:sale.number,customerId:c.id,customer:c.name,insurer:ins.insurer.trim(),memberId:(ins.memberId||'').trim(),approval:(ins.approval||'').trim(),claimRef:'',amount,total:sale.total,paidAmount:0,note:'',status:'To submit',created:new Date().toISOString()});const owe=R.balanceOf(c.id)-amount;msg='Claim saved: '+ins.insurer+' '+money(amount)+(owe>0?' · now take the customer’s '+money(owe)+' (Credit → Receive payment)':'')}
   else msg='Insurance was NOT recorded: bill insurance sales with Credit'}
  return msg};

 // --- spectacle orders ---------------------------------------------------------------
 function screen(){const inView=o=>view==='Open'?!closed(o)&&o.status!=='Ready':view==='Ready'?o.status==='Ready':closed(o),n=f=>db.optical_orders.filter(f).length,list=db.optical_orders.filter(inView).sort((a,b)=>view==='Closed'?b.created.localeCompare(a.created):a.due.localeCompare(b.due)).slice(0,200);
  $('app').innerHTML=`<div class="panel"><div class="row" style="flex-wrap:wrap;gap:8px"><h2>Spectacle orders</h2><div class="actions" style="margin:0;flex-wrap:wrap">${tabs([['Open',n(o=>!closed(o)&&o.status!=='Ready')],['Ready',n(o=>o.status==='Ready')],['Closed','']],view,'optView')}<button class="primary" onclick="optOrderNew()">+ New order</button></div></div>
  ${list.map(o=>`<div class="row" style="padding:10px 0;border-bottom:1px solid #eee;flex-wrap:wrap;gap:10px"><div style="min-width:240px;flex:1"><b>#${o.number||'…'} · ${esc(o.customer)}</b> ${badge(o.status)}<div class="helper">${esc(o.frame)} · ${esc(o.lens)}${o.lensDetails?' ('+esc(o.lensDetails)+')':''}</div><div class="helper"><span${late(o)?' style="color:#b42318;font-weight:700"':''}>Ready by ${esc(o.due)}${late(o)?' · late':''}</span>${o.lab?' · '+esc(o.lab):''} · ${money(orderTotal(o))}${o.advance?' · advance '+money(o.advance):''}${o.saleId?' · billed':''}</div></div><button onclick="optOrderOpen('${esc(o.id)}')">Open</button></div>`).join('')||`<div class="empty">${view==='Open'?'No orders in progress. Take one with “+ New order”.':'No orders here.'}</div>`}</div>`}
 function orderNew(pre={}){const frames=db.grocery_items.filter(i=>!R.isSvc(i)&&['Frames','Sunglasses','Reading glasses'].includes(i.category)).sort((a,b)=>a.name.localeCompare(b.name)),lenses=db.grocery_items.filter(i=>R.isSvc(i)&&i.serviceType==='lens');
  if(!lenses.length){alert('Add a lens service on Products first (type “Lenses (pair)”).');return}
  const stock=R.stockLevels?R.stockLevels():null,left=i=>{try{const v=stock?.get?stock.get(i.id):stock?.[i.id];return typeof v==='number'?' · '+v+' in stock':''}catch{return ''}};
  modal(`<h2>New spectacle order</h2><form id="oOrd"><label for="ooCust">Customer</label><select id="ooCust">${custOptions(pre.customerId||'')}<option value="+">+ New customer…</option></select>${newCust('oo')}
  <h3 style="margin-top:12px">Prescription</h3><p class="helper" id="ooRxHint"></p><select id="ooRxType" aria-label="Prescription type">${RX_TYPES.slice(0,3).map(t=>`<option>${t}</option>`).join('')}</select>${rxInputs('oo',pre.rx||{})}
  <label style="display:flex;gap:8px;align-items:center"><input type="checkbox" id="ooKeep" style="width:auto"> Save this as a new prescription for the customer</label>
  <h3 style="margin-top:12px">Frame &amp; lenses</h3><label for="ooFrame">Frame</label><select id="ooFrame"><option value="">Customer’s own frame</option>${frames.map(f=>`<option value="${esc(f.id)}">${esc(f.name)} · ${money(f.price)}${left(f)}</option>`).join('')}</select>
  <div class="business-grid"><div><label for="ooLens">Lenses</label><select id="ooLens">${lenses.map(l=>`<option value="${esc(l.id)}">${esc(l.name)}</option>`).join('')}</select></div><div><label for="ooLensPrice">Lens price (AED, pair)</label><input id="ooLensPrice" type="number" min="0" step="0.01" value="${(lenses[0].price/100).toFixed(2)}"></div></div>
  <label for="ooDetails">Lens details</label><input id="ooDetails" maxlength="200" placeholder="e.g. 1.60 index, anti-glare, blue cut">
  <div class="business-grid"><div><label for="ooDue">Ready by</label><input id="ooDue" type="date" min="${today()}" value="${plus(3)}" required></div><div><label for="ooLab">Lab</label><input id="ooLab" maxlength="100" list="ooLabs"><datalist id="ooLabs">${[...new Set(db.optical_orders.map(o=>o.lab).filter(Boolean))].map(l=>`<option value="${esc(l)}">`).join('')}</datalist></div></div>
  <div class="business-grid"><div><label for="ooAdv">Advance received now (AED)</label><input id="ooAdv" type="number" min="0" step="0.01" placeholder="0.00"></div><div><label for="ooMethod">Advance paid by</label><select id="ooMethod"><option>Cash</option><option value="Card (external terminal)">Card</option></select></div></div>
  <label for="ooNote">Note</label><input id="ooNote" maxlength="200"><p id="ooTotal" class="helper"></p><p id="ooErr" class="pending-note" role="alert" hidden></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save &amp; print job order</button></div></form>`);
  let loaded=null;
  const total=()=>{const f=item($('ooFrame').value),sub=(f?.price||0)+cents($('ooLensPrice').value||0),tax=Math.round(sub*(db.settings.tax||0)/100);$('ooTotal').innerHTML='Order total <b>'+money(sub+tax)+'</b> incl. VAT'};
  const load=()=>{const v=$('ooCust').value;$('ooNew').style.display=v==='+'?'grid':'none';const last=rxOf(v).find(r=>r.type!=='Contact lens');loaded=last||null;
   if(last&&!pre.rx){for(const k of ['right','left'])for(const f of ['sph','cyl','axis','add'])$('oo'+k+f).value=last[k][f]||'';$('oopd').value=last.pd||'';$('ooRxType').value=RX_TYPES.includes(last.type)?last.type:'Distance'}
   $('ooRxHint').textContent=last?'Filled from the prescription of '+last.date+(last.optometrist?' · '+last.optometrist:'')+'. Change it if today’s test differs.':'No saved prescription: enter it from the eye test or the customer’s paper.';$('ooKeep').checked=!last};
  $('ooCust').onchange=load;load();$('ooFrame').onchange=total;$('ooLensPrice').oninput=total;$('ooLens').onchange=()=>{$('ooLensPrice').value=((item($('ooLens').value)?.price||0)/100).toFixed(2);total()};total();
  if(pre.rx){$('ooRxType').value=RX_TYPES.slice(0,3).includes(pre.rxType)?pre.rxType:'Distance';loaded=pre.rx;$('ooKeep').checked=false}
  $('oOrd').onsubmit=e=>{e.preventDefault();const err=m=>{$('ooErr').textContent=m;$('ooErr').hidden=!m},who=pickCust('oo');if(who.err){err(who.err);return}const rx=readRx('oo');if(rx.error){err(rx.error);return}
   const f=item($('ooFrame').value),l=item($('ooLens').value),lensPrice=cents($('ooLensPrice').value||0),advance=$('ooAdv').value?cents($('ooAdv').value):0,method=$('ooMethod').value;if(!$('ooDue').value){err('Choose the ready date.');return}if(!(lensPrice>=0)||!(advance>=0)){err('Check the amounts.');return}
   if(!l.openPrice&&lensPrice!==l.price){err(l.name+' has a fixed price of '+money(l.price)+'. Tick “price can change” on the product to edit it here.');return}
   if(advance&&method!=='Cash'&&!confirm('Confirm '+money(advance)+' was approved on your card terminal?'))return;
   const id=uid(),now=new Date().toISOString(),keep=$('ooKeep').checked||!sameRx(rx,loaded),type=$('ooRxType').value;
   if(change(()=>{const c=who.make();
    if(keep){db.optical_rx.push({id:uid(),customerId:c.id,customer:c.name,date:today(),type,...rx,optometrist:'',source:'shop',note:'',created:now});recall(c,'test',plus(365),'Yearly eye test')}
    if(advance)db.grocery_payments.push({id:uid(),customerId:c.id,customer:c.name,amount:advance,method,note:'Advance · spectacles',at:now});
    db.optical_orders.push({id,number:0,customerId:c.id,customer:c.name,phone:c.phone||'',frameItemId:f?.id||'',frame:f?.name||'Customer’s own frame',framePrice:f?.price||0,lensItemId:l.id,lens:l.name,lensPrice,lensDetails:$('ooDetails').value.trim(),rxType:type,...rx,due:$('ooDue').value,advance,lab:$('ooLab').value.trim(),labRef:'',note:$('ooNote').value.trim(),status:'Ordered',saleId:'',created:now,history:[{status:'Ordered',at:now}]})})){view='Open';render();orderSlip(id)}}}
 function orderSlip(id){const o=db.optical_orders.find(x=>x.id===id);if(!o)return;const tax=Math.round(orderTotal(o)*(db.settings.tax||0)/100);
  modal(`<h2>Job order</h2>${o.number?'':'<p class="pending-note">The order number is issued when this device syncs. Reprint after syncing to show it.</p>'}<pre class="receipt" id="receiptText">${esc(`${head()}SPECTACLE ORDER${o.number?' No. '+o.number:''}\n${new Date(o.created).toLocaleString()}\n${line}\nCustomer: ${o.customer}\nPhone: ${o.phone||'-'}\nREADY BY: ${o.due}\n${line}\n${o.rxType||'Distance'}\n${rxTable(o)}\n${line}\nFrame: ${o.frame}\nLenses: ${o.lens}${o.lensDetails?'\n  '+o.lensDetails:''}\n${o.lab?'Lab: '+o.lab+(o.labRef?' · '+o.labRef:'')+'\n':''}${line}\nTotal: ${money(orderTotal(o)+tax)} incl. VAT\nAdvance paid: ${money(o.advance||0)}\nBalance on collection: ${money(Math.max(0,orderTotal(o)+tax-(o.advance||0)))}\n${o.note?'Note: '+o.note+'\n':''}${line}\nBring this slip to collect your glasses.\nLenses are made to your prescription and\ncannot be returned once ordered.`)}</pre><div class="actions"><button onclick="closeModal()">Close</button><button class="primary" onclick="printReceipt()">Print / Save PDF</button></div>`)}
 function orderOpen(id){const o=db.optical_orders.find(x=>x.id===id);if(!o)return;const done=closed(o),sale=o.saleId?db.sales.find(s=>s.id===o.saleId):null,bal=R.balanceOf(o.customerId),next={Ordered:['At lab','Ready'],'At lab':['Ready'],Ready:['At lab']}[o.status]||[];
  modal(`<h2>#${o.number||'…'} · ${esc(o.customer)}</h2><p>${badge(o.status)} ready by <b${late(o)?' style="color:#b42318"':''}>${esc(o.due)}</b>${o.phone?' · '+esc(o.phone):''}</p><p><b>${esc(o.frame)}</b>${o.framePrice?' · '+money(o.framePrice):''}<br><b>${esc(o.lens)}</b> · ${money(o.lensPrice)}${o.lensDetails?' · '+esc(o.lensDetails):''}</p><p class="helper">${esc(o.rxType||'')} · ${esc(rxLine(o))}</p><p>Total <b>${money(orderTotal(o))}</b> + VAT · advance ${money(o.advance||0)}${o.note?' · '+esc(o.note):''}</p>
  ${done?`<p>${o.cancelReason?'Cancelled: '+esc(o.cancelReason)+'<br>':''}${sale?'Bill '+esc(sale.number||'')+' · '+money(sale.total):''}</p>`:`<form id="oEd"><div class="business-grid"><div><label for="oeLab">Lab</label><input id="oeLab" maxlength="100" value="${esc(o.lab||'')}"></div><div><label for="oeRef">Lab order no.</label><input id="oeRef" maxlength="60" value="${esc(o.labRef||'')}"></div></div><div class="business-grid"><div><label for="oeDue">Ready by</label><input id="oeDue" type="date" value="${esc(o.due)}" required></div><div><label for="oeNote">Note</label><input id="oeNote" maxlength="200" value="${esc(o.note||'')}"></div></div><button>Save details</button></form>
  <h3 style="margin-top:14px">${o.status==='Ready'?'Needs remaking? Send back':'Move to'}</h3><div class="actions">${next.map(s=>`<button class="${s==='Ready'?'primary':''}" data-oe="${esc(s)}">${s==='At lab'?'Sent to lab':esc(s)}</button>`).join('')}</div>
  <h3 style="margin-top:14px">Bill &amp; hand over</h3><div class="actions">${o.saleId?`<span class="badge">Billed${sale?' · '+esc(sale.number||''):''}</span>`:'<button class="primary" id="oeBill">Bill this order</button>'}${o.saleId&&o.status==='Ready'?'<button class="primary" id="oeGive">Hand over (delivered)</button>':''}${o.status==='Ready'&&o.phone?'<button id="oeWa">WhatsApp “ready”</button>':''}</div>`}
  ${bal?`<p class="helper" style="padding:8px 10px;border-radius:8px;${bal>0?'background:#fde8e6;color:#8a1c14':'background:#dff3e9;color:#155e48'}">Customer account: <b>${bal>0?money(bal)+' due':money(-bal)+' paid in advance'}</b> ${bal>0?'<button id="oeBal" style="margin-left:8px">Receive balance</button>':''}</p>`:''}
  <div class="actions"><button onclick="closeModal()">Close</button><button id="oeSlip">Job order</button>${sale?`<button onclick="receipt('${esc(sale.id)}')">Receipt</button>`:''}${done?'':'<button class="danger" id="oeCancel">Cancel order</button>'}</div>`);
  $('oeSlip').onclick=()=>orderSlip(id);if($('oeBal'))$('oeBal').onclick=()=>{closeModal();groceryPayment(o.customerId)};if(done)return;
  const upd=(fn,msg)=>{if(change(()=>fn(db.optical_orders.find(x=>x.id===id)))){closeModal();toast(msg);if(tab==='Spectacles')screen()}};
  const details=x=>{x.lab=$('oeLab').value.trim();x.labRef=$('oeRef').value.trim();if($('oeDue').value)x.due=$('oeDue').value;x.note=$('oeNote').value.trim()};
  $('oEd').onsubmit=e=>{e.preventDefault();upd(details,'Saved')};
  document.querySelectorAll('[data-oe]').forEach(b=>b.onclick=()=>upd(x=>{details(x);x.status=b.dataset.oe},'#'+o.number+' → '+b.dataset.oe));
  $('oeCancel').onclick=()=>{if(o.saleId){alert('This order is already billed. Refund the bill on Sales first.');return}const why=prompt('Reason for cancelling this order:');if(why?.trim())upd(x=>{x.status='Cancelled';x.cancelReason=why.trim()},o.advance?'Cancelled · the advance of '+money(o.advance)+' stays on the customer’s account':'Order cancelled')};
  if($('oeBill'))$('oeBill').onclick=()=>{const link={kind:'optical_orders',id};closeModal();if(R.billed(link)){navigate('Checkout');return}const l=item(o.lensItemId);if(!l){alert('The lens service was deleted from Products. Add it again to bill this order.');return}
   R.bill({lines:[...(o.frameItemId&&item(o.frameItemId)?[{id:o.frameItemId,qty:1,link,note:'Order #'+o.number}]:[]),{id:l.id,qty:1,...(l.openPrice?{price:o.lensPrice}:{}),link,note:('Order #'+o.number+(o.lensDetails?' · '+o.lensDetails:'')).slice(0,100)}],customerId:o.customerId});toast(o.advance?'Advance '+money(o.advance)+' is on the account: press Credit, then receive the balance':'Take payment to finish')};
  if($('oeGive'))$('oeGive').onclick=()=>upd(x=>{x.status='Delivered'},'Handed over');
  if($('oeWa'))$('oeWa').onclick=()=>wa(o.phone,`Hello ${o.customer.split(' ')[0]}, your glasses are ready for collection at ${db.settings.name}. Order no. ${o.number}. Please bring your slip. Thank you!`)}

 // --- prescriptions ---------------------------------------------------------------
 function rxScreen(){const q=rxSearch.trim().toLowerCase(),has=new Set(db.optical_rx.map(r=>r.customerId)),list=db.customers.filter(c=>q?(c.name+' '+(c.phone||'')).toLowerCase().includes(q):has.has(c.id)).sort((a,b)=>a.name.localeCompare(b.name)).slice(0,60);
  $('app').innerHTML=`<div class="panel"><div class="row"><div><h2>Prescriptions</h2><p class="helper">Every eye test and outside prescription, kept per customer.</p></div><button class="primary" onclick="optRxNew()">+ New prescription</button></div><label for="orSearch">Search customer name or mobile</label><input id="orSearch" value="${esc(rxSearch)}" autocomplete="off">
  ${list.map(c=>{const all=rxOf(c.id);return `<div style="padding:10px 0;border-bottom:1px solid #eee"><div class="row" style="flex-wrap:wrap;gap:8px"><b>${esc(c.name)}${c.phone?' · '+esc(c.phone):''}</b><span class="actions" style="margin:0"><button onclick="optRxNew('${esc(c.id)}')">+ Prescription</button>${all.length?`<button onclick="optOrderFromRx('${esc(all[0].id)}')">Order spectacles</button>`:''}</span></div>${all.slice(0,4).map(r=>`<div class="row" style="gap:8px;flex-wrap:wrap"><span class="helper"><b>${esc(r.date)}</b> · ${esc(r.type)} · ${esc(rxLine(r))}${r.optometrist?' · '+esc(r.optometrist):''}${r.source==='outside'?' · outside':''}</span><button onclick="optRxPrint('${esc(r.id)}')">Print</button></div>`).join('')||'<div class="helper">No prescription saved</div>'}${all.length>4?`<div class="helper">+ ${all.length-4} older</div>`:''}</div>`}).join('')||`<div class="empty">${q?'No customer found.':'No prescriptions yet. Add one after an eye test with “+ New prescription”.'}</div>`}</div>`;
  const el=$('orSearch');el.oninput=()=>{rxSearch=el.value;rxScreen();const n=$('orSearch');n.focus();n.setSelectionRange(n.value.length,n.value.length)}}
 function rxNew(cid='',after){modal(`<h2>New prescription</h2><form id="oRx"><label for="orCust">Customer</label><select id="orCust">${custOptions(cid)}<option value="+">+ New customer…</option></select>${newCust('or')}<div class="business-grid"><div><label for="orDate">Test date</label><input id="orDate" type="date" max="${today()}" value="${today()}" required></div><div><label for="orType">For</label><select id="orType">${RX_TYPES.map(t=>`<option>${t}</option>`).join('')}</select></div></div>${rxInputs('or')}<div class="business-grid"><div><label for="orDoc">Optometrist</label><input id="orDoc" maxlength="100" list="orDocs" value="${esc(after?.optometrist||'')}"><datalist id="orDocs">${db.staff.map(s=>`<option value="${esc(s.name)}">`).join('')}</datalist></div><div><label for="orSrc">Tested</label><select id="orSrc"><option value="shop">Here in the shop</option><option value="outside">Outside (customer’s paper)</option></select></div></div><label for="orNote">Note</label><input id="orNote" maxlength="300" placeholder="e.g. first progressive, dry eyes"><label style="display:flex;gap:8px;align-items:center"><input type="checkbox" id="orRecall" checked style="width:auto"> Remind the customer for an eye test in 12 months</label><p id="orErr" class="pending-note" role="alert" hidden></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save prescription</button></div></form>`);
  $('orCust').onchange=()=>{$('orNew').style.display=$('orCust').value==='+'?'grid':'none'};
  $('oRx').onsubmit=e=>{e.preventDefault();const err=m=>{$('orErr').textContent=m;$('orErr').hidden=!m},who=pickCust('or');if(who.err){err(who.err);return}const rx=readRx('or');if(rx.error){err(rx.error);return}const id=uid();
   if(change(()=>{const c=who.make();db.optical_rx.push({id,customerId:c.id,customer:c.name,date:$('orDate').value,type:$('orType').value,...rx,optometrist:$('orDoc').value.trim(),source:$('orSrc').value,note:$('orNote').value.trim(),created:new Date().toISOString()});if($('orRecall').checked)recall(c,'test',plus(365),'Yearly eye test');if(after?.done)after.done()})){closeModal();toast('Prescription saved');render();rxPrint(id)}}}
 function rxPrint(id){const r=db.optical_rx.find(x=>x.id===id);if(!r)return;modal(`<h2>Prescription</h2><pre class="receipt" id="receiptText">${esc(`${head()}SPECTACLE PRESCRIPTION\nDate: ${r.date}\n${line}\nName: ${r.customer}\nFor: ${r.type}\n${line}\n${rxTable(r)}\n${line}\n${r.optometrist?'Optometrist: '+r.optometrist+'\n':''}${r.note?'Note: '+r.note+'\n':''}Next eye test advised within 12 months.\n\nSignature: ______________`)}</pre><div class="actions"><button onclick="closeModal()">Close</button><button onclick="optOrderFromRx('${esc(r.id)}')">Order spectacles</button><button class="primary" onclick="printReceipt()">Print / Save PDF</button></div>`)}

 // --- eye test bookings ---------------------------------------------------------------
 const dayOf=t=>R.localDay(new Date(t.when)),timeOf=t=>new Date(t.when).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});
 function tests(){const t=today(),list=db.optical_tests.filter(x=>testView==='Upcoming'?['Booked','No-show'].includes(x.status)&&(x.status==='Booked'||dayOf(x)>=plus(-7)):['Done','Cancelled'].includes(x.status)).sort((a,b)=>testView==='Upcoming'?a.when.localeCompare(b.when):b.when.localeCompare(a.when)).slice(0,200);
  $('app').innerHTML=`<div class="panel"><div class="row" style="flex-wrap:wrap;gap:8px"><h2>Eye tests</h2><div class="actions" style="margin:0">${tabs([['Upcoming',db.optical_tests.filter(x=>x.status==='Booked').length],['Past','']],testView,'optTests')}<button class="primary" onclick="optTestNew()">+ Book eye test</button></div></div>
  ${list.map(x=>`<div class="row" style="padding:10px 0;border-bottom:1px solid #eee;flex-wrap:wrap;gap:10px"><div style="min-width:240px;flex:1"><b>${dayOf(x)===t?'Today':esc(dayOf(x))} · ${esc(timeOf(x))} · ${esc(x.customer)}</b> ${badge(x.status)}<div class="helper">${esc([x.phone,x.optometrist,x.note].filter(Boolean).join(' · '))}</div></div><span class="actions" style="margin:0">${x.status==='Booked'?`<button class="primary" data-ot-rx="${esc(x.id)}">Record prescription</button><button data-ot-bill="${esc(x.id)}">Bill test</button>${x.phone?`<button data-ot-wa="${esc(x.id)}">WhatsApp</button>`:''}<button data-ot-no="${esc(x.id)}">No-show</button><button data-ot-x="${esc(x.id)}">Cancel</button>`:x.status==='No-show'?`<button data-ot-re="${esc(x.id)}">Rebook</button>`:''}</span></div>`).join('')||'<div class="empty">No eye tests here. Book one with “+ Book eye test”.</div>'}</div>`;
  const set=(id,status,msg)=>{if(change(()=>{db.optical_tests.find(x=>x.id===id).status=status})){toast(msg);tests()}},get=b=>db.optical_tests.find(x=>x.id===Object.values(b.dataset)[0]);
  document.querySelectorAll('[data-ot-rx]').forEach(b=>b.onclick=()=>{const x=get(b);rxNew(x.customerId,{optometrist:x.optometrist,done:()=>{x.status='Done'}})});
  document.querySelectorAll('[data-ot-bill]').forEach(b=>b.onclick=()=>{const x=get(b),svc=db.grocery_items.find(i=>R.isSvc(i)&&i.serviceType==='eyetest');if(!svc){alert('Add a service of type “Eye test” on Products first.');return}R.bill({lines:[{id:svc.id,qty:1}],customerId:x.customerId})});
  document.querySelectorAll('[data-ot-wa]').forEach(b=>b.onclick=()=>{const x=get(b);wa(x.phone,`Hello ${x.customer.split(' ')[0]}, a reminder of your eye test at ${db.settings.name} on ${dayOf(x)} at ${timeOf(x)}. Please bring your current glasses. Reply if you need another time.`)});
  document.querySelectorAll('[data-ot-no]').forEach(b=>b.onclick=()=>set(b.dataset.otNo,'No-show','Marked as no-show'));
  document.querySelectorAll('[data-ot-re]').forEach(b=>b.onclick=()=>{const x=get(b);if(change(()=>{x.status='Booked'}))testNew(x.id)});
  document.querySelectorAll('[data-ot-x]').forEach(b=>b.onclick=()=>{if(confirm('Cancel this eye test booking?'))set(b.dataset.otX,'Cancelled','Booking cancelled')})}
 function testNew(editId){const x=editId?db.optical_tests.find(t=>t.id===editId):null,d=new Date(Date.now()+3600000);d.setMinutes(0,0,0);const local=v=>{const t=new Date(v);return new Date(t.getTime()-t.getTimezoneOffset()*60000).toISOString().slice(0,16)};
  modal(`<h2>${x?'Rebook eye test':'Book eye test'}</h2><form id="oTest">${x?`<p><b>${esc(x.customer)}</b></p>`:`<label for="otCust">Customer</label><select id="otCust">${custOptions()}<option value="+">+ New customer…</option></select>${newCust('ot')}`}<div class="business-grid"><div><label for="otWhen">Date &amp; time</label><input id="otWhen" type="datetime-local" value="${local(x?.status==='Booked'&&Date.parse(x.when)>Date.now()?x.when:d)}" required></div><div><label for="otDoc">Optometrist</label><input id="otDoc" maxlength="100" list="otDocs" value="${esc(x?.optometrist||db.staff[0]?.name||'')}"><datalist id="otDocs">${db.staff.map(s=>`<option value="${esc(s.name)}">`).join('')}</datalist></div></div><label for="otNote">Note</label><input id="otNote" maxlength="200" value="${esc(x?.note||'')}" placeholder="e.g. contact lens fitting, child"><p id="otErr" class="pending-note" role="alert" hidden></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save booking</button></div></form>`);
  if(!x)$('otCust').onchange=()=>{$('otNew').style.display=$('otCust').value==='+'?'grid':'none'};
  $('oTest').onsubmit=e=>{e.preventDefault();const err=m=>{$('otErr').textContent=m;$('otErr').hidden=!m},when=new Date($('otWhen').value);if(!Number.isFinite(when.getTime())){err('Choose the date and time.');return}const f={when:when.toISOString(),optometrist:$('otDoc').value.trim(),note:$('otNote').value.trim()};
   if(x){if(change(()=>Object.assign(x,f))){closeModal();toast('Rebooked');tests()}return}
   const who=pickCust('ot');if(who.err){err(who.err);return}const now=new Date().toISOString();
   if(change(()=>{const c=who.make();db.optical_tests.push({id:uid(),customerId:c.id,customer:c.name,phone:c.phone||'',...f,status:'Booked',created:now,history:[{status:'Booked',at:now}]})})){testView='Upcoming';closeModal();toast('Eye test booked');if(tab==='Eye tests')tests()}}}

 // --- insurance claims ---------------------------------------------------------------
 const claimOpen=c=>['To submit','Submitted'].includes(c.status);
 function claims(){const list=db.optical_claims.filter(c=>claimView==='Outstanding'?claimOpen(c):!claimOpen(c)).sort((a,b)=>claimView==='Outstanding'?a.created.localeCompare(b.created):b.created.localeCompare(a.created)).slice(0,200),by=new Map();for(const c of db.optical_claims.filter(claimOpen))by.set(c.insurer,(by.get(c.insurer)||0)+c.amount);
  $('app').innerHTML=`<div class="panel"><div class="row" style="flex-wrap:wrap;gap:8px"><div><h2>Insurance claims</h2><p class="helper">The insurer’s share of each bill, until it is paid. Start one at Checkout: choose the customer, open “Insurance pays part of this bill”, press Credit.</p></div><div class="actions" style="margin:0">${tabs([['Outstanding',db.optical_claims.filter(claimOpen).length],['Closed','']],claimView,'optClaims')}</div></div>
  ${claimView==='Outstanding'&&by.size?`<p>${[...by].sort((a,b)=>b[1]-a[1]).map(([i,v])=>`<span class="badge" style="margin-right:6px">${esc(i)} · ${money(v)}</span>`).join('')} <b>Total ${money([...by.values()].reduce((n,v)=>n+v,0))}</b></p>`:''}
  ${list.map(c=>`<div class="row" style="padding:10px 0;border-bottom:1px solid #eee;flex-wrap:wrap;gap:10px"><div style="min-width:240px;flex:1"><b>#${c.number||'…'} · ${esc(c.insurer)} · ${money(c.amount)}</b> ${badge(c.status)}<div class="helper">${esc(c.customer)}${c.memberId?' · member '+esc(c.memberId):''}${c.approval?' · approval '+esc(c.approval):''}</div><div class="helper">Invoice ${esc(c.invoice||'')} · bill ${money(c.total)} · ${esc(R.localDay(new Date(c.created)))}${c.claimRef?' · claim ref '+esc(c.claimRef):''}${c.status==='Paid'?' · paid '+money(c.paidAmount):''}${c.rejectReason?' · '+esc(c.rejectReason):''}</div></div><button onclick="optClaimOpen('${esc(c.id)}')">Open</button></div>`).join('')||'<div class="empty">No claims here.</div>'}</div>`}
 function claimOpenModal(id){const c=db.optical_claims.find(x=>x.id===id);if(!c)return;const open=claimOpen(c),sale=db.sales.find(s=>s.id===c.saleId);
  modal(`<h2>Claim #${c.number||'…'} · ${esc(c.insurer)}</h2><p>${badge(c.status)} <b>${money(c.amount)}</b> of a ${money(c.total)} bill · ${esc(c.customer)}</p><p class="helper">Invoice ${esc(c.invoice||'')}${c.memberId?' · member '+esc(c.memberId):''}${c.status==='Paid'?' · insurer paid '+money(c.paidAmount):''}${c.rejectReason?' · rejected: '+esc(c.rejectReason):''}</p>
  ${open?`<form id="oCl"><div class="business-grid"><div><label for="ocRef">Insurer’s claim no.</label><input id="ocRef" maxlength="60" value="${esc(c.claimRef||'')}"></div><div><label for="ocApp">Approval no.</label><input id="ocApp" maxlength="60" value="${esc(c.approval||'')}"></div></div><label for="ocNote">Note</label><input id="ocNote" maxlength="200" value="${esc(c.note||'')}"><div class="actions">${c.status==='To submit'?'<button class="primary" data-oc="Submitted">Submitted to insurer</button>':'<button data-oc="save">Save details</button>'}</div>
  <h3 style="margin-top:12px">Insurer paid</h3><label for="ocPaid">Amount received (AED)</label><input id="ocPaid" type="number" min="0.01" step="0.01" value="${(c.amount/100).toFixed(2)}"><div class="actions"><button class="primary" data-oc="Paid">Record payment</button><button class="danger" data-oc="Rejected">Rejected</button></div></form>`:''}
  <div class="actions"><button onclick="closeModal()">Close</button>${sale?`<button onclick="receipt('${esc(sale.id)}')">Invoice</button>`:''}</div>`);
  if(!open)return;
  const upd=(fn,msg)=>{if(change(()=>fn(db.optical_claims.find(x=>x.id===id)))){closeModal();toast(msg);if(tab==='Claims')claims()}},details=x=>{x.claimRef=$('ocRef').value.trim();x.approval=$('ocApp').value.trim();x.note=$('ocNote').value.trim()};
  $('oCl').onsubmit=e=>e.preventDefault();
  document.querySelectorAll('[data-oc]').forEach(b=>b.onclick=()=>{const s=b.dataset.oc;
   if(s==='save'){upd(details,'Saved');return}if(s==='Submitted'){upd(x=>{details(x);x.status='Submitted'},'Marked as submitted');return}
   if(s==='Rejected'){const why=prompt('Why did the insurer reject it? The amount stays due on the customer’s account.');if(why?.trim())upd(x=>{details(x);x.status='Rejected';x.rejectReason=why.trim()},'Claim rejected · '+money(c.amount)+' is due from the customer');return}
   const paid=cents($('ocPaid').value||0);if(!(paid>0)||paid>c.amount){alert('Enter what the insurer paid, up to '+money(c.amount)+'.');return}if(paid<c.amount&&!confirm('The insurer paid '+money(paid)+' of '+money(c.amount)+'. The remaining '+money(c.amount-paid)+' stays due on the customer’s account. Continue?'))return;
   upd(x=>{details(x);x.status='Paid';x.paidAmount=paid;db.grocery_payments.push({id:uid(),customerId:c.customerId,customer:c.customer,amount:paid,method:'Insurance',note:(c.insurer+' claim '+(c.number||'')+(x.claimRef?' · '+x.claimRef:'')).slice(0,200),at:new Date().toISOString()})},'Insurer payment recorded')})}

 // --- recalls: contact-lens reorders and yearly eye tests ---------------------------------------------------------------
 function recalls(){const soon=plus(7),open=db.optical_recalls.filter(r=>r.status==='Open').sort((a,b)=>a.due.localeCompare(b.due)),due=open.filter(r=>r.due<=soon),later=open.filter(r=>r.due>soon).slice(0,60);
  const row=r=>`<div class="row" style="padding:10px 0;border-bottom:1px solid #eee;flex-wrap:wrap;gap:10px"><div style="min-width:220px;flex:1"><b>${esc(r.customer)}</b>${r.phone?' · '+esc(r.phone):''}<div class="helper">${r.type==='contact'?'Contact lenses running out':'Eye test due'} · ${esc(r.about||'')} · <span${r.due<today()?' style="color:#b42318;font-weight:700"':''}>${esc(r.due)}</span></div></div><span class="actions" style="margin:0">${r.phone?`<button class="primary" data-rc-wa="${esc(r.id)}">WhatsApp</button>`:''}${r.type==='test'?`<button data-rc-book="${esc(r.id)}">Book test</button>`:''}<button data-rc-done="${esc(r.id)}">Done</button><button data-rc-x="${esc(r.id)}" aria-label="Dismiss">×</button></span></div>`;
  $('app').innerHTML=`<div class="panel"><h2>Recalls</h2><p class="helper">Customers to message: contact lenses about to run out (from what they bought) and eye tests that are a year old.</p><h3>Due now · ${due.length}</h3>${due.map(row).join('')||'<div class="empty">Nobody to remind this week.</div>'}</div>${later.length?`<div class="panel"><h3>Coming up</h3>${later.map(row).join('')}</div>`:''}`;
  const get=id=>db.optical_recalls.find(r=>r.id===id),close=(id,status)=>{if(change(()=>{get(id).status=status}))recalls()};
  document.querySelectorAll('[data-rc-wa]').forEach(b=>b.onclick=()=>{const r=get(b.dataset.rcWa);wa(r.phone,r.type==='contact'?`Hello ${r.customer.split(' ')[0]}, your ${r.about||'contact lenses'} should be running low. Shall we keep a new box ready for you at ${db.settings.name}? Reply here to order.`:`Hello ${r.customer.split(' ')[0]}, it has been a year since your last eye test at ${db.settings.name}. We recommend a check every 12 months. Reply here to book a time that suits you.`)});
  document.querySelectorAll('[data-rc-book]').forEach(b=>b.onclick=()=>{const r=get(b.dataset.rcBook);testNew();$('otCust').value=r.customerId});
  document.querySelectorAll('[data-rc-done]').forEach(b=>b.onclick=()=>close(b.dataset.rcDone,'Done'));
  document.querySelectorAll('[data-rc-x]').forEach(b=>b.onclick=()=>close(b.dataset.rcX,'Dismissed'))}

 Object.assign(R.screens,{Spectacles:screen,Prescriptions:rxScreen,'Eye tests':tests,Claims:claims,Recalls:recalls});
 Object.assign(window,{optView:v=>{view=v;screen()},optOrderNew:()=>orderNew(),optOrderOpen:orderOpen,optOrderFromRx:id=>{const r=db.optical_rx.find(x=>x.id===id);if(r)orderNew({customerId:r.customerId,rx:r,rxType:r.type})},optRxNew:id=>rxNew(id||''),optRxPrint:rxPrint,optTests:v=>{testView=v;tests()},optTestNew:()=>testNew(),optClaims:v=>{claimView=v;claims()},optClaimOpen:claimOpenModal,
  optIns:(k,v)=>{const ins={...(R.cartState().extra.ins||{})};ins[k]=k==='amount'?Math.max(0,cents(v||0)||0):v;R.setExtra('ins',ins)}});
})();
