// Perfume & oud screens for Palace POS (business type "perfume"). Checkout, products, stock and credit come
// from grocery.js; this file adds Blends (custom oil blends per customer), Clients (loyalty points + scent
// profile), branches (stock per shop / mall kiosk, transfers), gift sets and loyalty settings.
(function(){
 'use strict';
 const R=window.RetailUI;if(!R)return;
 R.ext??={};const EXT=R.ext.perfume={};
 const FAMILIES=['Oud','Musk','Rose','Amber','Floral','Woody','Citrus','Fresh','Sweet','Spicy','Leather','Aquatic'];
 const LOYALTY={enabled:true,earnPerAed:1,redeemFils:5,minRedeem:100};
 let blendSearch='',clientSearch='';
 const isOwner=()=>cloudUser?.role==='owner';
 const cfg=()=>db.grocery_config.find(c=>c.id==='config')||{};
 const loyalty=()=>({...LOYALTY,...(cfg().loyalty||{})});
 const item=id=>db.grocery_items.find(i=>i.id===id);
 const oils=()=>db.grocery_items.filter(i=>!R.isSvc(i)&&R.dec(i.unit)).sort((a,b)=>a.name.localeCompare(b.name));
 const bottles=()=>db.grocery_items.filter(i=>!R.isSvc(i)&&i.unit==='piece'&&i.category==='Bottles & packaging').sort((a,b)=>a.name.localeCompare(b.name));
 const customer=id=>db.customers.find(c=>c.id===id);
 const custOptions=(sel='',blank='Walk-in / shop recipe')=>`<option value="">${esc(blank)}</option>`+db.customers.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(c=>`<option value="${esc(c.id)}" ${c.id===sel?'selected':''}>${esc(c.name)}${c.phone?' · '+esc(c.phone):''}</option>`).join('');
 const profile=id=>db.perfume_profiles.find(p=>p.id===id);
 const qt=(q,u)=>R.qtyText(q,u);
 // Points: the server's balance (all tills, refunds excluded) plus this device's unsynced points.
 function points(cid){const sum=cache?.summary?.points;if(!sum)return db.perfume_points.filter(p=>p.customerId===cid).reduce((n,p)=>n+p.points,0);return (sum[cid]||0)+(cache.pending||[]).filter(o=>o.kind==='perfume_points'&&o.base===0&&o.data?.customerId===cid).reduce((n,o)=>n+o.data.points,0)}
 const blendPrice=b=>b.components.reduce((n,c)=>n+Math.round((item(c.itemId)?.price||0)*c.qty),0)+(b.bottleId?(item(b.bottleId)?.price||0):0);
 const blendText=b=>b.components.map(c=>qt(c.qty,c.unit)+' '+c.name).join(' + ')+(b.bottle?' · '+b.bottle:'');

 // --- checkout: points ------------------------------------------------------------------------------------
 EXT.checkoutExtra=(c,t)=>{const l=loyalty();if(!c||!l.enabled)return '';const bal=points(c.id),st=R.cartState(),used=st.extra.redeem||0,earn=Math.floor((t.sub-t.off)*l.earnPerAed/100),p=profile(c.id);
  return `<div class="panel" style="margin:10px 0;padding:12px;background:#faf8ff"><div class="row"><b>⭐ ${bal} points</b><span class="helper">= ${money(bal*l.redeemFils)}</span></div>${p?.families?.length?`<div class="helper">Likes ${esc(p.families.join(', '))}${p.avoid?' · avoid '+esc(p.avoid):''}</div>`:''}
  ${used?`<div class="row"><span>Using ${used} points</span><button onclick="perfRedeem(0)">Remove</button></div>`:bal>=l.minRedeem&&t.sub>0?`<div class="row" style="gap:6px"><input id="pfUse" type="number" min="${l.minRedeem}" max="${bal}" step="1" value="${Math.min(bal,Math.floor(t.sub/l.redeemFils))}" style="margin:0;width:110px" aria-label="Points to use"><button onclick="perfRedeem(Number($('pfUse').value))">Use points</button></div>`:`<div class="helper">Redeem from ${l.minRedeem} points</div>`}
  ${earn>0?`<div class="helper">This bill earns ${earn} points</div>`:''}</div>`};
 function redeem(n){const st=R.cartState(),c=customer(st.customerId),l=loyalty();if(!n){R.setDiscount(0,{});return}if(!c)return;
  n=Math.round(n);const bal=points(c.id),maxByBill=Math.floor(st.totals.sub/l.redeemFils);
  if(!(n>=l.minRedeem)){alert('Use at least '+l.minRedeem+' points');return}if(n>bal){alert(c.name+' has '+bal+' points');return}if(n>maxByBill){alert('That is more than the bill. Use up to '+maxByBill+' points.');return}
  R.setDiscount(n*l.redeemFils,{redeem:n,offLabel:'Points ('+n+')'})}
 // After payment (inside the same change as the sale): points used and points earned.
 EXT.onPaid=(sale,links,extra)=>{const l=loyalty(),c=customer(sale.customerId);if(!c||!l.enabled)return '';const at=new Date().toISOString();
  if(extra?.redeem)db.perfume_points.push({id:'redeem-'+sale.id,customerId:c.id,customer:c.name,type:'redeem',points:-extra.redeem,saleId:sale.id,at});
  const earn=Math.floor((sale.sub-sale.off)*l.earnPerAed/100);if(earn>0)db.perfume_points.push({id:'earn-'+sale.id,customerId:c.id,customer:c.name,type:'earn',points:earn,saleId:sale.id,at});
  return c.name+': '+(earn?'+'+earn+' points':'')+(extra?.redeem?' −'+extra.redeem+' used':'')};

 // --- product form: scent family, gift set contents -------------------------------------------------------------
 EXT.itemFields=i=>{setTimeout(()=>{const cat=$('giCat');if(!cat)return;const show=()=>{$('pfSetBox').style.display=cat.value==='Gift sets'?'':'none'};cat.addEventListener('change',show);show()});
  return `<label for="pfFam">Scent family</label><select id="pfFam"><option value="">—</option>${FAMILIES.map(f=>`<option ${i.family===f?'selected':''}>${f}</option>`).join('')}</select>
  <div id="pfSetBox"><h3 style="margin-top:14px">Gift set contents</h3><div id="pfSet">${(i.components||[]).map(c=>setRow(c)).join('')}</div><button type="button" onclick="perfSetRow()">+ Add item to set</button><p class="helper">Assemble sets on Stock → Assemble gift sets; that takes these items out of stock.</p></div>`};
 const setRow=(c={})=>`<div class="row" style="gap:6px" data-setrow><select style="margin:0" data-setitem>${db.grocery_items.filter(x=>!R.isSvc(x)&&x.category!=='Gift sets').sort((a,b)=>a.name.localeCompare(b.name)).map(x=>`<option value="${esc(x.id)}" ${x.id===c.itemId?'selected':''}>${esc(x.name)} (${esc(x.unit)})</option>`).join('')}</select><input type="number" min="0.001" step="0.001" value="${c.qty||1}" style="width:90px;margin:0" data-setqty aria-label="Quantity"><button type="button" onclick="this.closest('[data-setrow]').remove()">×</button></div>`;
 EXT.readItem=i=>{const x={family:$('pfFam').value||undefined};if(!x.family)delete x.family;
  if($('giCat').value==='Gift sets'){const rows=[...document.querySelectorAll('[data-setrow]')].map(r=>{const it=item(r.querySelector('[data-setitem]').value),q=Number(r.querySelector('[data-setqty]').value);return{itemId:it?.id,qty:it&&!R.dec(it.unit)?Math.round(q):Math.round(q*1000)/1000}});
   if(!rows.length||rows.some(r=>!r.itemId||!(r.qty>0))){alert('Add the items in this gift set with their quantities');return false}if(new Set(rows.map(r=>r.itemId)).size!==rows.length){alert('List each item once');return false}x.components=rows}
  return x};

 // --- products & stock toolbar: branch, branches, loyalty, transfer, gift sets ----------------------------------------
 EXT.productButtons=()=>`${R.branches().length>1?`<button onclick="perfBranchPick()">Branch: ${esc(R.branchName())}</button>`:''}${isOwner()?'<button onclick="perfBranches()">Branches</button><button onclick="perfLoyalty()">Loyalty</button>':''}`;
 EXT.stockButtons=()=>`${R.branches().length>1?`<button onclick="perfTransfer()">Transfer</button><button onclick="perfBranchPick()">Branch: ${esc(R.branchName())}</button>`:''}${db.grocery_items.some(i=>i.category==='Gift sets'&&i.components?.length)?'<button onclick="perfAssemble()">Assemble gift sets</button>':''}`;
 function branchPick(){modal(`<h2>This device's branch</h2><p class="helper">Sales and stock on this device count for the branch you choose.</p>${R.branches().map(b=>`<button class="${b.id===R.branch()?'primary':''}" style="display:block;width:100%;margin:6px 0" onclick="perfSetBranch('${esc(b.id)}')">${esc(b.name)}</button>`).join('')}<div class="actions"><button onclick="closeModal()">Cancel</button></div>`)}
 function branchesForm(){let list=(cfg().branches||[]).map(b=>({...b}));
  const draw=()=>{$('pbList').innerHTML=list.map((b,k)=>`<div class="row" style="gap:6px"><input value="${esc(b.name)}" maxlength="60" style="margin:0" data-bn="${k}" aria-label="Branch name"><button type="button" ${list.length<2?'disabled':''} onclick="this.dispatchEvent(new CustomEvent('rm',{bubbles:true,detail:${k}}))">×</button></div>`).join('');document.querySelectorAll('[data-bn]').forEach(x=>x.oninput=e=>{list[e.target.dataset.bn].name=e.target.value})};
  modal(`<h2>Branches</h2><p class="helper">Each branch or mall kiosk keeps its own stock. Each device chooses its branch (Products → Branch). Move stock with Stock → Transfer.</p><form id="pBr"><div id="pbList"></div><button type="button" id="pbAdd">+ Add branch</button><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save</button></div></form>`);
  draw();$('pbAdd').onclick=()=>{list.push({id:'b'+uid().replace(/[^a-z0-9]/gi,'').slice(0,8),name:'Branch '+(list.length+1)});draw()};$('pbList').addEventListener('rm',e=>{const b=list[e.detail];if(confirm('Remove '+b.name+'? Its stock records stay in history.')){list.splice(e.detail,1);draw()}});
  $('pBr').onsubmit=e=>{e.preventDefault();list=list.map(b=>({id:b.id,name:b.name.trim()})).filter(b=>b.name);if(!list.length){alert('Keep at least one branch');return}if(change(()=>{cfg().branches=list})){closeModal();toast('Branches saved')}}}
 function loyaltyForm(){const l=loyalty();
  modal(`<h2>Loyalty points</h2><form id="pLoy"><label style="display:flex;gap:10px;align-items:center"><input id="plOn" type="checkbox" style="width:auto;margin:0" ${l.enabled?'checked':''}> Customers earn and use points</label><label for="plEarn">Points per AED 1 spent</label><input id="plEarn" type="number" min="0" max="100" step="0.1" value="${l.earnPerAed}"><label for="plVal">Value of 100 points (AED)</label><input id="plVal" type="number" min="0.01" max="100" step="0.01" value="${(l.redeemFils).toFixed(2)}"><label for="plMin">Minimum points to use</label><input id="plMin" type="number" min="1" step="1" value="${l.minRedeem}"><p class="helper" id="plEx"></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save</button></div></form>`);
  const ex=()=>{const e=Number($('plEarn').value),v=Number($('plVal').value);$('plEx').textContent=`Example: a AED 500 bill earns ${Math.floor(500*e)} points, worth ${money(Math.round(Math.floor(500*e)*v))}  (${(e*v).toFixed(1)}% back).`};for(const x of ['plEarn','plVal'])$(x).oninput=ex;ex();
  $('pLoy').onsubmit=e=>{e.preventDefault();const v={enabled:$('plOn').checked,earnPerAed:Math.round(Number($('plEarn').value)*10)/10,redeemFils:Math.round(Number($('plVal').value)),minRedeem:Math.round(Number($('plMin').value))};
   if(!(v.earnPerAed>=0&&v.earnPerAed<=100)||!(v.redeemFils>=1&&v.redeemFils<=100)||!(v.minRedeem>=1)){alert('Check the values. 100 points can be worth AED 0.01 to AED 100.');return}
   if(change(()=>{cfg().loyalty=v})){closeModal();toast('Loyalty saved')}}}
 function transfer(){const others=R.branches().filter(b=>b.id!==R.branch()),levels=R.stockLevels();
  modal(`<h2>Transfer stock from ${esc(R.branchName())}</h2><form id="pTr"><label for="ptItem">Product</label><select id="ptItem">${db.grocery_items.filter(i=>!R.isSvc(i)).sort((a,b)=>a.name.localeCompare(b.name)).map(i=>`<option value="${esc(i.id)}">${esc(i.name)} · ${esc(qt(levels.get(i.id)||0,i.unit))} here</option>`).join('')}</select><label for="ptTo">To</label><select id="ptTo">${others.map(b=>`<option value="${esc(b.id)}">${esc(b.name)}</option>`).join('')}</select><label for="ptQty">Quantity</label><input id="ptQty" type="number" min="0.001" step="0.001" required><label for="ptNote">Note</label><input id="ptNote" maxlength="200"><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Transfer</button></div></form>`);
  $('pTr').onsubmit=e=>{e.preventDefault();const it=item($('ptItem').value),n=Number($('ptQty').value),q=R.dec(it?.unit)?Math.round(n*1000)/1000:Math.round(n),to=$('ptTo').value;if(!it||!(q>0)||!to){alert('Enter the quantity'+(it&&!R.dec(it.unit)?' in whole pieces':''));return}
   if(q>(levels.get(it.id)||0)&&!confirm('Only '+qt(levels.get(it.id)||0,it.unit)+' here. Transfer anyway?'))return;
   if(change(()=>db.grocery_stock.push({id:uid(),type:'transfer',itemId:it.id,item:it.name,unit:it.unit,qty:q,branch:R.branch(),toBranch:to,reason:$('ptNote').value.trim(),note:'',at:new Date().toISOString()}))){closeModal();toast(qt(q,it.unit)+' '+it.name+' → '+R.branchName(to))}}}
 function assemble(){const sets=db.grocery_items.filter(i=>i.category==='Gift sets'&&i.components?.length),levels=R.stockLevels();
  modal(`<h2>Assemble gift sets</h2><form id="pAs"><label for="paSet">Gift set</label><select id="paSet">${sets.map(i=>`<option value="${esc(i.id)}">${esc(i.name)}</option>`).join('')}</select><label for="paQty">How many sets</label><input id="paQty" type="number" min="1" step="1" value="1"><div id="paNeed" class="helper"></div><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Assemble</button></div></form>`);
  const need=()=>{const s=item($('paSet').value),n=Math.max(1,Math.round(Number($('paQty').value)||1));$('paNeed').innerHTML=(s?.components||[]).map(c=>{const have=levels.get(c.itemId)||0,want=c.qty*n;return `${esc(qt(want,c.unit))} ${esc(c.name)} <span class="${have<want?'danger':''}">(${esc(qt(have,c.unit))} in stock)</span>`}).join('<br>')};$('paSet').onchange=need;$('paQty').oninput=need;need();
  $('pAs').onsubmit=e=>{e.preventDefault();const s=item($('paSet').value),n=Math.round(Number($('paQty').value));if(!s||!(n>=1)){alert('Enter how many sets');return}const at=new Date().toISOString(),b=R.branch(),reason='Gift set: '+s.name;
   if(change(()=>{db.grocery_stock.push({id:uid(),type:'assemble',itemId:s.id,item:s.name,unit:s.unit,qty:n,branch:b,reason,note:'',at});for(const c of s.components)db.grocery_stock.push({id:uid(),type:'assemble',itemId:c.itemId,item:c.name,unit:c.unit,qty:-Math.round(c.qty*n*1000)/1000,branch:b,reason,note:'',at})})){closeModal();toast(n+' × '+s.name+' assembled')}}}

 // --- blends -------------------------------------------------------------------------------------------------------
 function blends(){
  const q=blendSearch.trim().toLowerCase(),list=db.perfume_blends.filter(b=>!q||(b.name+' '+b.customer).toLowerCase().includes(q)).sort((a,b)=>b.created.localeCompare(a.created));
  $('app').innerHTML=`<div class="panel"><div class="row"><div><h2>Custom blends</h2><p class="helper">Mix oils into a bottle. Selling a blend puts each oil and the bottle on the bill, so stock of every oil goes down by what was used.</p></div><button class="primary" onclick="perfBlend()">+ New blend</button></div>
  <label for="pbSearch">Search blend or customer</label><input id="pbSearch" value="${esc(blendSearch)}" oninput="perfBlendSearch(this.value)">
  ${list.map(b=>`<div class="row" style="padding:12px 0;border-bottom:1px solid #eee;flex-wrap:wrap;gap:10px"><div style="flex:1;min-width:240px"><b style="font-size:17px">${esc(b.name)}</b> <span class="helper">${esc(b.customer||'Shop recipe')}</span><div class="helper">${esc(blendText(b))}</div>${b.notes?`<div class="helper">${esc(b.notes)}</div>`:''}</div><b>${money(blendPrice(b))}</b><div class="actions" style="margin:0"><button class="primary" onclick="perfSellBlend('${esc(b.id)}')">Sell</button><button onclick="perfBlend('${esc(b.id)}')">Edit</button>${isOwner()?`<button class="danger" onclick="perfBlendDelete('${esc(b.id)}')">Delete</button>`:''}</div></div>`).join('')||'<div class="empty">No blends yet. Create the first one for a customer.</div>'}</div>`;
 }
 function blendForm(id,customerId=''){
  const b=db.perfume_blends.find(x=>x.id===id)||{name:'',customerId,components:[],bottleId:'',notes:''};if(!oils().length){alert('Add oils sold by ml, gram or tola on Products first.');return}
  const row=(c={})=>`<div class="row" style="gap:6px" data-brow><select style="margin:0" data-boil>${oils().map(o=>`<option value="${esc(o.id)}" ${o.id===c.itemId?'selected':''}>${esc(o.name)} · ${money(o.price)}/${esc(o.unit)}</option>`).join('')}</select><input type="number" min="0.001" step="0.001" value="${c.qty||''}" placeholder="qty" style="width:90px;margin:0" data-bqty aria-label="Quantity"><span class="helper" data-bunit style="min-width:34px"></span><button type="button" onclick="this.closest('[data-brow]').remove();perfBlendCalc()">×</button></div>`;
  modal(`<h2>${id?'Edit blend':'New blend'}</h2><form id="pBl"><label for="pbCust">Customer</label><select id="pbCust">${custOptions(b.customerId)}</select><label for="pbName">Blend name</label><input id="pbName" value="${esc(b.name)}" maxlength="60" required placeholder="e.g. Fatima's Rose Oud"><h3 style="margin-top:14px">Oils</h3><div id="pbRows">${(b.components.length?b.components:[{}]).map(row).join('')}</div><button type="button" id="pbAdd">+ Add oil</button>
  <label for="pbBottle" style="display:block;margin-top:12px">Bottle</label><select id="pbBottle"><option value="">No bottle</option>${bottles().map(x=>`<option value="${esc(x.id)}" ${x.id===b.bottleId?'selected':''}>${esc(x.name)} · ${money(x.price)}</option>`).join('')}</select><label for="pbNotes">Notes</label><input id="pbNotes" maxlength="300" value="${esc(b.notes)}" placeholder="e.g. stronger oud next time"><p id="pbTotal" style="font-size:18px"></p>
  <div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button type="button" id="pbSave">Save</button><button class="primary">Save & sell</button></div></form>`);
  window.perfBlendCalc=()=>{let t=0;document.querySelectorAll('[data-brow]').forEach(r=>{const o=item(r.querySelector('[data-boil]').value),q=Number(r.querySelector('[data-bqty]').value)||0;r.querySelector('[data-bunit]').textContent=o?.unit||'';t+=Math.round((o?.price||0)*q)});const bt=item($('pbBottle').value);t+=bt?.price||0;$('pbTotal').innerHTML='Price: <b>'+money(t)+'</b>'};
  $('pbRows').addEventListener('input',perfBlendCalc);$('pbRows').addEventListener('change',perfBlendCalc);$('pbBottle').onchange=perfBlendCalc;$('pbAdd').onclick=()=>{$('pbRows').insertAdjacentHTML('beforeend',row());perfBlendCalc()};perfBlendCalc();
  const save=sell=>{const rows=[...document.querySelectorAll('[data-brow]')].map(r=>{const o=item(r.querySelector('[data-boil]').value);return{itemId:o?.id,name:o?.name,unit:o?.unit,qty:Math.round(Number(r.querySelector('[data-bqty]').value)*1000)/1000}}).filter(r=>r.itemId&&r.qty>0),name=$('pbName').value.trim(),cid=$('pbCust').value,bt=item($('pbBottle').value);
   if(!name||!rows.length){alert('Enter a name and at least one oil with its quantity');return}if(new Set(rows.map(r=>r.itemId)).size!==rows.length){alert('List each oil once');return}
   const v={id:id||uid(),name,customerId:cid,customer:customer(cid)?.name||'',components:rows,bottleId:bt?.id||'',bottle:bt?.name||'',notes:$('pbNotes').value.trim(),created:b.created||new Date().toISOString(),by:b.by||cloudUser.id};
   if(change(()=>{const k=db.perfume_blends.findIndex(x=>x.id===v.id);if(k>=0)db.perfume_blends[k]=v;else db.perfume_blends.push(v)})){closeModal();if(sell)sellBlend(v.id);else toast('Blend saved')}};
  $('pbSave').onclick=()=>save(false);$('pBl').onsubmit=e=>{e.preventDefault();save(true)};
 }
 function sellBlend(id){const b=db.perfume_blends.find(x=>x.id===id);if(!b)return;const n=Math.round(Number(prompt('How many bottles of '+b.name+'?','1')));if(!(n>=1&&n<=100))return;
  const levels=R.stockLevels(),short=b.components.filter(c=>(levels.get(c.itemId)||0)<c.qty*n);
  if(short.length&&!confirm('Low stock: '+short.map(c=>c.name+' ('+qt(levels.get(c.itemId)||0,c.unit)+' left)').join(', ')+'. Sell anyway?'))return;
  const note='Blend: '+b.name;R.bill({customerId:b.customerId,lines:[...b.components.filter(c=>item(c.itemId)).map(c=>({id:c.itemId,qty:Math.round(c.qty*n*1000)/1000,note})),...(b.bottleId&&item(b.bottleId)?[{id:b.bottleId,qty:n,note}]:[])]});toast(b.name+' added to bill')}

 // --- clients: points + scent profile ---------------------------------------------------------------------------------
 function clients(){
  const q=clientSearch.trim().toLowerCase(),l=loyalty(),list=db.customers.filter(c=>!q||(c.name+' '+c.phone).toLowerCase().includes(q)).map(c=>({c,pts:points(c.id),p:profile(c.id),blends:db.perfume_blends.filter(b=>b.customerId===c.id).length})).sort((a,b)=>b.pts-a.pts||a.c.name.localeCompare(b.c.name)).slice(0,100);
  $('app').innerHTML=`<div class="panel"><div class="row"><div><h2>Clients</h2><p class="helper">${l.enabled?`Loyalty: ${l.earnPerAed} point per AED 1 · 100 points = ${money(l.redeemFils*100)}`:'Loyalty points are off'}</p></div><div class="actions" style="margin:0">${isOwner()?'<button onclick="perfLoyalty()">Loyalty settings</button>':''}<button class="primary" onclick="perfNewClient()">+ New client</button></div></div>
  <label for="pcSearch">Search name or mobile</label><input id="pcSearch" value="${esc(clientSearch)}" oninput="perfClientSearch(this.value)">
  ${list.map(({c,pts,p,blends})=>`<div class="row" style="padding:12px 0;border-bottom:1px solid #eee;flex-wrap:wrap;gap:10px"><div style="flex:1;min-width:220px"><b>${esc(c.name)}</b> <span class="helper">${esc(c.phone||'')}</span><div class="helper">${p?.families?.length?esc(p.families.join(' · ')):'No scent profile yet'}${blends?' · '+blends+' blend'+(blends>1?'s':''):''}</div></div><b>⭐ ${pts}</b><button onclick="perfClient('${esc(c.id)}')">Open</button></div>`).join('')||'<div class="empty">No clients found.</div>'}</div>`;
 }
 function clientCard(id){const c=customer(id);if(!c)return;const p=profile(id)||{families:[],favourites:'',avoid:'',notes:''},pts=points(id),hist=db.perfume_points.filter(x=>x.customerId===id).sort((a,b)=>b.at.localeCompare(a.at)).slice(0,12),sales=db.sales.filter(s=>s.customerId===id).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8),bl=db.perfume_blends.filter(b=>b.customerId===id);
  modal(`<h2>${esc(c.name)}</h2><p>${esc(c.phone||'')} · <b>⭐ ${pts} points</b> (${money(pts*loyalty().redeemFils)})</p>
  <form id="pProf"><h3>Scent profile</h3><div style="display:flex;flex-wrap:wrap;gap:6px">${FAMILIES.map(f=>`<label style="display:flex;gap:6px;align-items:center;border:1px solid #ddd;border-radius:20px;padding:4px 10px"><input type="checkbox" value="${f}" style="width:auto;margin:0" ${p.families.includes(f)?'checked':''}> ${f}</label>`).join('')}</div><label for="ppFav">Favourite perfumes</label><input id="ppFav" maxlength="300" value="${esc(p.favourites)}"><label for="ppAvoid">Avoid</label><input id="ppAvoid" maxlength="200" value="${esc(p.avoid)}" placeholder="e.g. too sweet, allergies"><label for="ppNotes">Notes</label><input id="ppNotes" maxlength="500" value="${esc(p.notes)}"><button class="primary" style="margin-top:10px">Save profile</button></form>
  <h3>Blends</h3>${bl.map(b=>`<div class="row" style="padding:4px 0;border-bottom:1px solid #eee"><span><b>${esc(b.name)}</b> <span class="helper">${esc(blendText(b))}</span></span><button onclick="closeModal();perfSellBlend('${esc(b.id)}')">Sell</button></div>`).join('')||'<p class="helper">None yet.</p>'}<button onclick="closeModal();perfBlend('','${esc(id)}')">+ New blend for ${esc(c.name)}</button>
  <h3>Recent bills</h3>${sales.map(s=>`<div class="row helper" style="padding:3px 0"><span>${esc(new Date(s.date).toLocaleDateString())} · ${esc(s.number)}</span><span>${money(s.total)}${s.status==='Refunded'?' (refunded)':''}</span></div>`).join('')||'<p class="helper">No recent bills on this device.</p>'}
  <h3>Points history</h3>${hist.map(h=>`<div class="row helper" style="padding:3px 0"><span>${esc(new Date(h.at).toLocaleDateString())} · ${esc(h.type)}${h.sale?' · '+esc(h.sale):''}${h.reason?' · '+esc(h.reason):''}</span><b>${h.points>0?'+':''}${h.points}</b></div>`).join('')||'<p class="helper">No points yet.</p>'}
  <div class="actions">${isOwner()?`<button onclick="perfAdjust('${esc(id)}')">Adjust points</button>`:''}<button onclick="closeModal()">Close</button></div>`);
  $('pProf').onsubmit=e=>{e.preventDefault();const v={id,customerId:id,customer:c.name,families:[...document.querySelectorAll('#pProf input[type=checkbox]:checked')].map(x=>x.value),favourites:$('ppFav').value.trim(),avoid:$('ppAvoid').value.trim(),notes:$('ppNotes').value.trim()};
   if(change(()=>{const k=db.perfume_profiles.findIndex(x=>x.id===id);if(k>=0)db.perfume_profiles[k]=v;else db.perfume_profiles.push(v)}))toast('Profile saved')}}
 function adjust(id){const c=customer(id),n=Math.round(Number(prompt('Points to add (use minus to remove), e.g. 50 or -20:')));if(!n)return;const why=prompt('Reason:');if(!why?.trim())return;if(points(id)+n<0){alert('Points cannot go below zero');return}
  if(change(()=>db.perfume_points.push({id:uid(),customerId:id,customer:c.name,type:'adjust',points:n,reason:why.trim(),at:new Date().toISOString()})))clientCard(id)}
 function newClient(){modal(`<h2>New client</h2><form id="pNc"><label for="pnName">Name</label><input id="pnName" maxlength="100" required><label for="pnPhone">Mobile</label><input id="pnPhone" type="tel" maxlength="40" placeholder="050 123 4567"><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Add</button></div></form>`);
  $('pNc').onsubmit=e=>{e.preventDefault();const v={id:uid(),name:$('pnName').value.trim(),phone:$('pnPhone').value.trim(),dob:''};if(!v.name)return;if(change(()=>db.customers.push(v))){clientCard(v.id)}}}

 // --- dashboard block ------------------------------------------------------------------------------------------------------
 EXT.dashboard=()=>{const t=R.localDay(),today=db.sales.filter(s=>s.status==='Paid'&&R.localDay(new Date(s.date))===t),blendsToday=new Set(today.flatMap(s=>s.items.filter(i=>(i.note||'').startsWith('Blend: ')).map(i=>s.id+i.note))).size,top=db.customers.map(c=>({c,pts:points(c.id)})).filter(x=>x.pts>0).sort((a,b)=>b.pts-a.pts).slice(0,6);
  return `<div class="layout"><section class="panel"><div class="row"><h3>Blends sold today · ${blendsToday}</h3><button onclick="navigate('Blends')">Blends →</button></div>${R.branches().length>1?`<p class="helper">This device: <b>${esc(R.branchName())}</b>. Stock and low-stock below are for this branch.</p>`:''}</section><aside class="panel"><div class="row"><h3>Top loyalty clients</h3><button onclick="navigate('Clients')">Clients →</button></div>${top.map(x=>`<div class="row" style="padding:6px 0;border-bottom:1px solid #eee"><span>${esc(x.c.name)}</span><b>⭐ ${x.pts}</b></div>`).join('')||'<div class="empty">No points yet.</div>'}</aside></div>`};

 Object.assign(R.screens,{Blends:blends,Clients:clients});
 Object.assign(window,{
  perfRedeem:redeem,perfSetRow:()=>$('pfSet').insertAdjacentHTML('beforeend',setRow()),
  perfBranchPick:branchPick,perfSetBranch:id=>{try{localStorage.setItem('wifipos-branch',id)}catch{}closeModal();toast('This device: '+R.branchName(id));render()},
  perfBranches:branchesForm,perfLoyalty:loyaltyForm,perfTransfer:transfer,perfAssemble:assemble,
  perfBlend:blendForm,perfSellBlend:sellBlend,perfBlendSearch:v=>{blendSearch=v;blends();const el=$('pbSearch');el.focus();el.setSelectionRange(v.length,v.length)},
  perfBlendDelete:id=>{if(!confirm('Delete this blend recipe? Past bills keep their lines.'))return;if(change(()=>{db.perfume_blends=db.perfume_blends.filter(b=>b.id!==id)}))toast('Blend deleted')},
  perfClient:clientCard,perfClientSearch:v=>{clientSearch=v;clients();const el=$('pcSearch');el.focus();el.setSelectionRange(v.length,v.length)},perfAdjust:adjust,perfNewClient:newClient
 });
})();
