// Tailoring & abaya shop screens for Palace POS (business type "tailor"). Checkout, products, stock, credit and
// branches come from grocery.js / perfume.js; this file adds Tailoring (stitching orders and alterations with a
// production flow, job slip, tailor and piece rate, advance and balance on collection) and saved Measurements.
(function(){
 'use strict';
 const R=window.RetailUI;if(!R)return;
 R.ext??={};const EXT=R.ext.tailor={};
 const STAGES=['New','Cutting','Stitching','Finishing','Ready','Delivered'];
 const GARMENTS={Abaya:['Length','Shoulder','Bust','Waist','Hip','Sleeve length','Sleeve opening','Neck'],'Kaftan / jalabiya':['Length','Shoulder','Bust','Waist','Hip','Sleeve length'],Kandura:['Length','Shoulder','Chest','Waist','Sleeve length','Neck','Bottom width'],Dress:['Length','Shoulder','Bust','Waist','Hip','Sleeve length'],'Trousers / sirwal':['Length','Waist','Hip','Thigh','Bottom'],Other:['Length','Chest','Waist']};
 const ALTERATIONS=['Shorten length','Take in sides','Let out','Shorten sleeves','Replace zip','Add buttons / hooks','Repair','Other alteration'];
 let view='Open',draft=null,measureSearch='';
 const isOwner=()=>cloudUser?.role==='owner';
 const today=()=>R.localDay();
 const plus=n=>{const d=new Date();d.setDate(d.getDate()+n);return R.localDay(d)};
 const order=id=>db.tailor_orders.find(o=>o.id===id);
 const saved=cid=>db.tailor_measurements.find(m=>m.id===cid);
 const closed=o=>['Delivered','Cancelled'].includes(o.status);
 const pieces=o=>o.items.reduce((n,g)=>n+g.qty,0);
 const fabricQty=g=>Math.round(g.fabricQty*g.qty*1000)/1000;
 const fabrics=()=>db.grocery_items.filter(i=>i.unit==='m'&&!R.isSvc(i)).sort((a,b)=>a.name.localeCompare(b.name));
 const charge=o=>o.items.reduce((n,g)=>n+g.price*g.qty+(g.fabric==='shop'?Math.round((db.grocery_items.find(i=>i.id===g.fabricItemId)?.price||0)*fabricQty(g)):0),0);
 const late=o=>!closed(o)&&o.status!=='Ready'&&o.due<today();
 const custOptions=(sel='')=>`<option value="">Choose customer…</option>`+db.customers.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(c=>`<option value="${esc(c.id)}" ${c.id===sel?'selected':''}>${esc(c.name)}${c.phone?' · '+esc(c.phone):''}</option>`).join('');
 const badge=s=>`<span class="badge" style="${s==='Ready'?'background:#dff3e9;color:#155e48':s==='Delivered'?'background:#eceaf3;color:#555':s==='Cancelled'?'background:#fde8e6;color:#8a1c14':s==='New'?'background:#fdf0d8;color:#7a5200':''}">${esc(s)}</span>`;
 const measureText=list=>(list||[]).filter(m=>m.value).map(m=>m.label+' '+m.value).join(' · ');

 // --- product form, buttons, dashboard, checkout ---------------------------------------------------------------
 EXT.units=[['piece','Piece'],['m','Metre (m)']];
 EXT.services={types:[['stitching','Stitching'],['alteration','Alteration'],['other','Other service']],category:t=>t==='stitching'?'Stitching':t==='alteration'?'Alterations':'Other',blank:{name:'',category:'Stitching',serviceType:'stitching',price:0,duration:60,openPrice:true}};
 EXT.itemFields=i=>`<div class="business-grid"><div><label for="tlSize">Size (optional)</label><input id="tlSize" maxlength="20" value="${esc(i.size||'')}" placeholder="e.g. 56"></div><div><label for="tlColour">Colour (optional)</label><input id="tlColour" maxlength="30" value="${esc(i.colour||'')}" placeholder="e.g. Black"></div></div><p class="helper">Add one product per size, with the size in the name (e.g. “Classic abaya 56”), so stock and the bill show it.</p>`;
 EXT.readItem=()=>({...($('tlSize')?.value.trim()?{size:$('tlSize').value.trim()}:{}),...($('tlColour')?.value.trim()?{colour:$('tlColour').value.trim()}:{})});
 EXT.productButtons=()=>`${R.branches().length>1?`<button onclick="perfBranchPick()">Branch: ${esc(R.branchName())}</button>`:''}${isOwner()?'<button onclick="perfBranches()">Branches</button>':''}`;
 EXT.stockButtons=()=>R.branches().length>1?`<button onclick="perfTransfer()">Transfer</button><button onclick="perfBranchPick()">Branch: ${esc(R.branchName())}</button>`:'';
 EXT.dashboard=()=>{const open=db.tailor_orders.filter(o=>!closed(o)),t=today();
  return `<section class="panel"><div class="row"><h3>Tailoring orders</h3><button onclick="navigate('Tailoring')">Tailoring →</button></div><div class="grid">${[['Due today',open.filter(o=>o.due===t&&o.status!=='Ready').length],['Late',open.filter(late).length],['In production',open.filter(o=>o.status!=='Ready').length],['Ready for collection',open.filter(o=>o.status==='Ready').length]].map(([l,v])=>`<div class="panel" style="margin:0">${l}<div class="metric">${v}</div></div>`).join('')}</div></section>`};
 EXT.checkoutExtra=c=>{if(!c)return '';const bal=R.balanceOf(c.id);return bal<0?`<p class="helper" style="background:#dff3e9;color:#155e48;padding:8px 10px;border-radius:8px">Advance on account: <b>${money(-bal)}</b>. Press <b>Credit</b> to use it; then take the balance from the order (Receive balance) or on Credit.</p>`:''};
 EXT.onPaid=(sale,links)=>{let msg='';
  for(const l of links)if(l.kind==='tailor_orders'){const o=order(l.id);if(o&&!o.saleId){o.saleId=sale.id;if(o.status==='Ready'){o.status='Delivered';msg='Order #'+o.number+' billed and handed over'}else msg='Order #'+o.number+' billed · hand it over when it is ready'}}
  return msg};

 // --- order list ---------------------------------------------------------------
 function screen(){const inView=o=>view==='Open'?!closed(o)&&o.status!=='Ready':view==='Ready'?o.status==='Ready':closed(o),n=f=>db.tailor_orders.filter(f).length,
   list=db.tailor_orders.filter(inView).sort((a,b)=>view==='Closed'?b.created.localeCompare(a.created):a.due.localeCompare(b.due)||a.created.localeCompare(b.created)).slice(0,200);
  $('app').innerHTML=`<div class="panel"><div class="row" style="flex-wrap:wrap;gap:8px"><h2>Tailoring</h2><div class="actions" style="margin:0;flex-wrap:wrap">${[['Open',n(o=>!closed(o)&&o.status!=='Ready')],['Ready',n(o=>o.status==='Ready')],['Closed','']].map(([v,c])=>`<button class="${view===v?'primary':''}" onclick="tailorView('${v}')">${v}${c!==''?' ('+c+')':''}</button>`).join('')}<button class="primary" onclick="tailorNew('stitching')">+ Stitching order</button><button onclick="tailorNew('alteration')">+ Alteration</button>${isOwner()?'<button onclick="tailorWork()">Tailor work &amp; pay</button>':''}</div></div>
  ${list.map(o=>`<div class="row" style="padding:10px 0;border-bottom:1px solid #eee;flex-wrap:wrap;gap:10px"><div style="min-width:240px;flex:1"><b>#${o.number||'…'} · ${esc(o.customer)}</b> ${badge(o.status)}${o.type==='alteration'?' <span class="badge">Alteration</span>':''}<div class="helper">${esc(o.items.map(g=>g.qty+' × '+g.garment).join(', '))}${o.phone?' · '+esc(o.phone):''}</div><div class="helper"><span${late(o)?' style="color:#b42318;font-weight:700"':''}>Due ${esc(o.due)}${late(o)?' · late':''}</span>${o.tailor?' · '+esc(o.tailor):''} · ${money(charge(o))}${o.advance?' · advance '+money(o.advance):''}${o.saleId?' · billed':''}</div></div><button onclick="tailorOpen('${esc(o.id)}')">Open</button></div>`).join('')||`<div class="empty">${view==='Open'?'No orders in production. Take one with “+ Stitching order”.':'No orders here.'}</div>`}</div>`}

 // --- new order ---------------------------------------------------------------
 const blankGarment=type=>({key:uid(),garment:type==='alteration'?ALTERATIONS[0]:'Abaya',qty:1,price:(db.grocery_items.find(i=>R.isSvc(i)&&i.serviceType===type)?.price||0),design:'',measurements:[],fabric:'customer',fabricItemId:'',fabricQty:''});
 // Measurement boxes for a garment: the standard list for its type, filled from the order line or the customer's saved set.
 const fieldsFor=(g,cid)=>{const set=saved(cid)?.garments.find(x=>x.type===g.garment),labels=[...new Set([...(GARMENTS[g.garment]||GARMENTS.Other),...(set?.fields||[]).map(f=>f.label),...g.measurements.map(m=>m.label)])];return labels.map(label=>({label,value:g.measurements.find(m=>m.label===label)?.value??set?.fields.find(f=>f.label===label)?.value??''}))};
 function readDraft(){if(!draft||!$('tlOrder'))return;draft.customerId=$('toCust').value;draft.newName=$('toName').value;draft.newPhone=$('toPhone').value;draft.due=$('toDue').value;draft.advance=$('toAdv').value;draft.method=$('toMethod').value;draft.tailorId=$('toTailor').value;draft.rate=$('toRate').value;draft.note=$('toNote').value;draft.keep=$('toKeep')?$('toKeep').checked:false;
  draft.items.forEach((g,n)=>{const q=s=>document.querySelector(`[data-g="${n}"][data-f="${s}"]`);g.garment=q('garment').value;g.qty=Math.max(1,Math.min(50,Math.round(Number(q('qty').value)||1)));g.price=cents(q('price').value||0);g.design=q('design').value.trim();if(draft.type==='stitching'){g.fabric=q('fabric').value;g.fabricItemId=q('fabricItemId').value;g.fabricQty=q('fabricQty').value;g.measurements=[...document.querySelectorAll(`[data-g="${n}"][data-m]`)].map(i=>({label:i.dataset.m,value:i.value.trim()}))}})}
 function form(){const d=draft,st=d.type==='stitching',fab=fabrics(),cid=d.customerId==='+'?'':d.customerId;
  modal(`<h2>${st?'New stitching order':'New alteration'}</h2><form id="tlOrder"><label for="toCust">Customer</label><select id="toCust">${custOptions(d.customerId)}<option value="+" ${d.customerId==='+'?'selected':''}>+ New customer…</option></select><div id="toNew" class="business-grid" style="display:${d.customerId==='+'?'grid':'none'}"><div><label for="toName">Name</label><input id="toName" maxlength="100" value="${esc(d.newName||'')}"></div><div><label for="toPhone">Phone</label><input id="toPhone" maxlength="40" value="${esc(d.newPhone||'')}"></div></div>
  ${d.items.map((g,n)=>`<div class="panel" style="margin:10px 0;padding:12px"><div class="row"><b>${st?'Garment':'Item'} ${n+1}</b>${d.items.length>1?`<button type="button" data-g-del="${n}">Remove</button>`:''}</div><div class="business-grid"><div><label>${st?'Garment':'Work to do'}</label><select data-g="${n}" data-f="garment">${(st?Object.keys(GARMENTS):ALTERATIONS).map(t=>`<option ${g.garment===t?'selected':''}>${esc(t)}</option>`).join('')}</select></div><div><label>Pieces</label><input data-g="${n}" data-f="qty" type="number" min="1" max="50" step="1" value="${g.qty}"></div></div><div class="business-grid"><div><label>${st?'Stitching charge':'Charge'} per piece (AED)</label><input data-g="${n}" data-f="price" type="number" min="0" step="0.01" value="${(g.price/100).toFixed(2)}"></div><div><label>${st?'Design / style notes':'Details'}</label><input data-g="${n}" data-f="design" maxlength="300" value="${esc(g.design)}" placeholder="${st?'e.g. open front, lace on sleeves':'e.g. shorten by 5 cm'}"></div></div>
   ${st?`<label>Measurements (inches or cm, as you work)</label><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(110px,1fr));gap:8px">${fieldsFor(g,cid).map(f=>`<div><span class="helper">${esc(f.label)}</span><input data-g="${n}" data-m="${esc(f.label)}" maxlength="20" value="${esc(f.value)}" inputmode="decimal"></div>`).join('')}</div>
   <div class="business-grid"><div><label>Fabric</label><select data-g="${n}" data-f="fabric"><option value="customer" ${g.fabric==='customer'?'selected':''}>Customer’s own fabric</option><option value="shop" ${g.fabric==='shop'?'selected':''} ${fab.length?'':'disabled'}>From our stock</option></select></div><div data-g-shop="${n}" style="display:${g.fabric==='shop'?'':'none'}"><label>Fabric &amp; metres per piece</label><div style="display:flex;gap:6px"><select data-g="${n}" data-f="fabricItemId" style="flex:2">${fab.map(f=>`<option value="${esc(f.id)}" ${g.fabricItemId===f.id?'selected':''}>${esc(f.name)} · ${money(f.price)}/m</option>`).join('')}</select><input data-g="${n}" data-f="fabricQty" type="number" min="0.1" max="500" step="0.001" value="${esc(g.fabricQty||'')}" placeholder="m" style="flex:1"></div></div></div>`:`<input type="hidden" data-g="${n}" data-f="fabric" value="customer">`}</div>`).join('')}
  <button type="button" id="toAdd">+ Add another ${st?'garment':'item'}</button>
  <div class="business-grid"><div><label for="toDue">Delivery date</label><input id="toDue" type="date" min="${today()}" value="${esc(d.due)}" required></div><div><label for="toTailor">Tailor</label><select id="toTailor"><option value="">Not assigned yet</option>${db.staff.map(s=>`<option value="${esc(s.id)}" ${d.tailorId===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div></div>
  <div class="business-grid"><div><label for="toAdv">Advance received now (AED)</label><input id="toAdv" type="number" min="0" step="0.01" value="${esc(d.advance||'')}" placeholder="0.00"></div><div><label for="toMethod">Advance paid by</label><select id="toMethod"><option ${d.method==='Cash'?'selected':''}>Cash</option><option value="Card (external terminal)" ${d.method==='Card (external terminal)'?'selected':''}>Card</option></select></div></div>
  <div class="business-grid"><div><label for="toRate">Tailor’s pay per piece (AED, optional)</label><input id="toRate" type="number" min="0" step="0.01" value="${esc(d.rate||'')}" placeholder="0.00"></div><div><label for="toNote">Note</label><input id="toNote" maxlength="200" value="${esc(d.note||'')}"></div></div>
  ${st?`<label style="display:flex;gap:8px;align-items:center"><input type="checkbox" id="toKeep" ${d.keep?'checked':''} style="width:auto"> Save these measurements on the customer for next time</label>`:''}
  <p id="toErr" class="pending-note" role="alert" hidden></p><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save &amp; print job slip</button></div></form>`);
  const redraw=()=>{readDraft();form()};
  $('toCust').onchange=()=>{readDraft();if(st)for(const g of draft.items)g.measurements=[];form()};
  $('toAdd').onclick=()=>{readDraft();if(draft.items.length>=20)return;draft.items.push(blankGarment(d.type));form()};
  document.querySelectorAll('[data-g-del]').forEach(b=>b.onclick=()=>{readDraft();draft.items.splice(Number(b.dataset.gDel),1);form()});
  document.querySelectorAll('[data-f="garment"]').forEach(s=>s.onchange=()=>{if(!st)return;readDraft();draft.items[Number(s.dataset.g)].measurements=[];form()});
  document.querySelectorAll('[data-f="fabric"]').forEach(s=>s.onchange=redraw);
  $('tlOrder').onsubmit=e=>{e.preventDefault();readDraft();const err=m=>{$('toErr').textContent=m;$('toErr').hidden=!m},x=draft;let cid=x.customerId;
   if(!cid){err('Choose the customer, or add a new one.');return}if(cid==='+'&&!x.newName?.trim()){err('Enter the customer name.');return}if(!x.due||x.due<today()){err('Choose the delivery date.');return}
   for(const g of x.items)if(g.fabric==='shop'&&!(Number(g.fabricQty)>0&&Number(g.fabricQty)<=500&&g.fabricItemId)){err('Enter the metres of fabric per piece for '+g.garment+'.');return}
   const advance=x.advance?cents(x.advance):0,rate=x.rate?cents(x.rate):0;if(!(advance>=0)||!(rate>=0)){err('Check the advance and the tailor’s pay.');return}
   if(advance&&x.method!=='Cash'&&!confirm('Confirm '+money(advance)+' was approved on your card terminal?'))return;
   const id=uid(),now=new Date().toISOString(),tl=db.staff.find(s=>s.id===x.tailorId);let c=db.customers.find(k=>k.id===cid);
   const items=x.items.map(g=>({key:g.key,garment:g.garment,qty:g.qty,price:g.price,design:g.design,measurements:(g.measurements||[]).filter(m=>m.value),fabric:g.fabric,...(g.fabric==='shop'?{fabricItemId:g.fabricItemId,fabricName:db.grocery_items.find(i=>i.id===g.fabricItemId)?.name||'',fabricQty:Math.round(Number(g.fabricQty)*1000)/1000}:{})}));
   if(change(()=>{if(cid==='+'){c={id:uid(),name:x.newName.trim(),phone:(x.newPhone||'').trim(),dob:''};db.customers.push(c);cid=c.id}
    if(x.keep&&x.type==='stitching'){let m=saved(cid);if(!m){m={id:cid,customerId:cid,customer:c.name,garments:[]};db.tailor_measurements.push(m)}for(const g of items){if(!g.measurements.length)continue;const set=m.garments.find(s=>s.type===g.garment);if(set)set.fields=g.measurements;else if(m.garments.length<12)m.garments.push({type:g.garment,fields:g.measurements,note:''})}}
    if(advance)db.grocery_payments.push({id:uid(),customerId:cid,customer:c.name,amount:advance,method:x.method,note:'Advance · '+(x.type==='stitching'?'stitching order':'alteration'),at:now});
    db.tailor_orders.push({id,number:0,type:x.type,customerId:cid,customer:c.name,phone:c.phone||'',items,due:x.due,advance,note:(x.note||'').trim(),tailorId:tl?.id||'',tailor:tl?.name||'',rate,status:'New',saleId:'',created:now,history:[{status:'New',at:now}]})})){draft=null;view='Open';render();slip(id)}}}
 function create(type){if(!db.grocery_items.some(i=>R.isSvc(i)&&i.serviceType===type)){alert('Add a service of type “'+type+'” on Products first (e.g. '+(type==='stitching'?'Stitching charge':'Alteration')+', with “price can change” ticked).');return}
  draft={type,customerId:'',due:plus(type==='stitching'?7:2),advance:'',method:'Cash',tailorId:'',rate:'',note:'',keep:true,items:[blankGarment(type)]};form()}

 // --- job slip (goes to the workshop with the fabric) ---------------------------------------------------------------
 function slip(id){const o=order(id);if(!o)return;const l='--------------------------------';
  modal(`<h2>Job slip</h2>${o.number?'':'<p class="pending-note">The order number is issued when this device syncs. Reprint the slip after syncing to show it.</p>'}<pre class="receipt" id="receiptText">${esc(`${db.settings.name}\n${db.settings.address||''}\n${db.settings.phone||''}\n${l}\n${o.type==='alteration'?'ALTERATION':'STITCHING ORDER'}${o.number?' No. '+o.number:''}\n${new Date(o.created).toLocaleString()}\n${l}\nCustomer: ${o.customer}\nPhone: ${o.phone||'-'}\nDELIVERY: ${o.due}\n${o.tailor?'Tailor: '+o.tailor+'\n':''}${l}\n${o.items.map((g,n)=>`${n+1}. ${g.garment} × ${g.qty}${g.design?'\n   '+g.design:''}${g.measurements?.length?'\n'+g.measurements.map(m=>'   '+m.label+': '+m.value).join('\n'):''}\n   Fabric: ${g.fabric==='shop'?g.fabricName+' '+fabricQty(g)+' m (ours)':'customer’s own'}\n   Charge: ${money(g.price*g.qty)}`).join('\n')}\n${l}\nEstimate: ${money(charge(o))} + VAT\nAdvance paid: ${money(o.advance||0)}\n${o.note?'Note: '+o.note+'\n':''}${l}\nBring this slip to collect your order.\nThe balance is paid on collection.\nOrders not collected within 30 days of\nbeing ready may be disposed of.\n\nCustomer signature: ______________`)}</pre><div class="actions"><button onclick="closeModal()">Close</button><button class="primary" onclick="printReceipt()">Print / Save PDF</button></div>`)}

 // --- open an order: stage, tailor, bill, hand over ---------------------------------------------------------------
 function open(id){const o=order(id);if(!o)return;const done=closed(o),sale=o.saleId?db.sales.find(s=>s.id===o.saleId):null,at=STAGES.indexOf(o.status),next=o.status==='Ready'?['Stitching','Finishing']:STAGES.slice(at+1,5),bal=R.balanceOf(o.customerId);
  modal(`<h2>#${o.number||'…'} · ${esc(o.customer)}</h2><p>${badge(o.status)} ${o.type==='alteration'?'Alteration':'Stitching order'} · due <b${late(o)?' style="color:#b42318"':''}>${esc(o.due)}</b>${o.phone?' · '+esc(o.phone):''}</p>
  ${o.items.map(g=>`<div style="padding:8px 0;border-bottom:1px solid #eee"><b>${g.qty} × ${esc(g.garment)}</b> · ${money(g.price*g.qty)}<div class="helper">${esc([g.design,measureText(g.measurements),g.fabric==='shop'?'Fabric: '+g.fabricName+' '+fabricQty(g)+' m':'Customer’s fabric'].filter(Boolean).join(' · '))}</div></div>`).join('')}
  <p>Estimate <b>${money(charge(o))}</b> + VAT · advance ${money(o.advance||0)}${o.note?' · '+esc(o.note):''}</p>
  ${done?`<p>${o.cancelReason?'Cancelled: '+esc(o.cancelReason)+'<br>':''}${sale?'Bill '+esc(sale.number||'')+' · '+money(sale.total):''}${o.tailor?'<br>Tailor: '+esc(o.tailor):''}</p>`:`<form id="tlEdit"><div class="business-grid"><div><label for="teTailor">Tailor</label><select id="teTailor"><option value="">Not assigned yet</option>${db.staff.map(s=>`<option value="${esc(s.id)}" ${o.tailorId===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div><div><label for="teRate">Tailor’s pay per piece (AED)</label><input id="teRate" type="number" min="0" step="0.01" value="${((o.rate||0)/100).toFixed(2)}"></div></div><div class="business-grid"><div><label for="teDue">Delivery date</label><input id="teDue" type="date" value="${esc(o.due)}" required></div><div><label for="teNote">Note</label><input id="teNote" maxlength="200" value="${esc(o.note||'')}"></div></div><button>Save details</button></form>
  ${next.length?`<h3 style="margin-top:14px">${o.status==='Ready'?'Needs more work? Send back to':'Move to'}</h3><div class="actions">${next.map(s=>`<button class="${s==='Ready'?'primary':''}" data-te-status="${esc(s)}">${esc(s)}</button>`).join('')}</div>`:''}
  <h3 style="margin-top:14px">Bill &amp; hand over</h3><div class="actions">${o.saleId?`<span class="badge">Billed${sale?' · '+esc(sale.number||''):''}</span>`:'<button class="primary" id="teBill">Bill this order</button>'}${o.saleId&&o.status==='Ready'?'<button class="primary" id="teDeliver">Hand over (delivered)</button>':''}${o.status==='Ready'&&o.phone?'<button id="teWa">WhatsApp “ready”</button>':''}</div>`}
  ${bal?`<p class="helper" style="padding:8px 10px;border-radius:8px;${bal>0?'background:#fde8e6;color:#8a1c14':'background:#dff3e9;color:#155e48'}">Customer account: <b>${bal>0?money(bal)+' due':money(-bal)+' paid in advance'}</b> ${bal>0?`<button id="teBal" style="margin-left:8px">Receive balance</button>`:''}</p>`:''}
  <div class="actions"><button onclick="closeModal()">Close</button><button id="teSlip">Job slip</button>${sale?`<button onclick="receipt('${esc(sale.id)}')">Receipt</button>`:''}${done?'':'<button class="danger" id="teCancel">Cancel order</button>'}</div>`);
  const upd=(fn,msg)=>{if(change(()=>fn(order(id)))){closeModal();toast(msg);if(tab==='Tailoring')screen()}};
  $('teSlip').onclick=()=>slip(id);if($('teBal'))$('teBal').onclick=()=>{closeModal();groceryPayment(o.customerId)};if(done)return;
  const details=x=>{const s=db.staff.find(k=>k.id===$('teTailor').value);x.tailorId=s?.id||'';x.tailor=s?.name||'';x.rate=cents($('teRate').value||0);if($('teDue').value)x.due=$('teDue').value;x.note=$('teNote').value.trim()};
  $('tlEdit').onsubmit=e=>{e.preventDefault();upd(details,'Saved')};
  document.querySelectorAll('[data-te-status]').forEach(b=>b.onclick=()=>{const s=b.dataset.teStatus;if(s==='Ready'&&!$('teTailor').value&&!confirm('No tailor is on this order, so nobody is paid for it. Mark it ready anyway?'))return;upd(x=>{details(x);x.status=s;if(s==='Ready')x.readyAt=new Date().toISOString()},'#'+o.number+' → '+s)});
  $('teCancel').onclick=()=>{if(o.saleId){alert('This order is already billed. Refund the bill on Sales first if the customer is not taking it.');return}const why=prompt('Reason for cancelling this order:');if(why?.trim())upd(x=>{x.status='Cancelled';x.cancelReason=why.trim()},o.advance?'Cancelled · the advance of '+money(o.advance)+' stays on the customer’s account':'Order cancelled')};
  if($('teBill'))$('teBill').onclick=()=>{const svc=db.grocery_items.filter(i=>R.isSvc(i)&&i.serviceType===o.type).sort((a,b)=>(b.openPrice===true)-(a.openPrice===true))[0];if(!svc){alert('Add a service of type “'+o.type+'” on Products first.');return}const link={kind:'tailor_orders',id};closeModal();if(R.billed(link)){navigate('Checkout');return}
   const lines=[];for(const g of o.items){lines.push({id:svc.id,qty:g.qty,price:g.price,link,note:('#'+o.number+' '+g.garment).slice(0,100)});if(g.fabric==='shop'&&db.grocery_items.some(i=>i.id===g.fabricItemId))lines.push({id:g.fabricItemId,qty:fabricQty(g),link,note:'#'+o.number+' fabric'})}
   R.bill({lines,customerId:o.customerId});toast(o.advance?'Advance '+money(o.advance)+' is on the account: press Credit, then receive the balance':'Take payment to finish')};
  if($('teDeliver'))$('teDeliver').onclick=()=>upd(x=>{x.status='Delivered'},'Handed over');
  if($('teWa'))$('teWa').onclick=()=>{try{window.open(SalonWhatsApp.link(o.phone,`Hello ${o.customer.split(' ')[0]}, your order no. ${o.number} (${o.items.map(g=>g.qty+' '+g.garment).join(', ')}) is ready for collection at ${db.settings.name}. Please bring your job slip. Thank you!`),'_blank','noopener')}catch(e){alert(e.message)}}}

 // --- tailor work & piece-rate pay (owner) ---------------------------------------------------------------
 function work(month=today().slice(0,7)){const rows=new Map(),list=db.tailor_orders.filter(o=>['Ready','Delivered'].includes(o.status)&&o.readyAt&&R.localDay(new Date(o.readyAt)).slice(0,7)===month);
  for(const o of list){const k=o.tailor||'Not assigned',r=rows.get(k)||{orders:0,pieces:0,pay:0};r.orders++;r.pieces+=pieces(o);r.pay+=pieces(o)*(o.rate||0);rows.set(k,r)}
  const all=[...rows].sort((a,b)=>b[1].pieces-a[1].pieces),sum=k=>all.reduce((n,[,r])=>n+r[k],0);
  modal(`<h2>Tailor work &amp; pay</h2><label for="twMonth">Month</label><input id="twMonth" type="month" value="${esc(month)}" max="${today().slice(0,7)}"><p class="helper">Pieces from orders marked <b>Ready</b> in this month, at the pay per piece set on each order.</p>${all.length?`<div class="scroll"><table><tr><th>Tailor</th><th>Orders</th><th>Pieces</th><th>Pay</th></tr>${all.map(([t,r])=>`<tr><td>${esc(t)}</td><td>${r.orders}</td><td>${r.pieces}</td><td>${money(r.pay)}</td></tr>`).join('')}<tr><th>Total</th><th>${sum('orders')}</th><th>${sum('pieces')}</th><th>${money(sum('pay'))}</th></tr></table></div>`:'<div class="empty">No orders were finished in this month.</div>'}<div class="actions"><button onclick="closeModal()">Close</button></div>`);
  $('twMonth').onchange=()=>{if($('twMonth').value)work($('twMonth').value)}}

 // --- measurements ---------------------------------------------------------------
 function measurements(){const q=measureSearch.trim().toLowerCase(),list=db.customers.filter(c=>q?(c.name+' '+(c.phone||'')).toLowerCase().includes(q):saved(c.id)?.garments.length).sort((a,b)=>a.name.localeCompare(b.name)).slice(0,60);
  $('app').innerHTML=`<div class="panel"><div class="row"><div><h2>Measurements</h2><p class="helper">Saved once per customer and garment; a new order fills them in for you.</p></div></div><label for="tmSearch">Search customer name or mobile</label><input id="tmSearch" value="${esc(measureSearch)}" autocomplete="off">
  ${list.map(c=>{const m=saved(c.id);return `<div class="row" style="padding:10px 0;border-bottom:1px solid #eee;flex-wrap:wrap;gap:10px"><div style="min-width:220px;flex:1"><b>${esc(c.name)}</b>${c.phone?' · '+esc(c.phone):''}${(m?.garments||[]).map(g=>`<div class="helper"><b>${esc(g.type)}</b>: ${esc(measureText(g.fields)||'—')}${g.note?' · '+esc(g.note):''}</div>`).join('')||'<div class="helper">No measurements saved</div>'}</div><button onclick="tailorMeasure('${esc(c.id)}')">${m?.garments.length?'Edit':'Add'}</button></div>`}).join('')||`<div class="empty">${q?'No customer found. Add them on Customers first.':'No measurements saved yet. Search a customer to add theirs, or tick “save measurements” on a stitching order.'}</div>`}</div>`;
  const el=$('tmSearch');el.oninput=()=>{measureSearch=el.value;measurements();const n=$('tmSearch');n.focus();n.setSelectionRange(n.value.length,n.value.length)}}
 function measure(cid,sets,type){const c=db.customers.find(x=>x.id===cid);if(!c)return;sets??=JSON.parse(JSON.stringify(saved(cid)?.garments||[]));type??=sets[0]?.type||'Abaya';
  let set=sets.find(s=>s.type===type);const labels=[...new Set([...(GARMENTS[type]||GARMENTS.Other),...(set?.fields||[]).map(f=>f.label)])];
  modal(`<h2>Measurements · ${esc(c.name)}</h2><form id="tlMeas"><label for="tmType">Garment</label><select id="tmType">${Object.keys(GARMENTS).map(t=>`<option ${t===type?'selected':''}>${esc(t)}${sets.some(s=>s.type===t&&s.fields.length)?' ✓':''}</option>`).join('')}</select><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(110px,1fr));gap:8px;margin-top:10px">${labels.map(l=>`<div><span class="helper">${esc(l)}</span><input data-tm="${esc(l)}" maxlength="20" inputmode="decimal" value="${esc(set?.fields.find(f=>f.label===l)?.value||'')}"></div>`).join('')}</div><label for="tmNote">Note</label><input id="tmNote" maxlength="200" value="${esc(set?.note||'')}" placeholder="e.g. likes loose fit"><div class="actions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save</button></div></form>`);
  const keep=()=>{const fields=[...document.querySelectorAll('[data-tm]')].map(i=>({label:i.dataset.tm,value:i.value.trim()})).filter(f=>f.value),note=$('tmNote').value.trim();sets=sets.filter(s=>s.type!==type);if(fields.length||note)sets.push({type,fields,note})};
  $('tmType').onchange=()=>{keep();measure(cid,sets,$('tmType').value.replace(/ ✓$/,''))};
  $('tlMeas').onsubmit=e=>{e.preventDefault();keep();if(change(()=>{const m=saved(cid);if(m)m.garments=sets;else db.tailor_measurements.push({id:cid,customerId:cid,customer:c.name,garments:sets})})){closeModal();toast('Measurements saved');if(tab==='Measurements')measurements()}}}

 Object.assign(R.screens,{Tailoring:screen,Measurements:measurements});
 Object.assign(window,{tailorView:v=>{view=v;screen()},tailorNew:create,tailorOpen:open,tailorWork:()=>work(),tailorMeasure:id=>measure(id)});
})();
